/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache(["login","cancel"],[]);
vBulletin.createAjaxTools=(v,n,k,w)=>{function q(a,b){if(Array.isArray(a))a.unshift(b);else{var c=a;a=function(...d){b.apply(this,d);"function"==typeof c&&c.apply(this,d)}}return a}function B(a){return'<textarea style="border:1px solid #999;margin-top:10px;height:120px;width:100%;">'+a+"</textarea>"}function C(a){for(var b=[],c=0;c<a.length;c++){var d=$.isArray(a[c])?a[c][0]:a[c],e=k.get(a[c]);1==$("#debug-information").length&&d!=e&&(e+=" ("+d+")");b.push(e)}return b}function D(a,b){return(c,d,e)=>
{var g="";"undefined"!=typeof c.status&&(g+=" "+c.status);null!=d&&(g+=" "+d);"undefined"!=typeof e&&(g+=" "+e);console.log(b+" Error callback: "+a.url);E(c,d,e);c=k.get(a.error_phrase)+"<br /><br />"+k.get("error_information_x",g);w.openAlertDialog({title:k.get(a.title_phrase),message:c,iconType:"error",onAfterClose:a.after_error})}}function F(a,b,c,d,e,g){(c=a.errors)||(c=[a.error]);if(!b.api_error||b.api_error.apply(d,[c,a,b])){var f=h=>{g.data=g.data.replace(/securitytoken=[^&]*(&|$)/,"securitytoken="+
h.newtoken+"$1");$.ajax(g)};if(0!=n){if(x(c,["inlinemodauth_required"])){y("inlinemod_auth",f,n,"cplogin");return}if(0==a.userid&&x(c,[/^humanverify_/,/^no_permission(?:_|$)/,"no_create_permissions","session_timed_out_login","not_logged_no_permission","no_delete_permissions","no_featured_permissions"])){a=()=>{y("login",f,n,b.cpaction?"cplogin":"")};L(f,a,n)||a();return}}z(c,a,b)}}function x(a,b){if(!$.isArray(a))return!1;var c=b;$.isArray(c)||(c=[b]);for(b=0;b<a.length;b++){var d=a[b];$.isArray(d)&&
(d=d[0]);for(var e=0;e<c.length;e++){var g=c[e];if("regexp"==$.type(g)){if(g.test(d))return!0}else if(g==d)return!0}}return!1}function z(a,b,c){var d={title_phrase:"error",after_error:null};$.extend(!0,d,c);a:{for(c=0;c<a.length;c++){var e=a[c];if($.isArray(e)&&"exception_trace"==e[0]){a.splice(c,1);c=e[1];break a}}c=""}a=C(a);1==$("#debug-information").length&&(c&&a.push(B(c)),a.push(B(JSON.stringify(b))));a="<ul>\n<li>"+a.join("</li>\n<li>")+"</li>\n</ul>";return w.openAlertDialog({title:k.get(d.title_phrase),
message:a,iconType:"error",onAfterClose:d.after_error})}function E(a,b,c){console.dir({textStatus:b,jqXHRStatus:a.status,jqXHRResponseText:a.responseText,errorThrown:c});console.trace()}function l(a){var b={type:"POST",dataType:"json",title_phrase:"error",error_phrase:"error",api_error:!1,after_error:null,silent:!1};a.data instanceof FormData&&(b.processData=!1,b.contentType=!1);$.extend(!0,b,a);b.call&&(b.url=v+b.call,b.call="");b.silent&&(b.error=$.noop,b.api_error=$.noop);b.error||(b.error=D(b,
"ajax"));var c=this;b.success=function(d,e,g){d||b.allowEmptyResponse||(d={errors:[["invalid_server_response_please_try_again"]]});d&&(d.errors||d.error)?F(d,b,a,c,l,this):a.success&&a.success.apply(this,arguments)};return $.ajax(b)}function G(a){var b={dataType:"json",title_phrase:"error",error_phrase:"error",api_error:!1,after_error:null,iframe:!1,silent:!1};$.extend(b,a);b.silent&&(b.error=$.noop,b.api_error=$.noop);b.error||(b.error=D(b,"ajaxForm"));b.beforeSubmit=function(d,e,g){if(a.beforeSubmit&&
!1===a.beforeSubmit.apply(this,arguments))return!1;var f=$("button, .b-button",e);f.prop("disabled",!0);$(document).one("ajaxComplete",()=>{f.prop("disabled",!1)});return!0};var c=this;b.success=function(d,e,g,f){d||b.allowEmptyResponse||(d={errors:[["invalid_server_response_please_try_again"]]});d&&(d.errors||d.error)?F(d,b,a,c,G,this):a.success&&a.success.apply(this,arguments)};this.ajaxForm(b)}function L(a,b,c){return"undefined"!=typeof vBfb&&vBfb.isFbLogin()?(vBfb.makeAuthEvent(d=>{l({call:"/auth/login-external",
data:{provider:"facebook",auth:d.accessToken,userid:c},success:e=>{vBulletin.doReplaceSecurityToken(e.newtoken);return a(e)},api_error:b})})(),!0):!1}function y(a,b,c,d){let e,g;w.openTemplateConfirmDialog(H,{title:a,width:400,yesPhrase:"login",noPhrase:"cancel",onClickYes:f=>{g.text("").addClass("h-hide");l({call:"/auth/ajax-login",data:e.serializeArray(),success:h=>{f.trigger("vb-login",h)},api_error:h=>{g.html(k.get(h[0])).removeClass("h-hide");g.find("a").attr("target","_blank")},title_phrase:a});
return!1}},{call:"/auth/login-dialog",data:{logintype:d,userid:c},api_error:z}).then(f=>{e=f.find(".js-login-form");g=$(".js-error-box",e);var h=$('[type="text"], [type="password"]',f);h.on("keydown",m=>{13==m.which&&(m.preventDefault(),$("#btnConfirmDialogYes",f).trigger("click"))});h.filter(":visible").first().trigger("focus");f.on("vb-login",(m,p)=>{m.stopPropagation();vBulletin.doReplaceSecurityToken(p.newtoken);f.dialog("close");return b(p)})})}$.ajaxSetup({contentType:"application/x-www-form-urlencoded; charset=UTF-8"});
let A,I=!1,J=!0,r,t,u=[];$(()=>{A=$("#debug-information");(I=0<A.length)?(r=A.find("#debug-ajax-request-count"),t=$("<ol />").attr("id","debug-ajax-request-list").hide().css({height:"150px",overflow:"auto",padding:"4px",border:"1px solid #CCC",background:"#EEE","margin-top":"2px","margin-bottom":"4px"}).appendTo(r.closest("li")),r.css("cursor","pointer").on("click",()=>{t.toggle()})):(J=!1,u=[])});$.ajaxPrefilter((a,b,c)=>{if(J){var d={url:a.url,startTimeStamp:Date.now(),endTimeStamp:0,finalTimeStamp:0,
status:"UNKNOWN",errorThrown:""};u.push(d);a.success=q(a.success,(e,g,f)=>{d.endTimeStamp=Date.now()});a.error=q(a.error,(e,g,f)=>{d.endTimeStamp=Date.now();d.errorThrown=f});a.complete=q(a.complete,(e,g)=>{d.finalTimeStamp=Date.now();d.status=g;if(I)for(e=u.length,r.text(e),g=0;g<e;g++){var f=u[g];let h="js-request-counter-"+g;if(0==t.find("."+h).length){let m=0==f.url.indexOf(v)?f.url.substring(v.length):f.url,p=f.endTimeStamp-f.startTimeStamp,K=f.finalTimeStamp-f.startTimeStamp;f='{0} <span style="font-size:x-small;">({1}, <span title="Request Time: {2}ms, Processing Time: {3}ms, Total Time: {4}ms" style="text-decoration:underline;">{2}ms, {3}ms</span>){5}</span>'.format(m,
f.status,p,K-p,K,f.errorThrown?" Error: "+f.errorThrown:"");$("<li />").addClass(h).html(f).appendTo(t)}}})}});var H={hasError:x,ajax:l,ajaxSilent:function(a){vBulletin.loadingIndicator.suppressNextAjaxIndicator();return l(a)},render:function(a){a.template&&(a.call="/ajax/render/"+a.template,a.template="");a.data.isTemplateRender=!0;a.data.isAjaxTemplateRenderWithData=!0;return l(a)},ajaxForm:G,logApiError:function(a){console.dir(C(a))},logAjaxError:E,showApiError:z,runBeforeCallback:q,library:{inlineMod(a){y("inlinemod_auth",
a,n,"cplogin")}}};return H};
