/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache(["closed","this_topic_is_closed"],[]);
(function(b){if(!vBulletin.pageHasSelectors([".forum-channel-content-widget",".blog-channel-content-widget",".sg-channel-content-widget",".search-results-widget .topic-list-container"]))return!1;var x={};vBulletin.conversation.editTopicTitle=function(h){h=b(h.target).closest(".js-topic-item");var a=h.find(".js-topic-wrapper"),k=h.data("node-id");h.data("can-edit-title")&&!x[k]&&(x[k]="edit",0==a.find(".js-loading-icon").length&&b('<img class="loading-icon js-loading-icon" src="'+pageData.baseurl+
'/images/misc/progress.gif" />').appendTo(a),a.find(".js-loading-icon").show(),vBulletin.AJAX({call:"/create-content/loadtitleedit",data:{nodeid:k,isAjaxTemplateRender:!0},success:function(c){a.find(".js-topic-title").hide();a.find(".js-loading-icon").hide();a.find(".js-topic-title").after(c);c=a.find(".js-topic-title-edit");c.data("original-title",c.val());var l=30;a.find(".js-prefix, .js-post-icon, .js-topic-prefix, .js-go-to-first-unread").each(function(){l+=b(this).outerWidth(!0)});c.outerWidth(c.outerWidth()-
l);a.find(".js-topic-title-edit-form").on("submit",vBulletin.conversation.saveTopicTitle);c.on("blur",vBulletin.conversation.saveTopicTitle);c.trigger("select").trigger("focus")}}))};vBulletin.conversation.saveTopicTitle=function(h){h.preventDefault();var a=b(h.target).closest(".js-topic-wrapper");h=a.find(".js-topic-title-edit-form");var k=h.find(".js-node-id").val(),c=h.find(".js-topic-title-edit").val();"save"!=x[k]&&(x[k]="save",a.find(".js-topic-title-edit").data("original-title")==c?(a.find(".js-loading-icon").remove(),
a.find(".js-topic-title-edit-form").remove(),a.find(".js-topic-title").show(),x[k]=!1):(a.find(".js-loading-icon").appendTo(h).show(),vBulletin.AJAX({call:"/create-content/savetitleedit",data:{nodeid:k,title:c},success:function(l){a.find(".js-topic-title-edit-form").remove();a.find(".js-topic-title").html(l.title).show()},complete:function(){a.find(".js-loading-icon").remove();x[k]=!1}})))};vBulletin.conversation.openOrCloseTopic=function(h){h.stopPropagation();var a=b(this),k=a.closest(".js-topic-item"),
c=k.find(".js-topic-wrapper");h=k.data("node-id");var l=k.hasClass("closed");0==c.find(".js-loading-icon").length&&b('<img class="loading-icon js-loading-icon" src="'+pageData.baseurl+'/images/misc/progress.gif" />').appendTo(c);var r=c.find(".js-loading-icon");r.show();vBulletin.AJAX({call:"/ajax/api/node/"+(l?"openNode":"closeNode"),data:{nodeid:h},error_phrase:"error_open_close_topic",api_error:function(d){var f=vBulletin.ajaxtools;if(f.hasError(d,"inlinemodauth_required"))return!0;f.logApiError(d)},
complete:function(){r.hide()},success:function(d){k.toggleClass("closed",!l);d=a.attr("title")||"";var f=vBulletin.phrase.get("this_topic_is_closed");subStrIndex=d.indexOf(f);l&&0<=subStrIndex?(d=(d.slice(0,subStrIndex)+d.slice(subStrIndex+f.length)).trim(),a.attr("title",d)):!l&&0>subStrIndex&&a.attr("title",f+" "+d);d=c.find(".js-prefix");f=[];var v=vBulletin.phrase.get("closed");if(d.length){var g=d.text().trim();":"==g.charAt(g.length-1)&&(g=g.substring(0,g.length-1));0<g.length&&(f=g.split(", "));
if(!l)f.push(v);else if(0<f.length)for(g=f.length-1;0<=g;g--)f[g]==v&&f.splice(g,1)}else d=b('<span class="prefix js-prefix"></span>'),g=c.find(".js-go-to-first-unread"),g.length?d.insertAfter(g):d.prependTo(c),l||f.push(v);d.text(f.join(", ")+": ");d.toggle(0!=f.length)}})};b(function(){vBulletin.conversation=vBulletin.conversation||{};var h=vBulletin.tabtools,a=b(".channel-content-widget .channel-conversation-list-wrapper"),k=b("#media-tab",a),c,l,r,d,f,v,g,G,z=!0,A,t=a.find(".widget-tabs-nav .ui-tabs-nav > li"),
B=t.filter(".ui-tabs-active"),C=B.index(),y="1"==t.parent().data("allow-history"),I=new vBulletin.history.instance(y);-1==C&&(C=0,B=t.first());var D=B.find("> a").attr("href");var H=function(e){return a.offset().top+(a.outerHeight()-parseFloat(a.css("border-bottom-width")))-e.height()},E=function(e,u){var w=u.filter;u.pagination&&u.pagination.setOption("context",e);w.setOption("context",e);"undefined"!=typeof w.lastFilters&&0<b(".conversation-empty:not(.h-hide)",e).length&&delete w.lastFilters},F=
function(e,u,w,m,n,q,p){q=b(".conversation-list",e);return h.newTab(e,u,w,m,n,q,p,b.noop,y)};h.initTabs(a,I,t,y,C,D,[d,l,v],!0,function(e,u,w){var m=b(w),n="#"+m.prop("id");e=D==n;"#activity-stream-tab"!=n&&"#article-tab"!=n&&r&&d.toggleNewConversations(!1);"#topic-tab"!=n&&c&&l.toggleNewConversations(!1);if("#activity-stream-tab"==n||"#article-tab"==n)r?E(m,r):(r=F(m,a,!0,!0,e,null),d=r.filter),d.applyFilters(!1,!0);else if("#subscribed-tab"==n)f?E(m,f):(f=F(m,a,!0,!0,e,null),v=f.filter),v.applyFilters(!1,
!1);else if("#topic-tab"==n)c?E(m,c):(c=F(m,a,!0,!0,e,function(){vBulletin.markreadcheck()}),l=c.filter),l.applyFilters(!1,!0);else if("#media-tab"==n){if(g)z=!0;else{g=b(".conversation-toolbar-wrapper.scrolltofixed-floating",k);G=new vBulletin.scrollToFixed({element:g,limit:H(g)});var q=new vBulletin.history.instance(y);if(q.isEnabled()){e=q.getState();if(!e||b.isEmptyObject(e.data))e={from:"filter",page:1,tab:n,filters:vBulletin.getSelectedFilters(b("form.toolbar-filter-overlay",m))},q.setDefaultState(e,
document.title,location.href);q.setStateChange(function(p,J,K){p=q.getState();"filter"==p.data.from&&(q.log(p.data,p.title,p.url),n!=p.data.tab?vBulletin.selectTabByIndex.call(b(u).closest(".ui-tabs-nav"),u.index()):(p=b('.media-filter-overlay input[name="filter_time"][value="{0}"]'.format(p.data.filters.filter_time),m).prop("checked",!0),p.hasClass("js-default-checked")&&p.prop("defaultChecked")?b(".filtered-by .x",m).trigger("click"):p.trigger("change",[!0])))},"filter")}D==n&&(z=!1)}z&&0==b("#profileMediaDetailContainer .js-album-detail",
m).length&&(A||(A=vBulletin.media.calculatePhotosPerPage(vBulletin.media.TARGET_PHOTOS_PERPAGE)),vBulletin.media.loadGalleryById({nodeid:-2,channelid:pageData.channelid,pageno:1,dateFilter:b(".filter-options input[name=filter_time]:checked",m).val()||"time_lastweek",perpage:A},!0,{complete:function(){b(".profile-toolbar .media-toolbar-filter",k).removeClass("h-hide");G.updateLimit(H(g))}}))}});t=b(".conversation-list",a);vBulletin.conversation.initPollEvents(t);vBulletin.conversation.initContentEvents(t);
t.off("click",".js-comment-entry__post").on("click",".js-comment-entry__post",function(e){vBulletin.conversation.postComment.apply(this,[e,function(){d.updatePageNumber(1).applyFilters(!1,!0)}])});vBulletin.conversation.bindEditFormEventHandlers("all");b(document).offon("dblclick",".js-cell-topic a",e=>e.stopPropagation());b(document).offon("dblclick",".js-cell-topic",vBulletin.conversation.editTopicTitle);b(document).offon("dblclick",".js-open-close-topic",vBulletin.conversation.openOrCloseTopic)})})(jQuery);
