/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,q,w){if(f==Array.prototype||f==Object.prototype)return f;f[q]=w.value;return f};
$jscomp.getGlobal=function(f){f=["object"==typeof globalThis&&globalThis,f,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var q=0;q<f.length;++q){var w=f[q];if(w&&w.Math==Math)return w}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(f,q){var w=$jscomp.propertyToPolyfillSymbol[q];if(null==w)return f[q];w=f[w];return void 0!==w?w:f[q]};$jscomp.polyfill=function(f,q,w,A){q&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(f,q,w,A):$jscomp.polyfillUnisolated(f,q,w,A))};
$jscomp.polyfillUnisolated=function(f,q,w,A){w=$jscomp.global;f=f.split(".");for(A=0;A<f.length-1;A++){var D=f[A];if(!(D in w))return;w=w[D]}f=f[f.length-1];A=w[f];q=q(A);q!=A&&null!=q&&$jscomp.defineProperty(w,f,{configurable:!0,writable:!0,value:q})};
$jscomp.polyfillIsolated=function(f,q,w,A){var D=f.split(".");f=1===D.length;A=D[0];A=!f&&A in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var V=0;V<D.length-1;V++){var ca=D[V];if(!(ca in A))return;A=A[ca]}D=D[D.length-1];w=$jscomp.IS_SYMBOL_NATIVE&&"es6"===w?A[D]:null;q=q(w);null!=q&&(f?$jscomp.defineProperty($jscomp.polyfills,D,{configurable:!0,writable:!0,value:q}):q!==w&&(void 0===$jscomp.propertyToPolyfillSymbol[D]&&(w=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[D]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(D):$jscomp.POLYFILL_PREFIX+w+"$"+D),$jscomp.defineProperty(A,$jscomp.propertyToPolyfillSymbol[D],{configurable:!0,writable:!0,value:q})))};$jscomp.arrayIteratorImpl=function(f){var q=0;return function(){return q<f.length?{done:!1,value:f[q++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};$jscomp.makeIterator=function(f){var q="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];return q?q.call(f):$jscomp.arrayIterator(f)};
$jscomp.polyfill("Promise.allSettled",function(f){function q(A){return{status:"fulfilled",value:A}}function w(A){return{status:"rejected",reason:A}}return f?f:function(A){var D=this;A=Array.from(A,function(V){return D.resolve(V).then(q,w)});return D.all(A)}},"es_2020","es3");vBulletin.precache("error_fetching_avatar insert_video retrieve_remote_file_and_ref_local insert_page_break insert_preview_break wrap_x_tags".split(" "),"maxuserlength minuserlength threadpreview useemoji userbbcodeavatar allowedbbcodes".split(" "));
(function(f,q,w,A,D,V){function ca(a,b){var c=$("#"+a);if(c.is(".js-ckeditor-init-on-focus")||c.is(".js-ckeditor-focus-editor-after-init"))b.focus(),console.log("Ckeditor: Focus on editor for editor: {0}".format(a))}function oa(a){a+="";if(1E3<a.length||a.match(/<(table|ol|ul|li|img|hr)/)||a.match(/<(div|ol|ul|li|img) style="(margin-left|margin-right|text-align)/)||a.match(/<h3\s+class="wysiwyg_pagebreak">/))return!1;a=$("<div />").append(a).text();a=$.trim(a).replace(/&nbsp;|\s|\n|\t/g,"");return!a}
function ya(a,b){function c(){setTimeout(function(){var l=b.document?b.document.getBody():null;var h=e.closest(".b-editor").find(".cke_contents");var d=h.find(".b-editor__placeholder");0==d.length&&(d=$("<div />").text(g).addClass("b-editor__placeholder h-hide placeholder").appendTo(h));h=d;l&&l.$&&(l&&l.$&&!l.hasClass("js-vbulletin-has-placeholder-events")&&(console.log("Ckeditor: Placeholder text: attachBodyEventHandlers"),l.on("keydown",c),l.on("drop",c),l.addClass("js-vbulletin-has-placeholder-events")),
l=oa(l.getHtml()),h.toggleClass("h-hide",!l),k&&!l&&(l=e.closest(".js-content-entry"),l.find(".js-contententry-buttons").removeClass("h-hide"),q.hv.show(l.find(".js-human-verification")),k=!1))},10)}var e=$("#"+a),g=e.attr("placeholder"),k=!0;b=b||T(a);g&&(b.on("saveSnapshot",c),b.on("afterCommandExec",c),b.on("afterSetData",c),b.on("mode",function(l){"source"!=l.editor.mode&&c()}),$(b.editable().$).on("keydown",l=>{if(![8,13,37,38,39,40,46].includes(l.which)&&(l=b.getSelection())){var h=l.getRanges();
if(h&&h[0]){h=h[0];var d=h.getEnclosedNode();l.isFake&&d&&d.hasClass("cke_widget_image")&&(h.setEndAfter(d),h.collapse(),h.select())}}}),c())}function za(a,b){a=$("#"+a).closest(".b-editor");b=$("<button />").attr("type","button").addClass("b-button b-button--close-btn js-contententry-panel-x js-ckeditor-toolbar-close ").attr("tabindex","0");$("<span />").addClass("b-icon-fa fa-xmark b-icon-fa--24 fa-solid").appendTo(b);b.appendTo(a)}function Aa(a,b){a=T(a);b=c=>{q.togglePageScrolling(c)};a.on("dialogShow",
b.bind(null,!1));a.on("dialogHide",b.bind(null,!0))}function Ba(a,b,c,e,g,k){function l(n,t){if(!n)return-1;var I,z,H=!1;for(I=0;I<n.styleSheets.length;++I)try{$.each(E.contentsCss,function(K,M){(n.styleSheets[I].href+"").replace(/&amp;/g,"&")==(M+"").replace(/&amp;/g,"&")&&(H=!0)});var x=n.styleSheets[I].cssRules;for(z=0;z<x.length;++z)if(x[z].selectorText==t)return 1}catch(K){}return H?0:-1}function h(){++r;0<c&&0==l(d,g)?(--c,setTimeout(h,e)):(k.apply(b,[a,b]),console.log("Ckeditor: Init: verifyEditorCss: checkCss called {0} times".format(r)))}
var d=function(n){return n&&n.document&&n.document.$&&n.document.$.defaultView&&n.document.$.defaultView.frameElement?(n=n.document.$.defaultView.frameElement,n.contentDocument||n.contentWindow.document):!1}(b),r=0;h()}function Ca(a,b){b.on("mode",function(c){W(a).find(".js-smilie-container .js-smilie-button").toggleClass("b-smilie__button--disabled","source"==c.editor.mode)})}function Da(a,b){b.on("focus",function(c){c=W(a);c.find(".js-contententry-buttons").removeClass("h-hide");q.hv.show(c.find(".js-human-verification"))});
b.on("blur",function(c){c=W(a);var e=pa(a);D.populateMetaDescription(e,c)})}function ha(a,b){a=$(a);var c=a.closest(".b-editor"),e=b;"undefined"!=typeof e&&(e=!b);c.toggleClass("b-editor--cke-toolbar-is-hidden",e);b=!c.hasClass("b-editor--cke-toolbar-is-hidden");a.closest(".js-content-entry").find(".js-toolbar-secondary .b-toolbar__item").filter(function(){return"b-content-entry-panel__content--toggle-editor"==$(this).data("panel")}).toggleClass("b-toolbar__item--active",b)}function da(a){a=S(a);
return a in Z&&Z[a]}function T(a){a=S(a);return da(a)?Z[a]:null}function ia(a){var b=Math.floor(1E3*Math.random()),c=Date.now();return"temp_"+a+"_"+c+"_"+b}function qa(a){a.editor.on("langLoaded",function(b){b=1==$("#debug-information").length;var c="ckeditorPhrases"in vBulletin;f.vBulletin=f.vBulletin||{};if("langInit"in f.vBulletin||!c)!c&&b&&console.warn("Ckeditor phrases not loaded.");else{f.vBulletin.langInit=!0;if(b){function e(g,k){k=k||"";$.each(g,function(l,h){"object"==typeof h?e(g[l],k+
l+"."):g[l]="~~"+h+"~~ ("+k+l+")"})}e(f.lang.en)}$.each(q.ckeditorPhrases,function(e,g){for(var k=f.lang.en,l=e.split("."),h=0;h<l.length;h++){var d=l[h];if(h==l.length-1)k[d]=null===g?"Undefined: "+e:g;else{if("object"!=typeof k[d]||null===k[d])k[d]={};k=k[d]}}});f.lang.en.dir=pageData.textdirection}});f.removeListener("instanceCreated",qa)}function ra(a,b){$("#"+(b||a.editor).id+"_top .cke_button__table").hide()}function sa(a,b){var c=new Image;c.onload=function(){b.execCommand("autogrow_ifallowed")};
c.src=a}function ja(a){var b=pageData.baseurl+"/js/ckeditor/images/"+pageData.ckeditor_image_path+"/",c=ka.hidpi?"icons_hidpi.png":"icons.png";$.each([[".cke_dialog_close_button","close.png"],[".cke_notification_close","close.png"],[".cke_btn_reset","refresh.png"],[".cke_btn_locked","lock.png"],[".cke_btn_unlocked","lock-open.png"],[".cke_menuarrow","arrow.png"]],function(){a.find(this[0]).css("backgroundImage","url("+b+this[1]+")")});a.find(".cke_button_icon").each(function(){var e=$(this),g=e.attr("style"),
k=e.css("background-image");"none"==k||k.match(/js\/ckeditor\/plugins\/icons.png/)||k.match(/js\/ckeditor\/skins\/.*\/icons/)?e.attr("style",g+"background-image:url("+b+c+") !important;"):k.match(/js\/ckeditor\/images\/default\/vbulletin/)?(k=k.replace("js/ckeditor/images/default/vbulletin","js/ckeditor/images/"+pageData.ckeditor_image_path+"/vbulletin"),e.attr("style",g+"background-image:"+k+" !important;")):k.match(/js\/ckeditor\/images\/default\/icons/)?(g=g.replace("js/ckeditor/images/default/",
"js/ckeditor/images/"+pageData.ckeditor_image_path+"/"),e.attr("style",g)):k.match(/js\/ckeplugins\/image2\/icons\/image_default.png/)&&(g=g.replace("default",pageData.ckeditor_image_path),e.attr("style",g))})}function la(a,b){function c(){++e;e==E.contentsCss.length&&q.ensureFun(b)(a)}var e=0;setTimeout(()=>{var g=a.contents().find("head");if(!g.is(".js-added-extra-css")){for(var k of E.contentsCss){var l=$("<link />",{rel:"stylesheet",type:"text/css",href:k.replace(/&amp;/g,"&")});l.on("load",c);
g.append(l)}g.addClass("js-added-extra-css")}},0)}function ta(a){function b(h){var d=h.find(".js-vb-toolbar-more");1>d.length&&(d=$("<a />").addClass("js-vb-toolbar-more cke_button").css({borderRadius:"3px"}).on("click",function(r){$(r.target).closest(".js-vb-toolbar-more").toggleClass("cke_button_on");e()}),$("<span />").addClass("b-icon b-icon__ellipsis").appendTo(d),$("<div />").addClass("cke_toolgroup js-vb-toolbar-more-container").css({borderColor:"transparent",background:"transparent",marginRight:0,
marginLeft:0}).append(d).appendTo(h));return d}function c(h){var d=b(g);d.is(".cke_button_on")&&(h=0);k.addClass("h-hide-imp");$.each([0,1,2],function(r,n){l.filter(".js-button-priority-"+n).toggleClass("h-hide-imp",n<h)});l.not(".h-hide-imp").closest(".cke_toolbar").removeClass("h-hide-imp");d.toggleClass("h-hide-imp",!$("body").is(".l-small"))}function e(){var h=$("body"),d=h.is(".l-small");h=h.is(".l-xsmall");c(h?2:d?1:0)}var g=$("#cke_"+a+" .cke_toolbox"),k=g.find(".cke_toolbar"),l=g.find(".cke_button, .cke_combo");
(function(h){function d(n){var t=0;$.each(r,function(I,z){if(n.is("."+I))return t=z,!1});return t}if(!(0<h.filter(".js-button-priority-0").length)){var r={cke_button__source:0,cke_button__removeformat:0,cke_button__pastetext:0,cke_button__pastefromword:0,cke_combo__font:0,cke_combo__fontsize:0,cke_button__textcolor:1,cke_button__undo:1,cke_button__redo:1,cke_button__bold:2,cke_button__italic:2,cke_button__underline:2,cke_button__justifyleft:2,cke_button__justifycenter:2,cke_button__justifyright:2,
cke_button__numberedlist:2,cke_button__bulletedlist:2,cke_button__outdent:1,cke_button__indent:1,cke_button__link:0,cke_button__unlink:0,cke_button__image:2,cke_button__video:0,cke_button__emojipanel:2,cke_button__quote:0,cke_button__code:0,cke_button__html:0,cke_button__php:0,cke_button__table:0,cke_button__vbtable:0,cke_button__subscript:0,cke_button__superscript:0,cke_button__horizontalrule:0,cke_button__pagebreak:0,cke_button__previewbreak:0};h.each(function(){var n=$(this),t=d(n);n.addClass("js-button-priority-"+
t)})}})(l);e();(function(h){function d(r){function n(H){return H.find(".cke_toolbar, .js-vb-toolbar-more-container").filter(":visible")}var t=n(r);if(0<t.length){if(b(r).is(":visible")&&$("body").is(".l-small"))for(var I=10;0<--I&&0<t.length&&!q.Responsive.Debounce.areElementsOnOneRow(t);){t=r.find(".cke_button, .cke_combo").not(".js-vb-toolbar-more").filter(":visible").last().addClass("h-hide-imp").closest(".cke_toolbar");var z=0==t.find(".cke_button:visible, .cke_combo:visible").length;t.toggleClass("h-hide-imp",
z);t=n(r)}return!0}return!1}d(h)||setTimeout(function(){d(h)},0)})(g)}function Ea(a,b){b=b||T(a);b.fire("disableResize")}var X=f.dom.element,E=f.config,ka=f.env,Z={},S=w.verifyEditorId,ua=w.hideLoadingDialog,pa=w.getEditorContent,W=a=>$("#"+a).closest(".js-content-entry");E.allowedContent=!0;E.baseHref=pageData.baseurl+"/";var P=pageData.ckeditorCss;if("undefined"!=typeof P){"string"==typeof P&&(P=[P]);$.isArray(E.contentsCss)||(E.contentsCss=[]);for(var aa of P)E.contentsCss.push((q.isAbsoluteUrl(aa)?
"":E.baseHref)+aa)}P=A.get("allowedbbcodes");var Fa=P&1024,Ga=P&8192,ma="UTF-8"==document.characterSet.toUpperCase()&&A.get("useemoji");E.toolbar_vBulletinFull=(()=>{var a=[["EnhancedSource","Source","RemoveFormat"],["Font","FontSize"],["TextColor","-","Undo","Redo"],["Bold","Italic","Underline"],["JustifyLeft","JustifyCenter","JustifyRight"],["NumberedList","BulletedList","Outdent","Indent"],["Link","Email","Unlink"],["Quote"],["Code","Html","Php"],["Table","vBTable"],["Subscript","Superscript",
"HorizontalRule"]];"article"==pageData.channelType&&a.push(["PageBreak","PreviewBreak"]);if("customBbcode"in q){var b=[],c;for(c in q.customBbcode)c&&b.push(q.customBbcode[c].title);0<b.length&&(a[a.length]=b)}b=a[6];Fa&&b.push("Image");Ga&&b.push("Video");ma&&b.push("EmojiPanel");return a})();var va={Font:"font",FontSize:"size",TextColor:"color",Bold:"b",Italic:"i",Underline:"u",Subscript:"sub",Superscript:"sup",HorizontalRule:"hr",Table:"table",TableProperties:"table",DeleteTable:"table",InsertRowBefore:"table",
InsertRowAfter:"table",DeleteRow:"table",InsertColumnBefore:"table",InsertColumnAfter:"table",DeleteColumn:"table",JustifyLeft:"left",JustifyCenter:"center",JustifyRight:"right",NumberedList:"list",BulletedList:"list",Outdent:"indent",Indent:"indent",Link:"url",Email:"email",Unlink:"url",Image:"img",Quote:"quote",Code:"code",Html:"html",Php:"php"};E.smiley_path=pageData.baseurl_core+"/";E.enterMode=f.ENTER_BR;E.entities=!1;E.height=70;E.width="100%";E.autoGrow_minHeight=70;E.autoGrow_maxHeight=800;
E.autoGrow_viewportLimit=!0;E.image2_alignClasses=["align_left","align_center","align_right"];"undefined"==typeof D||"undefined"==typeof D.image2_showuploadcheckbox?(E.image2_showuploadcheckbox=!1,E.image2_checkuploadbydefault=!1):(E.image2_showuploadcheckbox=D.image2_showuploadcheckbox,E.image2_checkuploadbydefault=E.image2_showuploadcheckbox);E.contentsLangDirection=pageData.textdirection;E.language="en";E.defaultLanguage="en";E.language_list=["en"];E.skin="moono-lisa";var U={toolbar:"vBulletinFull",
customConfig:"",toolbarCanCollapse:!1,resize_dir:"vertical",removePlugins:"about,contextmenu,elementspath,link,smiley,liststyle,sourcearea,scayt",extraPlugins:"vblink,vbwrapbuttons,vbsource,videotag,autosave,autogrow,vbtable,resize,image2",pluginPath:pageData.baseurl+"/js/ckeplugins/",tabIndex:0,disableNativeSpellChecker:!1,filebrowserImageUploadUrl:pageData.baseurl+"/uploader/CKEditorInsertImage",filebrowserUploadMethod:"form"};ma||(U.removePlugins+=",emoji");for(var ba of U.extraPlugins.split(",")){P=
U.pluginPath+ba+"/";aa=P+"plugin.js";try{f.plugins.get(ba)||(console.log("Ckeditor: Plugin Loaded: "+aa),f.plugins.addExternal(ba,P,"plugin.js"))}catch(a){console.warn("Ckeditor: Plugin failed to load: "+aa)}}(()=>{var a=X.createFromHtml;X.createFromHtml=function(){function c(l,h){return l&&l.tagName&&l.tagName.toUpperCase()==h.toUpperCase()}var e=a.apply(this,arguments),g=e&&e.$?e.$:e,k=!1;c(g,"IFRAME")?k=g:g&&g.firstChild&&c(g.firstChild,"IFRAME")&&(k=g.firstChild);if(k)$(k).on("load",function(l){var h=
$(l.target);h.is(".cke_pasteframe")&&la(h);if(h.is(".cke_panel_frame")&&h.parent().is(".cke_emoji-panel")){h.parent().css("visibility","hidden");function d(){var t=$(".cke_button__emojipanel.cke_button_on").closest(".js-content-entry").find(".js-editor").attr("id");return T(t)}function r(t){var I=$(t.target||t.srcElement);if(I.data("cke-emoji-name")){t.preventDefault();var z=d();t.stopPropagation();t=z.focus;z.focus=function(){};z.insertHtml(I.data("cke-emoji-symbol"));z.focus=t}}function n(){h.parent().css("visibility",
"");var t=h.contents().find("body").get(0);t.removeEventListener("click",r,!0);t.addEventListener("click",r,!0)}la(h,n);setTimeout(n,2E3)}});return e};var b=X.prototype.setHtml;X.prototype.setHtml=function(c){var e=c.indexOf("cke_emoji-search");if(-1<e&&(e=c.indexOf("<input",e),-1<e&&(e=c.indexOf('type="search"',e),-1<e))){var g=c.substring(0,e);c=c.substring(e);c=g+'class="b-form-input__input" '+c}return b.call(this,c)}})();var wa="imgAlignment imgSize imgTitle imgDescription imgStyles imgLink imgLinkURL imgLinkTarget".split(" ");
f.on("instanceCreated",qa);ba=[function(a){var b=a.editor;a=$("#"+b.id+"_contents").children().filter((c,e)=>"IFRAME"==e.tagName);310>parseInt(b.config.width)&&(a.hide(),a.show());"ontouchstart"in document.documentElement&&a.get(0).contentWindow.scrollTo(0,10);b.dataProcessor.dataFilter.addRules({elements:{img:function(c){if(c.attributes["class"]&&-1!==c.attributes["class"].indexOf("js-need-data-att-update")){var e=c.attributes["data-tempid"],g=$("#"+b.element.getId()).closest("form");if(e&&g)for(var k=
0;k<wa.length;k++)if(cleanId=wa[k].substring(3).toLowerCase(),inputName="setting["+e+"]["+cleanId+"]",inputValue=($inputElement=g.find('input[name="'+inputName+'"]'))&&$inputElement.is(":enabled")&&$inputElement.val())switch(c.attributes["data-"+cleanId]=inputValue,cleanId){case "size":newImgSrc=c.attributes.src.replace(/&type=[A-Za-z]+/,"")+"&type="+inputValue;c.attributes.src=newImgSrc;break;case "alignment":c.attributes["class"]=c.attributes["class"].replace("align_left","").replace("align_center",
"").replace("align_right",""),"none"!==inputValue&&(c.attributes["class"]=c.attributes["class"]+" align_"+inputValue)}c.attributes["class"]=c.attributes["class"].replace("js-need-data-att-update","")}}}})},ra,function(a){function b(m){if(xa.includes(m.data.keyCode))return H&&(clearTimeout(H),H=0),c(m);H||(H=setTimeout(()=>{c(m)},300))}function c(m){if(!m.data.keyCode)return!0;var p=m.data.keyCode,v=e(m.editor),u=!0;if(xa.includes(p))if(p=m.data.keyCode,u=O.autocomplete("widget"),u.is(":visible")){switch(p){case 27:M=
!0;n();break;case 13:u.menu("select");break;case 38:u.menu("previous");break;case 40:u.menu("next")}m.cancel();m.stop();u=!1}else u=!0;M&&!v&&(M=!1);H=0;return u}function e(m){if(m.mode&&"source"==m.mode)return!1;var p=k(m),v="";p&&(v=p.tokentext);if(""!=v&&3<=v.length&&v.length<=Y[Q].max){if(v!=O.val())try{l(m,p)}catch(u){return!1}return!0}n();return!1}function g(m,p,v){var u=-1,F;for(F of p)u=Math.max(u,m.lastIndexOf(F,v));return u}function k(m){var p=m.getSelection();if(!p)return!1;p=p.getRanges();
if(0==p.length)return!1;p=p[0];p.collapse(!0);p.setStartAt(m.editable(),f.POSITION_AFTER_START);var v=p.endOffset,u=v,F=new f.dom.walker(p),C=0,y=F.previous();--C;var L=y;if(!y||y.type===f.NODE_COMMENT||y.equals(m.editable()))return!1;m=y.getText();var B=g(m,ea,u);if(-1==B)for(;;){var G=F.previous();--C;if(G&&G.type==f.NODE_TEXT){var N=G.getText();B=g(N,ea);m=N+m;u+=N.length;if(-1!=B){L=G;break}}else break}if(-1==B||B==m.length-1)return!1;N="[\\s"+String.fromCharCode(8203)+"]";if(0==B&&(G=F.previous(),
--C,G)){var J=G.getText();if(""!=J&&!(new RegExp(N+$)).test(J))return!1;G=G.$.tagName.toUpperCase();if("BR"!=G&&"HR"!=G)return!1}if(0<B&&!(new RegExp(N)).test(m[B-1]))return!1;Q=m[B];N=B;for(G=m;;)if(J=F.previous(),--C,J)J&&J.type==f.NODE_TEXT&&(J=J.getText(),G=J+G,N+=J.length);else break;G=G.substr(0,N);N=!1;J={CODE_TAG:0,PHP_TAG:0,HTML_TAG:0};for(var Ha=/\[(\/?)(noparse|code|php|html)\]/gi,R,fa;R=Ha.exec(G);)if(fa="/"==R[1],R=R[2].toUpperCase(),N)"NOPARSE"==R&&fa&&(N=!1);else switch(R){case "NOPARSE":fa||
(N=!0);break;case "CODE":case "PHP":case "HTML":R+="_TAG",fa?0<J[R]&&--J[R]:++J[R]}if(N||0<J.CODE_TAG||0<J.PHP_TAG||0<J.HTML_TAG)return!1;for(;0>C;)F.next(),++C;for(C=y;;)if((y=F.next())&&y.type==f.NODE_TEXT)G=y.getText(),C=y,v=G.length,""!=G&&(m+=G,u+=G.length);else break;p.setStart(L,B);p.setEnd(C,v);v=m.substr(B+1);v=v.substr(0,u-B-1);v=$.trim(v);return{tokentext:v,range:p}}function l(m,p){function v(G,N){for(var J of G.childNodes){if(J.isEqualNode(N))return J;if(G=v(J,N))return G}return null}
if(M)n();else{var u=p.tokentext;p=p.range;var F=p.startContainer,C=p.endContainer;m=W(S(m));var y=F.getParent(),L=y.$.cloneNode(!0);y=y.getDocumentPosition();var B=document.createRange();B.setStart(v(L,F.$),p.startOffset);B.setEnd(v(L,C.$),p.endOffset);B.insertNode($('<span id="vb-get-pos">x</span>').get(0));B=m.find(".cke_wysiwyg_frame").offset();C=m.offset();F=C.top;C=C.left;L=$("<div />").css({position:"absolute",top:B.top-F+y.y,left:B.left-C.left+y.x,border:"1px solid red",background:"#CCC",zIndex:"999"}).appendTo(m).append(...L.childNodes);
y=$("#vb-get-pos",m);m=y.offset();y=y.outerHeight();L.remove();O.css({top:m.top-F+y,left:m.left-C});O.val(u);O.autocomplete("search",u);O.data("range",p)}}function h(m,p){function v(C){p(C);setTimeout(function(){$(".ui-autocomplete",F).find(".ui-menu-item").on("mouseout",()=>!1)},10)}var u=m.term,F=O.closest(".js-content-entry");K[Q].some(C=>0==u.indexOf(C))?n():u in x[Q]?v(x[Q][u]):q.AJAX({call:Y[Q].fetch,data:{searchStr:u,limitnumber:15},success:function(C){if(Array.isArray(C.suggestions)){var y=
[];$.each(C.suggestions,function(L,B){L={label:B.title,value:B.title,userid:B.id};B.hasOwnProperty("id")&&B.id&&(L.id=B.id);B.hasOwnProperty("htmllabel")&&(L.htmllabel=B.htmllabel);y.push(L)});0<y.length?(v(y),x[Q][u]=y):(K[Q].push(u),n())}},error_phrase:"error_getting_suggestions"})}function d(m,p,v){p=v.item.value;v=O.data("range");m.insertHtml("","html",O.data("range"));var u=Y[Q],F=u.render;a:{for(y in x[Q])for(var C of x[Q][y])if(C.value==p){var y=C.userid;break a}y=!1}F.call(u,m,v,p,y);H=0;
n()}function r(m){H=0}function n(){O.val("").autocomplete("close")}function t(m,p,v){v=X.createFromHtml(v);var u=X.createFromHtml("&nbsp;");p.insertNode(u);p.insertNode(v);p.moveToElementEditEnd(u);m.getSelection().selectRanges([p]);return v}function I(m,p,v,u){u="c"==u[0]?'data-nodeid="'+u.substring(1)+'"':"";t(m,p,'<a href="#" '+u+'class="b-bbcode__hashtag">'+v+"</a>&nbsp;")}function z(m,p,v,u){var F=t(m,p,'<a href="#" class="b-bbcode-user js-bbcode-user">'+q.htmlEntities(v)+"</a>");if(A.get("userbbcodeavatar")){function y(L,
B,G){B.addClass("b-bbcode-user--has-avatar");$(B.$).css("background-image","url('"+pageData.baseurl_core+"/"+G+"')")}var C="userid_"+u;C in na?y(m,F,na[C]):q.AJAX({call:"/ajax/api/user/fetchAvatar",data:{userid:u,thumb:!0},success:function(L){if(L=L.avatarpath)y(m,F,L),na[C]=L},error_phrase:"error_fetching_avatar"})}}var H=0,x={},K=[],M=!1,na={},Y={},ea=[],Q="",xa=[13,27,38,40],O;(function(m){if(m){var p=D.bbcode_enabled;user=p.user;hashtag=p.hashtag;if(user||hashtag){user&&(Y["@"]={fetch:"/ajax/api/user/getAutocomplete",
render:z,max:A.get("maxuserlength")});hashtag&&(Y["#"]={fetch:"/create-content/hashtag-autocomplete",render:I,max:256});ea=Object.keys(Y);for(var v of ea)x[v]={},K[v]=[];m.on("key",b,null,null,1);m.document.on("click",function(u){e(m)});p=W(S(m)).css("position","relative");O=$('<input type="text" style="position:absolute;top:0px;left:0px;visibility:hidden;width:1px;height:1px;" />');O.appendTo(p).autocomplete({appendTo:p,autoFocus:!0,delay:0,minLength:3,source:h,select:d.bind(null,m),close:r}).autocomplete("instance")._renderItem=
function(u,F){F=F.hasOwnProperty("htmllabel")?$("<div>").html(F.htmllabel):$("<div>").text(F.label);return $("<li>").append(F).appendTo(u)};m.on("blur",n)}}else console.log("Editor instance in empty")})(a.editor)},function(a){async function b(d,r){try{let {panelitem:n,upload:{filedataid:t,name:I}}=await V.uploadFile(d[1],r),z=ia(t),H='<img class="bbcode-attachment" title="{3}" src="{0}" {1}="{2}" /> '.format(pageData.baseurl+"/filedata/fetch?filedataid="+t+"&type=full","data-tempid",z,I);n.data("first-insert-id",
z);D.updatePanelItemData(n,z,t,I);D.openAttachmentPanel(r);replaceElement(d[0],H)}catch(n){throw replaceElement(d[0],""),n;}}function c(d,r){var n=$(d.editable().$),t=n.clone(!0).removeAttr("id");n.css("opacity",0);d.execCommand("autogrow_disable");n.after(t);var I="zz"+Math.random().toString(36)+"zz";d.insertHtml(r+" "+I);r=d.getData();var z=()=>{t.remove();n.css("opacity","");d.execCommand("autogrow_enable");d.execCommand("autogrow_ifallowed");l=!1};q.AJAX({call:"/create-content/cleanpastedhtml",
data:{nodeid:pageData.nodeid,data:r},success:H=>{var x=d.createRange();x.selectNodeContents(d.editable());x.select();d.insertHtml(H.data);if(H=e(d.editable(),I)){var K=H[0],M=H[1];H=H[2];x=d.createRange();x.setStart(K,M);x.setEnd(K,M+H);x.select();d.insertHtml("&ZeroWidthSpace;")}z()},after_error:z})}function e(d,r){if(3==d.type){var n=d.getText(),t=n.indexOf(r);if(-1==t)return!1;r=r.length;0!=t&&" "==n.charAt(t-1)&&(t--,r++);return-1!=t?[d,t,r]:!1}if(d.getChildren)for(n of d.getChildren().toArray())if(d=
e(n,r))return d;return!1}var g=a.editor,k=f.htmlParser,l=!1,h=d=>{var r=new k.basicWriter;d.writeHtml(r);return r.getHtml()};replaceElement=(d,r)=>d.replaceWith(new k.text(r));wrapElement=(d,r,n)=>replaceElement(d,r+d.getHtml()+n);g.on("paste",d=>{var r=d.data;if(l)r.dataValue="",d.cancel();else{l=!0;var n=r.dataTransfer,t=n.getFilesCount(),I=[];for(var z=0;z<t;z++)n.getFile(z).type.match(RegExp("^image/"))&&(r.dataValue+='<img style="display:none" src="" data-index="'+z+'" />');z=new k.filter({elements:{pre:x=>
{replaceElement(x,x.getHtml().replace(/\r?\n/g,"$&<br>"))},p:x=>{var K="<br>",M="<br>";previous=x.previous;next=x.next;previous&&previous.type==f.NODE_TEXT?K="<br><br>":previous&&previous.type==f.NODE_ELEMENT&&"p"==previous.name||null===previous&&(K="");next&&next.type==f.NODE_TEXT?M="<br><br>":next&&next.type==f.NODE_ELEMENT&&"p"==next.name?M="":null===x.next&&(M="");wrapElement(x,K,M)},div:x=>{wrapElement(x,"<br>","<br>")},img:x=>{let K=x.attributes.src;if(""==K){let M=x.attributes["data-index"];
if(M){I.push([x,n.getFile(M)]);return}}0<t?replaceElement(x,""):K.match(/^data:/)&&I.push([x,K])}}});var H=k.fragment.fromHtml(r.dataValue);H.filter(z);if(0==I.length)z=h(H),z.match(/<[a-z]/i)?(r.dataValue="",d.cancel(),c(g,z)):(r.dataValue=z,l=!1);else{r.dataValue="";d.cancel();let x=W(S(g));Promise.allSettled(I.map(K=>b(K,x))).then(()=>{var K=h(H);c(g,K)})}}})},function(a){ja($(a.editor.container.$))},function(a){function b(c){var e=null;try{e=c.element.$.children[0]}catch(g){}la($(e))}a.editor.on("menuShow",
function(c){b(c.data[0])});f.ui.on("ready",function(c){b(c.data._.panel)})},function(a){var b=S(a.editor);ta(b);q.Responsive.Debounce.registerCallback(function(){ta(b)})},function(a){if(ma){var b=a.editor;a=S(b);$("#cke_"+a).find(".cke_button__emojipanel").one("click",()=>{b.focus()})}}];for(var Ia of ba)f.on("instanceReady",Ia);f.on("dialogDefinition",function(a){var b=a.data;a=b.definition;switch(b.name){case "table":case "tableProperties":b=a.contents;var c=a.getContents("info");for(e of["txtCaption",
"txtSummary","selHeaders","txtCellSpace"])c.remove(e);var e=b[0].elements;delete e[1];delete e[2];a.minHeight=200;delete b[1]}a.dialog.on("load",function(){var g=$(this.definition.dialog.parts.dialog.$);g.addClass("ckeditor-dialog");g.find('input[type="text"]').addClass("b-form-input__input b-form-input__input--border-box");g.find(".cke_dialog_ui_button").each((k,l)=>{k=$(l);k.parent().closest(".cke_dialog_ui_button").length||k.addClass("b-button").addClass(k.is(".cke_dialog_ui_button_ok")?"b-button--primary":
"b-button--secondary")});ja(g)});a.dialog.on("show",function(){var g=$(this.definition.dialog.parts.dialog.$);setTimeout(function(){g.find(".cke_pasteframe").addClass("b-editor__pasteframe")},0)})});$.extend(w,{config:U,fixTableFunctionality:ra,autogrowEditorOnImageLoad:sa,isEditorEmpty:function(a){a=pa(a);return!1===a||""===a?!0:oa(a)},resetEditor:function(a,b){a=S(a);b=b||function(){};a=T(a);if(!a)return!1;a.setData("",b)},toggleToolbar:ha,doInitEditor:function(a,b){if(ka.mobile&&!ka.isCompatible)console.log("Ckeditor: Not supported on this mobile device"),
ua(a);else{console.log("Ckeditor: Initializing editor: {0}".format(a));var c=$("#"+a);c.trigger("beforeInit",[a]);if(da(a))console.log("The editor ({0}) already exists.".format(a));else{var e=c.data("disable-features");if(e)if("all"==e)console.log("Ckeditor: Disabling features: All"),U.toolbar=[];else{e=e.split(",");var g=E["toolbar_"+U.toolbar],k,l;for(k=0;k<g.length;k++)for(l=0;l<g[k].length;l++){var h=g[k][l];0!=h.length&&"-"!=h&&va[h]&&0<=jQuery.inArray(va[h],e)&&(console.log("Ckeditor: Disabling feature: "+
h),delete g[k][l])}for(k=0;k<g.length;k++)g[k]=g[k].filter(function(d){return d})}ha(c,!1);c.ckeditor(function(){ua(a);Z[a]=this;ya(a,this);Da(a,this);ca(a,this);za(a,this);Ca(a,this);Aa(a,this);try{this._.magiclineBackdoor.that.triggers.h3=1,console.log("Ckeditor: Added h3 to ckeditor magicline triggers.")}catch(d){console.warn("Ckeditor: Unable to add h3 to ckeditor magicline triggers. Error: {0}".format(d))}console.log("Ckeditor: Editor initialized: {0}".format(a));c.closest("form").attr("ck-editorid",
a);c.data("disable-resize")&&Ea(a,this);D.restoreEditorState(a);Ba(a,this,10,100,"hr.previewbreak",function(d,r){c.trigger("afterInit",[d]);w.fireCallbacks(d,b,"success",this)})},U)}}},editorExists:da,getEditor:T,closeFileDialog:function(a,b){var c=T(a);if(c){var e=f.dialog.getCurrent();if("image2"==e.getName())for(var g=0;g<b.length;g++){var k=b[g].url,l=b[g].filedataid,h=b[g].name,d=ia(l);l&&k&&d&&(sa(k,c),e.widget.setData("tempid",d),""!=h&&""==e.getValueOf("info","title")&&(e.widget.setData("title",
h),e.setValueOf("info","title",h)),"function"==typeof e.checkUrlSrcAndRemoteCheckbox&&e.checkUrlSrcAndRemoteCheckbox(),k=l,l=$("#"+a).closest("form"),filedataObj={filedataid:k,filename:h||""},D.addAttachmentItemPanel(l,d||"",filedataObj))}}},destroyEditor:function(a){console.log("Ckeditor: Destroying editor: {0}".format(a));a=S(a);if(da(a)){try{T(a).destroy()}catch(b){}Z[a]=null;ha($("#"+a),!1);return!0}console.warn("Ckeditor: Not destroyed, because editor {0} does not exist.".format(a));return!1},
generateTempAttachmentId:ia,modifyImagePaths:ja})})(CKEDITOR,vBulletin,vBulletin.ckeditor,vBulletin.options,vBulletin.contentEntryBox,vBulletin.upload);
