/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache("channel_deleted_confirmation confirm_delete confirm_delete_channel_has_x_posts_y_forums emails_sent_successfully enter_email_message_and_recipients forum_created forum_deleted forum_description_updated forum_title_updated home_page_changed logo_changed no_permission unable_to_update_home_page_route".split(" "),[]);
(function(a){var g=!1,m=function(b){var c=this;vBulletin.assertUserHasAdminPermission("canusesitebuilder",c,function(){var d=a(".js-top-menu-tab--quicksetup").get(0);vBulletin.sitebuilder.activateSB.apply(d);h.call(c,b)});return!1},h=function(b){var c=a(this),d=a(document.body),e=!c.hasClass("b-top-menu__item-link--selected");e?(d.addClass("js-edit-mode-style"),a(".js-site-config__upload_file").trigger("click"),a(".js-config-site-panel").css("display","none").removeClass("h-hide").slideDown(400,n)):
a(".js-config-site-panel").slideUp(function(){var f=!e;a(document).trigger("vb-toggle-sitebuilder-menu",{enableButtons:f,currentButton:c});d.removeClass("js-edit-mode-style");f=new URL(location.href);f.searchParams.delete("adminAction");location.replace(f.href)})},p=function(b){b=a(b.target).is(".js-site-config__upload_file");a(".js-site-config__urlForm").toggleClass("h-hide",b);a(".js-site-config__fileForm").toggleClass("h-hide",!b);a(".js-site-config__upload_"+(b?"url":"file")).prop("checked",!1)},
q=function(){h.call(a(".js-top-menu-tab--quicksetup").get(0))},r=function(){a(".js-config-site-panel").fileupload({dropZone:a(".js-site-config__upload-logo"),dataType:"json",add:function(b,c){a("body").css("cursor","wait");a(".js-config-site-panel").find(".js-upload-progress:first").removeClass("h-hide");c.submit()},done:function(b,c){c.result&&c.result.filedataid?(a("#header .site-logo img").attr({src:c.result.imageUrl,"data-fileid":c.result.filedataid,"data-styleselection":a("#edit-site-logo-dialog .styleselection:checked").val()}),
vBulletin.flashPhrase("logo_changed")):vBulletin.error("error","error_uploading_logo")},fail:function(b,c){vBulletin.error("error","error_uploading_logo")},always:function(b,c){a("body").css("cursor","auto");a(".js-config-site-panel").find(".js-upload-progress:first").addClass("h-hide")}})},t=function(){var b=a(".js-site-config__url_form .js-site-config__url"),c=a.trim(b.val());if(c){a("body").css("cursor","wait");var d=a(this).closest(".dialog-content").find(".js-upload-progress:last").removeClass("h-hide");
vBulletin.AJAX({call:"/uploader/upload-logo-url",data:{urlupload:c},complete:function(){a("body").css("cursor","auto");d.addClass("h-hide")},success:function(e){a("#header .site-logo img").attr({src:e.imageUrl,"data-fileid":e.filedataid,"data-styleselection":a("#edit-site-logo-dialog .styleselection:checked").val()});vBulletin.flashPhrase("logo_changed")},error_phrase:"error_processing_site_logo"})}else b.trigger("focus")},w=function(){var b=a(".js-site-config__homepage-container");vBulletin.AJAX({call:"/ajax/render/admin_configuresite_homepage_list",
data:{isAjaxTemplateRenderWithData:!0},error:function(){var c=a("<div />").addClass("b-config-site__message").text(vBulletin.phrase.get("error_fetching_home_page_options"));b.html(c)},success:function(c){b.html(c.template);a(document).off("click",".js-site-config__homepage-opt").on("click",".js-site-config__homepage-opt",u);a(document).off("click",".js-site-config__revert-to-custom").on("click",".js-site-config__revert-to-custom",v);vBulletin.vBScroller&&vBulletin.vBScroller.initializeScroller&&(c=
b.find(".js-vbscroller-wrapper"),vBulletin.vBScroller.initializeScroller(c))}})},u=function(b){var c=a(b.target).closest(".js-site-config__homepage-opt"),d=c.data("routeid");c.is(".b-config-site__homepage-opt--selected")||vBulletin.AJAX({call:"/ajax/api/route/setAsHomeRoute",data:{routeid:d},error_phrase:"unable_to_update_home_page_route",success:function(e){e.success&&e.routeid==d?(a(".js-site-config__homepage-opt").removeClass("b-config-site__homepage-opt--selected"),c.addClass("b-config-site__homepage-opt--selected"),
a(".js-site-config__homepage-custom-current").addClass("h-hide"),a(".js-site-config__homepage-custom-prev").removeClass("h-hide"),vBulletin.flashPhrase("home_page_changed")):vBulletin.error("error","unable_to_update_home_page_route")}})},v=function(b){var c=a(b.target).data("routeid");vBulletin.AJAX({call:"/ajax/api/route/setAsHomeRoute",data:{routeid:c},error_phrase:"unable_to_update_home_page_route",success:function(d){d.success&&d.routeid==c?(a(".js-site-config__homepage-opt").removeClass("b-config-site__homepage-opt--selected"),
a(".js-site-config__homepage-custom-current").removeClass("h-hide"),a(".js-site-config__homepage-custom-prev").addClass("h-hide")):vBulletin.error("error","unable_to_update_home_page_route")}});return!1},x=function(b){var c=a(b.target),d=c.data("nodeid");if("undefined"==typeof d)a(b.currentTarget).hide();else{var e=c.data("postcount")||0;vBulletin.AJAX({call:"/ajax/api/search/getInitialResults",data:{search_json:{channel:d,type:"vBForum_Channel"},perpage:100},title_phrase:"error",error_phrase:"error_deleting_forum",
success:function(f){subforums=f&&f.totalRecords?f.totalRecords:0;openConfirmDialog({title:vBulletin.phrase.get("confirm_delete"),message:vBulletin.phrase.get("confirm_delete_channel_has_x_posts_y_forums",e,subforums),iconType:"warning",onClickYes:function(){vBulletin.AJAX({call:"/ajax/api/content_channel/delete",data:{nodeid:d},title_phrase:"error",error_phrase:"error_deleting_forum",success:function(A){a(b.target).closest(".js-site-config__forum-record").html(vBulletin.phrase.get("channel_deleted_confirmation")).addClass("h-margin-bottom-xxl");
vBulletin.flashPhrase("forum_deleted")}})}})}})}},k=function(){var b=a(".js-site-config__more-forums-sample").find(".js-site-config__forum-record").clone();a(".js-site-config__forum-div").append(b);b.find(".autogrow").autogrow()},y=function(b){var c=a(b.target);b=c.val();var d=c.data("nodeid");""!=b&&(d?vBulletin.AJAX({call:"/ajax/api/content_channel/update",title_phrase:"error",error_phrase:"error_updating_forum",data:{nodeid:d,data:{title:b}},success:function(e){vBulletin.flashPhrase("forum_title_updated")}}):
(b={title:b},d=c.closest(".js-site-config__forum-record").find(".b-config-site__forum-desc"),0<d.length&&(b.description=d.val()),vBulletin.AJAX({call:"/createcontent/channel",title_phrase:"error",error_phrase:"error_updating_forum",data:b,success:function(e){c.data("nodeid",e.nodeid);e.candelete&&c.closest(".js-site-config__forum-record").find(".b-config-site__delete-link").removeClass("h-hide h-hide-imp").data("nodeid",e.nodeid);a(document).trigger("vbulletin-quicksetup-forumcreated",{nodeid:e.nodeid});
vBulletin.flashPhrase("forum_created")}})))},l=function(b){var c=a(b.target),d=c.closest(".js-site-config__forum-record").find(".b-config-site__forum-title");if(d.data("nodeid"))vBulletin.AJAX({call:"/ajax/api/content_channel/update",title_phrase:"error",error_phrase:"error_updating_forum",data:{nodeid:d.data("nodeid"),data:{description:c.val()}},success:function(f){vBulletin.flashPhrase("forum_description_updated")}});else{var e=this;a(document).one("vbulletin-quicksetup-forumcreated",function(){l.call(e,
b)})}},z=function(){var b=a(".b-config-site__email-list").val(),c=a(".b-config-site__email-title").val(),d=a(".b-config-site__email-content").val();4>b.length||4>d.length?vBulletin.error("error","enter_message_and_recipients"):vBulletin.AJAX({call:"/ajax/api/mail/send",title_phrase:"error",error_phrase:"error_sending_email",data:{to:b,subject:c,message:d},success:function(e){e.success?vBulletin.flashPhrase("emails_sent_successfully"):e.message&&vBulletin.error("error",e.message)}})},n=function(){if(!g){r();
var b=a(document);b.off("click",".js-site-config__upload_file, .js-site-config__upload_url").on("click",".js-site-config__upload_file, .js-site-config__upload_url",p);b.off("click",".js-site-config__btn-url").on("click",".js-site-config__btn-url",t);b.off("click",".b-config-site__delete-link").on("click",".b-config-site__delete-link",x);b.off("click",".js-site-config__more-forums").on("click",".js-site-config__more-forums",k);b.off("change",".b-config-site__forum-title").on("change",".b-config-site__forum-title",
y);b.off("change",".b-config-site__forum-desc").on("change",".b-config-site__forum-desc",l);b.off("click",".js-site-config__send-btn").on("click",".js-site-config__send-btn",z);b.off("click",".js-site-config__close-btn").on("click",".js-site-config__close-btn",q);a(".js-config-site-panel .autogrow").autogrow().trigger("input");k();1==a(".js-config-site-panel .js-theme-selector__container").length&&vBulletin.sitebuilder.initThemesInQuickConfig();w();g=!0}};a(function(){a(document).on("vb-sitebuilder-panel--quicksetup",
m)})})(jQuery);
