/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache("all_changes_made_will_be_lost_would_you_like_to_continue attach_video close_preview enter_link_title enter_photo_gallery_title enter_poll_question enter_title error_x_while_saving_content event_invalid_enddate follow following following_pending html_off html_on invalid_user_filedata loading max_attachments_reached no_photos_or_albums no_post_content_to_preview please_enter_message_x_chars please_enter_video_url preview preview_map saving select_from_photo_album unexpected_error write_something_here write_something_here_optional x_selected your_post_is_now_being_reviewed_and_waiting_for_moderators_approval".split(" "),
["commentminchars","threadpreview"]);vBulletin.ensureObj("contentEntryBox");
$.extend(vBulletin.contentEntryBox,((p,u,I,M,x,U)=>{function N(a,b){return $("<input />").attr({type:"hidden",name:a}).val(b)}function oa(a){var b=$(this),c=b.closest("form");a=c.find('input[name="parentid"]').val();var d=c.find('input[name="channelid"]').val(),f=c.find('input[name="nodeid"]'),e=c.data("content-type")||"",h=c.find(".js-editor").attr("id");h=u.getEditorContent(h);var g=c.find('.tag-editor-wrapper .tag-list input[name="tags"]').val(),l=c.find('select[name="htmlstate"]').val();if("text"==
e&&""==h)p.error("preview","no_post_content_to_preview");else{var m={parentid:a,channelid:d,pagedata:pageData,conversationtype:e,posttags:g,rawtext:h,htmlstate:l,disable_bbcode:S,isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0};f.length&&(m.nodeid=f.val());if("gallery"==e){var n=[];$('.js-photo-postdata input[name="filedataid[]"]',c).each(function(){n.push(this.value);m["title_"+this.value]=$('.js-photo-postdata input[name="title_'+this.value+'"]',c).val()||""});m.filedataid=n}"link"==e&&
(m.link={},m.link.title=$(".js-link-title",c).val(),m.link.meta=$(".js-link-meta",c).val(),m.link.url=$(".js-link-url",c).val(),m.link.url_image=$(".js-link-preview-checkbox",c).is(":checked")?0:$(".js-link-url-image:checked",c).val());"poll"==e&&(m.poll={options:[],mutliple:$('input[name="multiple"]',c).is(":checked")?1:0},$(".js-poll-option",c).each(function(){m.poll.options.push(this.value)}));"video"==e&&(m.video={},m.video.title=$(".js-link-title",c).val(),m.video.meta=$(".js-link-meta",c).val(),
m.video.url=$(".js-link-url",c).val(),m.video.items=[],$(".js-video-url",c).each(function(){m.video.items.push(this.value)}));"event"==e&&($.each(["eventstartdate","eventenddate","location"],function(k,q){k=$('input[name="'+q+'"]',c);k.length&&(m[q]=k.val())}),$.each(["is_all_day","ignoredst"],function(k,q){k=$('input[name="'+q+'"]:checked',c);k.length&&(m[q]=k.val())}));b.prop("disabled",!0);p.AJAX({call:"/create-content/load-preview",data:m,success:function(k){var q=$("<div />").attr("id","preview-overlay").addClass("h-hide").append($("<div />").addClass("dialog-content")).append($("<div />").addClass("b-button-group h-margin-bottom-m")).appendTo("body");
$("<ul />").addClass("conversation-list list-container stream-view activity-view h-clearfix b-post--preview").appendTo($(".dialog-content",q));$("<button />").addClass("js-content-entry-preview-submit b-button b-button--primary").text($(".js-content-entry-submit",c).text()).on("click",()=>{c.trigger("submit");q.dialog("close")}).appendTo($(".b-button-group",q));$("<button />").addClass("js-content-entry-preview-close b-button").text(x.get("close")).on("click",()=>{q.dialog("close")}).appendTo($(".b-button-group",
q));$(k.template).appendTo($("ul",q));$(".js-post .js-post__content-text",q).html(k.parsedText);$(".dialog-content a",q).addClass("h-disabled").on("click",()=>!1);$(".dialog-content .js-button, .dialog-content .b-button, .dialog-content button",q).prop("disabled",!0);q.removeClass("h-hide").dialog({title:x.get("preview"),autoOpen:!0,modal:!0,resizable:!1,closeOnEscape:!0,showCloseButton:!1,width:800,minHeight:0,dialogClass:"preview-dialog-container dialog-container dialog-box",open:()=>{$(".b-button--primary",
q).trigger("focus")},close:()=>{q.dialog("destroy").remove()}})},title_phrase:"preview",error_phrase:"error_loading_preview",complete:()=>{b.prop("disabled",!1)}})}}function pa(a){var b=$(this).closest("form");0==b.find('input[name="save_draft"]').length&&N("save_draft",1).appendTo(b);setTimeout(function(){b.find('input[name="save_draft"]').remove()},100)}function qa(a){a=$(this);var b=a.closest("form");ba(b,a)}function ba(a,b,c){var d=a.find('input[name="parentid"]').val(),f=a.find('input[name="channelid"]').val(),
e=pageData.lastloadtime||pageData.current_server_datetime,h=0,g=pageData.past_page_limit||!1,l=a.closest(".conversation-content-widget");0==l.length&&(l=a.closest("#activities-tab"));var m=$(".conversation-list",l),n="stream",k={"activity-view":"activity-stream","full-activity-view":"full-activity-stream","thread-view":"thread"};for(B in k)m.hasClass(B)&&(n=k[B]);var q=$(".list-container",l);l=$(".list-container>li.b-post",l);m=l.length;k=parseInt($('form.toolbar-filter-overlay input[name="pagenum"]').val())||
1;var B=Number($("form.pagenav-form span.pagetotal").text())||0;var E=[];l.each((r,t)=>{(r=$(t).data("node-id"))&&E.push(r);(t=$(t).data("node-publishdate"))&&t>h&&(h=t)});d={parentid:d,channelid:f,newreplyid:c,loadednodes:E,lastpublishdate:h,lastloadtime:e,pageload_servertime:pageData.current_server_datetime,view:n,currentpage:k,pagetotal:B,postcount:m,postsperpage:I.POSTS_PER_PAGE,commentsperpage:I.COMMENTS_PER_PAGE,past_page_limit_aware:g};p.loadingIndicator.show();b&&b.prop("disabled",!0);p.AJAX({call:"/create-content/loadnewposts",
data:d,success:function(r){if(r.redirect)location.href=r.redirect;else if(pageData.lastloadtime=r.timenow,r.past_page_limit&&(pageData.past_page_limit=r.past_page_limit),r.template){if(1<q.length){var t=a.closest(".tab");q=0<t.length?$(".list-container",t):$(".list-container",$(".tab.media-tab"))}r=$(r.template);q.hasClass("ajax-order-newest-first")&&0<$("li.list-item:first",q).length?$("li.list-item:first",q).before(r):(q.append(r),t=r.closest(".ui-tabs-panel").find(".conversation-toolbar-wrapper"),
t.hasClass("scrolltofixed-floating")&&(t=t.data("object-instance"))&&t.addLimit(r.filter((J,z)=>z.nodeType==Node.ELEMENT_NODE).outerHeight(!0)),c&&p.scrollToAnchor("#post"+c));(t=pageData.nodeid)&&("0"==pageData.threadmarking||"0"==pageData.userid)&&p.markRead(t);$(document).trigger("vb-loadnewposts",{insertedHtml:r})}},complete:function(){b&&b.prop("disabled",!1);p.loadingIndicator.hide()}})}function ra(a){var b=$(this),c=$(this.form).data("content-type"),d=c,f=b.closest(".js-content-entry");a=b.closest(".js-post");
var e=a.data("node-id");e||(e=a.data("nodeid"));"comment"!=c&&"media"!=c&&(1==b.closest('.list-item-body-wrapper[data-node-type="visitorMessage"], .js-post__content-wrapper[data-node-type="visitorMessage"]').length?c="visitorMessage":1==b.closest(".js-conversation-starter").length?(c=1==b.closest(".conversation-list.blog-list").length?"blog":"topic",c=1==b.closest(".conversation-list.article-list").length?"article":"topic"):c="reply");x.register["delete_x","posttype_"+c];a=x.get("delete_x",x.get("posttype_"+
c));U.openTemplateConfirmDialog(p.ajaxtools,{title:a,width:500,dialogClass:"no-buttons-while-loading",yesPhrase:a,noPhrase:"cancel",onClickYes:function(h){var g=f.find("form");if(!1!==p.triggerHandler.apply(g.get(0),["beforeDelete"])){h=h.find(".delete-posts-form");var l=h.find("input:radio[name=deletetype]:checked").val()||1,m={hard:2==l?1:0,reason:h.find(":input[name=deletereason]").val(),nodeids:e};p.AJAX({url:p.normalizeAjaxUrl(h.attr("action")),data:m,error_phrase:"error_deleting_posts",success:function(n){$(window).off("beforeunload.editPost");
$("body").trigger(d+"_editform_onunload",[f]);2==l?"topic"==c||"blog"==c?location.replace($("#breadcrumbs .crumb a:last").attr("href")||pageData.baseurl):$('.js-post[data-node-id="'+e+'"]').remove():(n=$(".filter-wrapper",b.closest(".conversation-view, .ui-tabs-panel, .widget-content").find(".conversation-toolbar")).data("object-instance"))&&"function"==typeof n.applyFilters?n.forceApplyFilters():"visitorMessage"==c?history.back():location.reload();g.trigger("afterDelete")}})}}},{name:"delete_post_form",
data:{postType:c,nodeid:e,authorid:b.data("userid")}})}function sa(a,b){var c=this.form;a=$(c);var d=$(this),f=d.closest(".edit-conversation-container");if(!b){var e=p.triggerHandler.apply(c,["beforeCancel"]);if(!1===e)return!1}if(1==f.length){if(!b)return O(function(){!1!==p.triggerHandler.apply(c,["beforeCancel"])&&d.trigger("click",[!0])},"cancel_edit");b=a.data("content-type");e=d.closest("comment"==b?".js-comment":".js-post__content-wrapper");0==e.length&&(e=d.closest(".js-post__content-wrapper"));
e.removeClass("b-post--edit");e.find(".b-post__content--edit").removeClass("b-post__content--edit");e.find(".b-post__footer--edit").removeClass("b-post__footer--edit");$(window).off("beforeunload.editPost");a.trigger("afterCancel");$("body").trigger(b+"_editform_onunload",[e]);f.empty().hide()}else if(1==d.closest(".sb-dialog").length)P(a,!0,()=>{d.closest(".sb-dialog").dialog("close")});else if("vm"==a.data("message-type")||"pm-reply"==a.data("message-type")||"reply"==a.data("message-type"))P(a,
!0);else{var h="";h=c.ret&&c.ret.value?c.ret.value:"pm-new"==a.data("message-type")?pageData.baseurl+"/messagecenter/index":"pm-forward"==a.data("message-type")?pageData.baseurl+"/messagecenter/index":c.parentid&&c.parentid.value?pageData.baseurl+"/node/"+c.parentid.value:pageData.baseurl;ca(a.closest(".js-content-entry"))?location.href=h:O(()=>{location.href=h})}a.trigger("afterCancel")}function da(){var a=$(this),b=p.options.get("commentminchars"),c=$(".js-editor",a);c.attr("id");var d=$.trim(c.val()),
f=0<a.closest(".js-comments").length?!0:!1,e=a.data("content-type"),h=p.contentEntryBox.ATTACHLIMIT||0,g=$(".b-content-entry-panel__content--"+e,a);"video"==e&&0==g.length&&(g=$(".b-content-entry-panel__content--link",a));var l=function(k){return function(){setTimeout(function(){k.trigger("focus")},10)}};if("comment"==e||f)return d.length<b?(p.warning("error",["please_enter_message_x_chars",b],l(c)),!1):!0;if($(".js-content-entry-title",a).is(":visible")&&""==$.trim($(".js-content-entry-title",a).val()))return p.warning("error",
"please_enter_title_of_topic",l($(".js-content-entry-title",a))),!1;if("gallery"==e){if(0==$(".js-photo-postdata input",g).length)return p.warning("error","please_upload_at_least_one_photo"),!1;if(0<h&&$('.js-photo-postdata input[name^="filedataid"]',g).length>h)return p.warning("error",["you_may_only_attach_x_files_per_post",h]),!1}if(("link"==e||"video"==e)&&!$.trim(g.find(".js-panel-content").html()))return p.warning("error","please_enter_a_valid_url_and_click_attach",l($(".b-link-input__url",
g))),!1;if("poll"==e){var m=0,n;$(".js-poll-option:visible",a).each(function(){""!=$.trim($(this).val())?m++:n||(n=$(this));if(2<=m)return!1});if(2>m)return p.warning("error",["please_enter_at_least_x_poll_answers",2],l(n)),!1}return!0}function ta(a,b,c,d){console.log("vBulletin.contentEntryBox.callbackSubmitSuccess");d.closest(".js-dialog-body").dialog("close");var f=d.data("content-type")||"",e=d.data("current-channeltype")||"";d.attr("ck-editorid")||$(".js-editor",d).attr("id");P(d);if(!1!==p.triggerHandler.apply(d.get(0),
["afterSave",$(document),a])){b=pageData;var h=a.nodeId,g=d.closest(".conversation-content-widget");0==g.length&&(g=d.closest("#activities-tab"));var l=$(".conversation-list",g),m=$(".list-container",g);1==d.closest(".private-message-widget").length?1==d.closest(".private-message-widget").find(".conversation-list").length?location.reload():location.href=pageData.baseurl+"/messagecenter/index":a.retUrl&&0==m.length?location.href=a.retUrl:(c=l.hasClass("thread-view")?"thread":l.hasClass("full-activity-view")?
"full-activity-stream":l.hasClass("activity-view")?"activity-stream":"stream","forum"===e&&"thread"===c?(ba(d,null,a.nodeId),M.reset()):(e=$(".js-post:not(.js-comment):last .js-show-post-link:first",l).text()||"1",e=Number(e.replace("#","")),b["posts-perpage"]=I.POSTS_PER_PAGE,"thread"==c&&(b["comments-perpage"]=I.COMMENTS_PER_PAGE),p.ajaxtools.hasError(a.warnings,"warning_spam_post")?p.ajaxtools.showApiError(a.warnings,a,{title_phrase:"warning",after_error:function(){a.warningReturnUrl?location.href=
a.warningReturnUrl:location.reload(!0)}}):(p.AJAX({call:"/create-content/loadnode",data:{nodeid:h,view:c,index:e,page:b,type:f,isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0},success:function(n){d.find("textarea").val("");a.moderateNode&&U.showStatusMessage("your_post_is_now_being_reviewed_and_waiting_for_moderators_approval","moderate");var k=$(n.template);1<m.length&&($tab=d.closest(".tab"),m=0<$tab.length?$(".list-container",$tab):$(".list-container",$(".tab.media-tab")));if(m.hasClass("ajax-order-newest-first")&&
0<$("li.list-item:first",m).length)$("li.list-item:first",m).before(k);else{m.append(k);var q=k.closest(".ui-tabs-panel").find(".conversation-toolbar-wrapper");q.hasClass("scrolltofixed-floating")&&(q=q.data("object-instance"))&&q.addLimit(k.outerHeight(!0));m.removeClass("h-hide");p.scrollToAnchor("#post"+h)}0<m.children(".list-item").length&&m.parent().find(".conversation-empty").addClass("h-hide");$("body").trigger(f+"_savepost_success",[d]);$(document).trigger("vb-loadnode",{insertedHtml:k,context:"content_entry_box"});
p.Responsive.checkForVideoSignature();(k=$(".js-conversation-starter",g).attr("data-node-id"))&&p.markRead(k);p.subscribe.updateSubscribeButton(n.topic_subscribed)},title_phrase:"conversation",error_phrase:"error_loading_post"}),M.reset())))}}function ua(){$(".js-content-entry").each(function(){var a=$(this);a.data("initAjaxFormSubmitDone")||1==a.closest(".edit-conversation-container").length||($("form.js-contententry-form",a).each(function(b,c){b=$(c);b.data("content-type");p.ajaxForm.apply(b,[{success:ta,
error_phrase:"error_x_while_saving_content",api_error:M.resetOnError,beforeSerialize:d=>{d=d.find("[name=text]");d.val(d.val().replace(String.fromCharCode(8203),""))},beforeSubmit:(d,f,e)=>!1!==da.apply(f,[e])}])}),a.data("initAjaxFormSubmitDone",!0))})}function va(){I.bindEditFormEventHandlers("video");$(".b-content-entry .b-content-entry-panel__content--video").each(function(){$this=$(this);$this.data("initVideoEditPaneDone")||($("body").trigger("video_editform_onload",[$this]),$this.data("initVideoEditPaneDone",
!0))})}function wa(a){function b(d){var f=d.val();return""==f||d.data("last-autofill-value")==f}function c(d,f,e,h){var g=!1;b(d)&&(d.data("last-autofill-value",f),d.val(f),g=!0);b(e)&&(e.data("last-autofill-value",h),e.val(h),g=!0);!g||e.is(":visible")&&d.is(":visible")||(d=$('.js-collapse__icon.js-collapse--collapsed[data-collapse-id="{0}"]'.format("collapse_advoptionspanel_meta_new")),$('.js-collapse__icon.js-collapse--collapsed[data-collapse-id="{0}"]'.format("collapse_advoptionspanel_new")).trigger("click"),
d.trigger("click"))}a.each(function(d,f){d=$(f);var e=d.find(".js-content-entry-title").first(),h=d.find(".js-content-entry-url-alias").first(),g=d.find(".js-content-entry-html-title").first();e.off("change.urlident").on("change.urlident",function(l){l=e.val();""!=l&&b(h)?p.AJAX({call:"/create-content/get-url-ident",data:{text:l},silent:!0,success:m=>{c(h,m.urlident,g,e.val())}}):c(h,"",g,e.val())})})}function xa(){function a(f,e,h){f=f.data("collapse-id");var g='data-collapse-id="'+f+'"',l=$(".js-collapse__link["+
g+"]"),m=$(".js-collapse__icon["+g+"]"),n=$(".js-collapse__body["+g+"]");g=m.add(n);l=l.add(m).is(".js-collapse--collapsed");e&&(l=!l);if(l){n.show();var k=n.find(".js-toggle-slider__dependent.h-hide").removeClass("h-hide");n.find(".js-select-box").selectBox();k.addClass("h-hide");n.hide();n.slideDown("fast");m.removeClass("b-icon__plus-circle").addClass("b-icon__minus-circle");g.removeClass("js-collapse--collapsed")}else n.is(".b-content-entry-panel__section--lite")||(n.slideUp("fast",function(){n.hide()}),
m.removeClass("b-icon__minus-circle").addClass("b-icon__plus-circle"),g.addClass("js-collapse--collapsed"));!e&&h&&c(f,!l)}var b=p.storagetools.createStorage("editor"),c=(f,e)=>b.set(f.replace(/(^collapse_|_edit$|_new$)/g,""),e?"1":"0"),d=$(".js-collapse__icon");d.each((f,e)=>{a($(e),!0,!1)});$(".js-collapse__link").add(d).addClass("b-link js-link").offon("click",function(f){f=!!f.originalEvent;a($(this),!1,f)});d.addClass("b-icon");$(".js-content-entry-edit-post .js-collapse__icon.js-collapse--collapsed").trigger("click");
setTimeout(function(){$(".js-content-entry .js-collapse__icon").each((f,e)=>{f=$(e);e=b.get(f.data("collapse-id").replace(/(^collapse_|_edit$|_new$)/g,""));null!=e&&"1"==e!=f.is(".js-collapse--collapsed")&&a(f,!1,!1)})},0)}function ya(){var a=[],b=null,c=null,d=null,f=function(g){function l(v,w,y){var F=v.first();"undefined"==typeof F.data("css-prop-restore-value_"+w)&&F.data("css-prop-restore-value_"+w,F.css(w));"undefined"!=typeof y&&v.css(w,y)}function m(v,w){var y=v.first().data("css-prop-restore-value_"+
w);"undefined"!=typeof y&&v.css(w,y)}function n(v,w){g.css({width:v});k.css({width:w})}var k=c.parent();d||(d={originalPanelWidth:g.width(),originalDialogWidth:k.width(),scrollbarWidth:p.getScrollbarWidth(),originalPanelHeight:g.height(),originalDialogHeight:k.height()});var q="margin"+pageData.textDirLeft.charAt(0).toUpperCase()+pageData.textDirLeft.slice(1);l(k,"height");l(g,"height");l(k.find(".photoSelectorTabs"),"height");l(k.find(".js-dialog-body"),"padding");l(k.find(".photoSelectorTabs ul"),
"width");l(k.find(".photoSelectorTabs ul li"),"width");l(k.find(".photoSelectorTabs .tabPanel"),"width");l(k.find(".photo-item-wrapper"),"width");l(k.find(".js-photo-counter"),q);var B=$(window).width(),E=d.originalDialogWidth+d.scrollbarWidth>B,r=d.originalPanelWidth,t=d.originalDialogWidth;E&&(r-=200,t-=200);n(r,t);var J=k.outerWidth()>B;J||(m(k,"height"),m(g,"height"),m(k.find(".photoSelectorTabs"),"height"),m(k.find(".js-dialog-body"),"padding"),m(k.find(".photoSelectorTabs ul"),"width"),m(k.find(".photoSelectorTabs ul li"),
"width"),m(k.find(".photoSelectorTabs .tabPanel"),"width"),m(k.find(".photo-item-wrapper"),"width"),m(k.find(".js-photo-counter"),q),k.find(".photo-checkbox input").css(pageData.textDirLeft,""),k.find(".photo-checkbox input").css(pageData.textDirRight,"5px"),k.find(".js-photo-counter").removeClass("h-margin-top-s"));n(r,t);var z=g.find(".photo-item-wrapper"),C=z.first().outerHeight();E?(E=z.length,z.addClass("last-in-row")):(E=Math.ceil(z.length/2),z.filter(":even").removeClass("last-in-row"));z=
E*C;d.originalPanelHeight<z&&(r+=d.scrollbarWidth,t+=d.scrollbarWidth,n(r,t));J&&(k.css({width:B+"px",left:0,top:0,marginLeft:0,marginTop:0}),l(k,"height","auto"),l(g,"height",z+"px"),l(k.find(".photoSelectorTabs"),"height",z+"px"),l(k.find(".js-dialog-body"),"padding",0),l(k.find(".photoSelectorTabs ul"),"width","30%"),l(k.find(".photoSelectorTabs ul li"),"width","100%"),l(k.find(".photoSelectorTabs .tabPanel"),"width","70%"),l(k.find(".photo-item-wrapper"),"width","auto"),l(k.find(".js-photo-counter"),
q,"12px"),k.find(".photo-checkbox input").css(pageData.textDirRight,""),k.find(".photo-checkbox input").css(pageData.textDirLeft,"5px"),k.find(".js-photo-counter").addClass("h-margin-top-s"));$("body").is(".l-xsmall")&&l(k,"height","auto")},e=function(g){var l=$(".photo-item-wrapper .photo-item .filedataid",g),m=$(".js-photo-counter",g.parent());f(g);l.off("click").on("click",function(n){n.stopPropagation();n=$(this).data("nodeid");var k=$(this).closest(".photo-item-wrapper");this.checked?(a.push(n),
k.addClass("selected")):(k.removeClass("selected"),n=$.inArray(n,a),-1!=n&&a.splice(n,1));m.html(x.get("x_selected",a.length));$(".js-photo-selector-continue",c).prop("disabled",0==a.length)});$(".photo-item-wrapper",g).off("click").on("click",function(){var n=$(".photo-checkbox .filedataid",this);n.prop("checked",!n.prop("checked")).triggerHandler("click")});0<a.length?(l.each(function(){-1!=$.inArray($(this).data("nodeid"),a)&&(this.checked=!0,$(this).closest(".photo-item-wrapper").addClass("selected"))}),
$(".js-photo-selector-continue",c).prop("disabled",!1)):(l.prop("checked",!1),$(".photo-item-wrapper",this).removeClass("selected"),$(".js-photo-selector-continue",c).prop("disabled",!0));m.html(x.get("x_selected",a.length))},h=function(g,l){g=g.nodes;b=$(".photo-selector-galleries",l);var m=b.find(".photo-selector-tabs");m.empty();b.children(".tabPanel").remove();$.each(g,function(k,q){-1!=q.nodeid&&(k="tab-gallery-"+(-2==q.nodeid?0:q.nodeid),m.append('<li class="tab-item"><a href="{0}"><span>{1}</span></a></li>'.format("#"+
k,q.title)),b.append('<div id="{0}" class="tabPanel photo-display h-left"></div>'.format(k)))});var n=function(k){var q=k.attr("id");q=q.substring(q.lastIndexOf("-")+1);k.html()?f(k):p.AJAX({call:"/profile/get-photo-tab-content",data:{nodeid:q,ppr:2,isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0},success:function(B){k.html(B.template);e(k)}})};c=l.dialog({modal:!0,width:597,autoOpen:!1,showCloseButton:!1,closeOnEscape:!0,resizable:!1,showTitleBar:!0,title:x.get("select_from_photo_album"),
dialogClass:"js-photo-selector-wrapper photo-selector-wrapper dialog-container dialog-box"});b.tabs({create:function(k,q){n(q.panel)},activate:function(k,q){n(q.newPanel)}});c.addClass("js-no-responsive-resize");c.off("vbulletin:dialogresize").on("vbulletin:dialogresize",function(){var k=c.find(".ui-tabs-panel");f(k)});c.dialog("open")};$(document).offon("click",".js-photo-selector-button",function(){$(document).data("gallery-container",$(this).closest(".b-content-entry-panel__content--gallery"));
a=[];var g=$(".js-photo-selector-wrapper .js-photo-selector-container");0==g.length&&(g=$(this).closest(".b-content-entry").find(".js-photo-selector-container"));p.AJAX({call:"/profile/get-photo-tabs",success:l=>h(l,g)})})}function P(a,b,c){var d=a.closest(".js-content-entry"),f=d.find(".js-editor");if(b&&!ca(d))return O(()=>{P(a,!1,c)});a.trigger("reset");$(".linkcontainer, .js-photo-postdata, .js-attach-postdata",a).html("");$(".edit-photo-link",a).addClass("h-hide");$(".upload-photo-dialog-container .photo-display-container .photo-display").html("");
a.attr("default-action")&&a.attr("action",a.attr("default-action"));p.upload&&p.upload.setUploadButtonText&&p.upload.setUploadButtonText(a);u.resetEditor(f,function(){d.find(".b-content-entry-panel__content").each(function(e,h){L($(h))});V(d);f.attr("id")&&u.editorExists(f.attr("id"))&&u.toggleToolbar(f,!1);d.data("prev-selected-panel","");d.find(".b-toolbar__item").removeClass("b-toolbar__item--active");ea(d.find(".b-toolbar"));d.find(".js-content-entry-title").val("");d.find(".js-contententry-buttons").data("hide-buttons-until-click")&&
(d.find(".js-contententry-buttons").addClass("h-hide"),d.find(".js-human-verification").addClass("h-hide"));I&&I.replyWithQuotes&&p.ensureMethod(I.replyWithQuotes,"clickCancelButton")();fa(f.attr("id"));p.ensureFun(c).apply(a)})}function ha(a){if(a.hasClass("b-content-entry-panel__content--gallery"))return!$.trim(a.find(".js-panel-content").html());if(a.hasClass("b-content-entry-panel__content--link")||a.hasClass("b-content-entry-panel__content--video"))return!$.trim(a.find(".js-panel-content").html())&&
!a.find(".b-link-input__url").val();if(a.hasClass("b-content-entry-panel__content--poll")){var b=!1;$(".b-poll-fieldset .b-form-input__input",a).each((e,h)=>{if($(h).val())return b=!0,!1});b||$(".b-poll-fieldset .b-form-control__control",a).each((e,h)=>{if(h.defaultChecked!=h.checked)return b=!0,!1});return!b}if(a.hasClass("b-content-entry-panel__content--attachment"))return!(1<a.find(".js-attach-list .js-attach-item").length);if(a.hasClass("b-content-entry-panel__content--event")){b=!1;var c=$('input[name="eventstartdate"]',
a),d=$(".js-toggle-slider[data-name='is_all_day']",a);a=$('input[name="eventenddate"]',a);var f=$("input[name='location']");c.length&&c.val()!=c.data("initial-value")&&(b=!0);d.length&&d.hasClass("b-toggle-slider--no")&&(b=!0);a.length&&a.val()!=a.data("initial-value")&&(b=!0);f.length&&""!=f.val()&&(b=!0);return!b}return!0}function W(a){var b=$();a.is(".js-content-entry")&&(b=a);b.length||(b=a.find(".js-content-entry"));b.length||(b=a.closest(".js-content-entry"));a=1==b.find(".b-content-entry-panel__content--event:visible").length;
b=b.find(".js-content-entry-event-highlights-container");var c=b.find(".js-content-entry-event-highlights");b.toggleClass("h-hide-imp",!a);b.is(":visible")&&c.is(".selectBox")&&c.val()&&c.val("").selectBox("value","")}function L(a){a.addClass("h-hide");if(a.hasClass("b-content-entry-panel__content--gallery"))a.find(".js-panel-content").empty(),a.find(".b-button--upload .js-upload-label").text(x.get("upload")),a.find(".b-form-input__file--hidden").prop("disabled",!0),a.find(".js-photo-postdata").empty(),
a=p.upload.getUploadedPhotosDlg(!1,a),$(".photo-display",a).empty();else if(a.hasClass("b-content-entry-panel__content--link")||a.hasClass("b-content-entry-panel__content--video"))a.find(".js-panel-content").empty(),a.find(".b-link-input__url").val("").prop("disabled",!0).parent().removeClass("h-hide");else if(a.hasClass("b-content-entry-panel__content--poll")){var b=a.find(".b-poll-fieldset__poll-answers li");3<b.length&&b.filter(function(e){return 3<=e}).remove();a.find(".b-poll-fieldset input").each(function(){"text"==
this.type?(this.value="",this.disabled=!0):"checkbox"==this.type&&(this.checked=this.defaultChecked,$(this).hasClass("js-poll-timeout")&&p.triggerHandler.apply(this,["click"]))})}else if(a.hasClass("b-content-entry-panel__content--attachment"))a.find('.js-attach-list .js-attach-item:not(.h-hide) .js-attach-ctrl[data-action="remove"]').trigger("click");else if(a.hasClass("b-content-entry-panel__content--advanced-options"))a.removeClass("h-hide"),a.find(".js-htmlstate").selectBox("value","off"),b=a.find(".js-collapse__icon:not(.js-collapse--collapsed)"),
0==a.find(".b-content-entry-panel__section--lite").length?b.trigger("click"):b.first().trigger("click");else if(a.hasClass("b-content-entry-panel__content--event")){b=$('input[name="eventstartdate"]',a);var c=$(".js-toggle-slider[data-name='is_all_day']",a),d=$('input[name="eventenddate"]',a),f=$("input[name='location']");b.length&&b.val(b.data("initial-value"));c.length&&c.hasClass("b-toggle-slider--no")&&c.trigger("click");d.length&&d.val(d.data("initial-value"));f.length&&f.val("");W(a)}}function za(a){a.removeClass("h-hide");
W(a);1==a.closest(".edit-conversation-container").length&&(a.hasClass("b-content-entry-panel__content--link")||a.hasClass("b-content-entry-panel__content--video"))&&$(".b-link-input",a).addClass("h-hide")}function Aa(a){a.hasClass("b-content-entry-panel__content--gallery")?a.find(".b-form-input__file--hidden").prop("disabled",!1):a.hasClass("b-content-entry-panel__content--link")||a.hasClass("b-content-entry-panel__content--video")?a.find(".b-link-input__url").prop("disabled",!1):a.hasClass("b-content-entry-panel__content--poll")&&
a.find(".b-poll-fieldset .b-form-input__input").prop("disabled",!1)}function ea(a){var b=a.closest("form"),c=a.data("panel"),d=$(".js-content-entry-title",b),f=$(".js-editor",b);b.data("default-action")||b.data("default-action",b.attr("action"));!b.data("default-content-type")&&b.data("content-type")&&b.data("default-content-type",b.data("content-type"));d.data("default-placeholder")||d.data("default-placeholder",d.attr("placeholder"));f.data("default-placeholder")||f.data("default-placeholder",f.attr("placeholder"));
if(a.hasClass("b-toolbar__item--active")){if(a=c.replace(/^b-content-entry-panel__content--/,""),["gallery","link","video","poll","event"].includes(a)){b.attr("action",p.getAjaxBaseurl()+"/create-content/"+a);b.data("content-type",a);c={gallery:"enter_photo_gallery_title",poll:"enter_poll_question"};var e="event"==a?"enter_event_details_here":"write_something_here_optional";d.attr("placeholder",x.get(a in c?c[a]:"enter_"+a+"_title"));f.attr("placeholder",x.get(e));$(".b-editor__placeholder",b).text(x.get(e))}}else b.data("default-action")?
b.attr("action",b.data("default-action")):b.attr("action",p.getAjaxBaseurl()+"/create-content/text"),b.data("default-content-type")?b.data("content-type",b.data("default-content-type")):b.data("content-type","text"),d.data("default-placeholder")?d.attr("placeholder",d.data("default-placeholder")):d.attr("placeholder",x.get("enter_title")),f.data("default-placeholder")?(f.attr("placeholder",f.data("default-placeholder")),$(".b-editor__placeholder",b).text(f.data("default-placeholder"))):(f.attr("placeholder",
x.get("write_something_here")),$(".b-editor__placeholder",b).text(x.get("write_something_here")))}function Ba(a,b){var c=null,d=null,f=0,e=0,h=(g,l,m,n,k)=>{g.find(l).slice(m,n?n:void 0).height(k)};a.find(b).each((g,l)=>{l=$(l);d=l.position().top;d!==c&&(e&&h(a,b,f,g,e),f=g,e=0,c=l.position().top);g=l.outerHeight(!0);e=e>g?e:g});h(a,b,f,0,e)}function Ca(){var a=$(this),b=a.closest(".js-smilie-container"),c=e=>{$(".js-smilie-category",e).add(".js-toggle-more-smilies",e).add(".js-smilie-category-preview",
e).toggleClass("h-hide");e.toggleClass("b-smilie__container--big")};if(b.data("all-smilies-loaded"))c(b);else{var d=$("<span />").addClass("h-left h-margin-top-xs").text(x.get("loading")+"...");a.after(d).addClass("h-hide");var f=e=>{e.find(".js-smilie-category").each((h,g)=>{var l=$(g);h=l.find("img");var m=h.length,n=0;h.offon("load",k=>{++n;n>=m-1&&Ba(l,".js-smilie-button")})})};p.AJAX({call:"/ajax/render/contententry_panel_smilies",data:{previewOnly:0,isAjaxTemplateRenderWithData:1},success:e=>
{a.removeClass("h-hide");d.remove();e=$(e.template).find(".js-smilie-container");b.replaceWith(e);e.data("all-smilies-loaded","1");c(e);f(e)}})}return!1}function Da(a){var b=function(e,h){var g=$(e);e=g.attr("src");var l=g.attr("title");g=g.data("smilieid");e=h.document.createElement("img",{attributes:{src:e,"data-cke-saved-src":e,title:l,alt:l,smilieid:g}});h.insertElement(e)};a=$(this);var c=a.closest(".js-content-entry").find(".js-editor"),d=a.find("img").get(0),f=c.attr("id");if(a.hasClass("b-smilie__button--disabled"))return!1;
f&&u.editorExists(f)?b(d,u.getEditor(f)):u.initEditor(c,{showToolbar:!0,success:(e,h)=>{b(d,h)}});return!1}function Ea(a){a=$(a.target).closest(".js-content-entry-panel__content--event").find(".js-event-dateinput");var b=a.filter("[name=eventstartdate]");a=a.filter("[name=eventenddate]");var c=b.val(),d=a.val(),f=!1;"undefined"==typeof T&&(T=36E5,X=b.data("initial-value"),Y=a.data("initial-value"));if(c!=X){b=new Date(Date.parse(c));b=b.getTime()+T;b=new Date(b);function e(h){return 10>h?"0"+h:h}
d=e(b.getMonth()+1)+"/"+e(b.getDate())+"/"+b.getFullYear()+" "+e(b.getHours())+":"+e(b.getMinutes());f=!0}else d!=Y&&(b=new Date(Date.parse(c)),T=(new Date(Date.parse(d))).getTime()-b.getTime());X=c;Y=d;f&&p.flatpickr.getInstance(a).setDate(d)}function Fa(a){var b="1"==$(this).find("input[name=is_all_day]:checked").val(),c=$(a.target).closest(".js-content-entry-panel__content--event").find(".js-event-dateinput");a=c.filter("[name=eventstartdate]");var d=a.data("initial-value");d=a.val()||d;c=c.filter("[name=eventenddate]");
var f=c.data("initial-value");f=c.val()||f;var e="datetime";if(b)e="date",a.data("temp-saved-date",d),c.data("temp-saved-date",f);else{-1===a.val().indexOf(":")&&a.val(d);-1===c.val().indexOf(":")&&c.val(f);b=a.data("temp-saved-date");var h=c.data("temp-saved-date");b&&0<=b.indexOf(d)&&a.val(b);h&&0<=h.indexOf(f)&&c.val(h)}p.flatpickr.changePickerType(a,e);p.flatpickr.changePickerType(c,e)}function Ga(a){a=$(this);var b=a.closest(".b-content-entry-panel__content").data("class");a.is(".js-ckeditor-toolbar-close")&&
(b="b-content-entry-panel__content--toggle-editor");a.closest(".b-content-entry").find(".b-toolbar__item[data-panel="+b+"]").trigger("click")}function V(a){var b=a.find(".js-content-entry-panel"),c=b.find(".b-content-entry-panel__content").not(".h-hide");b.toggleClass("h-hide",!c.length);c.removeClass("b-content-entry-panel__content--first").first().addClass("b-content-entry-panel__content--first");b.closest(".js-content-entry").toggleClass("b-content-entry--all-panels-hidden",0==c.length);W(a);p.ensureFun(b.data("callback")).call(b)}
function O(a,b){U.openConfirmDialogSimple({title:b||"content_entry",message:"all_changes_made_will_be_lost_would_you_like_to_continue",iconType:"warning",onClickYes:a});return!1}function Ha(a){var b=!0;a.find(".b-content-entry-panel__content").each(function(c,d){if(!ha($(d)))return b=!1});return b}function ca(a){var b=a.find(".js-content-entry-title").val();return("string"!=typeof b||""==b)&&u.isEditorEmpty(a.find(".js-editor"))&&Ha(a)}function Z(a,b,c,d,f){a.find('input[type="hidden"]').filter((e,
h)=>{e=$(h).attr("name");for(key of["",b])for(field of["filedataids[{0}]","filenames[{0}]","setting[{0}][size]"])if(e==field.format(key))return!0}).remove();a.append([N("filedataids[{0}]".format(b),c),N("filenames[{0}]".format(b),d)]);f&&a.append(N("setting[{0}][size]".format(b),f))}function ia(a){a.find('.b-toolbar__item[data-panel="b-content-entry-panel__content--attachment"]:not(.b-toolbar__item--active)').trigger("click")}function ja(a,b,c){if(!a)return console.warn("addAttachmentItemPanel failed because $closestElement was not provided"),
!1;a=a.closest(".js-content-entry");var d=a.find(".js-attach-list"),f=d.find(".js-attach-item-sample").first().clone(!0),e=$("<img />").attr("src",pageData.baseurl+"/filedata/fetch?type=thumb&filedataid="+c.filedataid).addClass("b-attach-item__image");f.removeClass("js-attach-item-sample");f.find(".js-attach-item-image").append(e);f.find(".js-attach-item-filename").text(c.filename);e="";var h=c.filename.match(/\.([a-z]+)$/i);h&&(e=h[1]);f.data({fileext:e,filename:c.filename,filedataid:c.filedataid,
attachnodeid:0,"first-insert-id":b});Z(f,b,c.filedataid,c.filename,c.imagesize);f.appendTo(d).removeClass("h-hide");d.removeClass("h-hide");ia(a);return!0}function Ia(a){var b=$(this);a=b.closest("form");var c=b.closest(".js-attach-item"),d=b.data("action"),f=b.data("imagesize"),e=c.data("filedataid"),h=u.generateTempAttachmentId(e),g=c.data("attachnodeid")||0,l=c.data("fileext"),m=c.data("filename"),n=a.find(".js-editor"),k=c.data("first-insert-id"),q="icon thumb small medium large full".split(" "),
B=function(C,v,w,y,F,G,Ja){var A="",H="";A=pageData.baseurl+"/filedata/fetch?filedataid="+C;H=A+"&thumb=1";var Q="",K=null!==v.match(/^(gif|jpg|jpeg|jpe|png|bmp|webp)$/i),ka=!1;v=!1;var aa="data-tempid",R=h;if(k||0!=g)if(!k&&0<g){var D=!1;"wysiwyg"==y.mode?(temp=document.createElement("div"),temp.innerHTML=y.getData(),D=K?"img":"a",D=0<$(temp).find(D+'[data-attachmentid="'+g+'"]').length):(regex=new RegExp("\\[ATTACH(=[^\\]]+)?\\]n"+g+"\\[/ATTACH\\]","i"),sourceText=$(y.container.$).find("textarea.cke_source").val(),
(matches=regex.exec(sourceText))&&(D=!0));D?v=!0:(A=pageData.baseurl+"/filedata/fetch?id="+g,H=A+"&thumb=1",aa="data-attachmentid",R=g,h="n"+g,c.data("first-insert-id",h),"insert_image"==F||"insert_sigpic"==F||G||(G="thumb"),G&&(D={},D.attachmentid=g,D.size=G,p.AJAX({call:"/uploader/saveattachmentsetting",data:D})))}else k&&(v=K);else w=(w=c.find('input[type="hidden"][name="filenames[]"]'))&&w.val(),c.data("first-insert-id",h),ka=!0;K||(0<g?R=h=g:c.data("tempid")&&(R=h=c.data("tempid")));D=!1;K?("insert_sigpic"==
F?H=A=" [SIGPIC][/SIGPIC] ":(K="","insert_image"==F?(Ja.includes(G)&&(A+="&amp;type="+G),Q=A):(G="thumb",K=" thumbnail",Q=H),A=' <img class="bbcode-attachment'+K+'" src="{0}" {1}="{2}" /> '.format(Q,aa,R),H=" [ATTACH=CONFIG]{0}[/ATTACH] ".format(h)),D=G):"video"==c.data("filebasetype")?A=H="[VIDEO=videofile;{0}{1}]{0}[/VIDEO]".format(A,0==g?";"+h:""):"insert_sigpic"==F?H=A="":(A=' <a class="bbcode-attachment" href="{0}" {1}="{2}" />'.format(A,aa,R)+w+"</a> ",H=" [ATTACH]{0}[/ATTACH] ".format(h));
ka&&(Z(c,h,C,w,D),c.attr("data-tempid",h));v&&(filedataObj={filedataid:C,filename:w,imagesize:G},ja(b,h,filedataObj));if(C=y.document&&y.document.getBody())C.setAttribute("contentEditable",!1),C.setAttribute("contentEditable",!0);"wysiwyg"==y.mode?(y.insertHtml(A),""!=Q&&u.autogrowEditorOnImageLoad(Q,y)):($sourceTextArea=$(y.container.$).find("textarea.cke_source"),cursorStart=$sourceTextArea[0].selectionStart,cursorEnd=$sourceTextArea[0].selectionEnd,text=$sourceTextArea.val(),newtext=text.substring(0,
cursorStart)+H+text.substring(cursorEnd),$sourceTextArea.val(newtext));setTimeout(()=>{y.focus();y.execCommand("autogrow")},10)};switch(d){case "remove":var E=function(){console.log("removeAttachmentFromPanel attachnodeid: "+g);0<g&&N("removeattachnodeids[]",g).appendTo(c.closest("form"));c.remove()};if(u.editorExists(n.attr("id"))){a=u.getEditor(n.attr("id"));var r=a.getData(),t=pageData.baseurl+"/filedata/fetch?filedataid="+e;r=r.replace("[ATTACH]{0}[/ATTACH]".format(k),"");r=r.replace("[ATTACH=CONFIG]{0}[/ATTACH]".format(k),
"");r=r.replace("[IMG]{0}[/IMG]".format(t),"");for(var J of q)r=r.replace("[IMG]{0}&amp;type={1}[/IMG]".format(t,J),"");r=r.replace("[VIDEO=videofile;{0}]{0}[/VIDEO]".format(pageData.baseurl+"/filedata/fetch?id="+g),"");J=c.find('input[type="hidden"]');var z=(C,v,w)=>{C=C.replace(new RegExp("\\[ATTACH(=[^\\]]+)?\\]"+v+"\\[/ATTACH\\]","i"),"");v=document.createElement("div");v.innerHTML=C;$(v).find("img["+w+"], a["+w+"]").remove();return v.innerHTML};for(t=0;t<J.length;t++)regex=/filedataids\[([^\]]+)]/,
(tempid=(matches=regex.exec(J[t].name))&&matches[1])&&(r=z(r,tempid,'data-tempid="'+tempid+'"'));0<g&&(r=z(r,"n"+g,'data-attachmentid="'+g+'"'));a.setData(r,function(){E()})}else E();break;default:u.editorExists(n.attr("id"))?B(e,l,m,u.getEditor(n.attr("id")),d,f,q):u.initEditor(n,{success:()=>{setTimeout(()=>{B(e,l,m,u.getEditor(n.attr("id")),d,f,q)},0)}})}return!1}function Ka(a,b){var c=$(this);a=c.closest(".js-content-entry");var d=a.find("."+c.data("panel")),f=1==c.closest(".js-toolbar-primary").length,
e=a.data("prev-selected-panel")||"",h=l=>l.is(":visible")&&!ha(l);if(f){if("0"==a.data("allow-type-text")&&(c.addClass("b-toolbar__item--unselectable"),c.hasClass("b-toolbar__item--active")))return!1;if(!b&&(e.length&&h(e)||h(d)))return O(function(){e.length?(L(e),e=""):L(d);c.trigger("click",[!0])});$(".js-toolbar-primary .b-toolbar__item",a).removeClass(function(){return this==c.get(0)?($(this).toggleClass("b-toolbar__item--active"),""):"b-toolbar__item--active b-toolbar__item--unselectable"});
e.length&&e.is(":visible")&&(L(e),e="");c.hasClass("b-toolbar__item--active")?(Aa(d),za(d),e=d):(L(d),e="");ea(c);a.data("prev-selected-panel",e)}else{if(!b&&"b-content-entry-panel__content--attachment"==c.data("panel")&&h(d))return O(()=>{L(d);c.trigger("click",[!0])});c.toggleClass("b-toolbar__item--active");h=c.hasClass("b-toolbar__item--active");b=parseInt(pageData.user_editorstate,10);var g=c.data("panel");f=la(g);"b-content-entry-panel__content--toggle-editor"==g?toggleAdvancedEditor(c):d.toggleClass("h-hide",
!h);h?(b|=f,h="add"):(b-=b&f,h="remove");b!=pageData.user_editorstate&&(p.loadingIndicator.suppressNextAjaxIndicator(),p.AJAX({call:"/ajax/api/user/saveEditorState",data:{action:h,value:f},success:function(l){l.success&&"undefined"!=typeof l.editorstate&&(pageData.user_editorstate=parseInt(l.editorstate,10))}}))}V(a);a.find(".js-contententry-buttons").removeClass("h-hide");M.show(a.find(".js-human-verification"))}function la(a){var b={"b-content-entry-panel__content--toggle-editor":1,"b-content-entry-panel__content--attachment":2,
"b-content-entry-panel__content--smiley":4};return a in b?b[a]:0}function fa(a){$("#"+a).closest(".js-content-entry").find(".b-toolbar__item--secondary").each(function(){var b=$(this),c=b.data("panel");c=la(c);pageData.user_editorstate&c&&!b.hasClass("b-toolbar__item--active")&&b.trigger("click")})}function ma(a){var b=$(a).data("default-content-type");b&&"Text"!=b&&(a=$('.b-toolbar__item[data-panel="b-content-entry-panel__content--{0}"]'.format(b.toLowerCase()),a),a.data("defaultSelected")||a.hasClass("b-toolbar__item--active")||
(a.trigger("click"),a.data("defaultSelected",!0)))}function na(){var a=$(".js-content-entry").not(".js-content-entry-basic"),b=$(document);0<a.length&&($("form",a).each((c,d)=>{c=$(d);d=c.find(".js-editor");var f=u.getEditorContent(d);c.trigger("reset");f&&(u.editorExists(d)?u.getEditor(d).setData(f):d.val(f))}),ua(),ya(),va(),wa(a),xa(),b.offon("click",".js-content-entry-save-draft",pa),b.offon("click",".js-content-entry-preview",oa),b.offon("click",".js-content-entry-loadnewposts",qa),b.offon("keydown",
".js-content-entry .b-link-input__url",function(c){(c=13==c.keyCode)&&$(this).next(".js-attach-button").trigger("click");return!c}),b.offon("focus",".js-content-entry .js-editor",function(){var c=$(this).closest(".js-content-entry");c.find(".js-contententry-buttons").removeClass("h-hide");M.show(c.find(".js-human-verification"))}),S=$('.js-content-entry .js-toggle-slider[data-name="disable_bbcode"]').data("value"),b.offon("change",'.js-content-entry .js-toggle-slider[data-name="disable_bbcode"]',
(c,d)=>{S=d}),b.offon("change",".js-content-entry .js-content-entry-panel__content--event .js-event-dateinput",Ea).offon("change",".js-content-entry .js-content-entry-panel__content--event .js-toggle-slider[data-name='is_all_day']",Fa),b.offon("keyup",".js-event-location",c=>{c=$(c.target);c.closest("form").find(".js-event-previewmap").prop("disabled",""==c.val())}),b.offon("click",".js-event-previewmap",c=>{c=$(c.target).closest("form").find(".js-event-location").val();p.AJAX({call:"/ajax/render/display_event_map",
data:{location:c,isAjaxTemplateRenderWithData:1},success:d=>{openAlertDialog({title:x.get("preview_map"),message:d.template})}})}));b.offon("click",".js-content-entry-delete",ra);b.offon("click",".js-content-entry-cancel",sa);b.offon("click",".b-content-entry .b-toolbar__item",Ka);b.offon("click",".js-content-entry .js-contententry-panel-x",Ga);b.offon("click",".js-smilie-container .js-toggle-more-smilies",Ca);b.offon("click",".js-smilie-container .js-smilie-button",Da);b.offon("click",".js-content-entry .js-attach-ctrl",
Ia);a.each((c,d)=>{ma(d)});console.log("vBulletin.contentEntryBox.init finish")}var S=!1;toggleAdvancedEditor=function(a){var b=a.closest(".js-content-entry").find(".js-editor");b.attr("id")&&u.editorExists(b.attr("id"))?u.toggleToolbar(b):u.initEditor(b,{showToolbar:!0,success:(c,d)=>{d.focus();p.ensureFun(b.data("callback")).call(b)}})};var T,X,Y;na();return{init:na,addAttachmentItemPanel:ja,updatePanelItemData:Z,openAttachmentPanel:ia,setDefaultTab:ma,resetForm:P,validateForm:da,afterPanelChange:V,
restoreEditorState:fa,populateMetaDescription:function(a,b){var c=b.find(".js-meta-description").first();if(1==c.length){var d=c.val(),f="";b=b.is(".js-content-entry-edit-post");var e=p.options.get("threadpreview");0>=e&&(e=150);a=$("<div />").html(a).text();a=a.replace(/[\s\v\0]+/g," ").replace(/^ | $/g,"");if(a.length>e+10){a=a.substr(0,e+10);e=a.length-1;for(var h=20<a.length?20:a.length,g;0<h;){g=a.substr(e,1);if(g.match(/[\s\v\0\.\?\n-]/)){a=a.substr(0,a.length-(a.length-e));break}--h;--e}}b&&
(f=a);if(""==d&&""!=a||f==d&&""!=d||0===d.indexOf(f)&&""!=d)prevHtmlTitle=a,c.val(prevHtmlTitle),c.is(":visible")||(c=c.closest(".js-collapse__body"),a=$(".js-collapse__icon, .js-collapse__body"),c=a.index(c),a.eq(c-1).trigger("click"))}},allowBbcode:()=>!S}})(vBulletin,vBulletin.ckeditor,vBulletin.conversation,vBulletin.hv,vBulletin.phrase,vBulletin.dialogtools));
