/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache("answer_must_be_approved_published compare_versions edit_conversation error_loading_post flag_a_post onbeforeunload_message_while_editing_post people_who_liked please_enter_your_reason_why_you_want_to_flag_this_post send_report the_report_has_been_sent topic_answered you_have_a_pending_edit_unsaved".split(" "),[]);vBulletin.ensureObj("conversation");
$.extend(vBulletin.conversation,function(a,l){function D(b){function d(t,v,y,k){var m=a(".edit-conversation-container form",f).data("content-type");!1===vBulletin.triggerHandler.apply(k.get(0),["afterSave",a(document),t])?a("body").trigger(m+"_editform_onunload",[f]):(v=pageData,v["posts-perpage"]=vBulletin.conversation.POSTS_PER_PAGE,"thread"==x&&(v["comments-perpage"]=vBulletin.conversation.COMMENTS_PER_PAGE),t&&vBulletin.ajaxtools.hasError(t.warnings,"warning_spam_post")?vBulletin.ajaxtools.showApiError(t.warnings,
t,{title_phrase:"warning",after_error:function(){t.warningReturnUrl?location.href=t.warningReturnUrl:location.reload(!0)}}):l.AJAX({call:"/create-content/loadnode",data:{nodeid:u,view:x,index:A,page:v,type:c,isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0},success:function(q){var n=k.closest(".js-content-entry").data("current-channelid"),p=k.find('input[name="parentid"]:checked').val();if(0<n&&0<p&&n!=p)location.reload(!0);else{a("body").trigger(m+"_editform_onunload",[f]);n=a(q.template);
p=e.closest(".js-post");var w=p.parent();p.replaceWith(n);n=w.find(".js-post").filter((K,E)=>a(E).data("node-id")==u);q.hasOwnProperty("template_article_title_info")&&(p=a(".js-update-article-title-info"),w=a(q.template_article_title_info),0<p.length&&p.empty().append(w));a("body").trigger(m+"_newcontent_onload",[n]);a(document).trigger("vb-loadnode",{insertedHtml:n,context:"conversationcommon"});n.hasClass("js-conversation-starter")&&(p=a(".js-post-title",n).first().text(),w=p+" - "+vBulletin.options.get("bbtitle"),
"topic_url"in q&&(q=pageData.baseurl+q.topic_url,q!=location.href&&window.history.replaceState({},w,q)),document.title=w,a(".page-title-widget .js-main-title").text(p));a(".js-select-box",n).selectBox();vBulletin.animateScrollTop(n.offset().top,{duration:"slow"})}},title_phrase:"conversation",error_phrase:"error_loading_post"}))}var e=a(this),c,h=e.closest(".conversation-list");0<e.closest(".js-comments").length&&(c="comment");var r=a(".edit-conversation-container form",h);if(0<r.length)vBulletin.warning("edit_conversation",
"you_have_a_pending_edit_unsaved",function(){vBulletin.animateScrollTop(r.closest(".js-post").offset().top,{duration:"slow"})});else{b.preventDefault();var u=e.parent().attr("data-node-id"),f="comment"==c?e.closest(".js-comment"):e.closest(".js-post__content-wrapper");var x=h.hasClass("thread-view")?"thread":h.hasClass("full-activity-view")?"full-activity-stream":h.hasClass("activity-view")?"activity-stream":"stream";c=c||f.attr("data-node-type")||"";b=a(".js-show-post-link",f).text()||"1";var A=
Number(b.replace("#",""));("comment"!=c||"thread"!=x&&1!=h.closest(".blog-conversation-content-widget").length)&&A--;l.AJAX({call:"/create-content/loadeditor",data:{nodeid:u,type:c,view:x,isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0},success:function(t){var v=function(){if("undefined"==typeof vBulletin.upload||"undefined"==typeof vBulletin.tagEditor||"undefined"==typeof vBulletin.contentEntryBox.init)vBulletin.ckeditor.loadScripts("",{},v);else{f.addClass("b-post--edit");f.find(".js-post__content").first().addClass("b-post__content--edit");
f.find(".b-post__footer").first().addClass("b-post__footer--edit");$container=f.find(".edit-conversation-container").first();f.closest(".js-album-detail").find(".conversation-body, .profile-media-uploadphotos, .js-photo-preview").addClass("h-hide-imp");vBulletin.contentEntryBox.init();vBulletin.hv.init($container.find(".js-human-verification"));vBulletin.contentEntryBox.setDefaultTab($container.find(".js-content-entry").first());$container.show();var k=$container.find(".js-attach-list");vBulletin.upload.initializePhotoUpload(f);
var m=".js-post[data-node-id={0}] .tag-editor-container .tag-input".format(u);$tagEditorBox=a(m);0<$tagEditorBox.length&&"undefined"!=typeof vBulletin.tagEditor&&new vBulletin.tagEditor.instance(m);0<k.data("attach-count")&&(k=$container.find(".b-toolbar__item").filter(function(){return"b-content-entry-panel__content--attachment"==a(this).data("panel")}),k.hasClass("b-toolbar__item--active")||k.trigger("click"));vBulletin.contentEntryBox.afterPanelChange(f);vBulletin.flatpickr&&vBulletin.flatpickr.initPickers()}};
console.log("Edit mode: Adding Content Entry UI to DOM (contains parsed post text in the .js-editor-parsed-text element)");a(".edit-conversation-container",f).first().hide().html(t.template);var y=a(".edit-conversation-container form",f).data("content-type");a(window).off("beforeunload.editPost").on("beforeunload.editPost",function(){return vBulletin.phrase.get("onbeforeunload_message_while_editing_post")});a("body").trigger(y+"_editform_onload",[f,v]);vBulletin.ajaxForm.apply(a("form.js-contententry-form",
f),[{success:d,beforeSerialize:k=>{let m=k.find("[name=text]");m.val(m.val().replace(String.fromCharCode(8203),""));k.trigger("beforeSave");return!1!==a("body").triggerHandler(y+"_editform_onbeforeserialize",[k])},beforeSubmit:(k,m,q)=>{if(!1===vBulletin.contentEntryBox.validateForm.apply(m,[q]))return!1;a(window).off("beforeunload.editPost");return!0}}])},title_phrase:"edit_conversation"})}}function B(b,d=3){var e=0,c=a("ul.poll li",b),h=parseInt(c.css("line-height"),10);c.each(function(r){a(this).removeClass("h-hide");
r=a(this).height();e+=r/h;e>d?a(this).addClass("h-hide"):a(this).css("display","")});c=e>d;a(".view-more-ctrl",b).toggleClass("h-hide-imp",!c).next(".js-button-group").toggleClass("h-hide",c).next(".view-less-ctrl").toggleClass("h-hide-imp",c)}function z(b){return b.closest(".js-post").data("node-id")}function F(){var b=a(this),d=b.data("post-ip");b.data("post-host");g.register(["ip_info","ip_address_is","host_name_is","no_ip_found"]);d?(openAlertDialog({title:g.get("ip_info"),message:g.get("ip_address_is")+
": "+d+"<br />"+g.get("host_name_is")+': <span class="ip-host-name loading">...</span>',iconType:"none"}),l.AJAX({call:"/ajax/api/node/getHostName",data:{ip:d},success:function(e){a(".ip-host-name").removeClass("loading").html(e)}})):l.alert("ip_info","no_ip_found");return!1}function G(){var b=z(a(this)),d=C({title:g.get("flag_a_post"),message:g.get("please_enter_your_reason_why_you_want_to_flag_this_post"),buttonLabel:{okLabel:g.get("send_report"),cancelLabel:g.get("cancel")},multiline:!0,validation:{callback:C.validationString,
showError:!0},onClickOK:function(e){a("body").css("cursor","wait");l.AJAX({call:"/report/report",data:{reason:e,reportnodeid:b},success:function(c){d.dialog("close");l.alert("flag_a_post","the_report_has_been_sent")},complete:function(){a("body").css("cursor","default")},error_phrase:"unable_to_contact_server_please_try_again",title_phrase:"flag_a_post"});return!1}});return!1}function H(){var b=a(this).closest(".js-comment-entry__parent").find(".js-comment-entry");b.slideToggle("fast",function(){var d=
a(this).find(".js-comment-entry__textbox");d.is(":visible")&&d.trigger("focus")});b.find(".js-comment-entry__cancel").offon("click.convocom",function(d){b.slideToggle();return!1});return!1}function I(){function b(c,h,r){r.isAjaxTemplateRenderWithData=!0;l.AJAX({call:"/ajax/render/"+h,data:r,success:function(u){c.removeClass("loading").find(".dialog-content .message").html(u.template).end().dialog("option","position",{of:window})},after_error:function(){c.dialog("close")}})}var d=z(a(this)),e=openConfirmDialog({title:g.get("post_history"),
message:g.get("loading")+"...",width:800,dialogClass:"post-history-dialog dialog-container dialog-box loading",buttonLabel:{yesLabel:g.get("compare_versions"),noLabel:g.get("cancel")},onAfterClose:function(){if("btnConfirmDialogYes"==this.id){var c=e.find(".post-history-form");a("#btnConfirmDialogYes").hide();var h=openConfirmDialog({title:g.get("post_history"),message:g.get("loading")+"...",width:800,dialogClass:"post-history-comparison-dialog dialog-container dialog-box loading",buttonLabel:{yesLabel:g.get("compare_versions"),
noLabel:g.get("close")},onAfterClose:function(){a("#btnConfirmDialogYes").show()}});c={oldpost:c.find("input:radio[name=old]:checked").val()||1,newpost:c.find("input:radio[name=new]:checked").val()||1,nodeid:d};b(h,"post_history_form",c)}}});b(e,"post_history_form",{nodeid:d})}function J(){var b=a(this),d=z(b);b=!b.closest(".js-post").hasClass("isanswer");var e=vBulletin.getSelectedFilters(a(".toolbar-filter-overlay"));a("body").css("cursor","wait");l.AJAX({call:"/create-content/setExclusiveAnswer",
data:{nodeid:d,set:b?1:0,searchFilters:e,isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0},success:function(c){a(".js-post.isanswer").toggleClass("isanswer",!1);c.answers&&0<c.answers.length&&c.answers.forEach(u=>{a(".js-post[data-node-id="+parseInt(u,10)+"]").toggleClass("isanswer",!0)});let h=a(".js-post.pinned-answer");h.length&&h.hide("slow",()=>{h.remove()});if(c.template){var r=a(".js-conversation-starter");c=a(c.template);c.hide();c.insertAfter(r).show("slow")}},complete:function(){a("body").css("cursor",
"default")},error_phrase:"unable_to_contact_server_please_try_again",title_phrase:"setasanswer"});return!1}var g=l.phrase,C=l.openPromptDialog;return{initContentEvents:function(b){b.offon("click.convocom",".js-post-control__ip-address",F);b.offon("click.convocom",".js-post-control__edit",D);b.offon("click.convocom",".js-post-control__flag",G);b.offon("click.convocom",".js-post-control__comment",H);b.offon("click.convocom",".js-post__history",I);b.offon("click.convocom",".js-post-control__answer",
J)},initPollEvents:function(b){b.offon("click.convocom",".list-item-poll .view-more-ctrl",function(d){var e=a(this).closest("form.poll");d=e.find("ul.poll");a(this).addClass("h-hide-imp");d.css("max-height","none").find("li.h-hide").slideDown(100,function(){e.find(".js-button-group").removeClass("h-hide").next(".view-less-ctrl").removeClass("h-hide-imp");l.animateScrollTop(e.offset().top,{duration:"fast"})});return!1});b.offon("click.convocom",".list-item-poll .view-less-ctrl",function(d){d=a(this).closest("form.poll");
B(d,3);d.find("ul.poll").css("max-height","").find("li.h-hide").slideUp(100);return!1})},limitVisiblePollOptionsInAPost:B}}(jQuery,vBulletin));
