/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache("cancel_new_with_quote create_new_conversation_with_quote error_fetching_comments error_fetching_quotes error_x existing_message_will_be_deleted invalid_server_response_please_try_again new_with_quote please_click_on_the_quote_icon_of_the_post_you_want_to_quote post_reply share_post_link_help visitor_message x_comment x_comments_lower your_post_is_now_being_reviewed_and_waiting_for_moderators_approval".split(" "),[]);vBulletin.ensureObj("conversation.contentEntryBox");
$.extend(vBulletin.conversation,function(a,e){function H(c){0<c.nodeIds.length&&(a("body").css("cursor","wait"),e.AJAX({call:"/createcontent/fetch-quotes",data:{nodeid:c.nodeIds},complete:function(){a("body").css("cursor","auto")},success:function(f){var h="";a.each(f,function(t,r){h+=JShtmlEncode(r)+"<br/><br/>"});e.ensureFun(c.onSuccess)(a.trim(h))},title_phrase:"conversation",error_phrase:"error_fetching_quotes"}))}function C(c){var f=a(".b-post-control__quote--selected",c),h=a(".js-content-entry .js-editor",
c).last();if(0<f.length){var t=[];f.each(function(){t.push(a(this).parent().data("node-id"))});H({nodeIds:t,onSuccess:function(r){if(m.editorExists(h)){var u=m.getEditor(h);u&&u.setData("",function(){u.insertHtml(r.replace(/(\n)/gi,"<br />"));u.focus()})}else h.val(r.replace(/<br(\s*\/|)>/gi,"\n")).trigger("focus")}})}else m.editorExists(h)?m.getEditor(h).focus():h.trigger("focus")}function I(c){e.qtip.apply(c,"qtip-sharepostlink",{content:{title:{text:e.phrase.get("share_post_link_help"),button:!0},
text:'<input type="text" class="textbox stretch" value="'+c.attr("href")+'" />'},show:{event:"click",solo:!0,ready:!0},events:{visible:function(f,h){h.elements.content.find("input.textbox").trigger("select").trigger("focus")}},hide:{event:"unfocus",fixed:!0}})}function J(c){return 1==a(".conversation-media-view",c).length?2:1==a(".conversation-stream-view",c).length?1:0}function K(){var c=a(".conversation-content-widget"),f="1"==a(".conversation-toolbar-wrapper",c).data("allow-history"),h=c.filter(".widget-tabs").tabs({active:J(c)});
h.trigger("vb-tabinit");h.find(".widget-header .widget-tabs-nav li.ui-state-default:not(.ui-tabs-active) a").off("click").on("click",function(){location.href=a(this).attr("data-href");return!1});h=new e.pagination({context:c,allowHistory:f,onPageChanged:function(b,g,d){w.updatePageNumber(b);if(!g){if(g=w.getOption("customFilter"))g.pagenum=b,delete w.lastFilters,d&&delete g[a(".toolbar-search-form .js-filter-search",c).attr("name")];w.applyFilters(!1,!1,!1,!0)}e.Responsive.checkForVideoSignature()}});
var t=a(".conversation-toolbar-wrapper.scrolltofixed-floating",c),r=function(){return 0<c.length?c.offset().top+(c.outerHeight()-parseFloat(c.css("border-bottom-width")))-t.height():0};try{var u=new e.scrollToFixed({element:t,limit:r()})}catch(b){}var w=new e.conversation.filter({context:c,scrollToTop:c,pagination:h,allowHistory:f,hash:c.find(".js-module-top-anchor").attr("id"),onContentLoad:function(){u.updateLimit(r())}});a(document).offon("click",".js-show-post-link",function(b){b.preventDefault();
I(a(b.currentTarget))});a(document).offon("click","a.js-scroll-if-on-page",b=>{b=a(b.currentTarget);b=parseInt(b.data("nodeid"),10);$anchor=a(".js-post[data-node-id='"+b+"']:not(.pinned-answer)");if($anchor.length)return vBulletin.animateScrollTop($anchor.offset().top),!1});a(".conversation-toolbar .post-reply-btn").off("click").on("click",function(b){b=a(".js-content-entry").last();if(1==b.length){var g=a(".js-editor",b);b=b.offset().top;var d=a(".conversation-toolbar-wrapper"),n=d.hasClass("scrolltofixed");
d=d.length&&d.outerHeight(!0)||0;var k=m.editorExists(g);n||(b+=d);k?C(c):m.initEditor(g,{complete:function(){C(c)}});e.animateScrollTop(b,{duration:500,complete:function(){k&&m.focusEditor(g)}})}});a(document).off("mouseover",".js-userinfo__signature").on("mouseover",".js-userinfo__signature",function(){var b=a(this);"1"!=b.data("qtip-initialized")&&(b.data("qtip-initialized","1"),b.find(".user-signature"),e.qtip.apply(b,"qtip-signature",{content:b.find(".user-signature"),hide:{event:"unfocus"},
show:{solo:!0}}),a(this).trigger("mouseover"))});f=a(".conversation-list",c);a(".js-post-controls",f).disableSelection();f.off("click",".js-post-control__quote").on("click",".js-post-control__quote",function(){a(this).toggleClass("b-post-control__quote--selected");var b=a(".post-reply-btn .js-button__text-secondary").text().match(/[0-9]+/);b=b?Number(b[0]):0;a(this).hasClass("b-post-control__quote--selected")?b++:b--;D.clickQuoteIcon(b)});vBulletin.conversation.initContentEvents(f);"inlinemod"in e&&
e.ensureFun(e.inlinemod.init)(c);f.off("click",".js-comment-entry__post").on("click",".js-comment-entry__post",function(b){vBulletin.conversation.postComment.apply(this,[b,function(g){if(g)if(g.redirecturl)location.replace(g.redirecturl);else{var d=a(this).closest(".js-post"),n=g.totalcomments,k=d.find(".js-comments").removeClass("h-hide"),y=d.find(".js-comments__comments");a(this).closest(".js-comment-entry").addClass("b-comment-entry--has-comments").find(".js-comment-entry__textbox").val("").trigger("input");
var l=a(g.template),p=l.find(".js-comment");l.appendTo(y);k.find(".js-comments__footer").addClass("h-hide");k.find(".js-comments__page--prev").show().data("page-num",1).prev("label").hide();k.find(".js-comments__header").removeClass("h-hide").find(".js-comments__pagination").removeClass(function(){return 1<n?"h-hide":""}).end().find(".js-comments__total-text").text(function(){return e.phrase.get(1<n?"x_comments_lower":"x_comment",n)});d=d.closest(".ui-tabs-panel").find(".conversation-toolbar-wrapper");
d.hasClass("scrolltofixed-floating")&&(d=d.data("object-instance"))&&d.addLimit(p.outerHeight(!0));e.scrollToAnchor("#post"+g.nodeId)}}])});f.off("click",".js-comments__page--prev, .js-comments__page--next").on("click",".js-comments__page--prev, .js-comments__page--next",function(){a("body").css("cursor","wait");var b=a(this),g=b.closest(".js-post"),d=g.find(".js-comments"),n=d.find(".js-comments__comments"),k=Number(b.data("page-num"))||0,y=b.closest(".canvas-widget").attr("data-widget-instance-id");
e.AJAX({call:"/ajax/fetch-comments",data:{page:k,parentid:g.attr("data-node-id"),postindex:g.find(".js-post__content .js-show-post-link").text().replace("#",""),widgetInstanceId:y,isblogcomment:1==b.closest(".blog-list").length?1:0,isarticlecomment:1==b.closest(".article-list").length?1:0},complete:function(l,p){a("body").css("cursor","auto")},success:function(l,p,q){if(l.templates){var x=a("<ul />").attr("class",n.attr("class")),z=l.totalcomments;a.each(l.templates,function(E,v){x.append(v)});n.replaceWith(x);
p=Number(x.find(".js-comment:first-child .js-show-post-link span").text().replace(/\D/g,""));q=Number(x.find(".js-comment:last-child .js-show-post-link span").text().replace(/\D/g,""));var L=Math.ceil(z/vBulletin.conversation.COMMENTS_PER_PAGE);if(b.hasClass("js-comments__page--prev")){var A=b;var B=d.find(".js-comments__page--next")}else A=d.find(".js-comments__page--prev"),B=b;var G=function(E,v,F){E.find(".js-comments__pagination > label").show().text(v==F?v:"{0} - {1}".format(v,F))};k=l.page;
G(d.find(".js-comments__header"),p,q);1==k?d.find(".js-comments__footer").addClass("h-hide"):(p=q+1,q=p+vBulletin.conversation.COMMENTS_PER_PAGE-1,q=q>z?z:q,l=d.find(".js-comments__footer"),l.removeClass("h-hide"),G(l,p,q));A.data("page-num",k+1);B.data("page-num",k-1||1);A.removeClass("h-hide-imp")[L>k?"show":"hide"]().prev("label").show();B[1<k?"show":"hide"]()}},title_phrase:"conversation",error_phrase:"error_fetching_comments"})});vBulletin.conversation.bindEditFormEventHandlers("all");if(f=parseInt(pageData.nodeid))e.markRead(f),
e.AJAX({call:"/ajax/api/node/incrementNodeview",data:{nodeid:f},error:e.ajaxtools.logAjaxError,api_error:e.ajaxtools.logApiError});-1!=location.href.indexOf("edit=1")&&pageData.nodeid&&0<pageData.nodeid&&a("#edit-"+pageData.nodeid).trigger("click");a(document).off("change",".js-article-content-pagenav").on("change",".js-article-content-pagenav",function(){location.href=a(this).val()})}if(!e.pageHasSelectors([".forum-conversation-content-widget",".group-conversation-content-widget",".blog-conversation-content-widget",
".profile-widget","#privateMessageContainer .infractions"]))return!1;var m=e.ckeditor,D={clickQuoteIcon:function(c){this.setPostReplyButtonStyle(c);1==c&&a(".post-reply-btn:visible").trigger("click");0==c&&(c=a(".js-content-entry").last(),c=a(".js-editor",c).attr("id"),m.editorExists(c)&&m.getEditor(c).setData(""))},clickCancelButton:function(){a(".b-post-control__quote--selected").removeClass("b-post-control__quote--selected");this.setPostReplyButtonStyle(0);return!0},setPostReplyButtonStyle:function(c){var f=
a(".post-reply-btn").find(".js-button__text-secondary");0<c?f.text("("+c+")"):f.text("")}};a(function(){K()});return{replyWithQuotes:D}}(jQuery,vBulletin));
