/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache(["invalid_request","invalid_search_syntax","invalid_server_response_please_try_again","unknown_error"],[]);vBulletin.ensureObj("conversation");
(function(a){vBulletin.conversation.filter=function(r){function x(c,e){vBulletin.conversation.displaySelectedFilterText(c,e,b.context)}var f=this,u=null,v=0,z=!1,w=!1,b={context:document,autoCheck:!1,checkInterval:15E3,scrollToTop:null,customFilter:null,onContentLoad:null,closeOverlayOnScroll:!1,pagination:null,allowHistory:!1,tabParamAsQueryString:!0,hash:"",beforeApplyFilters:null,afterResetFilters:null};r&&"object"==typeof r&&a.extend(b,r);var p=new vBulletin.history.instance(b.allowHistory);(function(){a(".toolbar-filter-overlay input[type=radio]",
b.context).off("change.conversation_filter").on("change.conversation_filter",function(c,e,g){c=a(this);var d=a(this.form);if(!p.isEnabled()&&b.allowHistory)return c=vBulletin.makePaginatedUrl(location.href,1),location.href=vBulletin.makeFilterUrl(c,this.name,this.value,b.context,b.hash),!0;z=!0;b.customFilter=null;c.data("bypass-filter-display")||x(this);c=c.closest(".conversation-toolbar-wrapper");1<a(".conversation-toolbar-wrapper",b.context).length&&$toolbarWrappers.filter("."+(c.hasClass("top")?
"bottom":"top")).find("input[name={0}][value={1}]".format(this.name,this.value)).prop("checked",!0);"conversations_on"==this.value?(w=b.autoCheck=!0,v=1):(clearTimeout(v),w="filter_show"==this.name);a(".new-conversations-strip",b.context).hide();f.updatePageNumber(g||1);g=a('.filtered-by .filter-text[data-filter-name="q"]',b.context);if(g.length){var h=f.getSelectedFilters(d);h.q=g.data("filter-value");f.setOption("customFilter",h);f.forceApplyFilters()}else f.applyFilters(!1);p.isEnabled()&&!e&&
(h=f.getSelectedFilters(d),d=this.name,g=this.value,e=a(".filtered-by",c),h={from:"filter",page:1,tab:b.tabParamAsQueryString?"#"+c.closest(".ui-tabs-panel").attr("id"):vBulletin.getSelectedTabHashOrPath(c.closest(".ui-tabs"),!1),filters:h,filtervalue:g,filtername:d},e.data("reset")?(c=location.pathname.replace(/\/page[0-9]+/,""),b.tabParamAsQueryString&&(d=vBulletin.parseQueryString(location.search),d.tab?c+="?tab="+d.tab:d.view&&(c+="?view="+d.view))):(c=vBulletin.makePaginatedUrl(location.href,
1),c=vBulletin.makeFilterUrl(c,d,g,b.context)),p.pushState(h,document.title,c),e.data("reset",null))});a(".new-conversations-strip",b.context).off("click.conversation_filter").on("click.conversation_filter",function(){a(this).hide();w=!0;f.updatePageNumber(1);f.applyFilters(!1,!0)});a(".toolbar-filter",b.context).offon("click.conversation_filter",function(c,e,g){var d=a(".filter-wrapper",this);c=a(this).closest(".conversation-toolbar-wrapper");var h=c.find(".conversation-toolbar");let k=c.hasClass("bottom")?
"bottom":"top",m=a(".toolbar-filter-overlay",c),q=!d.is(".selected");var t=(q?0:100)+"%";"undefined"==typeof e&&(e="slow");d.toggleClass("selected");d.attr("aria-expanded",q);a(".js-expanded-indicator",this).toggleClass("fa-caret-down fa-caret-up");let C=()=>{var n="conversation_filter"+k;if(q){a("body").offon("click."+n,y=>{0==a(y.target).closest(".toolbar-filter-overlay").length&&0==a(y.target).closest(".toolbar-filter").length&&(a("body").off("click."+n),a(window).off("scroll."+n),y=0<a(y.target).closest(".toolbar-filter").length?
"fast":"slow",a(".conversation-toolbar-wrapper.{0} .conversation-toolbar .toolbar-filter".format(k),b.context).triggerHandler("click.conversation_filter",[y]))});var l=!0;if("scroll"!=g){l=a(".filtered-by",b.context);if(0==l.length||l.is(":hidden"))l=this;var A={};(l=vBulletin.isScrolledIntoView(l,A))||a("html,body").animate({scrollTop:"+="+Math.abs(A.bottom)},"fast",function(){setTimeout(function(){if(b.closeOverlayOnScroll)a(window).off("scroll."+n).on("scroll."+n,function(){a(".conversation-toolbar-wrapper.{0} .conversation-toolbar .toolbar-filter".format(k),
b.context).triggerHandler("click.conversation_filter",[0,"scroll"])})},50)})}if(l&&b.closeOverlayOnScroll)a(window).off("scroll."+n).on("scroll."+n,function(){a(".conversation-toolbar-wrapper.{0} .conversation-toolbar .toolbar-filter".format(k),b.context).triggerHandler("click.conversation_filter",[0,"scroll"])})}else a("body").off("click."+n),a(window).off("scroll."+n)};m.css("clip-path",`polygon(0 0, 100% 0, 100% ${t}, 0% ${t})`);m.show();t=m.offsetParent();t=t.offset().left+t.outerWidth();d=d.offset().left+
d.outerWidth();d=t-d;h=h.outerHeight();m.css("max-height",`calc(100vh - ${h}px)`);m.css("--js-filter-menu-right",`${d}px`);a({step:0}).animate({step:100},{step:(n,l)=>{"step"==l.prop&&(n=q?n:100-n,n=Math.max(Math.min(n,100),0),m.css("clip-path",`polygon(0 0, 100% 0, 100% ${n}%, 0% ${n}%)`))},complete:()=>{C()},duration:e});c.hasClass("bottom")&&a(".js-expanded-indicator",this).hasClass("fa-caret-up")&&(e=a(".conversation-toolbar-wrapper.bottom .toolbar-filter-overlay",b.context),a("html, body").animate({scrollTop:e.offset().top+
e.innerHeight()},500))});a(".filtered-by",b.context).offon("click.conversation_filter",".js-remove-filter",function(){var c=a(this),e=c.closest(".filtered-by"),g=c.closest(".filter-text"),d=g.data("filter-name");a();e.data("clicked",!0);if(!p.isEnabled()&&b.allowHistory)return"text"==g.data("filter-type")&&g.data("filter-js-selector")?(e=vBulletin.makePaginatedUrl(location.href,1),location.href=vBulletin.makeFilterUrl(e,"q","",b.context,b.hash,!0)):(e=vBulletin.makePaginatedUrl(location.href,1),location.href=
vBulletin.makeFilterUrl(e,d,g.data("filter-value"),b.context,b.hash,!0)),!1;var h=a(".toolbar-filter-overlay .filter-options input[name={0}]".format(d),b.context).prop("checked",!1).filter(".js-default-checked");f.updatePageNumber(1);if("text"==g.data("filter-type")&&g.data("filter-js-selector")){a(g.data("filter-js-selector")).val("");var k=f.getSelectedFilters(a("form.toolbar-filter-overlay",b.context));delete k[d];f.setOption("customFilter",k)}g.remove();g=e.find(".filter-text").length;0==g?(e.addClass("h-hide"),
e.data("reset",!0)):1==g&&e.find(".clear-all").addClass("h-hide");1==h.length?(h.data("bypass-filter-display",!0),h.trigger("click.conversation_filter"),h.data("bypass-filter-display",null)):(k&&(e=vBulletin.makePaginatedUrl(location.href,1),e=vBulletin.makeFilterUrl(e,"q","",b.context),p.pushState({from:"filter",page:1,tab:b.tabParamAsQueryString?"#"+c.closest(".ui-tabs-panel").attr("id"):vBulletin.getSelectedTabHashOrPath(c.closest(".ui-tabs"),!1),filters:k},document.title,e)),f.forceApplyFilters(),
k&&f.setOption("customFilter",null))});a(".filtered-by",b.context).offon("click.conversation_filter",".clear-all",function(c){var e=a(this).closest(".conversation-toolbar-wrapper");a(this).data("clicked",!0);f.setOption("customFilter",null);f.resetFilters(!1,!1,e);c.preventDefault()});a(".conversation-toolbar .filter-wrapper",b.context).data("object-instance",f);a(".js-conversation-showmore-button",b.context).off("click").on("click",function(){var c=parseInt(a('form.toolbar-filter-overlay input[name="pagenum"]',
b.context).val());w=!1;f.updatePageNumber(c+1);f.applyFilters(!1,!0,!0)});a(".conversation-toolbar .toolbar-search-form",b.context).off("submit.filtersearch").on("submit.filtersearch",function(){var c=a(this.elements.q),e=a.trim(c.val()),g=a(this).closest(".conversation-toolbar-wrapper");c.val(e);if(!p.isEnabled()&&b.allowHistory){var d=vBulletin.makePaginatedUrl(location.href,1);location.href=vBulletin.makeFilterUrl(d,"q",e,g);return!1}c=b.tabParamAsQueryString?"#"+a(this).closest(".ui-tabs-panel").attr("id"):
vBulletin.getSelectedTabHashOrPath(a(this).closest(".ui-tabs"),!1);if(e){var h=f.getSelectedFilters(g.find(".toolbar-filter-overlay"));d={};d.q=e;a.extend(h,d);f.setOption("customFilter",h);f.forceApplyFilters();f.displayCustomFilterText(this.elements.q);p.isEnabled()&&(d=vBulletin.makePaginatedUrl(location.href,1),d=vBulletin.makeFilterUrl(d,"q",e,g),p.pushState({from:"filter",page:1,tab:c,filters:h},document.title,d))}else d=g.find('.filter-text[data-filter-name="{0}"]'.format("q")),d.length&&(h=
f.getSelectedFilters(g.find(".toolbar-filter-overlay")),f.setOption("customFilter",h),a(".x",d).trigger("click"),p.isEnabled()&&(d=vBulletin.makePaginatedUrl(location.href,1),d=vBulletin.makeFilterUrl(d,"q",e,g),p.pushState({from:"filter",page:1,tab:c,filters:h},document.title,d)));return!1})})();this.isFilterSelected=function(c){return a('.toolbar-filter-overlay input[value="'+c+'"]',b.context).is(":checked")};this.getSelectedFilters=function(c){return vBulletin.getSelectedFilters(c,!1)};this.resetFilterForms=
function(c){if(!c||c instanceof a&&!c.length)c=b.context;a(".toolbar-filter-overlay .js-default-checked",c).prop("checked",!0);a(".toolbar-search-form .js-filter-search",c).val("")};a(".toolbar-filter-overlay, .toolbar-search-form",b.context).trigger("reset");if(p.isEnabled()){r=p.getState();if(!r||a.isEmptyObject(r.data)){a(b.context).hasClass("ui-tabs-panel")?a(b.context).attr("id"):a(".conversation-toolbar-wrapper",b.context).closest(".ui-tabs-panel").attr("id");var B={from:"filter",page:Number(a(".pagenav-form .defaultpage",
b.context).val())||1,tab:vBulletin.getSelectedTabHashOrPath(a(b.context).closest(".ui-tabs"),b.tabParamAsQueryString),filters:f.getSelectedFilters(a("form.toolbar-filter-overlay",b.context))};p.setDefaultState(B,document.title,location.href)}p.setStateChange(function(c,e,g){var d=p.getState();if("filter"==d.data.from||"pagination"==e||"tabs"==e){p.log(d.data,d.title,d.url);var h;d.data.tab&&(h=b.tabParamAsQueryString?a(d.data.tab):a('.ui-tabs .ui-tabs-panel[data-url-path="'+d.data.tab+'"]'));c=h&&
h.length&&h||b.context;if("pagination"==e){if(g){e=a(".filtered-by",c);var k=a(".toolbar-filter-overlay .filter-options-list",c),m=!1;a(".filter-text",e).filter('[data-filter-name!="q"]').remove();a(".clear-all",e).addClass("h-hide");k.find(".js-default-checked").prop("checked",!0);a.each(g,function(q,t){q=a('input[name="{0}"][value="{1}"]'.format(q,t),k);q.length&&(q.prop("checked",!0).trigger("change",[!0,d.data.page]),m=!0)});m||(k.first().data("bypass-filter-display",!0).trigger("change",[!0,
d.data.page]).data("bypass-filter-display",null),e.addClass("h-hide"))}}else g=a(c).closest(".ui-tabs"),e=b.tabParamAsQueryString?g.find('.ui-tabs-nav > li > a[href*="{0}"]'.format(d.data.tab)):g.find('.ui-tabs-nav > li > a[data-url-path="'+d.data.tab+'"]'),e.parent().hasClass("ui-tabs-active")?(g=f.getSelectedFilters(a(".toolbar-filter-overlay",c)),e=a(".conversation-toolbar .filter-wrapper",c).data("object-instance")||f,vBulletin.areJsonObjectsEqual(g,d.data.filters)||(e.setOption("context",c),
e.updatePageNumber(d.data.page),e.applyHistoryFilters(d.data))):(c=e.parent().index(),vBulletin.selectTabByIndex.call(g,c))}},"filter")}this.displayCustomFilterText=function(c,e){x(c,e||a(c).val())};this.isHistoryEnabled=function(){return p.isEnabled()};this.resetFilters=function(c,e,g){if(!g||g instanceof a&&!g.length)g=b.context;var d=a(".filtered-by",g).addClass("h-hide"),h=location.pathname.replace(/\/page[0-9]+/,"");if(b.tabParamAsQueryString){var k=vBulletin.parseQueryString(location.search);
k.tab?h+="?tab="+k.tab:k.view&&(h+="?view="+k.view)}a(".clear-all",d).addClass("h-hide");a(".filter-text",d).remove();f.resetFilterForms(g);if(!c)if(p.isEnabled()){d.data("reset",!0);f.updatePageNumber(1);k=f.getSelectedFilters(a("form.toolbar-filter-overlay",g));if(e){var m=a(".toolbar-search-form .js-filter-search",g).val("");delete k[m.attr("name")];f.setOption("customFilter",k)}f.forceApplyFilters();B={from:"filter",page:1,tab:b.tabParamAsQueryString?"#"+d.closest(".ui-tabs-panel").attr("id"):
vBulletin.getSelectedTabHashOrPath(d.closest(".ui-tabs"),!1),filters:k};p.pushState(B,document.title,h)}else b.allowHistory&&(location.href=h);"function"==typeof b.afterResetFilters&&b.afterResetFilters.apply(this,arguments);return f};this.applyHistoryFilters=function(c){if(c&&c.filters&&!a.isEmptyObject(c.filters)){var e=b.tabParamAsQueryString?a(c.tab):a('.ui-tabs .ui-tabs-panel[data-url-path="'+c.tab+'"]'),g=a(".toolbar-filter-overlay",e);"undefined"!=typeof f.lastFilters&&delete f.lastFilters;
f.resetFilters(!0,!1,e);a.each(c.filters,function(m,q){m=a('[name="'+m+'"]',g);"hidden"==m.attr("type")?m.val(q):"radio"==m.attr("type")&&q!=c.filtervalue&&m.filter('[value="'+q+'"]').prop("checked",!0)});var d=vBulletin.parseQueryString(location.href),h=!0,k=function(){a(".toolbar-search-form .js-filter-search",e).val("")};a.isEmptyObject(d)?k():a.each(d,function(m,q){var t=a('.filter-options-list input[name="{0}"][value="{1}"]'.format(m,q),g);t.length?c.filtername==m&&c.filtervalue==q?(h=!1,t.prop("checked",
!0).trigger("change",[!0])):x(t.get(0)):(t=a('.toolbar-search-form .js-toolbar-search-inner input[name="{0}"]'.format(m),e),t.length&&q?(x(t.get(0),q),t.val(q)):k())});h&&(f.setOption("customFilter",c.filters),f.forceApplyFilters(),f.setOption("customFilter",null))}return f};this.forceApplyFilters=function(){"undefined"!=typeof f.lastFilters&&delete f.lastFilters;w=!0;f.applyFilters(!1,!0);return f};this.applyFilters=function(c,e,g,d){if("function"==typeof b.beforeApplyFilters&&!1===b.beforeApplyFilters.apply(this,
arguments))return f;var h=a(".toolbar-filter-overlay",b.context);e&&clearTimeout(v);var k={filters:b.customFilter?b.customFilter:f.getSelectedFilters(h),isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0};if(a.isEmptyObject(k.filters))return f;c&&(k.filters.checkSince=u,k.filters.pagenum=1);d?w=!0:h.find('input[name="result-id"]').val(0).length&&(k.filters["result-id"]=0);if("undefined"!=typeof this.lastFilters&&vBulletin.areJsonObjectsEqual(this.lastFilters.filters,k.filters)&&!c)return f;this.lastFilters=
k;var m=a(".conversation-empty",b.context),q=a(".conversation-toolbar-wrapper",b.context);q.addClass("h-disabled");m.addClass("h-invisible");c&&window.vBulletin.loadingIndicator.suppressNextAjaxIndicator();var t=vBulletin.normalizeAjaxUrl(h.attr("action"))||vBulletin.getAjaxBaseurl()+"/activity/get",C=h.closest(".conversation-toolbar-wrapper").find('form.pagenav-form input[name="article_display_columns"]');1==C.length&&(k.article_display_columns=C.val());var n=a(".conversation-list",b.context);vBulletin.AJAX({url:t,
data:k,api_error:function(l){l=l[0];n.addClass("h-hide");l=vBulletin.phrase.get(l);m.html((l||"").replace(/<br\s*\/*>/g," ")).removeClass("h-hide h-invisible")},success:function(l){m.addClass("h-hide");if(c)!z&&0<l.total&&!a("body").hasClass("edit-mode")&&(a(".new-conversations-strip span",b.context).html(l.total),a(".new-conversations-strip",b.context).fadeIn("slow")),0==a(".conversation-list li.list-item",b.context).length&&m.removeClass("h-hide");else{var A=a(".js-conversation-showmore",b.context);
a(".new-conversations-strip",b.context).hide();if((0<l.total_with_sticky||0<l.total)&&l.template){l.resultId&&(a('input[name="result-id"]',h).val(l.resultId).length&&this.lastFilters&&(this.lastFilters.filters["result-id"]=l.resultId),b.pagination&&b.pagination.updateResultId(l.resultId));g?n.append(l.template):(m.addClass("h-hide"),n.html(l.template).removeClass("h-hide"));l.fixFlexGrid&&vBulletin.initFlexGridFixLastRowAll();var y=k.filters,D=parseInt(y.maxpages);y=parseInt(y.pagenum);var E=l.pageinfo;
D=D&&y>=D||E&&(y>=parseInt(E.totalpages)||!1===E.showseemore);A.toggleClass("h-hide",D)}else g||(m.removeClass("h-hide"),n.addClass("h-hide").empty());0==l.total_with_sticky&&A.addClass("h-hide");w&&b.scrollToTop&&(A=b.scrollToTop instanceof a?b.scrollToTop:a(b.scrollToTop),0<A.length&&a("body,html").animate({scrollTop:A.offset().top},"slow"));u=l.lastDate;"function"==typeof b.onContentLoad&&b.onContentLoad.apply(n.get(0),[l]);l.pageinfo&&(f.updatePageNumber(l.pageinfo.pagenumber||1),b.pagination&&
"function"==typeof b.pagination.updatePageInfo&&(b.pagination.setOption("context",b.context),b.pagination.updatePageInfo(l.pageinfo,!0)));vBulletin.inlinemod&&"function"==typeof vBulletin.inlinemod.init&&0<a(".moderationmenu_container",b.context).length&&vBulletin.inlinemod.init(b.context);a(document).trigger("vb-filterposts",{parentOfInsertedHtml:n})}z&&(z=!1)},error_phrase:"unable_to_contact_server_please_try_again",complete:function(){q.removeClass("h-disabled");m.removeClass("h-invisible");!z&&
b.autoCheck&&v&&(v=setTimeout(f.checkNewConversations,b.checkInterval))}});return f};this.updatePageNumber=function(c){c=Number(c);0<c&&a('form.toolbar-filter-overlay input[name="pagenum"]',b.context).val(c);return f};this.checkNewConversations=function(){a("body").hasClass("edit-mode")||(console.log("Checking for new activity since "+u),f.applyFilters(!0));return f};this.toggleNewConversations=function(c){c?(b.autoCheck=!0,v=setTimeout(f.checkNewConversations,b.checkInterval)):(b.autoCheck=!1,clearTimeout(v));
return f};this.hideFilterOverlay=function(){a(".conversation-toolbar-wrapper .toolbar-filter-overlay",b.context).filter(":visible").each(function(){a(this).prev(".conversation-toolbar").find(".toolbar-filter").triggerHandler("click.conversation_filter",[0])});return f};this.getOption=function(c){return b[c]};this.setOption=function(c,e){b[c]=e;return f};b.autoCheck&&(u=pageData.current_server_datetime,v=setTimeout(f.checkNewConversations,b.checkInterval))};vBulletin.conversation.displaySelectedFilterText=
function(r,x,f){var u=a(r);if(1!=u.data("bypass-filter-display")){f=f||u.closest(".conversation-toolbar-wrapper");var v=a(".filtered-by",f).removeClass("h-hide").find(".filter-text-wrapper").show(),z=a(".filter-text[data-filter-name={0}]".format(r.name),v);if("radio"==r.type){x=u.next("span").html();var w=a('<div class="filter-text" data-filter-name="{0}" data-filter-value="{1}"><span title="{2}">{3}</span><span class="js-remove-filter b-icon b-icon__x-circle"></span></div>'.format(r.name,vBulletin.htmlEntities(r.value),
u.closest(".filter-options").prev(".filter-header").html()+" - "+x,("filter_new_topics"==r.name||"filter_depth"==r.name||-1!=r.value.indexOf("_all")&&"time_all"!=r.value?(u.closest("li").find(".filter-header").html()||"")+" - ":"")+x))}else"text"==r.type&&(x="&quot;"+JShtmlEncode(x)+"&quot;",w=a('<div class="filter-text" data-filter-name="{0}" data-filter-value="{1}"><span title="{2}">{3}</span><span class="js-remove-filter b-icon b-icon__x-circle"></span></div>'.format(r.name,vBulletin.htmlEntities(r.value),
u.data("filter-name")+": "+x,x)).data("filter-type","text"),(u=u.attr("class").match(/js-.*/))&&w.data("filter-js-selector","."+u[0]));if(0<z.length)z.replaceWith(w);else{var b=[],p=!1;a(".toolbar-filter-overlay > ul > li",f).each(function(){b.push(a("input:first",this).attr("name"))});a(".filter-text",v).each(function(){var B=a(this);if(a.inArray(r.name,b)<a.inArray(B.attr("data-filter-name"),b))return B.before(w),p=!0,!1});p||v.append(w);1<a(".filter-text",v).length&&v.next(".clear-all").removeClass("h-hide")}}}})(jQuery);
