/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache(["cancel","no","ok","yes"],[]);
vBulletin.createDialogTools=(f,r,h)=>{function t(a,b,c){a.data("created")||a.dialog({autoOpen:!1,modal:!0,resizable:!1,closeOnEscape:!1,showCloseButton:!1,dialogClass:"dialog-container dialog-box "+c,create:()=>{a.data("created",!0)}});a.dialog("option","width",b||500);a.find(".js-button").toggleClass("b-button--sitebuilder",f("body").is(".edit-mode, .js-edit-mode-style"))}function u(a,b){a=a.find(".icon");a.removeClass((c,e)=>(e.match(/b-icon\S+\b/g)||[]).join(" ")+" no-icon b-icon");switch(b){case "warning":case "error":a.addClass("b-icon b-icon__warning-l--red h-margin-right-xl");
a.show();break;default:a.addClass("no-icon").hide()}}function v(a,b,c=e=>e){b&&a.find(".message").html(c(b))}function w(a){var b=f("#prompt-dialog");b.data("created")||b.dialog({autoOpen:!1,modal:!0,resizable:!1,closeOnEscape:!1,showCloseButton:!1,width:500,dialogClass:"dialog-container prompt-dialog-container dialog-box",create:function(){b.data("created",!0)}});a=a||{};b.dialog("option","title",a.title);var c=b.find(".dialog-content"),e=c.find(".message");a.message&&e.html(a.message);e=a.initialValue||
"";if(a.multiline){var d=b.find("textarea.input-box").val(e).removeClass("h-hide");d.prev().addClass("h-hide");c.removeClass("table");c.find("> .td").removeClass("td")}else d=b.find("input.input-box").val(e).removeClass("h-hide"),d.next().addClass("h-hide"),Number(a.maxlength)?d.attr("maxlength",Number(a.maxlength)):d.removeAttr("maxlength"),c.addClass("table"),c.find("> div").addClass("td");a.buttonLabel=a.buttonLabel||{};a.buttonLabel.okLabel=a.buttonLabel.okLabel||h.get("ok");a.buttonLabel.cancelLabel=
a.buttonLabel.cancelLabel||h.get("cancel");f("#btnPromptDialogOK").html(a.buttonLabel.okLabel);f("#btnPromptDialogCancel").html(a.buttonLabel.cancelLabel);var g;b.find(".js-button").toggleClass("b-button--sitebuilder",f("body").is(".edit-mode, .js-edit-mode-style"));b.off("dialogopen").on("dialogopen",function(){f("#btnPromptDialogOK").off("click").on("click",function(){g=this;var m=f.trim(d.val());if(a.validation&&"object"==typeof a.validation){var k=a.validation;if(!k.override&&k.callback){var l=
k.callback;Array.isArray(l)||(l=[l]);for(i=0;i<l.length;i++)if("function"==typeof l[i]){var n=l[i].apply(b,[d,a]);if(!0!==n)return n&&k.showError&&b.find(".js-prompt-error").html(h.get(n)).removeClass("h-hide"),d.trigger("select").trigger("focus"),!1}}if("function"==typeof k.custom&&!k.custom.apply(this,[d]))return!1}if("function"==typeof a.onClickOK){var A=a.onClickOK.apply(this,[m]);if("undefined"!=typeof a.onClickOKWithAjax&&a.onClickOKWithAjax)return!1}if(!1===A)return!1;if("function"==typeof a.onBeforeClose){var B=
a.onBeforeClose.apply(this);if("undefined"!=typeof a.onBeforeCloseWithAjax&&a.onBeforeCloseWithAjax)return!1}if(!1===B)return!1;b.dialog("close")}).trigger("focus");f("#btnPromptDialogCancel").off("click").on("click",function(){g=this;"function"==typeof a.onClickCancel&&a.onClickCancel.apply(this);"function"==typeof a.onBeforeClose&&a.onBeforeClose.apply(this);b.dialog("close")})});b.off("dialogclose").on("dialogclose",function(){b.find(".js-prompt-error").addClass("h-hide");"function"==typeof a.onAfterClose&&
(a.onAfterClose.apply(g),d.val(""))});b.dialog("open");d.trigger("focus");return b}function x(a){a=a||{};let b=f("#confirm-dialog");t(b,a.width,"");b.dialog("option","dialogClass","dialog-container confirm-dialog-container dialog-box "+(a.dialogClass||""));var c=a.title;b.dialog("option","title",c);b.closest(".ui-dialog").find(".ui-dialog-title").html(c);c=b.find(".dialog-content");u(c,a.iconType);v(c,a.message,g=>g.replace("\n","<br />"));c=a.buttonLabel||{};let e=f("#btnConfirmDialogYes").html(c.yesLabel||
h.get("yes"));$noButton=f("#btnConfirmDialogNo").html(c.noLabel||h.get("no"));e.addClass("b-button--primary").removeClass("b-button--secondary");$noButton.addClass("b-button--secondary").removeClass("b-button--primary");let d;processcallback=g=>p(g).apply(d,[b]);b.offon("dialogopen",function(){e.offon("click",function(){d=this;if(!1===processcallback(a.onClickYes)||a.onClickYesWithAjax||!1===processcallback(a.onBeforeClose))return!1;b.dialog("close")}).trigger("focus");$noButton.offon("click",function(){d=
this;processcallback(a.onClickNo);processcallback(a.onBeforeClose);b.dialog("close")})});b.offon("dialogclose",()=>{processcallback(a.onAfterClose)});b.dialog("open");return b}function y(a){return x({title:h.get(a.title),message:h.get(a.message),width:a.width,dialogClass:a.dialogClass,buttonLabel:{yesLabel:h.get(a.yesPhrase||"yes"),noLabel:h.get(a.noPhrase||"no")},onClickYes:a.onClickYes,onClickNo:a.onClickNo,iconType:a.iconType})}function z(a){a=a||{};var b=f("#alert-dialog");t(b,a.width,"alert-dialog-container");
b.dialog("option","title",a.title);var c=b.find(".dialog-content"),e=f("#btnAlertDialogOK"),d="",g="";u(c,a.iconType);v(c,a.message);a.maxHeight&&(d=a.maxHeight,g="auto");c.css({"max-height":d,overflow:g});e.html(a.buttonLabel||h.get("ok"));b.offon("dialogopen",function(){e.offon("click",function(){p(a.onBeforeClose).apply(this);b.dialog("close")}).trigger("focus");b.parent(".alert-dialog-container").css("z-index","10100")});b.offon("dialogclose",()=>{p(a.onAfterClose).apply(e)});b.dialog("open");
return b}function q(a,b,c,e){var d=e;d instanceof jQuery&&(d=()=>{e.trigger("focus")});z({title:h.get(a),message:h.get(b),iconType:c,onAfterClose:d})}let p=r.ensureFun;f.widget("ui.dialog",f.ui.dialog,{_allowInteraction:function(a){if(this._super(a)||a.target.ownerDocument!=this.document[0]||f(a.target).closest(".cke_dialog").length||f(a.target).closest(".cke").length)return!0}});(function(){var a=jQuery.fn.dialog;jQuery.fn.dialog=function(){if("object"==typeof arguments[0]){var b=function(){};"function"==
typeof arguments[0].open&&(b=arguments[0].open);arguments[0].open=function(){var e=f(this);setTimeout(function(){vBulletin.Responsive.Debounce.runCallbacks();e.closest(".ui-dialog").find(".ui-dialog-titlebar-close .ui-icon").removeClass("ui-icon ui-icon-closethick").addClass("b-icon b-icon__x-square--gray")},0);e.closest(".ui-dialog").find(".ui-dialog-content").removeClass("h-hide");return b.apply(this,arguments)};var c=function(){};"function"==typeof arguments[0].close&&(c=arguments[0].close);arguments[0].close=
function(){f(this).closest(".ui-dialog").find(".ui-dialog-content").addClass("h-hide");return c.apply(this,arguments)}}return a.apply(this,arguments)}})();w.validationString=function(a,b){return(a=f.trim(a.val()))?b.multiline&&a.length>b.maxlength?["message_too_long",b.maxlength]:!0:"please_enter_a_value"};return{openAlertDialog:z,openConfirmDialog:x,openConfirmDialogSimple:y,openPromptDialog:w,openTemplateConfirmDialog:function(a,b,c){b.message="loading_ellipsis";b.dialogClass=(b.dialogClass||"")+
" loading";let e=y(b),d=c.data||{};d.isAjaxTemplateRender=!0;d.isAjaxTemplateRenderWithData=!0;let g=c.call||"/ajax/render/"+c.name;return new Promise((m,k)=>{a.ajax({call:g,data:d,success:l=>{e.parent(".confirm-dialog-container").removeClass("loading");f(".dialog-content .message",e).html(l.template).trigger("vb-instrument");e.dialog("option","position",{of:window});f("select",e).selectBox();m(e)},api_error:c.api_error,title_phrase:b.title,error_phrase:"error_loading_dialog_form",after_error:()=>
{k();e.dialog("close")}})})},popupWindow:function(a,b,c,e){let d=window,g=document;a=d.open(a,b,"status=yes,resizable=yes,scrollbars=yes,width="+c+", height="+e+", top="+((d.innerHeight||g.documentElement.clientHeight||screen.height)/2-e/2+(d.screenTop||screen.top))+", left="+((d.innerWidth||g.documentElement.clientWidth||screen.width)/2-c/2+(d.screenLeft||screen.left)));d.focus&&a.focus();return a},alert:q,warning:(a,b,c)=>q(a,b,"warning",c),error:(a,b,c)=>q(a,b,"error",c),showStatusMessage:function(a,
b){let c=f(".conversation-status-message.notice");var e;if(0<c.length){a=h.get(a);let d=c.filter("."+b);c=1==d.length?d:1==(e=c.filter(".h-hide")).length?e:c.first().clone().removeClass().addClass("conversation-status-message notice").appendTo(".conversation-status-messages");c=(1==d.length?d:c).show();r.isScrolledIntoView(c)?c.hasClass("h-hide")?c.hide().removeClass("h-hide").addClass(b+" show-x").find("span").html(a).end().fadeIn(800,"linear"):c.fadeOut("slow","linear",function(){c.find("span").html(a).end().addClass(b+
" show-x").fadeIn("slow","linear")}):(e=c.offset().top-10,c.hide(),f("html,body").animate({scrollTop:e},"slow",function(){c.find("span").html(a).end().addClass(b+" show-x").fadeIn("slow","linear")}))}}}};
