/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache("add_caption attach_files click_to_add_caption drop_files_here_to_upload enter_url_file error_uploading_image invalid_image_allowed_filetypes_are remove_all_photos_confirmation_message remove_all_photos_q upload upload_more uploading you_are_already_editing_continue".split(" "),[]);
vBulletin.upload=((a,q,m,u,K,F,B)=>{function v(b,e){a(".b-button--upload .js-upload-label",b).each((f,l)=>{f=a(l);l=f.data("default-text");l||(l=f.text(),f.data("default-text",l));f.text(void 0===e?l:m.get(e))})}async function L(b){b=await (await fetch(b)).blob();let e="dataurl"+String(Date.now()).slice(-6)+"."+b.type.split("/")[1];return new File([b],e)}async function M(b,e){return new Promise((f,l)=>{var c=new FormData,d=()=>l(Error("Upload Failed"));c.append("uploadFrom","newContent");c.append("files",
b);u.ajax({call:"/uploader/upload",data:c,success:function(g){for(var h of g)if(g=h.error){if(Array.isArray(g)||(g=[g]),g=[h.name,...g.map(k=>m.get(k))],0<g.length){B.openAlertDialog({title:m.get("upload"),message:g.join("<br />\n"),iconType:"warning"});d();return}}else{g=C(a(".b-content-entry-panel__content--attachment",e),h);f({upload:h,panelitem:g});return}d()},error_phrase:"error_uploading_image",after_error:d})})}function C(b,e){console.log("Fileupload: attachDone");b=b.find(".js-attach-list");
var f=a(".js-uploadFrom").val();e.name||q.error("upload","unknown_error");var l=!1;if(e.name.match(/\.(gif|jpg|jpeg|jpe|png|bmp|webp)$/i)){var c=a("<img />").attr("src",pageData.baseurl+"/filedata/fetch?type=thumb&filedataid="+e.filedataid).addClass("b-attach-item__image");l=!0}else c=a("<span />").addClass("b-icon-fa b-icon-fa--16 fa-solid fa-file-lines");var d=b.find(".js-attach-item-sample").first().clone(!0);"signature"==f&&(b.find(".js-attach-item").not(".js-attach-item-sample").remove(),l=!1,
a('[data-action="insert"]',d).data("action","insert_sigpic").attr("data-action","insert_sigpic"));d.removeClass("js-attach-item-sample");d.find(".js-attach-item-image").append(c);d.find(".js-attach-item-filename").text(e.name);d.append(a("<input />").attr({type:"hidden",name:"filedataids[]"}).val(e.filedataid)).append(a("<input />").attr({type:"hidden",name:"filenames[]"}).val(e.name));d.data({fileext:e.extension,filebasetype:e.basetype,filename:e.name,filedataid:e.filedataid,attachnodeid:0});e=(g,
h)=>g.find(".js-attach-ctrl").filter((k,n)=>h.includes(a(n).data("action")));l||(e(d,["insert_image","insert_label"]).addClass("h-hide"),e(d,["insert"]).html(m.get("insert")));q.ckeditor.checkEnvironment()||e(d,["insert","insert_image","insert_label"]).addClass("h-hide");d.appendTo(b).removeClass("h-hide");b.removeClass("h-hide");return d}function D(b){function e(c){y(c,0<a(".photo-display .photo-item-wrapper:not(.h-hide)",c).length)}function f(c){c.length||(c=a("<form>"));let d=c.find('input[name="securitytoken"]');
d.length||(d=a('<input type="hidden" name="securitytoken" />'),c.append(d));d.val(pageData.securitytoken);return c.find(":input").filter((g,h)=>!a(h).parent().hasClass("js-photo-postdata")).serializeArray()}function l(c){var d=[["error_uploading_image"]];c&&0<c.files.length&&"acceptFileTypes"==c.files[0].error&&(d=[["invalid_image_allowed_filetypes_are"]]);u.showApiError(d,{},{title:"upload"})}console.log("Fileupload: vBulletin.upload.initializePhotoUpload");if(!b||0==b.length)if(b=a("body"),1<a(".js-photo-display",
b).length)return console.log("Fileupload: multiple upload forms, abort"),!1;a(".js-continue-button",b).offon("click",function(c){console.log("Fileupload: continue");var d=a(document).data("gallery-container"),g=d.find(".js-photo-postdata");c=g.closest(".js-contententry-form").find('input[name="nodeid"]');c=c.length&&c[0].value||0;var h={},k=a(this).closest(".js-photo-display"),n=[],E=0;g.empty();0<c&&q.gallery.clearCacheForNodeid(c);k.find(".photo-item-wrapper:not(.h-hide)").each(function(){var r=
a(this).find(".filedataid"),p=r.val();r=r.data("nodeid");var G=a.trim(a(this).find(".caption-box").val()),H=a.trim(a(this).find(".js-photo-title").val());a(this).removeClass("tmp-photo");"undefined"!==typeof r&&(a(this).removeClass("tmp-photo"),-1==a.inArray(r,z)&&z.push(r));E++;g.append(a("<input />").attr({type:"hidden",name:"filedataid[]"}).val(p)).append(a("<input />").attr({type:"hidden",name:"title_"+p}).val(H)).append(a("<input />").attr({type:"hidden",name:"caption_"+p}).val(G)).append(a("<input />").attr({type:"hidden",
name:"displayorder_"+p}).val(E));n.push({filedataid:p,caption:G,title:H,displayorder:E})});h.photocount=n.length;h.photos=n;h.isAjaxTemplateRenderWithData=!0;k.find(".photo-item-wrapper:hidden").remove();k.dialog("close");0<h.photos.length?(u.ajax({call:"/ajax/render/editor_gallery_photoblock",data:h,type:"POST",dataType:"json",success:function(r){var p=a(r.template);p.find(".b-gallery-thumbnail-list__aside").addClass("h-invisible");d.find(".js-gallery-content").removeClass("h-hide").find(".js-panel-content").empty().append(p);
setTimeout(function(){p.find(".b-gallery-thumbnail-list__aside").removeClass("h-invisible")},500);D(d);a(document).data("gallery-container",null)},silent:!0}),a(".js-edit-photos",d).removeClass("h-hide"),v(d,"upload_more")):(a(".js-panel-content",d).empty(),a(".js-edit-photos",d).addClass("h-hide"),v(d))});a(".js-edit-photos",b).offon("click",function(c){console.log("Fileupload: edit photos");a(document).data("gallery-container",a(this).closest(".b-content-entry-panel__content--gallery"));c=w(!1);
x(c.find(".photo-item-wrapper"));e(c);c.dialog("open");t(c);a(".b-button--upload",c).trigger("focus")});a(".js-cancel-button",b).offon("click",function(c){console.log("Fileupload: cancel");c=a(this).closest(".js-photo-display");var d=a(document).data("gallery-container");a(".photo-item-wrapper.tmp-photo",c).remove();a(".photo-item-wrapper",c).removeClass("h-hide");v(d,0<a(".js-slideshow--item",d).length?"upload_more":void 0);c.dialog("close")});a(".b-content-entry-panel__content--attachment",b).offon("click",
".js-upload-from-url",function(c){var d=a(this);B.openPromptDialog({title:m.get("enter_url_file"),message:"",buttonLabel:{okLabel:m.get("ok"),cancelLabel:m.get("cancel")},onClickOK:function(g){var h=d.parent().find(".js-upload-progress");h.removeClass("h-hide");u.ajax({call:"/uploader/url",data:{urlupload:g,attachment:1,uploadFrom:a(".js-uploadFrom",b).val()},skipdefaultsuccess:!0,complete:function(){h.addClass("h-hide")},success:function(k){k.imageUrl&&($panel=a(".b-content-entry-panel__content--attachment"),
k.name=k.filename,C($panel,k))},title_phrase:"error_uploading_image"})}});return!1});a(".b-content-entry-panel__content--gallery, .js-profile-media-photoupload-dialog",b).fileupload({dropZone:"vb-self",dataType:"json",url:q.getAjaxBaseurl()+"/uploader/upload-photo",type:"POST",formData:c=>f(c.find(".b-content-entry-panel__content--gallery")),add:function(c,d){console.log("Fileupload: gallery add");c=a(this);a(document).data("gallery-container",c);c=w(!0);a(".js-upload-progress",c).removeClass("h-hide");
v(c,"uploading");d.submit();a(".b-button--upload",c).trigger("focus")},done:function(c,d){c=a(this);var g=d&&d.result&&d.result.errors&&0<d.result.errors.length;a(document).data("gallery-container",c);var h=w(!1);if(d&&d.result&&!g&&d.result.edit){d=a(d.result.edit);var k=a(".photo-display",h),n=h.parent();c=a(".photo-item-wrapper:not(.h-hide)",k).length;d.addClass("tmp-photo");0==(c+1)%3&&d.addClass("last-in-row");c+1>F.ATTACHLIMIT&&a(".js-attach-limit-warning",h).show();t(h);k.append(d);d.fadeIn("fast",
function(){h.dialog("option","position",{of:window});n.hasClass("has-scrollbar")&&k.animate({scrollTop:k[0].scrollHeight-k.height()},"fast")})}else d=g?d.result.errors[0]:"unknown_error",q.warning("upload",d)},fail:(c,d)=>{l(d)},always:function(c,d){c=w(!1);c.find(".js-upload-progress").addClass("h-hide");e(c)}});a(".b-content-entry-panel__content--attachment",b).fileupload({dropZone:"vb-self",dataType:"json",url:q.getAjaxBaseurl()+"/uploader/upload",type:"POST",previewAsCanvas:!1,autoUpload:!0,formData:c=>
f(c.find(".b-content-entry-panel__content--attachment")),add:function(c,d){console.log("Fileupload: attachments add");b.find(".js-upload-progress").removeClass("h-hide");d.submit()},done:function(c,d){c=[];var g=[],h={};if(d&&d.result)if(h=d.result,h.error)c=[h.error];else if(h.errors)c=h.errors;else for(var k of d.result)(d=k.error)?(Array.isArray(d)||(d=[d]),g.push(k.name,...d.map(n=>m.get(n)))):C(a(this),k);else c=[["invalid_server_response_please_try_again"]];0<c.length?u.showApiError(c,h,{title:"upload"}):
0<g.length&&B.openAlertDialog({title:m.get("upload"),message:g.join("<br />\n"),iconType:"warning"})},fail:(c,d)=>{l(d)},always:function(c,d){b.find(".js-upload-progress").addClass("h-hide")}});a(document).offon("click.photoadd",".js-photo-selector-continue",function(){console.log("Fileupload: continue 2");var c=a(this).closest(".js-photo-selector-container"),d={};c.find(".photo-item-wrapper").each(function(){var g=a(this).find(".filedataid"),h=g.data("nodeid");if(g.is(":checked")){g=g.val();var k=
a.trim(a(this).find(".photo-title").text());d[h]={imgUrl:q.getAjaxBaseurl()+"/filedata/fetch?filedataid="+g+"&thumb=1",filedataid:g,title:k}}});a.isEmptyObject(d)||u.ajax({call:"/ajax/render/photo_item",data:{items:d,wrapperClass:"tmp-photo",isAjaxTemplateRenderWithData:!0},success:function(g){var h=w(!1),k=a(".photo-display",h);k.append(g.template);g=a(".photo-item-wrapper:not(.h-hide)",k);x(g);y(h,0<g.length);t(h);h.dialog("option","position",{of:window});h.dialog("open")}});a(".photo-selector-galleries",
c).tabs("destroy");c.dialog("close")});a(".js-photo-selector-cancel",b).offon("click",function(){console.log("Fileupload: cancel 2");a(document).data("gallery-container",null);var c=a(this).closest(".js-photo-selector-container");a(".photo-selector-galleries",c).tabs("destroy");c.dialog("close")})}function w(b,e){if(!e||0==e.length)if(e=a(document).data("gallery-container"),!e)return a();if(e.hasClass("profile-media-photoupload-dialog")){var f=e;b&&(f.dialog("open"),t(f));return f}f=e.find(".js-photo-display");
0==f.length?a(".js-photo-display").each(function(){if(a(this).data("associated-editor")==e.get(0))return f=a(this),!1}):(f.dialog({modal:!0,width:606,autoOpen:!1,showCloseButton:!1,closeOnEscape:!1,resizable:!1,showTitleBar:!1,dialogClass:"dialog-container upload-photo-dialog-container dialog-box"}),f.data("orig-width",f.dialog("option","width")),f.data("associated-editor",e.get(0)),f.find(".b-form-input__file--hidden").prop("disabled",!1));b&&(f.dialog("open"),t(f));N(f);return f}function N(b){var e=
b.find(".js-sortable-on-edit"),f=b.css("overflow")||"auto";e.length&&!e.data("sortable")&&e.sortable({forcePlaceholderSize:!1,placeholder:"photo-item-wrapper h-left sortable-placeholder",containment:"parent",tolerance:"pointer",start:function(l,c){a(".photo-item-wrapper:not(.h-hide)",e).removeClass("last-in-row");b.css("overflow","hidden")},update:function(l,c){l=a(".photo-item-wrapper:not(.h-hide)",e);x(l);y(b,0<l.length);t(b);b.css("overflow",f)}})}function t(b){var e=a(".photo-display",b),f=b.parent();
e=a(".photo-item-wrapper:not(.h-hide)",e).length;!f.hasClass("has-scrollbar")&&6<=e&&(e=q.getScrollbarWidth(),f.addClass("has-scrollbar"),b.dialog("option","width",b.dialog("option","width")+e+11))}function x(b){b.removeClass("last-in-row").filter(":not(.h-hide)").filter(e=>2==e%3).addClass("last-in-row")}function y(b,e){a(".js-continue-button, .btnPhotoUploadSave",b).toggle(e);v(b,e?"upload_more":void 0)}function O(){a(document).offon("click.removephoto",".photo-display .photo-item .js-remove-icon",
function(){var b=a(this).closest(".photo-item-wrapper"),e=a(".filedataid",b).data("nodeid"),f=b.parents(".js-photo-display").last();"undefined"!==typeof e&&(e=a.inArray(e,z),-1!=e&&z.splice(e,1));b.addClass("h-hide");b=f.find(".photo-item-wrapper:not(.h-hide)");b.length<=F.ATTACHLIMIT&&a(".js-attach-limit-warning",f).hide();x(b);6>=b.length&&(f.parent().removeClass("has-scrollbar"),f.dialog("option","width",f.data("orig-width")));y(f,0<b.length)});a(document).offon("blur.photocaption",".photo-display .photo-caption .caption-box",
function(){a(this).scrollTop(0)});K.bindEditFormEventHandlers("gallery")}function P(){var b=jQuery.fn.fileupload;jQuery.fn.fileupload=function(){arguments&&arguments[0]&&arguments[0].dropZone&&"vb-self"==arguments[0].dropZone&&(arguments[0].dropZone=a(this));arguments&&arguments[0]&&arguments[0].dropZone&&arguments[0].dropZone.addClass("js-fileupload-dropzone");return b.apply(this,arguments)}}function I(b){b&&b.each((e,f)=>{e=a(f);e.data("vb-dropzone-overlay-initialized")||(a("<div />").html(m.get("drop_files_here_to_upload")).addClass("h-hide-imp js-fileupload-dropzone-overlay fileupload-dropzone-overlay").appendTo(e),
e.css("position","relative").data("vb-dropzone-overlay-initialized","1"))});a(".js-fileupload-dropzone-overlay").toggleClass("h-hide-imp",!b)}function Q(b){var e=a(".js-fileupload-dropzone"),f=e.filter(":visible"),l=e.filter(".b-content-entry-panel__content--attachment");b.preventDefault();if(!(1>e.length)&&(0==f.length&&1==l.length&&(a(".js-content-entry").find(".js-toolbar-secondary .b-toolbar__item").filter(function(){return"b-content-entry-panel__content--attachment"==a(this).data("panel")}).trigger("click"),
f=e.filter(":visible")),0<f.length)){I(f);a(".js-fileupload-dropzone-overlay").removeClass("fileupload-dropzone-overlay--active");let c=b.originalEvent.dataTransfer;c.dropEffect="none";c.effectAllowed="none";a(b.target).parents().each(function(){var d=a(this);if(d.is(".js-fileupload-dropzone"))return d.find(".js-fileupload-dropzone-overlay").addClass("fileupload-dropzone-overlay--active"),c.dropEffect="copy",c.effectAllowed="copy",!1})}}function J(b){b.preventDefault();I(!1)}function R(){A&&(clearTimeout(A),
A=0)}function S(b){var e=this;A=setTimeout(()=>{J.call(e,b)},200)}var z=[],A=0;a(()=>{P();a:{if("FormData"in window&&"FileReader"in window){var b=document.createElement("div");if("draggable"in b||"ondragstart"in b&&"ondrop"in b){b=!0;break a}}b=!1}b&&(b=a(document),b.on("dragover.contentdragstart",Q),b.on("drop{0} dragend{0}".format(".contentdragstart"),J),b.on("dragenter{0} dragover{0}".format(".contentdragenter"),R),b.on("dragleave.contentdragenter",S));D();O()});return{uploadFile:async function(b,
e){"string"==typeof b&&(b=await L(b));return M(b,e)},setUploadButtonText:v,initializePhotoUpload:D,getUploadedPhotosDlg:w,adjustPhotoDialogForScrollbar:t,relocateLastInRowClass:x}})(jQuery,vBulletin,vBulletin.phrase,vBulletin.ajaxtools,vBulletin.conversation,vBulletin.contentEntryBox,vBulletin.dialogtools);
