/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
(function(a){function D(){vBulletin.AJAX({call:"/ajax/activate-sitebuilder",data:{pageid:pageData.pageid,nodeid:pageData.nodeid,userid:pageData.userid,loadMenu:!1,isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0},cache:!1,success:b=>{b.templates&&(a("#sitebuilder-wrapper").prepend(b.templates.main),a(".js-top-menu-sitebuilder").show(),a(".edit-switch-container .switch-control").addClass("on"),A.setCookie("sitebuilder_active","1"))}})}function E(b,c){var e=0,g=b.length;b.each(function(){if(this.complete&&
0<this.naturalHeight&&this.src)++e;else a(this).one("load",function(){++e;e==g&&c()})});e==g&&c()}function F(b,c,e,g,p){function m(n){n=n.position().top+n.outerHeight();n=Math.round(n);return[n-1,n,n+1]}function k(n,r){var f,l;for(f in n)for(l in r)if(n[f]===r[l])return!0;return!1}a(b).each(function(){var n=a(this);n.trigger("vbulletin:flexgridstart",{isResize:p});var r=a(c,n),f=r.last(),l=!1,t={},h=0,d=!1,q=!1,u=r.first();r.length&&(r.removeClass(e+" vb-temp-placeholder-grid-lastrow"),r.removeClass(g),
setTimeout(function(){l=m(f);r.each(function(){var w=a(this),x=m(w);k(l,x)?w.addClass("vb-temp-placeholder-grid-lastrow"):(d||(d=x),k(d,x)||(++h,u.addClass(g)),d=x,u=w,"undefined"==typeof t[h]&&(t[h]=0),++t[h])});u!=r.first()&&u.addClass(g);a.each(t,function(w,x){!1===q&&(q=x);x<q&&(q=x)});var v=r.filter(".vb-temp-placeholder-grid-lastrow");v.removeClass("vb-temp-placeholder-grid-lastrow");(!1===q||v.length<q)&&v.addClass(e);!1!==q&&v.length==q&&v.last().addClass(g);n.trigger("vbulletin:flexgridready",
{isResize:p})},0))})}function N(b,c,e,g,p,m,k){a(b).each(function(){var n=a(this),r=a(e,n);m?F(n,c,g,p,k):E(r,function(){F(n,c,g,p,k)})})}function P(b,c){function e(f,l,t){var h={},d=[];var q=f.data.length-32;var u=f.data;for(f=0;f<q;f+=32){var v=Math.round(u[f]/l);var w=Math.round(u[f+1]/l);var x=Math.round(u[f+2]/l);var z=Math.round(u[f+3]/l);v=v+100*w+1E4*x+1E6*z;h[v]?++h[v]:h[v]=1}for(f in h)d.push([f,h[f]]);d.sort(function(C,I){return C[1]>I[1]?-1:I[1]>C[1]?1:0});d.length>t&&(d=d.slice(0,t));
return d}function g(f){var l=Math.floor(f/1E6);var t=Math.floor(f/1E4)-100*l;var h=Math.floor(f/100)-1E4*l-100*t;return[f-1E6*l-1E4*t-100*h,h,t,l]}function p(f,l){f=g(f[0]);var t=g(l[0]);l=Math.min(f[0],f[1],f[2]);var h=Math.max(f[0],f[1],f[2]);f=Math.min(t[0],t[1],t[2]);t=Math.max(t[0],t[1],t[2]);l=h-l;f=t-f;return l>f?-1:f>l?1:0}function m(f,l){var t=0,h=0;f=g(f[0]);l=g(l[0]);f[0]!=f[1]&&++t;f[0]!=f[2]&&++t;f[1]!=f[2]&&++t;l[0]!=l[1]&&++h;l[0]!=l[2]&&++h;l[1]!=l[2]&&++h;return t>h?-1:h>t?1:0}function k(f,
l){f=a(c,l);var t=l.innerWidth();l=l.innerHeight();var h=f.outerWidth(),d=f.outerHeight();if(h>=t&&d>=l)switch(f.css("object-fit")){case "contain":return r(f);case "scale-down":return[t,l,h,d]=n(f),f=t<h&&l<d?!0:r(f),f;case "none":return[f,,t,l]=n(f),f<t||f<l;default:return!1}return!0}function n(f){return[f.prop("naturalWidth"),f.prop("naturalHeight"),f.prop("width"),f.prop("height")]}function r(f){var l;let t;[l,h,f,t]=n(f);l/=h;var h=t;let d=l*h;d>f&&(d=f,h=f/l);return f>d||t>h}a(b).each(function(f){var l=
a(this),t=a(c,l);t.length&&setTimeout(function(){E(t,function(){var h=a(c,l),d=h.data("bgStrat")||"primary-color";if(h.length&&k(h,l))switch(d){case "cover-blur":l.css("background-image","url('"+h.attr("src")+"')");l.css("background-size","cover");h.css("backdrop-filter","blur(10px)");break;default:var q=h.outerWidth(),u=h.outerHeight();h=h.get(0);d=document.createElement("canvas");var v=d.getContext&&d.getContext("2d");q=h.naturalWidth||q;u=h.naturalHeight||u;var w=!1;d.width=q;d.height=u;v.drawImage(h,
0,0);try{w=v.getImageData(0,0,q,u)}catch(x){}w&&w.data&&w.data.length&&(h=e(w,20,100),h.sort(p),h.sort(m),h=h.shift(),h=g(h[0]),h[0]*=20,h[1]*=20,h[2]*=20,h[3]*=20,245<=h[3]&&(h[3]=255),l.css("backgroundColor","rgba("+h.join(",")+")"))}})},0)})}function Q(){function b(){var c=a(this);if(""==c.prop("title")){var e=c.get(0);e.scrollWidth>e.clientWidth&&(e=c.text().trim(),300<e.length&&(e=e.substr(0,297)+"..."),c.prop("title",e))}c.addClass("js-ellipsis-has-title")}a(document).off("mouseover",".ellipsis:not(.js-ellipsis-has-title)",
b).on("mouseover",".ellipsis:not(.js-ellipsis-has-title)",b)}pageData=window.pageData||{};pageData=Object.assign(pageData,vBulletin.data());pageData.tzOffset=parseInt(pageData.tzOffset);pageData.dstauto=parseInt(pageData.dstauto);vBulletin.version=pageData.templateversion;a.fn.offon=function(b,c,e,g){null==g&&(g=e,null==e?(g=c,c=void 0):"string"!==typeof c&&(e=c,c=void 0));return this.off(b,c).on(b,c,e,g)};String.prototype.format=function(){for(var b=this,c=arguments.length;c--;)b=b.replace(new RegExp("\\{"+
c+"\\}","gm"),arguments[c]);return b};jQuery.fn.reverse=[].reverse;a(".js-module__hide-if-empty:not(:has(*))").each(function(){let b=a(this);/\s/.test(b.html())&&b.closest(".js-module").hide()});jQuery.ajaxPrefilter(function(b){b.crossDomain&&(b.contents.script=!1)});a.ajaxPrefilter("script",function(b){b.cache=!0});vBulletin.normalizeAjaxUrl=function(b){return 0==b.indexOf("http://")?b.substring(5):0==b.indexOf("https://")?b.substring(6):b};vBulletin.getAjaxBaseurl=function(){return vBulletin.normalizeAjaxUrl(pageData.baseurl)};
vBulletin.getAbsoluteUrl=function(){var b;return function(c){b||(b=document.createElement("a"));b.href=c;return b.href}}();vBulletin.regexEscape=function(b){return b.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")};let O=vBulletin.normalizeAjaxUrl(pageData.baseurl);vBulletin.isInternalUrl=function(){let b=new RegExp("^"+vBulletin.regexEscape(O));return function(c){c=vBulletin.normalizeAjaxUrl(vBulletin.getAbsoluteUrl(c));return b.test(c)}}();vBulletin.isInternalJSUrl=function(){let b=new RegExp("^"+vBulletin.regexEscape(O+
"/js/")+".*.js");return function(c){c=vBulletin.normalizeAjaxUrl(vBulletin.getAbsoluteUrl(c));return b.test(c)}}();vBulletin.isAbsoluteUrl=function(){var b=RegExp("^(?:[a-z]+:)?//","i");return function(c){return b.test(c)}}();vBulletin.isEmptyList=function(b){return a.isArray(b)&&0==b.length||a.isPlainObject(b)&&a.isEmptyObject(b)};vBulletin.getFormData=(b,c)=>{let e={};for(const g of b.serializeArray()){let {name:p,value:m}=g,k=e[p];"undefined"==typeof k?e[p]=m:(Array.isArray(k)||(e[p]=[k]),e[p].push(m))}"undefined"!=
typeof c&&a("input:checkbox:not(:disabled)",b).each((g,p)=>{e[p.name]||(e[p.name]=c)});return e};a.ajaxPrefilter(function(b,c,e){if(!b.url||vBulletin.isInternalUrl(b.url)&&!vBulletin.isInternalJSUrl(b.url))if("undefined"==typeof b.data)b.data="securitytoken="+pageData.securitytoken,"undefined"!==typeof b.formData&&Array.isArray(b.formData)&&b.formData.push({name:"securitytoken",value:pageData.securitytoken});else if("undefined"!==typeof FormData&&b.data instanceof FormData)b.data.append("securitytoken",
pageData.securitytoken);else{var g=!0;c=b.data.split("&");a.each(c,function(p,m){if(m.match(/^securitytoken=/))return g=!1});g&&(b.data+="&securitytoken="+pageData.securitytoken)}});a.ajaxPrefilter(function(b,c,e){(function(){var g=vBulletin.getAjaxBaseurl();if(0==c.url.indexOf(g)&&0==c.url.substr(g.length).indexOf("/ajax/render/")||c&&c.data&&c.data.isAjaxTemplateRender){var p=b.success;b.success=function(){console.log("Intercept AJAX template render calls: Start (URL: {0})".format(b.url));var m=
arguments[0];if(!m||"object"!=typeof m||a.isEmptyObject(m))return"function"==typeof p?p.apply(this,arguments):!1;c.data&&c.data.isAjaxTemplateRenderWithData?arguments[0]=m:(arguments[0]=m.template,arguments[1]=m.errors);var k=m.css_links;if(k&&0!=k.length){console.log("Intercept AJAX template render calls: Has CSS");var n=/sheet=([^&]+)&/;m=k.pop();var r=null!=m.match(n);k.push(m);var f=function(v){var w=v.match(n),x={};w&&w[1]?a.each(w[1].split(","),function(z,C){x[C]=v}):x[v.replace(/^.*\//g,"")]=
v;return x},l={};a("head link[rel=stylesheet]").each(function(){a.extend(l,f(a(this).attr("href")))});var t={};a.each(k,function(v,w){a.extend(t,f(w))});var h=[];a.each(t,function(v,w){v&&"undefined"==typeof l[v]&&(r?h.push(v):h.push(w))});if(0==h.length){if(console.log("Intercept AJAX template render calls: Needed CSS is already on the page"),"function"==typeof p)return console.log("Intercept AJAX template render calls: Calling original success handler"),p.apply(this,arguments)}else{k=[];r?(console.log("Intercept AJAX template render calls: found DB CSS"),
k.push(m.replace(/sheet=[^&]+&/,"sheet="+h.join(",")+"&"))):(console.log("Intercept AJAX template render calls: found FS CSS"),k=h);var d=this,q=arguments;console.log("Intercept AJAX template render calls: Fetching CSS: {0}".format(k.join(", ")));var u=function(v){if(0==v.length)console.log("Intercept AJAX template render calls: Done. Calling original callback."),setTimeout(function(){if("function"==typeof p)return p.apply(d,q)},50);else{var w=a("<div />").append(v.shift()).text();console.log("Intercept AJAX template render calls: Fetching CSS file: {0}".format(w));
a.get(w,{cache:!0},function(x){x=a("<link />",{rel:"stylesheet",type:"text/css",href:w});var z=a(".js-additional-css");1==z.length?z.before(x):a("head").append(x)}).then(function(){console.log("Intercept AJAX template render calls: Fetched CSS file: {0}".format(w));if(0<a(".js-debug-css-template-list").length){var x=f(w),z=a("<ol />");a.each(x,function(C,I){r?z.append(a("<li />").append(C)):z.append(a("<li />").append(I))});x=a(".js-debug-css-template-list").append(a("<li />").append(vBulletin.phrase.get("added_via_ajax_call")+
":").append(z)).prev("b");x.text(parseInt(x.text(),10)+1)}u(v)},function(){console.warn("Intercept AJAX template render calls: Failed to fetch CSS file: {0}".format(w));u(v)})}};u(k)}}else if(console.log("Intercept AJAX template render calls: No CSS"),"function"==typeof p)return console.log("Intercept AJAX template render calls: Calling original success handler"),p.apply(this,arguments)}}})()});vBulletin.isRtl=()=>"rtl"==a("html").attr("dir");let A=vBulletin.createStorageTools(pageData.cookie_prefix,
Cookies.withAttributes({path:pageData.cookie_path,domain:pageData.cookie_domain,secure:"https"==pageData.baseurl.substr(0,5).toLowerCase()||"https:"==location.protocol}));vBulletin.storagetools=A;jQuery.fn.swipeable=function(b){function c(l){var t={x:0,y:0};try{t={x:l.pageX||l.originalEvent.touches[0].pageX||0,y:l.pageY||l.originalEvent.touches[0].pageY||0}}catch(h){}return t}function e(l,t){return{x:l.x-t.x,y:l.y-t.y}}function g(l){n=!0;r=!1;f.start=c(l);f.previous=c(l);f.current=c(l);f.moved={x:0,
y:0};f.totalMoved={x:0,y:0};f.target=l.target;"touchstart"!=l.type&&l.preventDefault()}function p(l){if(n){f.current=c(l);f.moved=e(f.current,f.previous);f.totalMoved=e(f.current,f.start);if(f.moved.x||f.moved.y)r=!0;b.swiping.call(this,l,f);f.previous=f.current}}function m(l){n&&("mouseup"==l.type&&l.target!=f.target?k.call(this,l):"mouseleave"==l.type&&k.call(this,l));n=!1;l.preventDefault()}function k(l){if(f.totalMoved){var t=Math.abs(f.totalMoved.x);var h=Math.abs(f.totalMoved.y),d=Math.max(t,
h);t=40>d||d<=2*Math.min(t,h)?!1:t>h?0>f.totalMoved.x?"left":"right":0>f.totalMoved.y?"up":"down"}else t=!1;t&&b["swipe"+t].call(this,l,f);b.swipeend.call(this,l,f);n=!1;f={start:null,previous:null,current:null,moved:null,totalMoved:null,target:null};if(r)return r=!1}b=b||{};"object"==typeof b&&(b.swiping=b.swiping||function(){},b.swipeend=b.swipeend||function(){},b.swipeleft=b.swipeleft||function(){},b.swiperight=b.swiperight||function(){},b.swipeup=b.swipeup||function(){},b.swipedown=b.swipedown||
function(){});var n=!1,r=!1,f={start:null,previous:null,current:null,moved:null,totalMoved:null,target:null};return this.each(function(){var l=a(this);if("disable"==b)l.off(".vbswipeable","body");else l.on("mousedown.vbswipeable touchstart.vbswipeable","body",g).on("mousemove.vbswipeable touchmove.vbswipeable","body",p).on("mouseup.vbswipeable mouseleave.vbswipeable touchcancel.vbswipeable","body",m).on("click.vbswipeable touchend.vbswipeable","body",k)})};(function(){var b=jQuery.fn.selectBox;jQuery.fn.selectBox=
function(){var c=a(this);"undefined"==typeof c.attr("tabindex")&&c.attr("tabindex","0");c=b.apply(this,arguments);a(".selectBox-arrow").addClass("b-icon-fa b-icon-fa--12 fa-solid fa-caret-down");return c}})();(function(){(function(){var b=a(".js-login-menu");b.find(".js-comp-menu-dropdown__trigger").on("click",function(){setTimeout(function(){b.find(".js-login-username").trigger("focus")},0)});(function(){function c(m,k){a(m).toggleClass("h-hide-imp",!k)}var e=a(".js-top-menu-user--list"),g=[".js-header__notifications-label",
".js-pmchat__messages-label",".js-menu__username-label"],p=g.slice(0).reverse();e.on("vbulletin:shrink",function(){a.each(g,function(m,k){c(k,!1);if("need_shrink"!=vBulletin.Responsive.Debounce.checkElementShrinkRequirement(e))return!1})}).on("vbulletin:unshrink",function(){a.each(p,function(m,k){c(k,!0);if("need_shrink"==vBulletin.Responsive.Debounce.checkElementShrinkRequirement(e))return c(k,!1),!1})})})();(function(){var c=a(".js-top-menu-sitebuilder--list"),e=c.find(".b-top-menu__item"),g=e.find(".js-top-menu-link"),
p=c.closest(".js-top-menu-sitebuilder"),m=[function(k){g.toggleClass("b-top-menu__item-link--compact",k)},function(k){p.toggleClass("b-top-menu__background--compact",k)},function(k){vBulletin.CompMenuHorizontal.convertDropdownProgressive({$parent:c,$children:e,removeMenu:!k})}];c.on("vbulletin:shrink",function(){a.each(m,function(k,n){n(!0);if("need_shrink"!=vBulletin.Responsive.Debounce.checkElementShrinkRequirement(c))return!1})}).on("vbulletin:unshrink",function(){for(var k=m.length;0<=--k;)if(m[k](!1),
"need_shrink"==vBulletin.Responsive.Debounce.checkElementShrinkRequirement(c)){m[k](!0);break}})})()})();a(".ui-tabs .ui-tabs-nav > li").addClass("ui-state-disabled")})();vBulletin.pageHasSelectors=function(b){if(a.isArray(b)&&0<b.length&&""!=a.trim(b.toString())){var c=!1;a.each(b,function(e,g){if(0<a(g).length)return c=!0,!1});return c}return!0};vBulletin.areJsonObjectsEqual=function(b,c){var e=function(g,p){for(var m in g)if(g.hasOwnProperty(m)&&p.hasOwnProperty(m)){var k=g[m],n=p[m];if(k!=n)if(k instanceof
Array&&n instanceof Array){if(0<a(k).not(n).length||0<a(n).not(k).length)return!1}else return!1}else return!1;return!0};return Object.keys(b).length==Object.keys(c).length?e(b,c):!1};vBulletin.loadingIndicator=function(){function b(k){if(k){k=a(".js-loading-indicator");var n=k.outerWidth(),r=vBulletin.isRtl()?"margin-right":"margin-left";0<n&&k.css(r,-(n/2));k.removeClass("h-hide");a("body").css("cursor","wait")}else a(".js-loading-indicator").addClass("h-hide"),a("body").css("cursor","auto")}var c=
0,e=!1,g=!1,p=0,m=0;return{init:function(){e||(a(document).ajaxStart(function(){vBulletin.loadingIndicator.show("ajaxStart")}),a(document).ajaxStop(function(){vBulletin.loadingIndicator.hide("ajaxStop")}),e=!0)},show:function(k){0<p&&"ajaxStart"==k?(--p,++m,console.log("vBulletin.loadingIndicator.show ajax indicator suppressed")):(++c,console.log("vBulletin.loadingIndicator.show Counter: "+c+" Source: "+(k||"Unspecified")),0<c&&(g=setTimeout(function(){g&&(b(!0),g=!1)},1E3)))},hide:function(k){0<
m&&"ajaxStop"==k?(--m,console.log("vBulletin.loadingIndicator.hide ajax indicator suppressed")):(--c,c=0>c?0:c,k||(c=0),console.log("vBulletin.loadingIndicator.hide Counter: "+c+" Source: "+(k||"Unspecified")),1>c&&(g&&(clearTimeout(g),g=!1),b(!1)))},suppressNextAjaxIndicator:function(){++p}}}();vBulletin.precache("admin admin_auth april attach_link attach_video august cancel_edit close conversation december done email_addresses_must_match error error_loading_ckeditor_script error_loading_editor error_posting_comment_code error_x existing_reply_will_be_deleted february follow follow_error following following_pending following_remove friday_min go_to_first_new_post hour inlinemod_auth_password_empty invalid_data invalid_data_requested invalid_email_address invalid_request invalid_server_response_please_try_again invalid_special_channel_subscribe_request invalid_username_specified invalid_username_specified_maxlength_x invalid_username_specified_minlength_x invalid_query_definition_x january join joined join_error july june leave loading logged_out_while_editing_post login login_success_admin_auth march may minute moderator monday_min new_posts no no_create_permissions no_icon no_leave_channel_permission no_permission no_update_permissions no_valid_tags_found not_logged_no_permission november now october physically_remove_blog physically_remove_comment physically_remove_media physically_remove_reply physically_remove_topic physically_remove_visitorMessage please_enter_a_valid_url_and_click_attach please_enter_link_url please_enter_video_url please_enter_your_comment please_enter_your_email_address please_provide_search_string post_comment post_history posttype_blog posttype_comment posttype_media posttype_reply posttype_topic posttype_visitorMessage preview refer_a_friend saturday_min search see_less see_more select_option_and_click_delete_button_blog select_option_and_click_delete_button_comment select_option_and_click_delete_button_media select_option_and_click_delete_button_reply select_option_and_click_delete_button_topic select_option_and_click_delete_button_visitorMessage send_report september soft_delete_blog soft_delete_comment soft_delete_media soft_delete_notes_blog soft_delete_notes_comment soft_delete_notes_media soft_delete_notes_reply soft_delete_notes_topic soft_delete_notes_visitorMessage soft_delete_reply soft_delete_topic soft_delete_visitorMessage sunday_min thanks_for_signing_up_log_in time tuesday_min thursday_min unable_to_check_admin_permissions unable_to_contact_server_please_try_again unexpected_error unfollow_error usernametaken wednesday_min".split(" "),
["bbtitle","markinglimit","threadpreview"]);let y=vBulletin;var G=y.getAjaxBaseurl(),B=y.createSiteDataTools(G);B.phrase.init(pageData,pageData.languageid,A.createStorageTimed("phrase",pageData.phrasedate,pageData.current_server_datetime),y.phrase.precache);a.extend(y.phrase,B.phrase);B.options.init(A.createStorageTimed("options",pageData.optionsdate,pageData.current_server_datetime),y.options.precache);a.extend(y.options,B.options);B=y.createDialogTools(a,y,y.phrase);y.dialogtools=B;y.error=B.error;
y.warning=B.warning;y.alert=B.alert;y.openConfirmDialog=B.openConfirmDialog;y.openPromptDialog=B.openPromptDialog;window.openAlertDialog=B.openAlertDialog;window.openConfirmDialog=B.openConfirmDialog;window.openPromptDialog=B.openPromptDialog;let H=y.createAjaxTools(G,pageData.userid,y.phrase,y.dialogtools);y.ajaxtools=H;y.ajaxlib=H.library;y.AJAX=H.ajax;y.ajaxForm=H.ajaxForm;vBulletin.getScrollbarWidth=function(){if(a("body").data("scrollbar-width"))return a("body").data("scrollbar-width");var b=
a('<div style="width:50px;height:50px;overflow:auto;position:absolute;top:-99999px;"><div /></div>').appendTo("body"),c=b.children();c=c.innerWidth()-c.height(99).innerWidth();b.remove();a("body").data("scrollbar-width",c);return c};vBulletin.assertUserHasAdminPermission=function(b,c,e,g){if(a(c).data("in-progress"))return!1;a("body").css("cursor","wait");a(c).data("in-progress",!0);vBulletin.AJAX({call:"/ajax/api/user/currentUserHasAdminPermission",data:{adminPermission:b},complete:function(){a("body").css("cursor",
"auto");a(c).data("in-progress",null)},success:function(p){!0===p?e():(vBulletin.error("error","unable_to_check_admin_permissions"),a("#config-dialog .loader").hide())},api_error:"undefined"==typeof g?void 0:function(p){return vBulletin.ajaxtools.hasError(p,"inlinemodauth_required")?(vBulletin.ajaxlib.inlineMod(g),!1):!0},error_phrase:"unable_to_check_admin_permissions"})};vBulletin.selectTabByIndex=function(b){var c=this instanceof a?this:a(this);c.length&&-1<b&&c.hasClass("ui-tabs")&&c.data("noPushState",
!0).tabs("option","active",b).data("noPushState",null).find(".ui-tabs-nav li").removeClass("ui-state-focus").eq(b).addClass("ui-state-focus").find("a").trigger("focus")};a.ui.tabs.prototype._isLocal=function(){return!0};(function(){var b=a.ui.tabs.prototype._processTabs;a.ui.tabs.prototype._processTabs=function(){var c=b.apply(this,arguments);this.panels.removeClass("h-hide");return c}})();vBulletin.getSelectedTabHashOrPath=function(b,c){return(c?b.find(".ui-tabs-nav > .ui-tabs-active > a").prop("hash"):
b.find(".ui-tabs-nav > .ui-tabs-active > a").data("url-path"))||""};vBulletin.parseUrl=function(b){var c=document.createElement("a");c.href=b||"/";b=c.pathname;0!=b.indexOf("/")&&(b="/"+b);return{protocol:c.protocol,hostname:c.hostname,port:c.port,pathname:b,search:c.search,hash:c.hash}};vBulletin.makeTabUrl=function(b,c,e,g,p){b?(b=vBulletin.parseUrl(b),e?(p=p||"tab",e=new RegExp("([?+|&+])"+p+"=\\w+[-\\w]*","i"),b=b.search.match(e)?b.pathname+b.search.replace(e,"$1{0}={1}".format(p,c)):b.search?
"{0}{1}&{2}={3}".format(b.pathname,b.search,p,c):"{0}?{1}={2}".format(b.pathname,p,c)):(p=b.pathname.replace(/\/$/,""),e=p.split("/"),e="\\/"+e[e.length-(p.match(/\/page([0-9]+)/)?2:1)]+"$",b=b.pathname.replace(new RegExp(e),"/"+c)+b.search)):b="/";g&&(b+="#"+g);return b};vBulletin.makePaginatedUrl=function(b,c){if(b){var e=b.match(/\/page[0-9]+/);e?b=1<c?b.replace(e[0],"/page"+c):b.replace(e[0],""):1<c&&(b=b.match(/\?/)?b.replace(/\?/,"/page"+c+"?"):b.match(/#/)?b.replace(/#.*/,"/page"+c):b+("/page"+
c))}return b};vBulletin.makeFilterUrl=function(b,c,e,g,p,m){m=m||!1;b=b||location.href;var k=a(".filtered-by",g);b=vBulletin.parseUrl(b);var n=b.search,r=a(".js-button-filter.js-default-checked.js-checked",g);r.data("filter-name")==c&&r.data("filter-value")==e&&(m=!0);!m&&(k.data("clicked")&&a('.toolbar-filter-overlay input[name="{0}"][value="{1}"]'.format(c,e),g).hasClass("js-default-checked")||a('.toolbar-search-form input[name="{0}"]'.format(c),g).length&&!e)&&(m=!0,k.data("clicked",null));b=b.pathname;
if(n&&1<n.length)if(n.match(new RegExp(c+"=","i"))){if(g=vBulletin.parseQueryString(n),!a.isEmptyObject(g)){var f="";a.each(g,function(l,t){m&&l==c||(f+="{0}={1}&".format(l,l==c?e:t))});f&&(b+="?"+f.substring(0,f.length-1))}}else b=m?b+n:b+(n+"&{0}={1}".format(c,encodeURIComponent(e)));else m||(b+="?{0}={1}".format(c,encodeURIComponent(e)));p&&(b+="#"+p);return b};vBulletin.getSelectedFilters=function(b,c){var e={};if(c){var g=b.parent().find(".filtered-by .filter-text").filter(":visible");b.find(":input:radio:checked").each(function(p,
m){p=a(m);if((p.hasClass("js-default-checked")||1==p.data("bypass-filter-display"))&&(0==g.length||0==g.filter('[data-filter-name={0}][data-filter-value="{1}"]').length))return!0;"[]"==m.name.slice(-2)?(p=m.name.split("[]"),e[p[0]]=e[p[0]]||[],e[p[0]].push(m.value)):e[m.name]=m.value})}else b=b.serializeArray(),a.each(b,function(p,m){"securitytoken"!=m.name&&("[]"==m.name.slice(-2)?(p=m.name.split("[]"),e[p[0]]=e[p[0]]||[],e[p[0]].push(m.value)):e[m.name]=m.value)});return e};vBulletin.parseQueryString=
function(b,c){var e={};if(b&&1<b.length){var g=b.indexOf("?");c=c instanceof Array?c:[];-1!=g&&(b=b.substring(g+1).split("&"),a.each(b,function(p,m){p=m.split("=");if(0==c.length||-1==a.inArray(p[0],c))e[p[0]]=decodeURIComponent(p[1]||"").replace(/\+/g," ")}))}return e};vBulletin.togglePageScrolling=function(b){function c(){e.scrollTop(g).scrollLeft(p)}var e=a(window),g=e.scrollTop(),p=e.scrollLeft();e.off("scroll.vbtogglepagescrolling");if(!b)e.on("scroll.vbtogglepagescrolling",c)};vBulletin.pagination=
function(b){function c(){return parseInt((a(".pagetotal",this).html()||"").replace(/[^\d]+/g,""),10)||1}function e(h,d){var q=c.apply(this),u=a(".arrow[rel=next]",this),v=a(".arrow[rel=prev]",this);1>h?h=1:h>q&&(h=q);a(".js-pagenum",this).val(h);h==q?u.addClass("h-disabled").removeAttr("href"):u.removeClass("h-disabled").attr("href",vBulletin.makePaginatedUrl(location.href,h+1));1==h?v.addClass("h-disabled").removeAttr("href"):v.removeClass("h-disabled").attr("href",vBulletin.makePaginatedUrl(location.href,
h-1));"function"==typeof m.onPageChanged&&m.onPageChanged.apply(this,[h,d]);1<q&&r.isEnabled()&&!d&&(d=r.getState(),!d||!d.data||!d.data.from||a.inArray(d.data.from,-1==["filter_blogs","filter_groups"]))&&(t=1==h?a(".arrow[rel=next]",this).attr("href"):a(".arrow[rel=prev]",this).attr("href"))&&(t=vBulletin.makePaginatedUrl(t,h),h={from:"pagination",page:h,tab:m.tabParamAsQueryString?"#"+a(this).closest(".ui-tabs-panel").attr("id"):vBulletin.getSelectedTabHashOrPath(a(this).closest(".ui-tabs"),!1)},
r.pushState(h,document.title,t))}function g(h){a("a.see-all-btn",this).closest(".pagenav-controls")[h?"addClass":"removeClass"]("h-hide")}function p(){a(m.context).off("click",".js-pagenav .js-pagenav-button").on("click",".js-pagenav .js-pagenav-button",function(h){if(r.isEnabled()){h=a(this).data("page");var d=a(".pagenav-form",m.context).get(0);e.apply(d,[h,!1]);return!1}return!0}).off("mouseover",".js-pagenav .js-pagenav-button").on("mouseover",".js-pagenav .js-pagenav-button",function(h){h=a(this);
h.prop("href")||h.prop("href",vBulletin.makePaginatedUrl(location.href,parseInt(h.data("page"),10)))});a(".js-pagenav .js-pagenav-button",m.context).each(function(){this.href=vBulletin.makePaginatedUrl(location.href,parseInt(a(this).data("page")))});(function(){a(document).on("vbulletin:shrink vbulletin:unshrink",".js-pagenav",function(){var h=a(this),d=h.data("vbshrink-hidden-elements");"undefined"!=typeof d&&d.removeClass("h-hide-imp");d=h.find("> .js-pagenav-button").filter(":visible");var q=a(),
u=a(),v=d.filter(".js-pagenav-current-button").data("page");d.each(function(w,x){w=a(x);var z=w.data("page");x=w.is(".js-pagenav-prev-button, .js-pagenav-current-button, .js-pagenav-next-button");var C=w.is(".js-pagenav-first-button, .js-pagenav-last-button");z=z==v-1||z==v+1;C=C?"1":z?"2":"3";x||(q=q.add(w),w.data("vbshrink-priority",C))});a.each(["3","2","1"],function(w,x){q.each(function(z,C){z=a(C);if(z.data("vbshrink-priority")!=x)return!0;if("need_shrink"==vBulletin.Responsive.Debounce.checkElementShrinkRequirement(h))z.addClass("h-hide-imp"),
u=u.add(z);else return!1})});h.data("vbshrink-hidden-elements",u)});vBulletin.Responsive.Debounce.checkShrinkEvent(a(".js-pagenav"))})()}var m={context:document,onPageChanged:null,tabParamAsQueryString:!0,allowHistory:!1};b&&"object"==typeof b&&a.extend(m,b);var k=a(".pagenav-controls .pagenav-form",m.context),n=Number(a(".defaultpage",k).val())||Number(a(".js-pagenum",k).val())||1,r=new vBulletin.history.instance(m.allowHistory);k.data("object-instance",this);if(r.isEnabled()){b=vBulletin.parseQueryString(location.search,
["_"]);var f=location.pathname.match(/\/page([0-9]+)/),l=r.getState();if(f&&1<Number(f[1])&&a.isEmptyObject(b)&&(!l||a.isEmptyObject(l.data))){var t=vBulletin.makePaginatedUrl(location.href,n);b={from:"pagination",page:n,tab:m.tabParamAsQueryString?"#"+k.closest(".ui-tabs-panel").attr("id"):vBulletin.getSelectedTabHashOrPath(k.closest(".ui-tabs"),!1)};r.setDefaultState(b,document.title,t)}r.setStateChange(function(h){h=r.getState();if("pagination"==h.data.from){r.log(h.data,h.title,h.url);if(location.search){var d=
vBulletin.parseQueryString(location.search,["_"]);if(!a.isEmptyObject(d)||"groups-tab"==d.tab){delete d.tab;a(window).trigger("statechange.filter",["pagination",d]);return}}var q,u;h.data.tab&&(q=m.tabParamAsQueryString?a(h.data.tab):a('.ui-tabs .ui-tabs-panel[data-url-path="'+h.data.tab+'"]'));d=q&&q.length&&q||m.context;(u=a(".conversation-toolbar .filter-wrapper",d).data("object-instance"))&&u.resetFilters(!0);if(h.data.tab&&(q=q.closest(".ui-tabs"),$tabAnchor=m.tabParamAsQueryString?q.find('.ui-tabs-nav > li > a[href*="{0}"]'.format(h.data.tab)):
q.find('.ui-tabs-nav > li > a[data-url-path="'+h.data.tab+'"]'),!$tabAnchor.parent().hasClass("ui-tabs-active"))){h=$tabAnchor.parent().index();vBulletin.selectTabByIndex.call(q,h);return}q=a(".pagenav-controls .pagenav-form",d);(d=q.data("object-instance"))&&"function"==typeof d.getOption&&"function"==typeof d.getOption("onPageChanged")&&(h=h.data.page||n,d.getOption("onPageChanged").apply(q.get(0),[h,!1,!location.search,location.search]))}},"pagination")}a(".arrow",k).off("click").on("click",function(h){var d=
a(this);h=this.form||d.closest("form").get(0);if(!d.hasClass("h-disabled")){d=parseInt(a(".js-pagenum",h).val())+("next"==d.attr("rel")?1:-1);if(!r.isEnabled()&&m.allowHistory)return this.href&&this.hash!=this.href||(this.href=vBulletin.makePaginatedUrl(location.href,d)),!0;e.apply(h,[d,!1])}return!1});p();a(".js-pagenum",k).off("keypress").on("keypress",function(h){if(13==h.keyCode){h.preventDefault();h=a(this).val();h=isNaN(h)?1:parseInt(h,10);var d=c.apply(this.form);h>d&&(h=d);1>h&&(h=1);r.isEnabled()?
e.apply(this.form,[h,!1]):m.allowHistory?location.href=vBulletin.makePaginatedUrl(location.href,h):e.apply(this.form,[h,!1])}});a(".js-pagenum",k).off("click").on("click",function(h){a(this).select()});this.updatePageInfo=function(h,d){if(h&&"object"==typeof h){var q=h.totalpages||1,u=a(".pagenav-controls .pagenav-form",m.context);a(".pagetotal",u).text(q);"undefined"!=typeof h.showseemore&&g.apply(u,[!h.showseemore]);h.perpage=vBulletin.conversation.POSTS_PER_PAGE;d&&0<a(".pagenav-container",m.context).length&&
y.AJAX({call:"/ajax/render/pagenav",data:{pagenav:h,isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0},success:v=>{a(".pagenav-container",m.context).replaceWith(v.template);p()}});u.length&&e.apply(u.get(0),[h.pagenumber,d])}};this.updateResultId=function(h){(h=parseInt(h))&&"number"===typeof h&&a("input[name=result-id]",k).val(h)};this.setOption=function(h,d){m[h]=d};this.getOption=function(h){return m[h]};this.updatePageNavigation=function(h,d,q){e.apply(h.get(0),[d,q])}};vBulletin.conversation=
vBulletin.conversation||{};vBulletin.conversation.postComment=function(b,c){var e=this;b=a(e);var g=b.closest(".js-comment-entry"),p=g.find(".js-comment-entry__textbox"),m=a.trim(p.val());if(!m)return vBulletin.warning("post_comment","please_enter_your_comment",function(){p.trigger("focus")}),!1;a("body").css("cursor","wait");b.blur();var k=b.closest(".js-comment-entry__parent"),n=1==b.closest(".js-comment-entry--blog").length?1:0,r=1==b.closest(".js-comment-entry--article").length?1:0,f={text:m,
parentid:k.attr("data-node-id"),postindex:k.find(".js-post__content .js-show-post-link").text().replace("#",""),view:k.parent().hasClass("stream-view")?"stream":"thread",redirecturl:p.hasClass(".reload-on-post")?1:0,isblogcomment:n,isarticlecomment:r};g.find('[name^="humanverify"]').each((l,t)=>{l=a(t);f[l.attr("name")]=l.val()});vBulletin.AJAX({call:"/ajax/post-comment",data:f,complete:function(){console.log("post-comment complete.");a("body").css("cursor","auto");vBulletin.hv.reset()},success:function(l,
t,h){"function"==typeof c&&c.apply(e,[l]);n||r||g.slideToggle();vBulletin.subscribe.updateSubscribeButton(l.topic_subscribed);l=k.attr("data-node-id");vBulletin.markRead(l)},api_error:vBulletin.hv.resetOnError,title_phrase:"conversation",error_phrase:"error_posting_comment_code"})};vBulletin.conversation.bindEditFormEventHandlers=function(b){b=b?b.toLowerCase():"";if(-1!=a.inArray(b,"text gallery video poll link comment event".split(" "))||"all"==b){function g(n,r){if("function"==typeof r){console.log("Edit mode: initializeEditor");
var f=n.find(".js-editor");0<f.length?vBulletin.ckeditor.initEditor(f,{success:function(l){if("function"==typeof r){r();vBulletin.contentEntryBox.afterPanelChange(n);vBulletin.ckeditor.initEditorComponents(n);var t=this;setTimeout(function(){console.log("Edit mode: Adding post data to CKEditor (vBulletin.conversation.bindEditFormEventHandlers)");t.setData(f.prev(".js-editor-parsed-text").html(),function(){var h=vBulletin.ckeditor.getEditor(l);vBulletin.ckeditor.fixTableFunctionality.call(vBulletin.ckeditor,
{},h);setTimeout(function(){vBulletin.ckeditor.modifyImagePaths(a(h.container.$))},0);h.focus()})},0)}},error:function(l){"function"==typeof r&&r();f.prop("disabled",!1).removeClass("ckeditor-load-on-focus").closest(".js-content-entry").addClass("b-content-entry--no-ckeditor");l=f.prev(".js-editor-parsed-text").html();""!=l&&vBulletin.AJAX({call:"/ajax/api/editor/convertHtmlToBbcode",data:{nodeid:pageData.nodeid,data:l,allowsmilie:1,securitytoken:pageData.securitytoken},success:function(t){f.html(t.data)},
error_phrase:"error_converting_message"})},hideLoadingDialog:!1}):"function"==typeof r&&(r(),f.trigger("focus"))}}function p(n){n=n.find(".js-editor");if(0<n.length){var r=n.attr("id");vBulletin.ckeditor.editorExists(r)&&vBulletin.ckeditor.destroyEditor(r)}n.closest("form").remove()}function m(n,r,f,l,t){let h=a(".b-link-input__url",f),d=a.trim(h.val());l="attach_"+l;d?(d.match(/^https?:\/\//)||(d="http://"+d,h.val(d)),r.prop("disabled",!0),a("body").css("cursor","wait"),y.AJAX({call:"/createcontent/getlinkdata",
data:{url:d,isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0},success:q=>{let u=a(q.template);n.closest("form").data("content-type",q.contenttype);u.find("img").on("error",function(){a(this).closest("li").remove()});f.find(".js-panel-content").append(u);e(f,q.contenttype);u.fadeIn("slow",()=>{h.val("");a(".b-link-input",f).addClass("h-hide")})},after_error:()=>h.trigger("focus"),complete:()=>{a("body").css("cursor","default");r.prop("disabled",!1)},title_phrase:l})):y.warning(l,t,h)}function k(n){a("body").offon(n+
"_editform_onunload",function(r,f){p(f)}).offon(n+"_newcontent_onload",function(r,f){0<f.closest(".conversation-list.stream-view.activity-view").length&&vBulletin.truncatePostContent(f)})}var c={comment:function(){a("body").offon("comment_editform_onload",function(n,r,f){"function"==typeof f&&(f(),a(".js-editor",r).trigger("focus").filter(".autogrow").css("min-height",function(){return a(this).css("height")}).autogrow())})},text:function(){a("body").offon("text_editform_onload",function(n,r,f){g(r,
f)});k("text")},event:function(){a("body").offon("event_editform_onload",function(n,r,f){g(r,f)});k("event")},poll:function(){var n=function(r){r.find(".js-remove-button").prop("disabled",2>=r.find("li").length)};a("body").offon("poll_editform_onload",function(r,f,l){g(f,l);n(a(this).find(".b-poll-fieldset__poll-answers"))}).offon("poll_editform_onunload",function(r,f){p(f)}).offon("poll_newcontent_onload",function(r,f){n(a(this).find(".b-poll-fieldset__poll-answers"));0<f.closest(".conversation-list.stream-view.activity-view").length&&
(vBulletin.truncatePostContent(f),vBulletin.conversation.limitVisiblePollOptionsInAPost(a("form.poll",f),3))})},gallery:function(){a("body").offon("gallery_editform_onload",function(n,r,f){a('.b-toolbar__item[data-panel="b-content-entry-panel__content--gallery"]',r).trigger("click");g(r,function(){"function"==typeof f&&f();vBulletin.upload.initializePhotoUpload(r)})});k("gallery")},video:function(){a("body").offon("video_editform_onload",function(n,r,f){a('.b-toolbar__item[data-panel="b-content-entry-panel__content--video"]',
r).trigger("click");g(r,function(){"function"==typeof f&&f();e(a(".b-content-entry-panel__content--video",r),"video")});a(".js-attach-button",r).off("click").on("click",function(l){l.preventDefault();l=a(this);m(r,l,l.closest(".b-content-entry-panel__content--video"),"video","please_enter_video_url")})});k("video")},link:function(){a("body").offon("link_editform_onload",function(n,r,f){a('.b-toolbar__item[data-panel="b-content-entry-panel__content--link"]',r).trigger("click");g(r,function(){"function"==
typeof f&&f();e(a(".b-content-entry-panel__content--link",r),"link")});a(".js-attach-button",r).offon("click",function(l){l.preventDefault();l=a(this);m(r,l,l.closest(".b-content-entry-panel__content--link"),"link","please_enter_a_valid_url_and_click_attach")})}).offon("link_savepost_success",function(n,r){a(".b-link-input",r).removeClass("h-hide-imp")});k("link")}},e=function(n,r){a(".b-link-content__urlinfo .js-link-edit",n).on("click",function(l){l.preventDefault();var t=a(this).parent().parent();
t.addClass("b-link-content__urlinfo-meta--edit-mode");a(".js-link-textbox",t).val(a.trim(a(".b-link-content__urlinfo-text",t).text())).trigger("focus");a(".js-link-save",t).on("click",function(h){h.preventDefault();a(".b-link-content__urlinfo-text",t).text(a(".js-link-textbox",t).val());t.removeClass("b-link-content__urlinfo-meta--edit-mode")})});a(".js-link-remove",n).on("click",function(l){l.preventDefault();a(this).closest(".b-content-entry-panel__content").find(".b-link-input").removeClass("h-hide");
a(this).closest(".js-panel-content").empty();a(".b-link-input",n).removeClass("h-hide")});if("link"==r){a(".js-link-preview-checkbox",n).off("click").on("click",function(){a(".b-link-content__thumbnail",n)[this.checked?"addClass":"removeClass"]("h-hide")});var f=a(".b-link-thumbnail-list__item",n).length;a(".b-link-thumbnail-list",n).jcarousel({scroll:1,wrap:null,size:f,rtl:vBulletin.isRtl(),buttonNextCallback:function(l,t,h){a(".b-thumbnail-nav .b-thumbnail-nav__next-arrow",n).toggleClass("b-icon--disabled",
!h)},buttonPrevCallback:function(l,t,h){a(".b-thumbnail-nav .b-thumbnail-nav__prev-arrow",n).toggleClass("b-icon--disabled",!h)},initCallback:function(l,t){"init"==t&&0<f&&(a(".b-thumbnail-nav .b-thumbnail-nav__counter",n).html("1/"+f),a(".b-thumbnail-nav .b-thumbnail-nav__prev-arrow",n).off("click").on("click",function(){a(this).hasClass("b-icon--disabled")||a(".jcarousel-container .jcarousel-prev",n).trigger("click")}),a(".b-thumbnail-nav .b-thumbnail-nav__next-arrow",n).off("click").on("click",
function(){a(this).hasClass("b-icon--disabled")||a(".jcarousel-container .jcarousel-next",n).trigger("click")}))},itemVisibleInCallback:function(l,t,h,d){if("init"==d)return!1;a(".b-thumbnail-nav .b-thumbnail-nav__counter",n).html(h+"/"+f);a('input[type="radio"]',t).prop("checked",!0)},itemFallbackDimension:90})}};"all"!=b?c[b].call():a.each(c,function(n,r){r.call()})}};vBulletin.isScrolledIntoView=function(b,c){var e=!1;a.isPlainObject(c)&&"[object Object]"==c.toString()&&(e=!0,c.top=0,c.bottom=
0);b=b instanceof a?b:a(b);if(0==b.length)return!1;var g=a(window).scrollTop(),p=g+a(window).height(),m=b.offset().top;b=m+b.outerHeight();g=m-g;p-=b;e&&(c.top=g,c.bottom=p);return 0<=g&&0<=p};vBulletin.scrollToFixed=function(b){function c(m){g=a.extend({},g,m);if(g.element&&(g.element=g.element instanceof a?g.element:a(g.element),0<g.element.length)){a.inArray(g.fixedAt,["top","bottom"])&&(g.fixedAt="top");var k=g.element,n={width:k.width(),offset:k.offset(),"margin-top":parseInt(k.css("margin-top"),
10),"margin-bottom":parseInt(k.css("margin-bottom"),10),cssPosition:k.css("position"),coordinates:{left:k.css("left"),top:k.css("top"),right:k.css("right"),bottom:k.css("bottom")}},r=a("<div />").addClass("scrolltofixed-filler").hide().insertAfter(k);k.data("origOffsetTop",n.offset.top);k.css("z-index",g.zIndex);k.data("object-instance",e);m=a(window).off("scroll."+p).on("scroll."+p,function(){if(!k.is(":hidden")){var f=a(this).scrollTop();if(0<g.limit&&f>g.limit&&k.hasClass("scrolltofixed"))k.removeClass("scrolltofixed").css({position:"absolute",
left:"auto",right:"auto",top:"auto",bottom:"auto",width:n.width});else if(0<g.limit&&f<g.limit&&f>n.offset.top&&!k.hasClass("scrolltofixed")||0>=g.limit&&f>n.offset.top&&!k.hasClass("scrolltofixed")){if(r.css({display:k.css("display"),width:k.outerWidth(!0),height:k.outerHeight(!0),"float":k.css("float")}),f=vBulletin.Responsive&&vBulletin.Responsive.scrollToFixedBreakPoint?vBulletin.Responsive.scrollToFixedBreakPoint:0,a("#vb-page-body").width()>f?k.addClass("scrolltofixed").width(n.width).css({left:n.offset.left,
right:"auto",width:n.width,top:"top"==g.fixedAt?0:"auto",bottom:"bottom"==g.fixedAt?0:"auto",position:""}):r.hide(),f=n["margin-"+g.fixedAt]){var l={};l[g.fixedAt]=-f+"px";k.animate(l,"fast")}}else f<=n.offset.top&&k.hasClass("scrolltofixed")&&(r.hide(),k.removeClass("scrolltofixed").css({position:"",width:"",left:"",top:"",right:"",bottom:""}))}}).off("resize."+p).on("resize."+p,function(){k.removeClass("scrolltofixed").width("auto").css({position:"",left:""});n.width=k.width();n.offset=k.offset();
a(this).trigger("scroll."+p)});g.triggerOnload&&m.trigger("scroll."+p)}}var e=this,g={element:a(),fixedAt:"top",limit:0,triggerOnload:!0,zIndex:99},p=("scrollToFixed"+Math.random()).replace(".","");this.updateLimit=function(m){isNaN(Number(m))||(g.limit=m,a(window).trigger("scroll."+p))};this.addLimit=function(m){isNaN(Number(m))||(g.limit+=m,a(window).trigger("scroll."+p))};this.reset=function(m){c(m)};c(b)};vBulletin.scrollToAnchor=function(b){b=b.replace(/(:|\.|\[|\]|,|\/)/g,"\\$1");var c=a(b);
console.log("vBulletin.scrollToAnchor() hash: {0}, found: {1}".format(b,c.length));if(0<c.length){var e=c.show().offset().top-2;c.hide();var g=a("html,body"),p=a(".scrolltofixed-floating.scrolltofixed-top"),m=!1;0<p.length&&(1==a(".list-container .list-item:first > a.anchor"+b).length?(p.hasClass("scrolltofixed")&&p.removeClass("scrolltofixed"),e=p.offset().top,m=!0):p.hasClass("scrolltofixed")&&(e-=p.outerHeight()));function k(){g.stop(!0)}g.off("scroll mousedown wheel DOMMouseScroll mousewheel keyup",
k).one("scroll mousedown wheel DOMMouseScroll mousewheel keyup",k);g.animate({scrollTop:e},{duration:1E3,step:function(n,r){m||(n=c.show().offset().top,c.hide(),n-=p.hasClass("scrolltofixed")?p.outerHeight():0,r.end=Math.round(n))},always:function(){c.show();g.off("scroll mousedown wheel DOMMouseScroll mousewheel keyup",k)}});return!1}return!0};location.hash&&vBulletin.scrollToAnchor(location.hash);vBulletin.animateScrollTop=function(b,c){console.log("vBulletin.animateScrollTop({0})".format(b));var e=
a(".scrolltofixed-floating.scrolltofixed-top");if(0<e.length){var g=e.data("origOffsetTop")||e.offset().top;!e.hasClass("scrolltofixed")&&g<b&&(b-=e.outerHeight(!0));g<b&&(b-=e.outerHeight())}a("html, body").animate({scrollTop:b},c)};vBulletin.truncatePostContent=function(b){b=b instanceof a?b:a(b);b.length||(b=a("body"));a(".poll-desc.ellipsis, .message-body.ellipsis",b).each(function(){var c=a(this);truncatedHeight=c.height();c.removeClass("ellipsis");var e=c.height();c.addClass("ellipsis");if(e>
truncatedHeight)c.closest(".list-item-body").find(".post-links").removeClass("hide-see-link").find(".see-link").off("click").on("click",function(){var g=a(this);g.hasClass("more")?c.removeClass("ellipsis"):c.addClass("ellipsis");g.toggleClass("more less");var p=g.text();g.text(g.data("toggle-text")).data("toggle-text",p);return!1})});a(".list-item .see-link.more",b).each(function(c){var e=a(this).closest(".list-item"),g=a(e).find(".post-content");if(0<g.length){var p=!1,m=!1,k=a(this).text(),n="",
r=a(g).html(),f=this;a(this).on("click",function(){nodeid=a(e).attr("data-node-id");p?(a(f).text(k),a(g).html(r),p=!1):m?(a(f).text(vBulletin.phrase.get("see_less")),p=!0,a(g).html(n)):!m&&nodeid&&vBulletin.AJAX({call:"/activity/fetchText",data:{nodeid},success:function(l){n=l.nodeText;if(n.length<=r.length)a(f).addClass("ui-helper-hidden"),postLink=a(f).closest(".post-links").html().replace("<span>|</span>",""),a(f).closest(".post-links").html(postLink);else return a(g).html(n),a(f).text(vBulletin.phrase.get("see_less")),
console.log("loaded content for node "+nodeid),m=p=!0,!1},error:vBulletin.ajaxtools.logAjaxError,api_error:vBulletin.ajaxtools.logApiError});return!1})}})};var J=0<parseInt(pageData.threadmarking)&&0<parseInt(pageData.userid);if(!J){var K=A.createArrayCookie("discussion_view",!0);var L=A.createArrayCookie("channel_view",!0)}vBulletin.discussionViewCookie=K;vBulletin.markreadcheck=function(){function b(g){var p=g.getAll(),m;for(m in p)p[m]<e&&g.unset(m)}function c(g,p,m){var k=parseInt(g.data("lastcontent"));
if(k<=e)k=!1;else{var n=parseInt(L.get(g.data("channel-id"),0));k=k>n}g.find(".icon").toggleClass(p,k).toggleClass(m,!k)}if(!J){var e=Math.round(Date.now()/1E3)-86400*vBulletin.options.get("markinglimit");b(K);b(L);a(".forum-item").each(function(){c(a(this),"unread","read")});a(".subforum-item").each(function(){c(a(this),"unread","read")});a(".topic-item").each(function(){var g=parseInt(a(this).data("lastcontent")),p=parseInt(L.get(a(this).data("channel-id"),0)),m=parseInt(K.get(a(this).data("node-id"),
0));g<=Math.max(p,m,e)||a(this).hasClass("redirect")?a(this).addClass("read").removeClass("unread"):0==a(this).find(".topic-wrapper .js-go-to-first-unread").length&&(g=a(this).find(".topic-wrapper .topic-title").attr("href"),"undefined"!=typeof g&&(g+=(-1==g.indexOf("?")?"?":"&amp;")+"goto=newpost",a("<a />").addClass("go-to-first-unread js-go-to-first-unread").attr("href",g).attr("title",vBulletin.phrase.get("go_to_first_new_post")).html('<span class="b-icon-fa b-icon-fa--16 fa-solid fa-angles-down" aria-hidden="true"></span>').prependTo(a(this).find(".topic-wrapper")),
a(this).find(".vb-icon-topic-status").attr("title",vBulletin.phrase.get("new_posts"))))})}};vBulletin.markchannelsread=function(b,c,e){if(parseInt(b))vBulletin.setChannelRead(b,c);else if(pageData.channelid&&parseInt(pageData.channelid)&&0<parseInt(pageData.threadmarking)&&0<parseInt(pageData.userid))vBulletin.setChannelRead(pageData.channelid,c);else{var g=[];e=a(e).closest(".widget-content").find(".forum-list-container");b=e.find(".forum-item");e=e.find(".subforum-item");var p=function(m,k){(m=
parseInt(a(k).attr("data-channel-id"),10))&&g.push(m)};a.each(b,p);a.each(e,p);a.each(g,function(m,k){m>=g.length-1?vBulletin.setChannelRead(k,c):vBulletin.setChannelRead(k,[])})}};vBulletin.markRead=function(b){J?vBulletin.AJAX({call:"/ajax/api/node/markRead",data:{nodeid:b},success:a.noop,api_error:a.noop,error:a.noop}):K.set(b,Math.round(Date.now()/1E3))};vBulletin.setChannelRead=function(b,c){var e=Math.round(Date.now()/1E3);success=c.success&&"function"==typeof c.success?c.success:a.noop;J?vBulletin.AJAX({call:"/ajax/api/node/markChannelsRead",
data:{nodeid:b},success,api_error:vBulletin.ajaxtools.logApiError}):(0==b?A.setCookie("lastvisit",e):L.set(b,e),success());return!0};vBulletin.ckeditor=vBulletin.ckeditor||{};window.CKEDITOR_BASEPATH=pageData.baseurl+"/js/ckeditor/";vBulletin.ckeditor.requiredScriptsLoaded=!1;vBulletin.ckeditor.requiredScriptsLoadFailed=!1;vBulletin.ckeditor.requiredScriptLoadingStarted=!1;vBulletin.ckeditor.checkEnvironment=function(){return!0};vBulletin.ckeditor.fireCallbacks=function(b,c,e,g){"error"==e&&"function"==
typeof c.error&&c.error(b);"success"==e&&"function"==typeof c.success&&c.success.apply(g,[b,g]);"function"==typeof c.complete&&c.complete(b)};vBulletin.ckeditor.initEditor=function(b,c){c=c||{};b=vBulletin.ckeditor.verifyEditorId(b);console.log("Ckeditor: initEditor({0})".format(b));if(vBulletin.ckeditor.checkEnvironment())vBulletin.ckeditor.requiredScriptsLoaded?vBulletin.ckeditor.doInitEditor(b,c):vBulletin.ckeditor.loadScripts(b,c);else{var e=a("#"+b).closest(".js-content-entry");e.find("li[data-panel=b-content-entry-panel__content--toggle-editor]").addClass("h-hide");
e.find("li[data-panel=b-content-entry-panel__content--smiley]").addClass("h-hide");e.find("form").append(a('<input type="hidden" name="nl2br" value="1" />'));vBulletin.ckeditor.fireCallbacks(b,c,"error")}};vBulletin.ckeditor.loadScripts=function(b,c,e){if(vBulletin.ckeditor.requiredScriptLoadingStarted)console.warn("Ckeditor: Trying to load required scripts more than once.");else{vBulletin.ckeditor.requiredScriptLoadingStarted=!0;c=c||{};b=b||"";"undefined"===typeof c.hideLoadingDialog||c.hideLoadingDialog||
vBulletin.ckeditor.showLoadingDialog(b);var g=function(){!c.showError&&vBulletin.ckeditor.requiredScriptsLoadFailed||vBulletin.warning("error","error_loading_ckeditor_script");vBulletin.loadingIndicator.hide();vBulletin.ckeditor.requiredScriptsLoadFailed=!0;vBulletin.ckeditor.fireCallbacks(b,c,"error")},p=function(){vBulletin.ckeditor.requiredScriptsLoadFailed?(vBulletin.ckeditor.fireCallbacks(b,c,"error"),c.hideLoadingDialog||vBulletin.ckeditor.hideLoadingDialog(b)):("function"==typeof e&&e(),"function"==
typeof vBulletin.ckeditor.doInitEditor&&window.CKEDITOR?(vBulletin.ckeditor.requiredScriptsLoaded=!0,vBulletin.ckeditor.doInitEditor(b,c)):setTimeout(p,10))};"function"==typeof vBulletin.ckeditor.doInitEditor||window.CKEDITOR?p():vBulletin.AJAX({url:vBulletin.getAjaxBaseurl()+"/ajax/render/ckeditor_javascript",success:function(m){for(var k=[],n=/src="([^"]+)"/g;match=n.exec(m);)k.push(match[1]);var r=function(){0<k.length?(console.log("Ckeditor: Calling getScript for: {0}".format(k[0])),a.getScript(k[0],
function(f,l,t){if("success"!=l)return console.warn("Ckeditor: Error loading "+k[0]),g(),!1;console.log("Ckeditor: Script loaded: "+k[0]);k.splice(0,1);r()}).fail(function(f,l,t){console.warn("Ckeditor: Error loading script: "+l+" Exception: "+t);g()})):p()};r()},error_phrase:"error_fetching_dialog"})}};vBulletin.ckeditor.editorExists=function(b){return!1};vBulletin.ckeditor.isEditorEmpty=function(b){return!0};vBulletin.ckeditor.resetEditor=function(b){return!1};vBulletin.ckeditor.getEditorContent=
function(b){b=vBulletin.ckeditor.verifyEditorId(b);return b?vBulletin.ckeditor.editorExists(b)?(b=vBulletin.ckeditor.getEditor(b))&&b.getData?a.trim(b.getData()):!1:a.trim(a("#"+b).val()):!1};vBulletin.ckeditor.focusEditor=function(b){if(b=vBulletin.ckeditor.verifyEditorId(b))vBulletin.ckeditor.editorExists(b)?(b=vBulletin.ckeditor.getEditor(b))&&b.focus():a("#"+b).trigger("focus")};vBulletin.ckeditor.loadingDialogStack={};vBulletin.ckeditor.showLoadingDialog=function(b){if("undefined"==typeof vBulletin.ckeditor.loadingDialogStack[b]||
!vBulletin.ckeditor.loadingDialogStack[b]){vBulletin.ckeditor.loadingDialogStack[b]=!0;var c=a("#"+b);0<c.length&&c.is(":visible")&&c.prop("disabled",!0);vBulletin.loadingIndicator.show("vBulletin.ckeditor.showLoadingDialog editorId: "+b)}};vBulletin.ckeditor.hideLoadingDialog=function(b){"undefined"!=typeof vBulletin.ckeditor.loadingDialogStack[b]&&vBulletin.ckeditor.loadingDialogStack[b]&&(vBulletin.ckeditor.loadingDialogStack[b]=!1,a("#"+b).prop("disabled",!1),vBulletin.loadingIndicator.hide("vBulletin.ckeditor.hideLoadingDialog editorId: "+
b))};vBulletin.ckeditor.generatedIdCounter=0;vBulletin.ckeditor.verifyEditorId=function(b){b=b||"";if("string"==typeof b)return b;if("object"==typeof b&&"undefined"!=typeof b.checkDirty&&"undefined"!=typeof b.name)return b.name;b=b instanceof a?b:a(b);b.attr("id")||(++vBulletin.ckeditor.generatedIdCounter,b.attr("id","vb-cke-instance-"+vBulletin.ckeditor.generatedIdCounter));return b.attr("id")};vBulletin.ckeditor.initEditorComponents=function(b,c){b=b||document;a(function(){a(".js-ckeditor-init-on-focus",
b).off("focus").on("focus",function(){vBulletin.ckeditor.initEditor(a(this))});a(".js-ckeditor-init-on-page-load",b).each(function(){vBulletin.ckeditor.initEditor(a(this))});if(!c){var e=function(k){if(0==k)return a("<span />").html(vBulletin.phrase.get("no_icon")).get(0);var n=a(".js-content-entry-post-icons option",b).filter((f,l)=>a(l).val()==k),r=n.data("icon-url");return r?(n=n.text(),a("<img />").attr("src",r).attr("alt","").attr("title",n).get(0)):""},g=a(".js-content-entry-post-icons",b);
g.selectBox().on("change",function(){var k=a(this).val();a(".js-content-entry-post-icons.selectBox-dropdown .selectBox-label",b).html(e(k))});a(".js-content-entry-post-icons-selectBox-dropdown-menu li a").each(function(){var k=a(this).attr("rel");a(this).html(e(k))});g.trigger("change");a(".js-content-entry-prefixes",b).selectBox();g=a(".js-content-entry-event-highlights-container",b);var p=g.is(".h-hide-imp");p&&g.removeClass("h-hide-imp");a(".js-content-entry-event-highlights",b).selectBox();p&&
g.addClass("h-hide-imp");var m=[];a(".js-select-box",b).each(function(){for(var k=a(this),n;k.is(":hidden");){n=k.closest(".h-hide");if(1>n.length)break;m.push(n);n.removeClass("h-hide")}k.selectBox()});a.each(m,function(k,n){n.addClass("h-hide")})}})};vBulletin.ckeditor.initEditorComponents(document);a(".js-focus-on-page-load").first().trigger("focus");vBulletin.doReplaceSecurityToken=function(b){"undefined"!=typeof b&&""!=b&&(a("form").each(function(){var c=a(this);if(this.action&&!vBulletin.isInternalUrl(this.action))return console.log("Skipping security token for external url (form action): "+
this.action),!0;"undefined"!=typeof this.method&&"post"==this.method.toLowerCase()&&(c.find('input[name="securitytoken"]').length?c.find('input[name="securitytoken"]').val(b):c.append('<input type="hidden" name="securitytoken" value="'+b+'" />'))}),pageData.securitytoken=b,console.log("Securitytoken updated"))};var M=null;vBulletin.flashMessage=function(b){var c=a(".js-flash-message"),e=c.find(".js-flash-message-content");M&&clearTimeout(M);e.text(b);c.removeClass("h-hide").show();M=setTimeout(function(){c.fadeOut(function(){c.addClass("h-hide")})},
5E3)};vBulletin.flashPhrase=function(b){vBulletin.flashMessage(vBulletin.phrase.get(b))};bindFormReset=function(b){return a(b).on("reset",function(c,e){"function"==typeof e&&e()})};vBulletin.sitebuilder=vBulletin.sitebuilder||{};vBulletin.sitebuilder.toggleSitebuilder=function(b){b=a(this);b.hasClass("on")?(A.setCookie("sitebuilder_active",""),a(".js-top-menu-sitebuilder").slideUp("fast"),b.removeClass("on"),b.attr("aria-pressed","false")):(a(".js-top-menu-sitebuilder").slideDown("fast"),b.addClass("on"),
b.attr("aria-pressed","true"),A.setCookie("sitebuilder_active","1"))};vBulletin.sitebuilder.setupMenuProxy=()=>{var b=a(".js-top-menu-sitebuilder--list");b.find(".js-top-menu-link:not(.js-top-menu-tab--admincp)").removeClass("b-top-menu__item-link--disabled");b.on("click.menuproxy",".js-top-menu-link:not(.js-top-menu-tab--admincp)",c=>{D();vBulletin.ready(["sb_page","sb_page_style"]).then(()=>{b.off(".menuproxy");a(c.currentTarget).trigger("click")});return!1})};pageData.dstauto&&(G=(new Date).getTimezoneOffset()/
60,1==Math.abs(pageData.tzOffset+G)&&vBulletin.AJAX({call:"/profile/save-dst",data:{userid:pageData.userid,clientUtcOffset:G},success:()=>location.reload(),api_error:a.noop,error:a.noop}));vBulletin.initFlexGridFixLastRowAll=function(b){function c(e){N(".js-flexgrid",".js-flexgrid-item",".js-flexgrid-image","b-flexgrid__item--lastrow","b-flexgrid__item--lastinrow",!0,e);N(".js-photo-preview",".b-gallery-thumbnail-list__item",".b-gallery-thumbnail-list__thumbnail","b-gallery-thumbnail-list__item--lastrow",
"b-gallery-thumbnail-list__item--lastinrow",!1,e)}c("undefined"==typeof b?!1:b);vBulletin.Responsive.Debounce.registerCallbackOnce(function(){c(!0)})};vBulletin.initFrameImagesWithColor=function(){P(".js-frame-image-wrapper",".js-frame-image")};setTimeout(function(){function b(){clearTimeout(securitytoken_timeout);if("guest"!=pageData.securitytoken){securitytoken_timeout=setTimeout(b,36E5);var e=function(){3==++securitytoken_errors&&vBulletin.doReplaceSecurityToken("guest")};vBulletin.AJAX({call:"/ajax/replace-securitytoken",
data:{securitytoken:pageData.securitytoken},success:function(g){securitytoken_errors=0;vBulletin.doReplaceSecurityToken(g.newtoken)},api_error:e,error:e})}}a.support.selectstart||a.fn.extend({disableSelection:function(){return this.each(function(){a(this).css({"-moz-user-select":"-moz-none","-webkit-user-select":"none","-khtml-user-select":"none","-o-user-select":"none","user-select":"none"})})},enableSelection:function(){return this.each(function(){a(this).css({"-moz-user-select":"","-webkit-user-select":"",
"-khtml-user-select":"","-o-user-select":"","user-select":""})})}});(function(){function e(d){a("textarea.autogrow",d).css("min-height",function(){return a(this).css("height")}).autogrow()}function g(d){d.preventDefault();d=a(".js-refer-user-dialog");d.length?d.dialog("open"):vBulletin.AJAX({call:"/ajax/render/dialog_refer_user",data:{isAjaxTemplateRenderWithData:!0},success:function(q){a(q.template).appendTo("body");a(".js-refer-user-dialog").dialog({title:vBulletin.phrase.get("refer_a_friend"),
autoOpen:!0,modal:!0,resizable:!1,closeOnEscape:!0,showCloseButton:!1,width:500,dialogClass:"dialog-container dialog-box",create:function(){a(".js-close-button",this).on("click",function(u){u.preventDefault();a(this).closest(".js-refer-user-dialog").dialog("close")})},open:function(){function u(w){this.select()}var v=a(".js-referral-link",this);v.val(v.data("link")).off("focus",u).on("focus",u).trigger("focus")}})}})}function p(d){var q=a(`.js-namecard-html[data-userid="${d}"]`);return new Promise((u,
v)=>{0<q.length?u(q):vBulletin.AJAX({call:"/ajax/render/user_namecard",data:{userid:d,isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0},success:function(w){w.template&&(q=a(w.template).filter(".js-namecard-html"),q.appendTo(document.body),u(q))},after_error:()=>{v()}})})}function m(d){var q=parseInt(d.data("vbnamecard")||0);if(Number.isNaN(q))return!1;p(q).then(u=>{vBulletin.qtip.apply(d,"",{content:function(v,w){v=a(u[0].outerHTML).removeClass("h-hide-imp");v.find(".js-close-qtip").click(()=>
{w.hide()});return v},position:{my:"top center",at:"bottom center",viewport:a(window),adjust:{method:"shift flip"}},show:{solo:!1,ready:!0,event:!1},hide:{event:"unfocus",fixed:!0},style:{classes:"qtip--b-namecard"}})});return!0}function k(d){d.find("input.js-dependent-master").each(function(){var q=a(this),u=q.attr("type"),v=function(){var w=q.data("action"),x=!q.is(":checked"),z=a(document).find(q.data("on"));"invisible"==w?z.toggleClass("h-invisible",x):"hide"==w?z.toggleClass("h-hide-imp",x):
(z.find(":input").addBack(":input").prop("disabled",x),z.find("select").addBack("select").selectBox(x?"disable":"enable"))};if("checkbox"==u)q.on("change",v);else if("radio"==u)q.closest("form").find('input[name="'+q.attr("name")+'"]').on("change",v)})}function n(d){vBulletin.flashMessage(d);d=new URL(location.href);d.searchParams.delete("flashmsg");var q=document.title;History.replaceState({},q,d.href);document.title=q}function r(){a(".js-full-height").each(function(){var d=a(this),q=d.parent();
d.css("height","");d.outerHeight(Math.floor(q.height()),!0)})}function f(d){let q=u=>u.src="core/images/default/google-material/image_placeholder.svg";a("img.js-img-fallback",d).each((u,v)=>{!v.complete||v.naturalWidth&&v.naturalHeight||q(v);v.addEventListener("error",()=>q(v))})}vBulletin.loadingIndicator.init();var l=a(document);l.off("click","a.animate-scroll").on("click","a.animate-scroll",function(){vBulletin.scrollToAnchor(this.hash)&&(location.href=this.href);return!1});var t=A.createStorage("collapse");
l.off("click",".canvas-widget .toggle-button").on("click",".canvas-widget .toggle-button",function(d,q){d=a(this);var u=d.closest(".canvas-widget"),v=a(".widget-content",u),w=u.data("widget-instance-id"),x=d.closest(".edit-mode").length;d.hasClass("expand")?(u.removeClass("collapsed"),q?v.show():v.slideDown("slow"),x||t.unset(w)):(q?(v.hide(),u.addClass("collapsed")):v.slideUp("slow",function(){u.addClass("collapsed")}),x||t.set(w,1));d.toggleClass("collapse expand");q=d.attr("title");d.attr("title",
d.data("toggle-title")).data("toggle-title",q);return!1});(function(){var d=t.getAll("collapse");d&&null!=d&&a.each(d,function(q,u){a("#widget_"+q+":not(.widget-no-header-buttons) .widget-header .toggle-button").trigger("click",[!0])})})();a(".conversation-toolbar-wrapper form.toolbar-filter-overlay").trigger("reset");e(l);l.on("vb-loadnewposts",function(d,q){e(l,q.insertedHtml)});a(".edit-switch-container .switch-control").on("click",vBulletin.sitebuilder.toggleSitebuilder);vBulletin.sitebuilder.setupMenuProxy();
var h=(new URL(location.href)).searchParams.get("adminAction");actionMap={quickConfig:".js-top-menu-tab--quicksetup",stylePanel:".js-top-menu-tab--style",editPage:".js-top-menu-tab--editpage"};$action=a(actionMap[h]);0<$action.length?($action.trigger("click"),"editPage"==h&&vBulletin.ready("history").then(()=>{let d=new URL(location.href),q=new vBulletin.history.instance(!0);d.searchParams.delete("adminAction");q.pushState({},document.title,d)})):0==pageData.userid&&actionMap[h]&&vBulletin.assertUserHasAdminPermission("canusesitebuilder",
self,a.noop,function(){location.reload()});a("select.custom-dropdown",".js-select-box").selectBox();l.off("keypress",".js-button").on("keypress",".js-button",function(d){if(32==d.which||13==d.which)d.target&&d.target.nodeName&&"label"==(d.target.nodeName+"").toLowerCase()&&1==a(d.target).find("input").length?a(d.target).find("input").trigger("click"):a(this).trigger("click"),d.preventDefault()});l.off("keypress",".js-link").on("keypress",".js-link",function(d){13==d.which&&(a(this).trigger("click"),
d.preventDefault())});a(".js-debug-collapse-list").next("ol, ul").hide();l.off("click",".js-debug-collapse-list").on("click",".js-debug-collapse-list",function(d){a(this).next("ol, ul").toggle()});l.off("click",".js-refer-user",g).on("click",".js-refer-user",g);l.off("click",".js-toggle-slider").on("click",".js-toggle-slider",function(){var d=a(this);d.is(".b-toggle-slider--yes")?(d.removeClass("b-toggle-slider--yes").addClass("b-toggle-slider--no"),d.find(".b-toggle-slider__radio--no").prop("checked",
!0),d.data("value","0")):(d.removeClass("b-toggle-slider--no").addClass("b-toggle-slider--yes"),d.find(".b-toggle-slider__radio--yes").prop("checked",!0),d.data("value","1"));var q=a(".js-toggle-slider, .js-toggle-slider__dependent"),u=q.index(d),v=!1;q.each(function(w,x){if(w==u)v=!0;else if(1==v)if(w=a(this),w.is(".js-toggle-slider__dependent"))w.toggleClass("h-hide");else return v=!1});d.trigger("change",d.data("value"));return!1});vBulletin.options.get("usenamecard")&&a(document).offon("click",
"a[data-vbnamecard]",function(d){m(a(d.currentTarget))&&d.preventDefault()});a(document).offon("click",".js-follow-action",d=>{d=a(d.currentTarget);var q=parseInt(d.data("userid")),u=d.data("action");if("add"!=u&&"delete"!=u||isNaN(q))return!1;vBulletin.AJAX({call:"/ajax/api/user/changeUserRelation",data:{action:u,userid:q},success:function(v){if(1==v.follow||2==v.follow){var w=v.follow;"delete"==u&&(w=0);a(document).trigger("vb-userrelation-change",{newRelation:w,ignoring:v.ignoring,targetUserid:q})}},
title_phrase:"profile_guser"})});a(document).offon("vb-userrelation-change",(d,q)=>{var u=parseInt(q.hasOwnProperty("targetUserid")?q.targetUserid:"");d=q.hasOwnProperty("newRelation")?q.newRelation:null;q=q.hasOwnProperty("ignoring")?q.ignoring:null;var v=`.js-ignore-user[data-userid="${u}"][data-state="`,w=a(`${v}ignoring"]`);v=a(`${v}normal"]`);isNaN(u)||(null!==q&&(w.toggleClass("h-hide-imp",!q),v.toggleClass("h-hide-imp",q)),null!==d&&(w=`.js-follow-action[data-userid="${u}"]`,u=a(w),w=a(`${w}[data-state="${d}"]`),
u.addClass("h-hide-imp"),w.removeClass("h-hide-imp"),0===d||q||v.addClass("h-hide-imp")))});a(document).offon("click",".js-ignore-user",d=>{d=a(d.currentTarget);var q=parseInt(d.data("userid"));d=d.data("action");var u="ignore"==d?1:0;if("ignore"!=d&&"unignore"!=d||isNaN(q))return!1;vBulletin.AJAX({call:"/ajax/api/user/ignoreUser",data:{userid:q,add:u},success:function(v){v&&a(document).trigger("vb-userrelation-change",{ignoring:u,targetUserid:q})},title_phrase:"profile_guser"})});a(".channel-content-widget .new-conversation-btn").off("click").on("click",
function(){location.href=pageData.baseurl+"/new-content/"+pageData.channelid});a(".pagenav-form").on("submit",function(){var d=Number(this.page.value);0<d&&(location.href=this.action+"&p="+d);return!1}).trigger("reset");a(".toolbar-pagenav").off("keydown",".toolbar-pagenav input").on("keydown",".toolbar-pagenav input",function(d){var q=d.which;return d.shiftKey||d.altKey||d.ctrlKey||!(48<=q&&57>=q||96<=q&&105>=q||8==q||9==q||13==q||35==q||36==q||37==q||39==q||46==q||45==q)?!1:!0});a(document).offon("click",
".js-post__manage",function(){if("undefined"==typeof vBulletin.inlinemod){var d=vBulletin.getAjaxBaseurl()+"/js/inlinemod.js?v="+pageData.simpleversion;a.getScript(d,()=>{vBulletin.inlinemod.manage_deleted_form.apply(this)}).fail(()=>{vBulletin.warning("error","error_loading_inlinemod_script")})}else vBulletin.inlinemod.manage_deleted_form.apply(this)});a(document).offon("click",".js-post__show-hide",function(){var d=a(this),q=d.text(),u=d.data("toggle-text"),v=d.hasClass("js-post__show-hide--show");
d.closest(".js-post").toggleClass("b-post--show-deleted-content",v);d.html(u).data("toggle-text",q).toggleClass("js-post__show-hide--show",!v)});a(document).offon("click","a.video-frame",function(d){d.preventDefault();var q=a(this);vBulletin.AJAX({call:"/ajax/render/bbcode_video",data:{code:q.data("vcode"),provider:q.data("vprovider"),height:q.data("height"),width:q.data("width"),isAjaxTemplateRenderWithData:!0},success:u=>{(u=u.template)&&q.replaceWith(u)}})});vBulletin.markreadcheck();a(document).offon("click",
"a.markchannelsread, a.navbar_mark_channels_read",function(){vBulletin.markchannelsread(0,{success:function(){location.reload()}},a(this));return!1});a(".js-footer-go-to-top").off("click").on("click",function(d){d.preventDefault();a("body,html").animate({scrollTop:0},800)});k(a(document));a("input.js-select-all-master").on("change",function(){var d=a(this);$list=a(document).find(d.data("list"));$list.prop("checked",d.is(":checked"))});pageData.flash_message&&n(pageData.flash_message);a("input[placeholder]").each(function(){var d=
a(this),q=d.attr("placeholder");q&&!d.attr("aria-label")&&d.attr("aria-label",q)});r();vBulletin.Responsive.Debounce.registerCallbackOnce(r);a(document).off("vb-filterposts",r).on("vb-filterposts",r);f(a(document));a(document).on("vb-instrument",d=>{d=a(d.target);f(d);k(d)});vBulletin.ready("global").resolve()})();a("#btnAdvSearch").off("click").on("click",function(e){e.preventDefault();a(this).data("clicked2submit",1);e=a("#searchForm");a('<input type="hidden" name="AdvSearch" value="1" />').appendTo(e);
e.submit()});a("#searchForm").off("submit.searchform").on("submit.searchform",function(e){function g(r,f,l){0<l.length&&l.prop("checked")&&(r[f]=l.val())}var p=a(this),m={},k=p.find("#q"),n=a.trim(k.val());if(0<n.length)m.keywords=n;else if(!a("#btnAdvSearch").data("clicked2submit"))return vBulletin.warning("search","please_provide_search_string",function(){k.trigger("focus")}),e.stopPropagation(),!1;e=p.find(".searchPopupBody");g(m,"title_only",e.find(".searchFields_title_only"));g(m,"authorid",
e.find(".searchFields_authorid"));g(m,"channel",e.find(".searchFields_channel"));p.find("input[name=searchJSON]").val(JSON.stringify(m));return!0});var c=A.getCookie("np_notices_displayed");c=c?c.split(","):[];c=c.concat(a('ul.notices li[data-notice-persistent="0"]').map((e,g)=>a(g).data("notice-id")).get());c=c.filter((e,g)=>c.indexOf(e)===g);0<c.length&&A.setCookie("np_notices_displayed",c.join(","),!0);a("ul.notices > li > .close").off("click").on("click",function(e){var g=a(this).closest("li");
e=g.attr("data-notice-id");vBulletin.AJAX({call:"/ajax/api/notice/dismiss",data:{noticeid:e},success:function(p){g.hide("slow",function(){var m=a(this).parent();0==m.find(">li:visible").length&&m.addClass("h-hide")})}})});a(".js-stylechooser a").off("click").on("click",function(){let e=a(this).data("styleid");A.setCookie("userstyleid",e,365);pageData.userid?H.ajaxSilent({call:"/ajax/apidetach/user/save",data:{userid:pageData.userid,password:"",user:{styleid:e},options:[""],adminoptions:[""],userfield:[""]},
success:()=>location.reload()}):location.reload();return!1});a(".js-languagechooser a").off("click").on("click",function(){A.setCookie("languageid",a(this).data("languageid"),365);location.reload();return!1});vBulletin.doReplaceSecurityToken(pageData.securitytoken);securitytoken_timeout=setTimeout(b,36E5);securitytoken_errors=0;vBulletin.initFlexGridFixLastRowAll();vBulletin.initFrameImagesWithColor();Q();setTimeout(function(){""!=pageData.crontask&&vBulletin.ajaxtools.ajaxSilent({call:"/ajax/apidetach/cron/"+
pageData.crontask,api_error:a.noop,error:vBulletin.ajaxtools.logAjaxError})},5)},1);vBulletin.triggerHandler=function(b,c,e){c&&0!=c.length?c instanceof a||(c=a(c)):c=a(document);e=e||[];b=a.Event(b);b.target=this instanceof a?this.get(0):this;return c.triggerHandler(b,e)}})(jQuery);function JShtmlEncode(a){var D="";a&&"undefined"!==typeof a&&0<a.length&&(D=$("<div/>").text(a).html());return D=String(D).replace(/"/g,"&quot;")}
function isValidEmailAddress(a){return(new RegExp(/(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/i)).test(a)}
function str_repeat(a,D){for(var E="",F=0;F<D;F++)E=E.concat(a);return E}vBulletin.htmlEntities=function(a){return String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")};vBulletin.htmlEntities_decode=function(a){return String(a).replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"')};
