/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache("error_adding_infraction error_adding_warning error_reversing_infraction give_infraction_ginfraction infraction_added infraction_reversed please_check_the_box_to_reverse_infraction please_specify_reason_to_reverse_infraction received_infraction received_warning warning_added".split(" "),[]);vBulletin.ensureObj("infraction");vBulletin.ensureObj("privateMessage");
(function(a){function E(c){var b=getSelectedMessages(),f=function(n,k){for(var e in b)a("[data-node-id={0}]".format(b[e]),".infractions-list").toggleClass("read",k).find(".privateMessageActionCheck").prop("checked",!1)};if(0<b.length)if("0"==pageData.threadmarking||"0"==pageData.userid){for(var q in b){var l=vBulletin.discussionViewCookie;c?l.set(b[q],Math.round((new Date).getTime()/1E3)):l.unset(b[q])}f(b,c)}else vBulletin.AJAX({call:"/ajax/api/node/"+(c?"markReadMultiple":"markUnreadMultiple"),
data:{nodeids:b},success:function(n){f(n,c)}})}function y(c,b,f,q){if(!c&&(c=a("#private-message-toolbar .infractions-paginator .infractionsPageTo"),0==c.length))return!1;updateCounter=f||0;q=q||!1;var l=c.closest(".infractions-paginator"),n=a("#privateMessageContainer .main-pane .pending-posts-container"),k=l.find("#maxPageNum").filter(":input[type=hidden]").val();c=parseInt(l.find(":input[type=hidden][name=pagenum]").val(),10);var e=parseInt(l.find(":input[type=hidden][name=per-page]").val(),10);
b=parseInt(b,10);if(isNaN(b)||isNaN(k)||isNaN(c))return!1;if(1>b||b>k)return vBulletin.error("error","please_enter_a_valid_page_number"),!1;if(b==c&&!f)return!1;var t={};a("#infractionFilters input:checked").each(function(){t[this.name]=this.value});t.time&&(t.time={from:t.time});var x={setCurrentPage:b,setPerPage:e,getPagingInfo:f,options:t,isAjaxTemplateRenderWithData:!0};vBulletin.AJAX({call:"/ajax/render/privatemessage_infraction_main",data:x,success:function(r){n.html(r.template);0<a(".infractions-list").length&&
vBulletin.infraction.markInfractions();var w=r=0;b<k?(w=b+1,1<b&&(r=b-1)):r=b-1;l.find(":input[type=hidden][name=pagenum]").val(b);l.find(":input[type=hidden][name=next-page]").val(w);l.find(":input[type=hidden][name=prev-page]").val(r);l.find(".infractionsNext").toggleClass("h-disabled",!w);l.find(".infractionsPrev").toggleClass("h-disabled",!r);l.find(".infractionsPageTo").val(b);f&&(r=a("#privateMessageContainer .main-pane .pending-posts-container .pending-posts-pageinfo"),r=parseInt(r.find(".totalpages").val(),
10),l.find("#maxPageNum").filter(":input[type=hidden]").val(r),k=r,l.find(".infractionsPageCount").text(r));C&&vBulletin.privateMessage.updatePaginationLinks(F,b,k);C&&!q&&vBulletin.privateMessage.pmFilterHistory.isEnabled()&&(x.maxPage=k,r=vBulletin.privateMessage.getPrivateMessageUrl(b),vBulletin.privateMessage.pmFilterHistory.pushState({infractionFilterParams:x},document.title,r.url))}})}var p=a("#infractions-tab"),C=vBulletin.privateMessage&&vBulletin.privateMessage.jsReady||!1,F=a("#privateMessageContainer");
vBulletin.infraction.infractUser=function(c,b){var f=a(this);if(f.data("ajaxstarted"))return!1;var q=f.hasClass("js-infraction-received");if(q){c="received_infraction_form";var l="received_infraction";var n="receive-infraction-dialog"}else c="give_infraction_form",l="give_infraction_ginfraction",n="give-infraction-dialog";f.data("ajaxstarted",!0);vBulletin.AJAX({call:"/ajax/render/"+c,data:{userid:f.data("userid"),nodeid:f.closest(".js-post-controls").data("node-id")||f.data("nodeid"),userInfraction:f.data("userinfraction")},
complete:function(){f.data("ajaxstarted",null)},success:function(k){a("."+n).length?a("."+n).replaceWith(k):a(k).appendTo(document.body).hide();k=a("."+n);k.dialog({title:vBulletin.phrase.get(l),autoOpen:!0,modal:!0,resizable:!1,closeOnEscape:!1,showCloseButton:!1,width:k.hasClass("error-infraction-dialog")?500:q?600:700,dialogClass:"dialog-container infraction-dialog-container dialog-box",close:function(){var e=a(".js-editor",this);e.length&&vBulletin.ckeditor.editorExists(e)&&vBulletin.ckeditor.destroyEditor(e);
a(this).dialog("destroy").remove()},open:function(){var e=this;if(q)vBulletin.ajaxForm.apply(a(".infraction-reverse-form",e),[{error_phrase:"error_reversing_infraction",success:function(d,g,h,m){vBulletin.alert("reverse_this_infraction","infraction_reversed");"function"==typeof b&&b.apply(f.get(0),[d]);a(e).dialog("close")},beforeSubmit:function(d,g,h){if(a(".infraction-nodeid",g).is(":checked"))a.trim(a(".infraction-reason",g).val())||(m="please_specify_reason_to_reverse_infraction",u=a(".infraction-reason",
g));else{var m="please_check_the_box_to_reverse_infraction";var u=a(".infraction-nodeid",g)}return m?(vBulletin.warning("reverse_this_infraction",m,function(){u.trigger("focus")}),!1):!0}}]),a(".reverse-infraction",e).on("click",function(){a(".infraction-reverse-form",e).submit()});else{var t=a(".infraction-send-pm",e);vBulletin.ajaxForm.apply(a(e),[{dataType:"json",error_phrase:"error_adding_infraction",success:function(d,g,h,m){g=d.infractionNodeid&&!d.infractionNodeid.errors;m="warning";g?(h=d.isWarning?
"warning_added":"infraction_added",m=""):h=d.isWarning?"error_adding_warning":"error_adding_infraction";vBulletin.alert("give_infraction_ginfraction",h,m);g&&("function"==typeof b&&b.apply(f.get(0),[d]),a(e).dialog("close"))},beforeSubmit:function(d,g,h){if("0"==a(".infraction-level-control option:selected",g).val()){d=function(I,J){w(a(".infraction-level",e));vBulletin.warning("give_infraction_ginfraction",I,function(){J.trigger("focus")})};if(""==a.trim(a(".custom-reason",g).val()))return d("please_specify_custom_reason",
a(".custom-reason",g)),!1;h=Number(a(".custom-points",g).val());if(isNaN(h)||0>h)return d("please_specify_custom_points",a(".custom-points",g)),!1;h=a(".custom-period option:selected",g).val();var m=Number(a(".custom-expires",g).val());if("N"!=h&&(isNaN(m)||0>=m))return d("please_specify_custom_expires",a(".custom-expires",g)),!1}d=a(".infraction-ban-reason .ban-reason",e);if(d.is(":visible")&&!a.trim(d.val()))return w(a(".infraction-ban",e)),a(".ban-reason-desc",e).removeClass("h-hide"),d.trigger("focus"),
a(".dialog-content",e).scrollTop(0).scrollTop(a(".infraction-ban-reason",e).position().top),!1;if(Number(t.data("required"))){var u=a(".js-editor",g),z=vBulletin.ckeditor.getEditor(u);g=z?z.getData():z.val();if(!a.trim(g))return vBulletin.warning("give_infraction_ginfraction","please_specify_infraction_pm",function(){w(t);z?z.focus():u.trigger("focus")}),!1}}}]);var x=function(d){r.toggleClass("h-hide",!d).find("input, select").prop("disabled",!1).end().find(".selectBox").toggleClass("selectBox-disabled",
!d)};a(".infraction-level-control",e).on("change",function(d,g,h){d=a(this.options[this.selectedIndex]);h&&1==h.length||(h=a(this).closest(".infraction-level").find(".infraction-warning-control input"));g||(d.data("allow-warning")?(h.prop("disabled",!1).val(this.value).parent().removeClass("h-hide"),x(!1)):(h.prop("disabled",!0).parent().addClass("h-hide"),"0"==this.value&&(x(!0),a(".textbox",r).first().trigger("focus"))));var m=g=0;h.prop("checked")||"0"==this.value?"0"==this.value&&(g=Number(a(".custom-infraction-info .custom-points",
e).val())||0)&&(m=1):(g=Number(d.data("points"))||0,m=1);h=a(".infraction-dashboard-stats").data();h=g&&K(Number(h.points)+g,Number(h.infractions)+m);G(h);A()});a(".infraction-warning-control input",e).on("click",function(){this.checked?G(!1):a(".infraction-level-control",e).trigger("change",[!0,this])});a(".custom-points",e).on("change",function(){a(".infraction-level-control",e).trigger("change",[!0])});var r=a(".custom-infraction-info",e).removeClass("h-hide");a("select",e).selectBox();r.addClass("h-hide");
a(".js-content-entry-panel, .js-editor",t).data("callback",function(){A()});vBulletin.ckeditor.initEditorComponents(t,!0);a(".toggle-button",e).on("click",function(d){d=a(this);var g=d.closest(".blockrow-head"),h=g.next(".blockrow-body"),m=d.hasClass("expand");h.toggle(m);g.toggleClass("collapsed",!m);A();d.toggleClass("collapse expand");g=d.attr("title");d.attr("title",d.data("toggle-title")).data("toggle-title",g);return!1});var w=function(d){a(".toggle-button.expand",d).trigger("click")},K=function(d,
g){if(0==d&&0==g)return!1;var h=!1;a(".infraction-ban-list tbody tr",e).each(function(m,u){if(u=a(this).data())if(m=Number(u.points),u=Number(u.infractions),m&&d>=m||u&&g>=u)return h=!0,!1});return h},G=function(d){var g=a(".infraction-ban-reason",e);d?(g.removeClass("h-hide"),w(a(".infraction-ban",e))):g.addClass("h-hide")},B=a(".dialog-content",e),A=function(){B[0]||(B[0]=e);var d=B[0].scrollHeight>parseFloat(B.css("max-height"));B.toggleClass("has-scrollbar",d)};A();a(".infraction-level-control",
e).trigger("change")}a(".close-infraction",e).on("click",function(){a(e).dialog("close")});a(".ckeditor-bare-box.ckeditor-load-on-focus",e).on("focus",function(){vBulletin.ckeditor.initEditor(this.id,{complete:function(d){A()},error:function(d){a("#"+d).prop("disabled",!1).removeClass("ckeditor-load-on-focus")}})})}})}})};vBulletin.infraction.loadUserInfractions=function(c){a.post(vBulletin.getAjaxBaseurl()+"/ajax/render/user_infractions",{userid:c.userid,pagenum:c.pageNumber},function(b,f,q){c.container.html(b);
a(".pagenav-form",p).length&&new vBulletin.pagination({context:p,tabParamAsQueryString:!1,allowHistory:1==p.find(".conversation-toolbar-wrapper").data("allow-history"),onPageChanged:function(l,n){vBulletin.infraction.loadUserInfractions({container:p,userid:p.data("userid"),pageNumber:l,replaceState:!0})}});"function"==typeof c.callback&&c.callback(b);if(c.pushState||c.replaceState)b=vBulletin.makePaginatedUrl(location.href,c.pageNumber),v||(D="1"==p.find(".conversation-toolbar-wrapper").data("allow-history"),
v=new vBulletin.history.instance(D)),v.isEnabled()&&(f={from:"infraction_filter",page:c.pageNumber,tab:p.data("url-path")?p.data("url-path"):"#"+p.attr("id")},v[c.pushState?"pushState":"setDefaultState"](f,document.title,b))},"json")};var v,D;vBulletin.infraction.setHistoryStateChange=function(){v||(D="1"==p.find(".conversation-toolbar-wrapper").data("allow-history"),v=new vBulletin.history.instance(D));v.isEnabled()&&v.setStateChange(function(c){var b=v.getState();if("infraction_filter"==b.data.from){v.log(b.data,
b.title,b.url);c=p.closest(".ui-tabs");var f=c.find(".ui-tabs-nav > li").filter('li:has(a[href*="#{0}"])'.format(p.attr("id")));f.hasClass("ui-tabs-active")?vBulletin.infraction.loadUserInfractions({container:p,userid:p.data("userid"),pageNumber:b.data.page,pushState:!1}):(b=f.index(),vBulletin.selectTabByIndex.call(c,b))}},"infraction_filter")};vBulletin.infraction.markInfractions=function(){if("0"==pageData.threadmarking||"0"==pageData.userid){var c,b,f;a(".infractions-list .list-item").each(function(){f=
a(this);b=f.data("nodeId");(c=vBulletin.discussionViewCookie.get(b))&&f.addClass("read")})}};a(document).off("click",".js-post-control__infraction").on("click",".js-post-control__infraction",function(c){vBulletin.infraction.infractUser.apply(this,[c,function(b){var f=a(this),q=f.find(".b-icon"),l=f.hasClass("js-infraction-received");q.removeClass("b-icon__tickets--neutral b-icon__tickets--warned b-icon__tickets--infracted");if(l){b="give_infraction_ginfraction";var n="b-icon__tickets--neutral"}else b.isWarning?
(b="received_warning",n="b-icon__tickets--warned"):(b="received_infraction",n="b-icon__tickets--infracted");f.toggleClass("js-infraction-received",!l);f.attr("title",vBulletin.phrase.get(b));q.addClass(n)}])});p.off("click",".infractionCtrl").on("click",".infractionCtrl",function(c){vBulletin.infraction.infractUser.apply(this,[c,function(b){vBulletin.infraction.loadUserInfractions({container:p,userid:a(this).data("userid"),pageNumber:1,pushState:1!=Number(a('.pagenav-form input[name="page"]',p).val())})}])});
p.on("click",".view-infraction",function(c){vBulletin.infraction.infractUser.apply(this,[c,function(b){b=Number(a('.pagenav-form input[name="page"]',p).val())||1;vBulletin.infraction.loadUserInfractions({container:p,userid:a(this).data("userid"),pageNumber:b,pushState:1!=b})}])});a(document).off("click","#privateMessageContainer .js-button-group .view-infraction").on("click","#privateMessageContainer .js-button-group .view-infraction",function(c){vBulletin.infraction.infractUser.apply(this,[c,function(b){}])});
a(".infraction-delete").off("click").on("click",function(c){$button=a(this);var b=!1;if($button.parents("#pmFloatingBarContent").hasClass("infractions-paginator"))var f=getSelectedMessages();else f=[a("#privateMessageContainer .js-conversation-starter").data("nodeId")],b=!0;0<f.length&&openConfirmDialog({title:vBulletin.phrase.get("messages_header"),message:vBulletin.phrase.get("are_you_sure_delete_infractions"),iconType:"warning",onClickYes:function(){vBulletin.AJAX({url:vBulletin.getAjaxBaseurl()+
"/ajax/api/node/deleteNodes",data:{nodeids:f,hard:0},success:function(q){b?location.href=a("#pmBtnBackToInfractions").prop("href"):location.reload()}})}})});a(".infraction-mark_as_read").off("click").on("click",function(c){E(!0)});a(".infraction-mark_as_unread").off("click").on("click",function(c){E(!1)});a(document).ready(function(){0<a(".infractions-list").length&&vBulletin.infraction.markInfractions();if(0<a("#pmBtnBackToInfractions").length){var c=a("#privateMessageContainer .conversation-list .b-post--infraction").data("nodeId");
vBulletin.markRead(c)}});a("#infractionFilters").trigger("reset").find(".filter-options input").off("click").on("click",function(c){L.apply(this)});a(document).off("click","#privatemessagePaging .infractionsPrev").on("click","#privatemessagePaging .infractionsPrev",function(c){c.preventDefault();c=a(this).closest("#privatemessagePaging").find(':input[type=hidden][name="prev-page"]').val();y(a(this),c)});a(document).off("click","#privatemessagePaging .infractionsNext").on("click","#privatemessagePaging .infractionsNext",
function(c){c.preventDefault();c=a(this).closest("#privatemessagePaging").find(':input[type=hidden][name="next-page"]').val();y(a(this),c)});var H=function(c){var b=a("#privatemessagePaging"),f=b.find("input[name='pagenum']");c=f.val();var q=b.find("#maxPageNum");b=q.val();var l=a("#infractionFilters"),n={};vBulletin.privateMessage.updatePaginationLinks(F,c,b);vBulletin.privateMessage.getPageFiltersForUrl=function(k){l.find("input:checked").each(function(){k["filter_"+this.name]=this.value});return k};
a("#infractionsFilter").length&&a("#infractionFilters input:checked").each(function(){queryParams["filter_"+this.name]=this.value});vBulletin.privateMessage.pmFilterHistory.isEnabled()&&(n={infractionFilterParams:{setCurrentPage:c,options:{},maxPage:b}},l.find("input:checked").each(function(){n.infractionFilterParams.options[this.name]=this.value}),n.infractionFilterParams.options.time&&(n.infractionFilterParams.options.time={from:n.infractionFilterParams.options.time}),vBulletin.privateMessage.pmFilterHistory.setDefaultState(n,
document.title,window.location.href),vBulletin.privateMessage.pmFilterHistory.setStateChange(function(k){k=vBulletin.privateMessage.pmFilterHistory.getState();k.data.hasOwnProperty("infractionFilterParams")&&(k=k.data.infractionFilterParams,a.each(k.options,function(e,t){e="input[name='{0}'][value='{1}']".format(e,t);l.find(e).prop("checked",!0)}),q.val(k.maxPage),f.val(k.setCurrentPage),y(null,k.setCurrentPage,!0,!0))},"privatemessage"));C=!0};if(C)H();else a(document).one("vb-privatemessage-js-ready",
H);a(document).off("keypress","#privatemessagePaging .infractionsPageTo").on("keypress","#privatemessagePaging .infractionsPageTo",function(c){if(13==c.keyCode){c.preventDefault();c=a(this);var b=parseInt(c.val(),10);if(isNaN(b))return vBulletin.error("error","please_enter_a_valid_page_number"),!1;y(c,b)}});var L=function(c){$paginateButton=a("#private-message-toolbar .infractions-paginator .infractionsPageTo");if($paginateButton.length)y($paginateButton,1,!0);else{var b={};a(this).closest(".filter-options-list").find("input:checked").each(function(){b[this.name]=
a(this).val()});b.time&&(b.time={from:b.time});a(this).prop("checked",!0);b.page=1;b.perpage=pmPerPage;vBulletin.AJAX({call:"/ajax/render/privatemessage_infraction_main",data:{options:b,isAjaxTemplateRenderWithData:!0},success:function(f){a("#privateMessageContainer .pending-posts-container").html(f.template);pmPageNum=1;0<a(".infractions-list").length&&vBulletin.infraction.markInfractions()}})}}})(jQuery);
