/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache(["saving"],["commentminchars"]);vBulletin.ensureObj("media");
$.extend(vBulletin.media,function(b){function A(a){m&&m.length||(m=b("#mediaCurrentPage",a),p=b("#mediaPageCount",a),q=b("#mediaPreviousPage",a),v=b("#mediaNextPage",a))}function n(a){b("body").css("cursor","wait");var c=b(".js-profile-media-container",h);vBulletin.AJAX({call:"/ajax/render/profile_media_content",data:{userid:c.data("user-id"),pageno:a,perpage:c.data("perpage"),isAjaxTemplateRenderWithData:!0},success:function(d){b("#mediacontent").html(d.template);b("#profileMediaDetailContainer").empty();
b("#mediacontent").removeClass("h-hide");x(!1);f.currentMediaPage=a;r(b("#mediaList"),f.currentMediaPage);vBulletin.isScrolledIntoView(b("#profileTabs .profile-tabs-nav"))||b("html,body").animate({scrollTop:b("#profileTabs .profile-tabs-nav").offset().top},"slow")},complete:function(){b("body").css("cursor","auto")},title_phrase:"profile_media"})}function B(a){var c=a.currentTarget.id;if(b("#profileMediaDetailContainer").is(":visible"))return E(a),!1;"mediaCurrentPage"==c?(a=parseInt(m.val(),10),
0<a&&a<=parseInt(p.html(),10)?(n(a),y(a)):m.val(f.currentMediaPage)):"mediaPreviousPage"==c?1<f.currentMediaPage?(a=f.currentMediaPage-1,n(a),y(a)):q.addClass("h-disabled"):"mediaNextPage"==c&&(f.currentMediaPage<parseInt(p.html(),10)?(a=f.currentMediaPage+1,n(a),y(a)):v.addClass("h-disabled"));return!1}function y(a){var c=vBulletin.makePaginatedUrl(location.href,a);k.isEnabled()?(a={from:"media_filter",page:a||1,tab:h.data("url-path")?h.data("url-path"):"#"+h.attr("id")},k.pushState(a,document.title,
c)):t&&(location.href=c)}function E(a){if(!f.currentNodeId&&!f.currentUserId)return!1;a=a.currentTarget.id;var c=f.currentGalleryPage,d={pageno:null,perpage:vBulletin.media.calculatePhotosPerPage(vBulletin.media.TARGET_PHOTOS_PERPAGE)};if("mediaCurrentPage"==a){var e=parseInt(m.val(),10);if(0>=e||e>parseInt(p.html(),10))return m.val(c),!1}else if("mediaPreviousPage"==a)if(1<c)e=c-1;else return q.addClass("h-disabled"),!1;else if("mediaNextPage"==a)if(c<parseInt(p.html(),10))e=c+1;else return v.addClass("h-disabled"),
!1;d.pageno=e;u(d);return!1}function x(a){b("#profileMediaDetailContainer").toggleClass("h-hide",!a);b("#profileMediaContainer").toggleClass("h-hide",a);q.closest("pagenav-controls").toggleClass("h-hide",a);b('.js-media-toggle[data-show-on="in-album"]').toggleClass("h-hide-imp",!a);b('.js-media-toggle[data-show-on="mediahome"]').toggleClass("h-hide-imp",a)}function r(a,c){a=Number(a.data("totalpages"))||Math.max(c,1);b(".media-tab .pagenav-controls-container");q.toggleClass("h-disabled",1>=c);v.toggleClass("h-disabled",
c>=a);m.val(c);p.text(a)}function u(a,c,d){var e=b("#profileMediaDetailContainer");c={nodeid:f.currentNodeId,userid:f.currentUserId,channelid:f.currentChannelid,pageno:1,dateFilter:h.find(".media-filter-overlay input[name=filter_time]:checked").val(),albumid:0};var g=b(".media-tab");a=b.extend({},c,a);if(!isNaN(a.nodeid)){let w;if(0!=a.nodeid){w=-1==a.nodeid?"profile_media_videolist":"profile_textphotodetail";b("body").css("cursor","wait");0==e.closest(".media-tab").length&&g.append(f.profileMediaDetailContainer);
b("#profileMediaContainer").closest(".tab").find("li.list-item-gallery").remove();var l=a.pageno;c={nodeid:a.nodeid,userid:a.userid,channelid:a.channelid,pageno:l,albumid:a.albumid,isAjaxTemplateRenderWithData:!0};a.dateFilter&&(c.dateFilter=a.dateFilter);a.perpage&&(c.perpage=a.perpage);vBulletin.AJAX({call:"/ajax/render/"+w,data:c,success:function(F){f.currentNodeId=a.nodeid;f.currentUserId=a.userid;f.currentGalleryPage=l;e.html(F.template);e.addClass("list-item").attr("data-nodeid",a.nodeid);b(".profile-media-uploadphotos",
e).on("click",G);x(!0);a.perpage&&(g.data("perpage",a.perpage),g.data("callbacks",d));vBulletin.initFlexGridFixLastRowAll();-1==a.nodeid?r(b(".media-video-list",e),l):r(b(".js-album-detail",e),l);b(".profile-toolbar .media-toolbar-filter").removeClass("h-hide");d&&"function"==typeof d.success&&d.success()},after_error:function(){d&&"function"==typeof d.error&&d.error()},complete:function(){b("body").css("cursor","auto");d&&"function"==typeof d.complete&&d.complete()},title_phrase:"profile_media"})}}}
function G(a){b(document).data("gallery-container",b(this).closest(".js-album-detail"));var c=vBulletin.upload.getUploadedPhotosDlg(!1);(a=c.data("nodeid"))&&!isNaN(parseInt(a))&&vBulletin.AJAX({call:"/ajax/render/media_addphotos",data:{nodeid:a,isAjaxTemplateRenderWithData:!0},success:function(d){c.html(d.template);vBulletin.upload.initializePhotoUpload(c.parent());d=c.find(".js-save-button");d.off("click").on("click",H);c.find(".js-cancel-button").off("click").on("click",function(e){c.dialog("close")});
vBulletin.upload.relocateLastInRowClass(c.find(".photo-item-wrapper"));0<b(".photo-display .photo-item-wrapper:not(.h-hide)",c).length?(vBulletin.upload.setUploadButtonText(c,"upload_more"),d.show()):d.hide();c.dialog("open");vBulletin.upload.adjustPhotoDialogForScrollbar(c)},after_error:function(){c.dialog("close")},title_phrase:"profile_media"})}function I(a){a=C(b(this));a.pageno=1;a.perpage=vBulletin.media.calculatePhotosPerPage(vBulletin.media.TARGET_PHOTOS_PERPAGE);f.currentFilter=a;u(a)}function H(a){var c=
b(a.target).closest(".profile-media-photoupload-dialog"),d=b(a.target).closest("form");if(0<d.length){b(a.target).closest(".photo-display-container").find(".photo-item-wrapper:not(.h-hide)").each(function(g,l){g=parseInt(b(l).find(".filedataid").val(),10);isNaN(g)||(d.append('<input type="hidden" name="filedataid[]" value="'+g+'"/>'),b('<input type="hidden" name="title_'+g+'" />').val(b(l).find("textarea").val()).appendTo(d))});var e=b("button",d).prop("disabled",!0);vBulletin.AJAX({url:d.attr("action"),
data:d.serializeArray(),success:function(){c.dialog("close");n(f.currentMediaPage)},complete:function(){e.prop("disabled",!1)},title_phrase:"profile_media"})}else c.dialog("close")}function C(a){var c;b("#profileMediaContainer").is(":visible")?c=b("#profileMediaContainer"):b("#profileMediaDetailContainer").is(":visible")&&(c=b("#profileMediaDetailContainer"));a={nodeid:parseInt(a.data("nodeid"),10)||parseInt(c.attr("data-nodeid"),10),userid:parseInt(c.data("userid"),10),channelid:parseInt(c.data("channelid"),
10),albumid:parseInt(a.data("albumid"),10)};isNaN(a.channelid)&&(a.channelid=0);isNaN(a.nodeid)&&(a.nodeid=0);0<a.nodeid?a.userid=0:isNaN(a.userid)&&(a.userid=0);isNaN(a.albumid)&&(a.albumid=0);return a}function J(){var a=b("#profileMediaDetailContainer");let c=parseInt(a.data("channelid"),10),d=parseInt(a.data("nodeid"),10),e=a.find(".js-album-detail");a=parseInt(a.find(".albumSlideShowPageNo").val()||1,10);c&&d&&(f.currentNodeId=d,f.currentChannelid=c,r(e,a),D=!0)}if(!vBulletin.pageHasSelectors(["#media-tab",
".album-widget"]))return!1;var h=b("#media-tab"),m,p,q,v,t,k,z,f={mediaTypeFilter:!1,currentMediaPage:1,currentGalleryPage:1,currentNodeId:0,currentUserId:0,currentChannelid:0,profileMediaDetailContainer:!1},D=!1;b(document).on("vb-instrument",a=>{A(b(a.target))});A(h);f.currentMediaPage=Number(m.val())||1;vBulletin.media.calculatePhotosPerPage=function(a){a=a||50;if(D)return a;var c=b("#profileMediaDetailContainer").is(":visible");c||b("#profileMediaDetailContainer").removeClass("h-hide");var d=
Math.floor(b("#profileMediaDetailContainer").width()/128);c||b("#profileMediaDetailContainer").addClass("h-hide");return 0==a%d||a<=d?a:a-a%d};vBulletin.media.setHistoryStateChange=function(){t="1"==h.find(".conversation-toolbar-wrapper").data("allow-history");k=new vBulletin.history.instance(t);k.isEnabled()&&k.setStateChange(function(a){var c=k.getState();if("media_filter"==c.data.from){k.log(c.data,c.title,c.url);a=h.closest(".ui-tabs");var d=a.find(".ui-tabs-nav > li").filter('li:has(a[href*="#{0}"])'.format(h.attr("id")));
d.hasClass("ui-tabs-active")?n(c.data.page):(c=d.index(),vBulletin.selectTabByIndex.call(a,c))}},"media_filter")};b(function(){b(document).off("click","#mediaList .albumLink").on("click","#mediaList .albumLink",I);var a=!1;h.off("click",".profile-media-createvideo, .profile-media-upload").on("click",".profile-media-createvideo, .profile-media-upload",function(c){var d=b(this).hasClass("profile-media-upload")?"gallery":"video";a||(a=b(c.target).closest(".ui-widget-content").find(".profileMediaEditContainer").dialog({modal:!0,
autoOpen:!1,width:800,title:vBulletin.phrase.get("profile_media"),resizable:!1,closeOnEscape:!1,showCloseButton:!1,dialogClass:"dialog-container dialog-box edit-media-upload-dialog js-profile-media",close:function(){b(document).data("gallery-container",null)}}),vBulletin.ckeditor.initEditor(a.find(".js-ckeditor-init-on-focus")),vBulletin.upload.initializePhotoUpload(a));a.off("dialogopen").on("dialogopen",function(e,g){a.find('.b-toolbar__item[data-panel="b-content-entry-panel__content--{0}"]:not(.b-toolbar__item--active)'.format(d)).trigger("click");
vBulletin.ckeditor.initEditorComponents(a);b(document).data("gallery-container",b(this).find(".b-content-entry-panel__content--"+d))}).dialog("open")});h.off("click",".profile-media-backbtn").on("click",".profile-media-backbtn",function(c){b(".profile-toolbar .media-toolbar-filter").addClass("h-hide");x(!1);b(this).closest(".conversation-toolbar-wrapper").find(".filtered-by").addClass("h-hide").find(".filter-text-wrapper").empty();r(b("#mediaList"),f.currentMediaPage)});h.offon("change","#mediaCurrentPage",
B);h.offon("click","#mediaPreviousPage, #mediaNextPage",B);f.profileMediaDetailContainer=b("#profileMediaDetailContainer").clone();b(document).off("afterSave",".js-album-detail .js-post__content-wrapper .js-content-entry form").on("afterSave",".js-album-detail .js-post__content-wrapper .js-content-entry form",function(c,d){u(f.currentFilter);return!1});b(document).off("afterCancel",".js-album-detail .js-post__content-wrapper .js-content-entry form").on("afterCancel",".js-album-detail .js-post__content-wrapper .js-content-entry form",
function(c){b(c.currentTarget).closest(".js-album-detail").find(".conversation-body, .profile-media-uploadphotos, .js-photo-preview").removeClass("h-hide-imp");return!0});b(document).off("afterSave",".js-profile-media .js-content-entry form").on("afterSave",".js-profile-media  .js-content-entry form",function(c,d){if("b-content-entry-panel__content--gallery"==b(".b-toolbar__item--active",this).data("panel")){c=b("#mediaList");var e=Number(c.data("totalpages"));c=0==Number(c.data("totalcount"))%vBulletin.media.ALBUMS_PERPAGE?
e+1:e;d.alert&&vBulletin.alert("media",d.alert,"alert");n(c)}else n(1);return!1});h.length&&(vBulletin.media.setHistoryStateChange(),z=h.closest(".canvas-widget").find(".js-module-top-anchor").attr("id"),h.offon("click",".media-toolbar-filter",function(c){let d=b(".filter-wrapper",this);d.toggleClass("selected");d.attr("aria-expanded",d.is(".selected"));b(".js-expanded-indicator",this).toggleClass("fa-caret-down fa-caret-up");b(c.target).closest(".conversation-toolbar-wrapper").find(".toolbar-filter-overlay").slideToggle("slow",
function(){if(b(this).is(":visible")){b("body").off("click.media_filter").on("click.media_filter",function(g){0==b(g.target).closest(".toolbar-filter-overlay").length&&0==b(g.target).closest(".toolbar-filter").length&&(b("body").off("click.media_filter"),b(".media-toolbar-filter").trigger("click"))});var e={};vBulletin.isScrolledIntoView(this,e)||b("html,body").animate({scrollTop:"+="+Math.abs(e.bottom)},"fast")}else b("body").off("click.media_filter")})}),b("form.media-filter-overlay",h).trigger("reset"),
h.offon("change",".media-filter-overlay input[type=radio]",function(c,d){if(!k.isEnabled()&&t){var e=vBulletin.makePaginatedUrl(location.href,1);location.href=vBulletin.makeFilterUrl(e,this.name,this.value,g,z);return!0}c=C(b(c.target));var g=b(".media-tab");g.data("perpage")&&(c.perpage=g.data("perpage"));u(c,!0,g.data("callbacks"));b(this).data("bypass-filter-display")||vBulletin.conversation.displaySelectedFilterText(this,this.value);if(k.isEnabled()&&!d){e=vBulletin.getSelectedFilters(b("form.toolbar-filter-overlay",
g));d=this.name;c=this.value;var l=b(".conversation-toolbar-wrapper .filtered-by",g),w={from:"filter",page:1,tab:g.data("url-path")?g.data("url-path"):"#"+g.attr("id"),filters:e,filtervalue:c,filtername:d};l.data("reset")?e=location.pathname.replace(/\/page[0-9]+/,""):(e=vBulletin.makePaginatedUrl(location.href,1),e=vBulletin.makeFilterUrl(e,d,c,g));k.pushState(w,document.title,e);l.data("reset",null)}}),h.offon("click",".filtered-by .js-remove-filter",function(c){c=b(this).closest(".filtered-by");
var d=b(this).closest(".filter-text"),e=d.data("filter-name");if(!k.isEnabled()&&t)return location.href=vBulletin.makeFilterUrl(location.href,e,d.data("filter-value"),h,z),!1;$defaultSelectedFilter=b(".toolbar-filter-overlay .filter-options input[name={0}]".format(e),h).prop("checked",!1).filter(".js-default-checked");d.remove();d=c.find(".filter-text").length;0==d?(c.addClass("h-hide"),c.data("reset",!0)):1==d&&c.find(".clear-all").addClass("h-hide");1==$defaultSelectedFilter.length&&($defaultSelectedFilter.data("bypass-filter-display",
!0),$defaultSelectedFilter.trigger("click"),$defaultSelectedFilter.data("bypass-filter-display",null))}),b("#profileMediaContainer").length||J());vBulletin.initFlexGridFixLastRowAll()});return{loadGalleryById:u}}(jQuery));
