/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
(function(f){function q(a){a=f(".pagenav-form");var b=a.get(0),c=f(this).data("page");a.find(".js-pagenum").val(c);g.call(b,c);return!1}function h(a,b){b=b.find(".js-toolbar-pagenav");b.find(".js-pagenum").val(a);b.find(".left-arrow, .right-arrow").removeClass("h-disabled");1>=a&&b.find(".left-arrow").addClass("h-disabled");var c=b.find(".pagetotal").text();a>=c&&b.find(".right-arrow").addClass("h-disabled")}function n(a,b,c){c.find(".js-sort-by").removeClass("selected").find(".js-sort-arrow").removeClass("fa-caret-up fa-caret-down").addClass("h-hide-imp").end().filter("[data-sortby={0}]".format(a)).addClass("selected").find(".js-sort-arrow").addClass("fa-caret-{0}".format("asc"==
b?"up":"down")).removeClass("h-hide-imp");a=c.find(".js-memberlist-sortby-option").closest(".b-comp-menu-dropdown__content-item").removeClass("b-comp-menu-dropdown__content-item--current").end().filter("[data-sortby={0}][data-sortorder={1}]".format(a,b)).closest(".b-comp-menu-dropdown__content-item").addClass("b-comp-menu-dropdown__content-item--current");a.closest(".js-comp-menu-dropdown").find(".js-comp-menu-dropdown__trigger-text").text(a.text())}function k(a,b){a=a.toLowerCase();var c=b.find(".js-memberlist__letterfilter .letter");
c.removeClass("selected");b.find(".js-drop-down-startswith").val("").filter(".selectBox").selectBox("value","");if(""!==a){var d=a;"#"==a&&(d="numbers");c.filter(".js-letter-"+d).addClass("selected");b.find(".js-drop-down-startswith").val(d).filter(".selectBox").selectBox("value",d);b.find(".js-memberlist__usernamesearch").val("")}}function g(a){var b=f(this),c=b.closest(".js-memberlist-widget"),d={};d.perpage=c.find(".js-per-page").data("perpage");b.hasClass("pagenav-form")||(a=c.find(".toolbar-pagenav .js-pagenum").val());
d.pagenumber=a;a=e=>e.is(".js-letter-all")?"":e.html()||"";b.hasClass("js-drop-down-startswith")?(delete d.pagenumber,a=c.find(".js-drop-down-startswith").val(),k(a,c),h(1,c)):b.hasClass("letter")?(delete d.pagenumber,a=a(b),k(a,c),h(1,c)):a=a(c.find(".js-memberlist__letterfilter .js-letter.selected"));a&&(a=a.toLowerCase(),"all"===a&&(a=""),"numbers"===a&&(a="#"),a.length&&(d.startswith=a));b.is(".js-memberlist__usernamesearch")?(delete d.pagenumber,d.startswith&&delete d.startswith,a=b.val(),""!==
a?(d.username=a,k("",c)):k("all",c),c.find(".js-memberlist__usernamesearch").val(a),h(1,c)):(a=c.find(".js-memberlist__usernamesearch").val(),""!==a&&(d.username=a));if(b.hasClass("js-memberlist-sortby-option"))delete d.pagenumber,a=b.data("sortby"),b=b.data("sortorder"),n(a,b,c),h(1,c);else if(b.hasClass("js-sort-label")){delete d.pagenumber;var l=b.parents(".js-sort-by");a=l.data("sortby");b=l.data("sortorder");l.hasClass("selected")&&(b="asc"==b?"desc":"asc",l.data("sortorder",b));n(a,b,c);h(1,
c)}else b=c.find(".js-sort-by.selected"),a=b.data("sortby"),b=b.data("sortorder");d.sortfield=a;d.sortorder=b;b=c.find(".js-memberlist-route-info").data("routeinfojson");vBulletin.AJAX({call:"/ajax/render/memberlist_items",data:{criteria:d,routeInfoJson:b},success:function(e){c.find(".js-memberlist-table-body").replaceWith(e);e=c.find(".js-memberlist-table-body");var p=e.data("totalPages"),r=e.find(".js-pagenav-current-button").data("page")||1,m=c.find(".js-toolbar-pagenav"),t=m.find(".js-pagenum").val(),
u=m.find(".right-arrow");m.find(".pagetotal").text(p);u.addClass("h-disabled");t<p&&m.find(".right-arrow").removeClass("h-disabled");h(r,c);e=e.find(".js-pagenav").clone();c.find(".js-under-toolbar-pagenav .js-pagenav").replaceWith(e);vBulletin.Responsive.Debounce.checkShrinkEvent(f(".js-pagenav"))}});return!1}f(function(){vBulletin.pagination({context:".memberlist-widget .conversation-toolbar",onPageChanged:g});var a=f(".js-drop-down-startswith");if(a.is(":visible"))a.selectBox().change(g);else{var b=
a.closest(".h-hide-on-large");b.removeClass("h-hide-on-large");a.selectBox().change(g);b.addClass("h-hide-on-large")}a=f(".memberlist-widget");a.offon("click.memberlist",".js-memberlist__letterfilter .letter",g);a.offon("click.memberlist",".js-sort-label",g);a.offon("click.memberlist",".js-memberlist-sortby-option",g);a.offon("click.memberlist",".js-pagenav .js-pagenav-button",q);f(".js-memberlist__usernamesearch").offon("keyup.memberlist",f.debounce(400,g))})})(jQuery);
