/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache("add_folder are_you_sure_move_to_trash are_you_sure_permanently_delete_messages delete_folder edit_folder error error_deleting_folder error_editing_folder error_x folder_name follow_request_denied invalid_node_id messages_updated_desc need_folder_name no_moderate_permissions no_publish_permissions page_does_not_exist pending_posts delete_pending_posts please_enter_a_valid_page_number please_select_messages pm_ajax_error_desc selected_folder_and_contents_will_be_deleted sent_follow_request private_messages mark_message_status_text_for_move mark_messages_status_text_for_move mark_message_status_text_for_delete mark_messages_status_text_for_delete mark_message_status_text_for_read mark_messages_status_text_for_read mark_message_status_text_for_unread mark_messages_status_text_for_unread mark_message_status_text_generic mark_messages_status_text_generic mark_report_status_text_for_delete mark_reports_status_text_for_delete mark_report_status_text_for_open mark_reports_status_text_for_open mark_report_status_text_for_closed mark_reports_status_text_for_closed mark_report_status_text_generic mark_reports_status_text_generic messages_header move following following_pending follow members_in_this_message cancel need_privatemessage_text invalid_pm_recipients".split(" "),
[]);var $pmWidget;vBulletin.ensureObj("privateMessage");
(function(a){function e(f){a.each(["readFilter","sortDir","typename"],function(m,r){m="filter_"+r;f.hasOwnProperty(m)&&(f[r]=f[m],delete f[m])});f.hasOwnProperty("readFilter")||(f.readFilter="unread_only");f.hasOwnProperty("sortDir")||(f.sortDir="DESC");f.hasOwnProperty("typename")||(f.typename="");a("#notificationFilters").find("input:radio").each(function(m,r){m=a(this);r=m.attr("name");f.hasOwnProperty(r)&&f[r]==m.val()&&m.prop("checked",!0)})}function g(f){a(this).closest(".filter-options").find(":input[type=radio]").removeAttr("checked");
a(this).prop("checked",!0);l(1)}function l(f,m){f=f||1;m=m||!1;var r=getNotificationsFilterParams();r.page=f;vBulletin.AJAX({call:"/ajax/render/privatemessage_notificationcontent",data:{params:r,isAjaxTemplateRenderWithData:!0},success:function(p){a("#notificationContent").html(p.template);pmPageNum=f;a("#notificationPageto").val(pmPageNum);a("#iconNotificationNext").toggleClass("h-disabled",f>=pmPages);a("#iconNotificationPrevious").toggleClass("h-disabled",1>=f);t.isEnabled()&&!m&&(p=n(pmPageNum),
t.pushState({notificationFilterParams:r},document.title,p.url));p={folderid,page:pmPageNum,perpage:pmPerPage,about:"",filterParams:r};vBulletin.privateMessage.updatePaginationLinks(a("#notificationContent").parent(),a("#notificationPageto").val());vBulletin.AJAX({call:"/ajax/api/content_privatemessage/getFolderMsgCount",data:p,success:function(q){if(q&&0<q.pages){if(t.isEnabled()&&!m&&pmPageNum!=q.pagenum){var A=n(q.pagenum);t.setDefaultState({notificationFilterParams:r},document.title,A.url)}pmPageNum=
q.pagenum;pmPages=q.pages;pmNotificationCount=q.count;a("#notificationPageCount").html(pmPages);a("#maxPageNum").val(pmPages);a("#iconNotificationNext").toggleClass("h-disabled",!(1<pmPages));a("#privatemessagePaging").toggleClass("h-hide",1>=pmPages);a("#notificationPageto").val(pmPageNum);a("#iconNotificationPrevious").toggleClass("h-disabled",1>=pmPageNum);a("#iconNotificationNext").toggleClass("h-disabled",pmPageNum>=pmPages);vBulletin.privateMessage.updatePaginationLinks(a("#notificationContent").parent(),
pmPageNum,pmPages)}}})}})}function n(f,m){var r={},p="",q={};"undefined"==typeof m&&(m=window.location.href);p=m;q=vBulletin.parseUrl(m);if(1<q.search.length){m=q.search.substr(1).split("&");for(p=0;p<m.length;p++){var A=m[p].split("=");1<A.length&&(r[A[0]]=A[1])}p=window.location.protocol+"//"+q.hostname;p=0<q.port.length?p+(":"+q.port+q.pathname):p+q.pathname}p=p.replace(/\/(\d+)\/?$/,"/"+f);if(a("#notificationFilters").length){var y=getNotificationsFilterParams();a.each(["readFilter","sortDir",
"typename"],function(H,w){y.hasOwnProperty(w)&&(r["filter_"+w]=y[w])})}r=vBulletin.privateMessage.getPageFiltersForUrl(r);queryString="?"+a.param(r);return{newHrefBase:p,queryString,hash:q.hash,url:p+queryString+q.hash}}function v(f){f=f.target.id.substring(15);f=parseInt(f);isNaN(f)||vBulletin.AJAX({call:"/ajax/render/privatemessage_participants",data:{nodeid:f,showFollowButtons:"undefined"!=typeof messageDetailPage&&messageDetailPage?0:1,isAjaxTemplateRenderWithData:!0},success:function(m){a("#pmInfoContent").html(m.template);
a(".pmBtnFollowRequest").off("click").on("click",sendFollowRequest);a("#pmInfoDialog").dialog({title:vBulletin.phrase.get("members_in_this_message"),autoOpen:!1,modal:!0,resizable:!1,closeOnEscape:!0,showCloseButton:!0,width:500,dialogClass:"dialog-container member-list-dialog-container dialog-box"}).dialog("open")},error_phrase:"pm_ajax_error_desc"})}var t=vBulletin.history.instance(!0),C=getNotificationsFilterParams(),J={};0<Object.keys(C).length&&(J.notificationFilterParams=C);t.setDefaultState(J,
document.title,window.location.href);t.setStateChange(function(f){f=t.getState();f.data.hasOwnProperty("notificationFilterParams")&&(f=f.data.notificationFilterParams,e(f),l(f.page,!0))},"privatemessage");vBulletin.privateMessage.pmFilterHistory=t;vBulletin.privateMessage.updatePaginationLinks=function(f,m,r){f=f.find(".js-pagenav");if(0<f.length){var p=f.find(".js-pagenav-button:not(.js-pagenav-button--template)"),q=f.find(".js-pagenav-next-button"),A=f.find(".js-pagenav-prev-button"),y=f.find(".js-pagenav-button--template"),
H=/\/(\d+)\/?$/;var w=m-2;var F=a("#maxPageNum").val();""==y.attr("href")&&""!=f.data("baseurl")&&y.attr("href",f.data("baseurl"));var D=y.attr("href");D=n(m,D);y.attr("href",D.newHrefBase);D=D.queryString;1>w&&(w=1);var x=w+4;x>F&&(x=F);p.not(".js-pagenav-next-button, .js-pagenav-prev-button").remove();for(p=w;p<=x;p++)w=y.attr("href").replace(H,"/"+p)+D,w=y.clone().removeClass("js-pagenav-button--template h-hide-imp").attr("data-page",p).text(p).attr("href",w),p==m&&w.removeClass("b-button--secondary").addClass("b-button--primary"),
w.insertBefore(q),a(document.createTextNode("\n")).insertBefore(q);x=parseInt(m,10)-1;x=1<x?x:1;A.data("page",x);w=y.attr("href").replace(H,"/"+x)+D;A.attr("href",w);x=parseInt(m,10)+1;x=x<=F?x:F;q.data("page",x);w=y.attr("href").replace(H,"/"+x)+D;q.attr("href",w);A.add(q).removeClass("h-hide h-hide-imp");1==m&&A.addClass("h-hide-imp");m==F&&q.addClass("h-hide-imp");"undefined"!=typeof r&&(m=1<r,f.closest(".pagenav-container").toggleClass("h-hide",!m),f.closest(".js-pagenav-wrapper").toggleClass("h-hide",
!m))}};vBulletin.privateMessage.getPageFiltersForUrl=function(f){return f};vBulletin.privateMessage.getPrivateMessageUrl=n;a(function(){function f(b,c){var d=!1,k=b.find(".edit-folder-box").val().toLowerCase(),h=a(".folder-list.custom-folder-list"),u;h.find(".folder-item",c).each(function(){u=a(this);if(k<u.find(".label").text().toLowerCase())return u.before(b),d=!0,!1});d||h.append(b)}function m(b,c){var d=!1,k=a("folder_"+b),h;c=vBulletin.htmlEntities(c);k.length?(k.find("span").html(c),k.parent().detach()):
k=a('<li class="pmMoveToFolder" id="folder_'+b+'"><span>'+c+"</span></li>");c=c.toLowerCase();a("#pmMoveToFolder li.pmMoveToFolder").each(function(u){h=a(this);if(0<u&&c<h.html().trim().toLowerCase())return h.before(k),d=!0,!1});!d&&h&&h.after(k)}function r(b){if(b){var c="data-href";var d="href"}else c="href",d="data-href";a(".folder-list .folder-item a",$pmWidget).each(function(){var k=a(this),h={};h[c]=k.attr(d);k.attr(h).removeAttr(d)})}function p(b){return q(b.postId,b.postContentTypeId,b.currentPosition,
b.maxPosition,b.userId,b.postType)}function q(b,c,d,k,h,u){var z={nodeid:b,contenttypeid:c,currentPosition:d,maxPosition:k};a.each(z,function(B,G){z[B]=parseInt(G,10)});h=parseInt(h,10);if(a.map(z,isNaN).some(Boolean)||isNaN(h))return!1;z.postType=u;z.isAjaxTemplateRenderWithData=!0;vBulletin.AJAX({call:"/ajax/render/privatemessage_pendingpost_overlay",type:"POST",data:z,success:function(B){a(".pending-post-overlay").html(B.template).dialog({title:vBulletin.phrase.get("pending_posts"),modal:!0,resizable:!1,
closeOnEscape:!1,showCloseButton:!1,width:700,dialogClass:"dialog-container pending-post-overlay-container dialog-box"}).dialog("open");var G=a(".pending-post-overlay-container");B=G.find(".ui-dialog-titlebar");B.find(".nav-buttons").remove();G=G.find(".pending-post-overlay .nav-buttons").detach();B.append(G);a(".pending-post-overlay .list-item").data("user-id",h).data("post-type",u).prepend(a(".pending-posts-container .list-container .list-item[data-node-id={0}] .list-item-header".format(z.nodeid)).clone());
vBulletin.ckeditor.initEditor("ckeditor-bare",{success:function(L,I){I||(I=vBulletin.ckeditor.getEditor(L));I.setData(a(".pending-post-overlay .list-item .ckeditor-bare-box").html())}})},error_phrase:"unable_to_contact_server_please_try_again"})}function A(b,c){var d=parseInt(b.data("nodeId"),10),k=parseInt(b.data("userId"),10);b=b.data("postType");c=parseInt(c,10);if(isNaN(d)||isNaN(c))return!1;var h=-1,u=0;a(".conversation-list .list-item",$pmWidget).filter(function(B){u++;if(a(this).attr("data-node-id")==
d)return h=B,!0});if(-1==h)return!1;h+=c;b=a(".conversation-list .list-item",$pmWidget).filter(function(B){if(h==B)return!0});if(0<b.length){c=parseInt(b.attr("data-node-id"),10);var z=parseInt(b.attr("data-node-contenttype-id"));k=b.data("userId");b=b.data("postType");h++;return{postId:c,postContentTypeId:z,currentPosition:h,maxPosition:u,userId:k,postType:b}}return!1}function y(b,c,d,k){if(!b&&(b=a("#private-message-toolbar .pending-posts-paginator .pendingpostsPageTo"),0==b.length))return!1;var h=
b.closest(".pending-posts-paginator"),u=h.find("#maxPageNum").filter("input[type=hidden]"),z=h.find("input[name=pagenum]"),B=u.val();b=parseInt(z.val(),10);var G=parseInt(h.find("input[name=per-page]").val(),10),L=h.find("input[name=routeInfoJson]").val();"current"==c&&(c=b);c=parseInt(c,10);if(isNaN(c)||isNaN(B)||isNaN(b))return!1;if(1>c||c>B)return vBulletin.error("error","please_enter_a_valid_page_number"),!1;if(c==b&&!k)return!1;var I={setCurrentPage:c,setPerPage:G,options:{},routeInfoJson:L,
isAjaxTemplateRenderWithData:!0};a("#pendingFilters input:checked").each(function(){I.options[this.name]=this.value});vBulletin.AJAX({call:"/ajax/render/privatemessage_pendingpost_main",data:I,success:function(E){a("#privateMessageContainer .main-pane .pending-posts-container").html(E.template);E=c-1;var M=0;c<B&&(M=c+1);z.val(c);h.find("input[name=next-page]").val(M);h.find("input[name=prev-page]").val(E);h.find(".pendingpostsNext").toggleClass("h-disabled",!M);h.find(".pendingpostsPrev").toggleClass("h-disabled",
!E);h.find(".pendingpostsPageTo").val(c);d&&(E=a("#privateMessageContainer .main-pane .pending-posts-container .pending-posts-pageinfo"),E=parseInt(E.find(".totalpages").val(),10),u.val(E),h.find("div.pendingpostsPageCount").text(E),a(".folder-list .folder-item.pending-posts .count",$pmWidget).text(E))},error_phrase:"unable_to_contact_server_please_try_again"})}function H(b){var c;a(".pending-post-overlay:visible").length&&((c=A(b,1))||(c=A(b,-1)));c?p(c):a(".pending-post-close").trigger("click")}
function w(b){a(b).each(function(){a(".pending-posts-container .list-container .list-item[data-node-id={0}]".format(this)).remove()})}function F(b,c){b=b.closest(".pending-post-overlay-container").find(".pending-post-overlay li.list-item");c=A(b,c);!1!==c&&(a("pending-post-overlay").dialog("close"),vBulletin.ckeditor.destroyEditor("ckeditor-bare"),p(c))}$pmWidget=a(".private-message-widget");var D=a(".js-pm-content-entry-container"),x=a(".js-editor",D);a(document).off("focus",".js-editor.js-focus-on-page-load").on("focus",
".ckeditor-bare-box.ckeditor-load-on-focus",function(){vBulletin.ckeditor.initEditor(a(this).attr("id"),{error:function(b){a("#"+b).prop("disabled",!1).removeClass("ckeditor-load-on-focus").closest(".js-pm-content-entry-container").addClass("no-ckeditor")}})});0<x.length&&(D.hasClass("msg-type-new")||D.hasClass("msg-type-forward"))&&vBulletin.ckeditor.initEditor(x.attr("id"),{success:function(b){b=x.prev(".js-editor-parsed-text");0<b.length&&this.setData(b.html());setTimeout(function(){a(".autocompleteHelper",
D)[0].focus()},200)},error:function(b){a("#"+b).prop("disabled",!1).removeClass("ckeditor-load-on-focus").closest(".js-pm-content-entry-container").addClass("no-ckeditor")}});a(".folder-list.custom-folder-list form",$pmWidget).trigger("reset");$pmWidget.off("click",".folder-item.custom-folder .edit-icon-wrapper").on("click",".folder-item.custom-folder .edit-icon-wrapper",function(b){b.stopPropagation();b=a(this).closest(".custom-folder").addClass("edit-folder-mode").find(".edit-folder-box").trigger("select").trigger("focus");
b.val(vBulletin.htmlEntities_decode(b.val()));b.data({origFolderName:b.val(),updateFlag:!0});r(!0);return!1});var N;$pmWidget.off("keydown blur",".folder-item.custom-folder .edit-folder-box").on("keydown",".folder-item.custom-folder .edit-folder-box",function(b){var c=a(this),d=!1;switch(b.which){case 27:c.data("updateFlag",!1);c.closest(".custom-folder").removeClass("edit-folder-mode");r(!1);c.val(c.data("origFolderName"));d=!0;break;case 13:c.data("updateFlag",!0),c.trigger("blur",[!0]),d=!0}return!d}).on("blur",
".folder-item.custom-folder .edit-folder-box",function(b,c){var d=a(this);b=function(){if(!d.data("updateFlag"))return!1;d.data("updateFlag",!1);if(!isFolderNameValid(d,"edit_folder"))return d.data("updateFlag",!0),!1;r(!1);var k=d.closest(".custom-folder"),h=d.val().trim(),u=d.data("origFolderName");h!=u?vBulletin.AJAX({call:"/ajax/api/content_privatemessage/updateFolderTitle",data:{folderName:h,folderid:d.data("nodeId")},success:function(z){k.find(".label").text(h);f(k.detach(),$pmWidget);m(folderid,
h)},title_phrase:"edit_folder",error_phrase:"error_editing_folder",complete:function(){k.removeClass("edit-folder-mode")},after_error:function(){d.val(u)}}):k.removeClass("edit-folder-mode")};c?b():N=setTimeout(b,200)});$pmWidget.offon("click",".folder-item.custom-folder .js-delete-icon",function(b,c){clearTimeout(N);b.stopPropagation();var d=a(this),k=d.prev(".edit-folder-box");if(!c)return openConfirmDialog({title:vBulletin.phrase.get("delete_folder"),message:vBulletin.phrase.get("selected_folder_and_contents_will_be_deleted"),
iconType:"warning",onClickYes:function(){d.trigger("click",[!0])},onClickNo:function(){k.trigger("select").trigger("focus")}}),!1;vBulletin.AJAX({call:"/ajax/api/content_privatemessage/deleteFolder",data:{folderid:k.attr("data-node-id")},success:function(h){r(!1);h=d.closest(".custom-folder");var u=h.find("a").hasClass("selected");h.remove();u&&(location.href=a(".nav-pane .folder-list .folder-item.messages a",$pmWidget).attr("href"))},title_phrase:"delete_folder",error_phrase:"error_deleting_folder"})});
$pmWidget.off("click",".folder-list .folder-item > a[href]").on("click",".folder-list .folder-item > a[href]",function(b){b=a(".folder-list .custom-folder.edit-folder-mode",$pmWidget);if(0<b.length)return b.trigger("blur",[!0]),!1;b=a(this);var c=b.parent();if(c.hasClass("edit-folder-mode")||!c.hasClass("special-folder")&&b.hasClass("selected"))return!1;c.hasClass("add-folder")||(a(".folder-list .folder-item > a.selected",$pmWidget).removeClass("selected"),b.addClass("selected"));return!0});$pmWidget.off("click",
".folder-list .folder-item.add-folder > a[href]").on("click",".folder-list .folder-item.add-folder > a[href]",function(b){createNewFolder.apply(this,[b,function(c,d){var k=a(".folder-item.custom-folder.template",$pmWidget).clone(!0).removeClass("h-hide template"),h=k.find("a");k.find(".label").text(d);h.attr("href",h.attr("href").replace(/\/list\/0\//i,"/list/"+c+"/"));k.find(".edit-folder-box").attr("data-node-id",c).val(d);f(k,$pmWidget);m(c,d)},function(){a(this).removeClass("selected")}]);return!1});
a("#pmBtnMarkRead").off("click").on("click",function(){markMessages(a(this).text(),"setRead","read",1,!1)});a("#pmBtnMarkUnRead").off("click").on("click",function(){markMessages(a(this).text(),"setRead","read",0,!1)});a("#pmBtnDelete").off("click").on("click",function(b){var c="undefined"!=typeof messageDetailPage&&messageDetailPage,d=getSelectedMessages(),k=a(this).text();0<d.length&&openConfirmDialog({title:vBulletin.phrase.get("messages_header"),message:vBulletin.phrase.get("are_you_sure_move_to_trash"),
iconType:"warning",onClickYes:function(){markMessages(k,"toTrashcan",!1,!1,c,d)}})});a(".pmBtnDeletePermanently").off("click").on("click",function(b){var c=getSelectedMessages(),d=a(this).text();0<c.length&&openConfirmDialog({title:vBulletin.phrase.get("messages_header"),message:vBulletin.phrase.get("are_you_sure_permanently_delete_messages"),iconType:"warning",onClickYes:function(){markMessages(d,"deleteMessages",!1,!1,!1,c)}})});a(".pmBtnUndelete").offon("click",function(b){markMessages(a(this).text(),
"undeleteMessage",!1,!1,!1)});a("#reportBtnMarkOpen").offon("click",function(b){markReports(a(this).text(),"openClose","op","open")});a("#reportBtnMarkClosed").offon("click",function(b){markReports(a(this).text(),"openClose","op","closed")});a("#reportBtnDelete").offon("click",function(b){markReports(a(this).text(),"bulkdelete",!1,!1)});a(".js-move-pm").offon("click",function(b){b=parseInt(this.id.substr(7),10);var c="undefined"!=typeof messageDetailPage&&messageDetailPage,d=vBulletin.phrase.get("move");
b&&markMessages(d,"moveMessage","newFolderid",b,c)});a(".js-pm-movenewfolder").offon("click",function(b){var c=getSelectedMessages(),d="undefined"!=typeof messageDetailPage&&messageDetailPage,k=vBulletin.phrase.get("move");0<c.length&&createNewFolder.apply(this,[b,function(h,u){markMessages(k,"moveMessage","newFolderid",h,d)}]);return!1});a("#pmBtnForward").offon("click",startForward);a("#pmInfoClose").offon("click",function(b){a("#pmInfoDialog").dialog("close")});a("#privatemessagePageto, #sentItemsPageTo").on("keydown blur",
gotoPage);a(".pmRequestAccept").offon("click",acceptRequest);a(".pmRequestDeny").offon("click",denyRequest);a("#pmBtnReply").offon("click",function(){var b=a(".js-pm-content-entry-container .js-editor"),c=b.attr("id"),d=vBulletin.ckeditor.editorExists(c)?vBulletin.ckeditor.getEditor(c):null;a("body,html").animate({scrollTop:a(".js-pm-content-entry-container").offset().top},"slow",function(){(d||b[0]||a()).focus()})});a("#pmFloatingBarContent .toolbar-filter").offon("click",function(b){var c=a(this);
b=a(".filter-wrapper",c);b.toggleClass("selected");b.attr("aria-expanded",b.is(".selected"));a(".js-expanded-indicator",c).toggleClass("fa-caret-down fa-caret-up");c.closest(".toolbar-wrapper").find(".toolbar-filter-overlay").slideToggle("slow",function(){if(a(this).is(":visible")){a("body").off("click.pm_filter").on("click.pm_filter",function(k){0==a(k.target).closest(".toolbar-filter-overlay").length&&0==a(k.target).closest(".toolbar-filter").length&&(a("body").off("click.pm_filter"),c.triggerHandler("click"))});
var d={};vBulletin.isScrolledIntoView(this,d)||a("html,body").animate({scrollTop:"+="+Math.abs(d.bottom)},"fast")}else a("body").off("click.pm_filter")})});a(".list-controls .select-all").off("click").on("click",function(b){a(".privateMessageActionCheck").prop("checked",!0)});a(".list-controls .select-none").off("click").on("click",function(b){a(".privateMessageActionCheck").prop("checked",!1)});if("undefined"!=typeof messageDetailPage&&messageDetailPage)a("#pmBtnBackToMessage").off("click").on("click",
function(b){pmParentFolderId?location.href="{0}/messagecenter/list/{1}/1".format(pageData.baseurl,pmParentFolderId):(b=a(".nav-pane .folder-list .folder-item.special-folder.messages a").attr("href"),location.href=b)});a("#notificationFilters").trigger("reset").find(".filter-options input").off("click").on("click",g);a("#pmBtnNotificationDismissAll").offon("click",dismissNotifications);a("#pmBtnNotificationDismissPage").offon("click",dismissNotifications);a("#iconNotificationNext").offon("click",function(b){b.preventDefault();
pmPageNum=parseInt(pmPageNum);pmPageNum<pmPages&&l(pmPageNum+1)});a("#iconNotificationPrevious").offon("click",function(b){b.preventDefault();pmPageNum=parseInt(pmPageNum);1<pmPageNum&&l(pmPageNum-1)});a("#notificationContent").on("click",".js-notification-dismiss",dismissSingleNotification);a("#notificationContent").on("click",".js-notification-others-dialog",toggleOthersDialog);0==a("#notificationContent").length&&(a("ul.pm-notification-list").on("click",".js-notification-dismiss",dismissSingleNotification),
a("ul.pm-notification-list").on("click",".js-notification-others-dialog",toggleOthersDialog));a("#notificationPageto").on("keydown blur",function(b){var c=a(this);return"blur"==b.type||"keydown"==b.type&&13==b.keyCode?(b=Number(c.val()),!isNaN(b)&&b!=pmPageNum&&0<b&&b<=pmPages?l(b):c.val(pmPageNum),!1):!0});searchAuthorAutocomplete=new vBulletin_Autocomplete(a(".privatemessage_author"),{apiClass:"user",delimiter:" ; "});a(document).off("click",".pmNotifDlgLink").on("click",".pmNotifDlgLink",v);a("#pmSearch").submit(function(){var b=
a(this),c=b.find("[name=searchJSON]");b=b.find("[name=q]");var d={};d.keywords=b.val();d.type="vBForum_PrivateMessage";d.ignore_protected=0;c.val(JSON.stringify(d));return 3<b.val().length});var K=!1;a(document).off("click",".view-post").on("click",".view-post",function(){a(this);var b=a(this).closest(".list-item"),c=parseInt(b.data("nodeId"),10),d=parseInt(b.data("nodeContenttypeId"),10),k=parseInt(b.data("userId"),10),h=b.data("postType"),u=a("ul.conversation-list li.list-item",$pmWidget).index(b)+
1;b=b.closest("ul.conversation-list").find("li.list-item").length;K=!1;q(c,d,u,b,k,h)});a(document).off("click",".pending-post-approve").on("click",".pending-post-approve",function(){var b=[],c=a(this),d=c.closest(".pending-post-overlay").find("li.list-item");0==d.length&&(d=c.closest("li.list-item"));if(0!=d.length)b.push(parseInt(d.data("nodeId"),10)),d.data("postType");else if(c.closest("#pmFloatingBarContent").length){if(a(".pending-posts-container .list-item .privateMessageActionCheck:checked").each(function(){d=
a(this).closest("li.list-item");b.push(parseInt(d.data("nodeId"),10))}),0==b.length)return!1}else return!1;c={nodeid:b,approved:1,data:{}};var k=a(".title-field",d),h=a(".text-field",d),u=a(".notes-field",d);k.length&&(c.data.title=k.val());h.length&&(c.data.rawtext=h.val());u.length&&(c.data.reason=u.val());vBulletin.AJAX({call:"/ajax/api/node/setApprovedPost",data:c,error_phrase:"unable_to_contact_server_please_try_again",success:function(z){K=!0;H(d);w(z)}})});a(document).off("click",".pending-post-delete").on("click",
".pending-post-delete",function(){var b=[],c=[];var d=a(this);var k=d.closest(".pending-post-overlay").find("li.list-item");0==k.length&&(k=d.closest("li.list-item"));if(0!=k.length)b.push(parseInt(k.data("nodeId"),10)),d=k.data("postType"),c.push(parseInt(k.data("userId"),10));else if(d.closest("#pmFloatingBarContent").length){a(".pending-posts-container .list-item .privateMessageActionCheck:checked").each(function(){k=a(this).closest("li.list-item");b.push(parseInt(k.data("nodeId"),10));c.push(parseInt(k.data("userId"),
10))});if(0==b.length||0==c.lenght)return!1;d="selected_posts"}else return!1;vBulletin.phrase.get("delete_x",vBulletin.phrase.get("posttype_"+d));vBulletin.inlinemod.delete_dialog(b,function(h){K=!0;H(k);w(h)})});a(document).off("click",".pending-post-next").on("click",".pending-post-next",function(){F(a(this),1)});a(document).off("click",".pending-post-previous").on("click",".pending-post-previous",function(){F(a(this),-1)});a(document).off("click",".pending-post-close").on("click",".pending-post-close",
function(){a(".pending-post-overlay").dialog("close");K&&y(!1,1,!0,!0)});a(document).off("click",".pending-posts-paginator .pendingpostsPrev").on("click",".pending-posts-paginator .pendingpostsPrev",function(b){b.preventDefault();b=a(this).closest(".pending-posts-paginator").find(':input[type=hidden][name="prev-page"]').val();y(a(this),b)});a(document).off("click",".pending-posts-paginator .pendingpostsNext").on("click",".pending-posts-paginator .pendingpostsNext",function(b){b.preventDefault();b=
a(this).closest(".pending-posts-paginator").find(':input[type=hidden][name="next-page"]').val();y(a(this),b)});a(document).off("keypress",".pending-posts-paginator .pendingpostsPageTo").on("keypress",".pending-posts-paginator .pendingpostsPageTo",function(b){if(13==b.keyCode){b.preventDefault();b=a(this);var c=parseInt(b.val(),10);if(isNaN(c))return vBulletin.error("error","please_enter_a_valid_page_number"),!1;y(b,c)}});$pmWidget.filter(".private-message-toolbar").off("click",".message-filters .filter-options :input[type=radio]").on("click",
".message-filters .filter-options :input[type=radio]",function(b){b=a(this).closest("form.toolbar-filter-overlay");b.attr("action",b.attr("action")+"?sortDir="+a(this).val());b.submit()});a("#pendingFilters").trigger("reset").find(".filter-options input").off("click").on("click",function(b){y(!1,"current",!1,!0)});vBulletin.truncatePostContent(a(".pm-message-list"));vBulletin.privateMessage.jsReady=!0;a(document).trigger("vb-privatemessage-js-ready")})})(jQuery);
isFolderNameValid=function(a,e,g){var l,n=$.trim(a.val()).toLowerCase();""==n?l="error_enter_folder":50<n.length?l="error_foldername_maxlength":$(".folder-list.custom-folder-list .folder-item .edit-folder-box",$pmWidget).each(function(){if(a.hasClass("edit-folder-box")&&a.get(0)==this)return!0;if(n==this.value.toLowerCase())return l="error_folder_exists",!1});!0===g?(e=a.closest("#prompt-dialog"),g=e.find("div.error-msg-box"),l?(0==g.length&&(g=$("<div></div>").addClass("error-msg-box error"),$(".dialog-content",
e).before(g)),g.text(vBulletin.phrase.get(l)).removeClass("h-hide")):0!=g.length&&g.addClass("h-hide").text("")):l&&vBulletin.warning(e,l,function(){a.trigger("focus")});return!l};getSelectedMessages=function(a){var e=[];!a&&$("#privateMessageNodeid").val()?e.push($("#privateMessageNodeid").val()):e=$(".privateMessageActionCheck:checked").map(function(){return this.value}).get();0==e.length&&vBulletin.warning("error","please_select_messages");return e};
markMessages=function(a,e,g,l,n,v){v||(v=getSelectedMessages());if(0<v.length){var t={nodeid:v.join(",")};g&&(t[g]=l);vBulletin.AJAX({call:"/ajax/api/content_privatemessage/"+e,data:t,success:function(C){C="mark_message"+(1<v.length?"s":"")+"_status_text_";var J={methodName:"for_move",toTrashcan:"for_delete",setRead:"for_"+(l?"read":"unread"),deleteMessages:"for_delete_permanently"};C=J[e]?C+J[e]:C+"generic";openAlertDialog({title:a,message:vBulletin.phrase.get(C),onAfterClose:function(){if(n)if(pmParentFolderId)location.replace("{0}/messagecenter/list/{1}/1".format(pageData.baseurl,
pmParentFolderId));else{var f=$(".nav-pane .folder-list .folder-item.special-folder.messages a").attr("href");location.replace(f)}else location.reload(!0)}})}})}return!1};
markReports=function(a,e,g,l){var n=getSelectedMessages();if(0<n.length){var v={nodeids:n.join(",")};g&&(v[g]=l);vBulletin.AJAX({call:"/ajax/api/content_report/"+e,data:v,success:function(){var t="mark_report"+(1<n.length?"s":"")+"_status_text_",C={bulkdelete:"for_delete",openClose:"for_"+l};t=C[e]?t+C[e]:t+"generic";openAlertDialog({title:a,message:vBulletin.phrase.get(t),onAfterClose:function(){"bulkdelete"==e?location.replace(pageData.baseurl+"/messagecenter/report/1"):location.reload(!0)}})},
error_phrase:"pm_ajax_error_desc"})}return!1};gotoPage=function(a){var e=$(this);if("blur"==a.type||"keydown"==a.type&&13==a.keyCode){a=Number(e.val());var g=$("#maxPageNum").val();if(!isNaN(a)&&a!=pmPageNum&&0<a&&a<=g){e="";if("undefined"!=typeof folderid)e="/"+routeAction+"/"+folderid+"/";else switch(routeAction){case "report":e="/"+routeAction+"/"}if(""!=e)newpage=window.location.href.replace(e+pmPageNum,e+a),window.location=newpage;else return!0}else e.val(pmPageNum);return!1}return!0};
createNewFolder=function(a,e,g){var l=this;$promtDlg=openPromptDialog({title:vBulletin.phrase.get("add_folder"),message:vBulletin.phrase.get("folder_name"),buttonLabel:{okLabel:vBulletin.phrase.get("ok"),cancelLabel:vBulletin.phrase.get("cancel")},validation:{custom:function(n){return isFolderNameValid(n,"add_folder",!0)},override:!0},onClickOK:function(n){function v(){0==t.length&&(t=$("<div></div>").addClass("error-msg-box error"),$(".dialog-content",$promtDlg).before(t));t.text(vBulletin.phrase.get("pm_ajax_error_desc"))}
var t=$promtDlg.find(".error-msg-box");vBulletin.AJAX({call:"/ajax/api/content_privatemessage/createMessageFolder",data:{folderName:n},success:function(C){$promtDlg.dialog("close");0!=t.length&&t.addClass("h-hide").text("");"function"==typeof e&&e.apply(l,[C,n])},api_error:v,error:v})},onAfterClose:function(){var n=$promtDlg.find(".error-msg-box");0!=n.length&&n.text("").addClass("h-hide");"function"==typeof g&&g.apply(l)}});return!1};
startForward=function(a){if(1==$(".privateMessageDetail .js-post").length)a=getSelectedMessages(),window.location=pageData.baseurl+"/messagecenter/forward/"+a[0];else{var e=function(g){$(".js-hide-on-forward").toggleClass("h-hide-imp",g);$(".js-show-on-forward").toggleClass("h-hide-imp h-hide",!g);$(".pmViewCb").toggleClass("h-hide",!g)};e(!0);$("#pmBtnCancel").off("click").on("click",function(g){e(!1);$("#pmBtnForward").off("click").on("click",startForward);$(".conversation-content.private-message-detail").removeClass("show-subcontrols")});
$(".conversation-content.private-message-detail").addClass("show-subcontrols");$("#pmBtnForward").off("click").on("click",function(g){g=getSelectedMessages(!0);0<g.length&&(window.location=pageData.baseurl+"/messagecenter/forward/"+g.join(","))})}};
acceptRequest=function(a){var e=parseInt(a.target.id.substr(16));vBulletin.AJAX({call:"/ajax/api/content_privatemessage/acceptRequest",data:{nodeid:e},success:function(g){openAlertDialog({title:vBulletin.phrase.get("private_messages"),message:g});$("#msgSummary_"+e).remove()}})};
denyRequest=function(a){var e=parseInt(a.target.id.substr(14));vBulletin.AJAX({call:"/ajax/api/content_privatemessage/denyRequest",data:{nodeid:e},success:function(g){g.result&&vBulletin.alert("private_messages",g.result,"");$("#msgSummary_"+e).remove()}})};notificationFadeOut=function(a){a.animate({opacity:"0.0"},{duration:500,complete:function(){a.empty();a.animate({height:0,width:0,"padding-top":0,"padding-right":0,"padding-bottom":0,"padding-left":0},{duration:100,complete:function(){a.remove()}})}})};
notificationFadeIn=function(a,e,g){a&&($container=$(".js-notification-container"),$temp=$(a).hide(),$container.append($temp),$temp.fadeIn())};function getNotificationsFilterParams(){var a={},e=$("#notificationFilters");if(!e.length)return{};e.find("input[type=hidden], input[type=radio]:checked").each(function(g){a[this.name]=this.value});"undefined"!=typeof pmPageNum&&(a.page=parseInt(pmPageNum));"undefined"!=typeof pmPerPage&&(a.perpage=parseInt(pmPerPage));return a}
decrementNotificationCount=function(){var a=$(".inbox .count"),e=$(".notifications .count"),g=a.text(),l=e.text();--g;0>=g&&a.hide();--l;0>=l&&e.hide();a.text(g);e.text(l);$(".js-header-count-contains-notifications").each(function(n,v){n=$(v).text();n--;0>=n&&$(v).addClass("h-hide-imp");$(v).text(n)})};
toggleOthersDialog=function(a){if($othersBox=$(a.currentTarget).closest("li.message-item").find(".js-others-wrapper"))a=$othersBox.data("titlephrase")||"members_in_this_message",vBulletin.qtip.apply($(this),"qtip-notificationothers",{content:{title:{text:vBulletin.phrase.get(a),button:!0},text:$othersBox.html()},position:{my:"top center",at:"bottom center",viewport:$(window)},show:{event:"click",solo:!0,ready:!0},events:{visible:function(e,g){$(".pmBtnFollowRequest").off("click").on("click",sendFollowRequest)}},
hide:{event:"unfocus",fixed:!0}})};
dismissSingleNotification=function(a){var e=$(a.currentTarget).closest("li.message-item");a=e.data("notificationid");if(null!=a){var g={};$(".pm-notification-list").find("li.message-item.notification-unread").each(function(n){n=$(this).data("notificationid");null!=n&&(g[n]=n)});var l={readIds:a,idsOnPage:g,filterParams:getNotificationsFilterParams()};"unread_only"!=l.filterParams.readFilter&&(l.skipFetch=!0);e.find(".js-waiting-for-ajax-response").removeClass("h-hide");vBulletin.AJAX({call:"/ajax/api/notification/dismissNotification",
data:l,success:function(n){var v=n.insertNotification||"";n=n.lastsenttime||-1;var t=l.filterParams.sortDir;e.removeClass("notification-unread js-notification-dismiss-touch");e.find("button.js-notification-dismiss").remove();decrementNotificationCount();"unread_only"==l.filterParams.readFilter&&(notificationFadeOut(e),notificationFadeIn(v,n,t),"undefined"!==typeof pmNotificationCount&&(pmNotificationCount--,0<=pmNotificationCount&&(v=$("#notificationPageto"),1<l.filterParams.page&&pmNotificationCount<
(l.filterParams.page-1)*l.filterParams.perpage+1&&(v.val(l.filterParams.page-1),v.trigger("blur")),1<pmPages&&pmNotificationCount<(pmPages-1)*l.filterParams.perpage+1&&(pmPages--,$("#notificationPageCount").text(pmPages),$("#maxPageNum").val(pmPages),vBulletin.privateMessage.updatePaginationLinks($("#notificationContent").parent(),v.val(),pmPages)))))},complete:function(){e.find(".js-waiting-for-ajax-response").addClass("h-hide")},error_phrase:"error_dismissing_notification"})}};
dismissNotifications=function(a){if("pmBtnNotificationDismissAll"==a.currentTarget.id)a=parseInt($(".js-notifications-folder-count").data("count")),isNaN(a)||0>=a?vBulletin.warning("dismiss_notification_all","nothing_to_dismiss"):openConfirmDialog({title:vBulletin.phrase.get("dismiss_notification_all"),message:vBulletin.phrase.get("confirm_about_to_dismiss_x_notifications",a),iconType:"warning",onClickYes:function(g){vBulletin.AJAX({call:"/ajax/api/notification/dismissAllNotifications",data:{},success:function(){location.reload()},
error_phrase:"error_dismissing_notification"})}});else if("pmBtnNotificationDismissPage"==a.currentTarget.id){var e={};$(".pm-notification-list").find(".js-notification-dismiss").each(function(g){g=$(this).data("notificationid");null!=g&&(e[g]=g)});$.isEmptyObject(e)?vBulletin.warning("dismiss_notification_page","nothing_to_dismiss"):(a={readIds:e,idsOnPage:e,filterParams:getNotificationsFilterParams(),skipFetch:!0},vBulletin.AJAX({call:"/ajax/api/notification/dismissNotification",data:a,success:function(){$(".pm-notification-list").find(".js-notification-dismiss").each(function(g){$(this).removeClass("notification-unread")});
location.reload()},error_phrase:"error_dismissing_notification"}))}};
sendFollowRequest=function(a){var e=$(this);a=Number(e.data("userid"));isNaN(a)||vBulletin.AJAX({call:"/ajax/api/follow/add",data:{follow_item:a},success:function(g){if("1"==g){e.removeClass("b-button--secondary").addClass("isSubscribed b-button--special");var l="following"}else"2"==g&&(e.addClass("subscribepending_button"),l="following_pending");l&&e.prop("disabled",!0).find(".js-button__text-primary").html(vBulletin.phrase.get(l))},error_phrase:"pm_ajax_error_desc"})};
