/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache("error error_trying_to_change_user_status error_x follow following following_pending following_remove invalid_server_response_please_try_again profile_guser edit_avatar invalid_data no_permission upload_invalid_url unable_to_upload_profile_photo profile_media album album_saved please_enter_message_x_chars please_enter_title_x_chars unable_to_contact_server_please_try_again".split(" "),[]);var albumPhotoCount=0;
(function(a){function h(){var c=a(this).closest(".section-content").find(".js-user-status-text"),n=a.trim(c.val()),d=a(".js-profile-about-container").data("user-id");vBulletin.AJAX({call:"/ajax/api/user/updateStatus",data:{userid:d,status:n},title_phrase:"profile_guser",error_phrase:"error_trying_to_change_user_status",success:function(f){c.val(f);f&&(f='"'+f+'"');a("#userStatus").text(f)},allowEmptyResponse:!0})}function m(c){let n=!!c.avatarpath;c=new URL(n?c.avatarpath:c[0],pageData.baseurl_core+
"/");n&&"data:"!=c.protocol&&c.searchParams.set("random",Math.random());a("#profilePicImg, .avatar-"+pageData.userid).attr("src",c);a("#profilePicImgCrop").attr("src","");a("#btnProfilePhotoClose").trigger("click")}function p(){let c=a("#editProfilePhotoDlg");vBulletin.AJAX({call:"/profile/resetAvatar",success:n=>{m(n);a(".js-edit-profile-hide-on-reset").addClass("h-hide-imp")},complete:()=>{c.find(".js-upload-progress").addClass("h-hide-imp");c.find("input,button").prop("disabled",!1);c.find(".js-upload-button").removeClass("h-disabled")}})}
function u(){a(".defaultAvatarSet").removeClass("defaultAvatarSelected");a("#defaultAvatars").html("");var c=a("#editProfilePhotoDlg").dialog({width:734,title:vBulletin.phrase.get("edit_avatar"),autoOpen:!1,modal:!0,resizable:!1,closeOnEscape:!1,showCloseButton:!1,dialogClass:"dialog-container edit-profile-photo-dialog-container dialog-box",close:function(){modifyIasForTouch("disable")}}).dialog("open");c.on("vbulletin:dialogresize",function(d){resizeAvatarEditDialog()});a(".profile-img-option-container .browse-option").off("click").on("click",
function(d){a(".avatarHolder .defaultAvatarSet.defaultAvatarSelected").removeClass("defaultAvatarSelected")});a(".profile-img-option-container .url-option").off("click").on("click",function(d){var f=a(this);a(".avatarHolder .defaultAvatarSet.defaultAvatarSelected").removeClass("defaultAvatarSelected");setTimeout(function(){f.closest(".profile-img-option-container").find(".profilePhotoUrl").trigger("focus.photourl")},10)});a(".js-edit-profile").data("avatarmaxsize");var n=!1;a("#profilePhotoFile").off("click").on("click",
function(){a(this).closest(".profile-img-option-container").find(".browse-option").trigger("click")}).fileupload({url:vBulletin.getAjaxBaseurl()+"/profile/upload-profilepicture",dropZone:a(".frmprofilePhoto"),dataType:"json",add:function(d,f){d=a("#profilePicImgCrop");if(f.crop)f.crop.resized_width=d.width(),f.crop.resized_height=d.height(),n.formData=f.crop,n.formData.securitytoken=pageData.securitytoken,n.submit(),closeUploader();else{n=f;let v=f.files[0].fileName||f.files[0].name;a(".profile-img-option-container .fileText").val(v);
a("#btnProfilePhotoContinue").trigger("click");initIAS();d.attr("src",URL.createObjectURL(f.files[0]))}},done:function(d,f){d=f.result||{errors:[["invalid_server_response_please_try_again"]]};if(d.errors)return vBulletin.ajaxtools.showApiError(d.errors,d,{title:"edit_avatar"}),!1;if(d.imageUrl)return a("#profilePhotoUrl").val(d.imageUrl).data("filedataid",d.filedataid).trigger("focus"),a("#btnProfilePhotoContinue").trigger("click"),!1;m(d)},fail:function(d,f){d="error";if(f&&0<f.files.length)switch(f.files[0].error){case "acceptFileTypes":d=
"warning"}vBulletin.alert("upload","error",d,function(){c.find(".fileText").val("");c.find(".browse-option").focus()})},always:function(d,f){c.find(".js-upload-progress").addClass("h-hide");c.find("input,button").prop("disabled",!1);c.find(".js-upload-button").removeClass("h-disabled");return!1}});a("#profilePhotoUrl").off("focus").on("focus",function(){a(this).closest(".profile-img-option-container").find(".url-option").trigger("click")})}function q(){if(""==a("#profilePicImgCrop").attr("src"))return closeUploader(),
vBulletin.error("edit_avatar","please_select_a_image_to_crop"),a("#btnProfilePhotoSave").addClass("h-hide-imp"),a("#btnProfilePhotoContinue").removeClass("h-hide-imp"),a("div#cropFrame").addClass("h-hide"),a("div#uploadFrame").removeClass("h-hide"),!1;var c={crop:{}},n=a(".js-edit-profile"),d=n.data("avatarmaxwidth");n=n.data("avatarmaxheight");c.crop.x1=a("#x1").val()||0;c.crop.x2=a("#x2").val()||d;c.crop.y1=a("#y1").val()||0;c.crop.y2=a("#y2").val()||n;c.crop.width=a("#width").val()||d;c.crop.height=
a("#height").val()||n;c.crop.resized_width=a("#profilePicImgCrop").width();c.crop.resized_height=a("#profilePicImgCrop").height();c.securitytoken=pageData.securitytoken;d=a("[name=profile-img-option]:checked").val();"1"==d?(c.files=a("#profilePhotoFile"),c.url=pageData.baseurl+"/profile/upload-profilepicture",a("#profilePhotoFile").fileupload("add",c)):"2"==d&&(c.profilePhotoUrl=a("#profilePhotoUrl").val(),c.filedataid=a("#profilePhotoUrl").data("filedataid"),vBulletin.AJAX({call:"/profile/upload-profilepicture",
data:c,success:f=>{m(f)}}));w()}function w(){a("#x1, #x2, #y1, #y2").val("")}if(!vBulletin.pageHasSelectors([".profile-sidebar-widget"]))return!1;a(()=>{var c=vBulletin.tabtools,n=a(".profile-widget"),d=a("#profileTabs");if(0<d.length){var f=d.find(".ui-tabs-nav > li");0==f.length&&(f=d.find(".profile-tabs-nav > li"));var v=f.filter(".ui-tabs-active");0==v.length&&(v=f.filter(".b-comp-menu-dropdown__content-item--current"));0==v.length&&(v=function(b,g){var k=[];b.find(".ui-tabs-nav > li > a, .widget-tabs-panel").each(function(t,
y){t=a(this).data("url-path");-1==a.inArray(t,k)&&k.push(t)});b=new RegExp("\\/("+k.join("|")+")/?$");var e=location.pathname.match(b);if(e){var r=!1;g.each(function(){var t=a(this);if(t.find("a").data("url-path")==e[1])return r=t,!1});if(r)return r}return a()}(d,f));var E=v.index(),z,A,C={},F="1"==f.parent().data("allow-history"),D=new vBulletin.history.instance(F);-1==E&&(E=0,v=f.first());var G=v.find("> a").attr("href");function l(b,g,k,e){if(D.isEnabled()){var r=D.getState();(e||!r||a.isEmptyObject(r.data))&&
D.setDefaultState({from:b,tab:g,page:"undefined"==typeof k?void 0:k},document.title,location.href)}}var H=function(b,g){g.setOption("context",b);"undefined"!=typeof g.lastFilters&&0<a(".conversation-empty:not(.h-hide)",b).length&&delete g.lastFilters},I=function(b,g,k,e,r){var t=a(".conversation-list",b);return c.newTab(b,null,!1,!1,g,t,e,r,k)};function B(b){const g=a(".js-profile-responsive-button-container");let k=!1,e=!1;"#activities-tab"!=b&&("#subscribed-tab"==b?k=!0:"#about-tab"!=b&&"#media-tab"==
b&&(e=!0));g.toggleClass("media",e);g.toggleClass("subscribed",k)}c.initTabs(d,D,f,F,E,G,[z,A],!1,function(b,g,k){var e=a(k);b="#"+e.attr("id");var r=G==b;b in C||(C[b]=c.tabAllowHistory(e));B(b);if("#activities-tab"==b)z?H(e,z):(k=function(){vBulletin.upload&&vBulletin.upload.initializePhotoUpload(e)},z=I(e,r,C[b],k,k).filter),z.applyFilters(!1,!0);else if("#subscribed-tab"==b)A?H(e,A):A=I(e,r,C[b],null,null).filter,A.applyFilters(!1,!0);else if("#about-tab"==b)if(r)l("tabs","about");else{var t=
a(".js-profile-about-container",k);0==a(".section",t).length&&vBulletin.AJAX({call:"/profile/fetchAbout",data:{userid:t.data("user-id"),isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0},success:function(x){t.html(x.template)}})}else if("#media-tab"==b)if(b=Number(a("#mediaCurrentPage").val()),r)l("media_filter","media",b,!0),e.data("media-statechange-set",!0);else{var y=a(".js-profile-media-container",k);0==a(".item-album",y).length?(k=0,"undefined"==typeof vBulletin.contentEntryBox&&(k=1),
vBulletin.AJAX({call:"/profile/fetchMedia",data:{userid:y.data("user-id"),perpage:y.data("perpage"),allowHistory:1,includeJs:k,isAjaxTemplateRender:!0,isAjaxTemplateRenderWithData:!0},success:function(x){y.html(x.template);r&&(x=Number(a("#mediaCurrentPage").val()),l("media_filter","media",x,!0));vBulletin.media.setHistoryStateChange();e.data("media-statechange-set",!0);y.trigger("vb-instrument");"undefined"!=typeof vBulletin.contentEntryBox&&vBulletin.contentEntryBox.init();"function"==typeof vBulletin.Responsive.ChannelContent.cloneAndMoveToolbarButtons&&
vBulletin.Responsive.ChannelContent.cloneAndMoveToolbarButtons()}})):e.data("media-statechange-set")||(l("media_filter","media",b,!0),e.data("media-statechange-set",!0))}else"#infractions-tab"==b&&(b=Number(a(".pagenav-form .js-pagenum",k).val())||1,r?(a(".pagenav-form",k).length&&!e.data("pagination-instance")&&(new vBulletin.pagination({context:e,tabParamAsQueryString:!1,allowHistory:1==e.find(".conversation-toolbar-wrapper").data("allow-history"),onPageChanged:function(x,J){vBulletin.infraction.loadUserInfractions({container:e,
userid:e.data("userid"),pageNumber:x,replaceState:!0})}}),e.data("pagination-instance",!0)),l("infraction_filter","infractions",b,!0),vBulletin.infraction.setHistoryStateChange(),e.data("infraction-statechange-set",!0)):0==a(".infraction-list",k).length?(l("infraction_filter","infractions",b,!0),vBulletin.infraction.loadUserInfractions({container:e,userid:e.data("userid"),pageNumber:b,callback:function(){vBulletin.infraction.setHistoryStateChange();e.data("infraction-statechange-set",!0)}})):e.data("infraction-statechange-set")||
(l("infraction_filter","infractions",b,!0),vBulletin.infraction.setHistoryStateChange(),e.data("infraction-statechange-set",!0)))});a(".customize-theme").off("click").on("click",function(b){var g=a(".profile_custom_edit");if(g.is(":hidden")){var k=function(){g.removeClass("h-hide");vBulletin.animateScrollTop(g.offset().top,{duration:"slow"})};0<a(".profileNavTabs",g).length?k():vBulletin.AJAX({call:"/ajax/render/profile_custom_edit",userid:g.data("page-userid"),success:function(e){g.html(e);g.prependTo("#content");
window.setTimeout(function(){var r=g.find(".tab:hidden").css("display","block"),t=g.find(".h-hide").removeClass("h-hide");g.find("select").selectBox();t.addClass("h-hide");r.css("display","none")},0);k()},error_phrase:"unable_to_contact_server_please_try_again"})}else vBulletin.animateScrollTop(g.offset().top,{duration:"slow"})})}else a(".customize-theme").addClass("h-hide-imp");a(".profileDetailTabs").tabs().trigger("vb-tabinit");a(".toggle_customizations").off("click").on("click",function(l){l=
"show"==a(this).attr("data-action")?1:0;vBulletin.AJAX({call:"/profile/toggle-profile-customizations",data:{showusercss:l},complete:function(){a("body").css("cursor","auto")},success:function(B){window.location.reload()}})});0<d.length&&(a(document).off("click",".profileTabs .action_button").on("click",".profileTabs .action_button",function(){if(!a(this).hasClass("subscribepending_button")){var l=a(this),B=parseInt(l.attr("data-userid")),b="";l.hasClass("subscribe_button")?b="add":l.hasClass("unsubscribe_button")&&
(b="delete");"number"==typeof B&&b&&vBulletin.AJAX({call:"/profile/follow-button",data:{"do":b,follower:B,type:"follow_members"},success:function(g){if(1==g||2==g){if("add"==b){var k=1==g?"subscribed":"subscribepending";g=1==g?"following":"following_pending";l.removeClass("subscribe_button").addClass(k+"_button b-button").find(".js-button__text-primary").text(vBulletin.phrase.get(g))}else"delete"==b&&l.removeClass("subscribed_button unsubscribe_button b-button b-button--special").addClass("subscribe_button b-button b-button--secondary").find(".js-button__text-primary").text(vBulletin.phrase.get("follow"));
location.reload()}},title_phrase:"profile_guser"})}}),a(document).off("mouseover",".profileTabs .action_button.subscribed_button").on("mouseover",".profileTabs .action_button.subscribed_button",function(l){a(this).html(vBulletin.phrase.get("following_remove")).addClass("b-button").toggleClass("subscribed_button unsubscribe_button b-button--special b-button--secondary")}),a(document).off("mouseout",".profileTabs .action_button.unsubscribe_button").on("mouseout",".profileTabs .action_button.unsubscribe_button",
function(l){a(this).html(vBulletin.phrase.get("following")).addClass("b-button").toggleClass("subscribed_button unsubscribe_button b-button--special b-button--secondary")}),a(document).offon("click",".js-update-status-btn",h),vBulletin.conversation.bindEditFormEventHandlers("all"),vBulletin.conversation.initPollEvents(n),vBulletin.conversation.initContentEvents(n),n.off("click",".js-comment-entry__post").on("click",".js-comment-entry__post",function(l){vBulletin.conversation.postComment.apply(this,
[l,function(){location.reload()}])}));a("body").is(".view-mode")&&(a(".js-edit-profile").off("click").on("click",u),a("#btnProfilePhotoSave").off("click").on("click",q));a("#btnProfilePhotoContinue").off("click").on("click",function(){var l=a("[name=profile-img-option]:checked").val();switch(parseInt(l)){case 2:l=a("#profilePhotoUrl").val();if(!l){vBulletin.error("edit_avatar","upload_invalid_url");break}initIAS();a("#profilePicImgCrop").attr("src",l);case 1:a("div#cropFrame").removeClass("h-hide");
a("#btnProfilePhotoSave").removeClass("h-hide-imp");a("#btnProfilePhotoContinue").addClass("h-hide-imp");a("div#uploadFrame").addClass("h-hide");a("#btnProfilePhotoClose").focus();break;case 4:p()}});a("#btnProfilePhotoClose").off("click").on("click",function(){closeUploader();w();a("div#uploadFrame").removeClass("h-hide");a("div#cropFrame").addClass("h-hide");a("#btnProfilePhotoSave").addClass("h-hide-imp");a("#btnProfilePhotoContinue").removeClass("h-hide-imp");a("#editProfilePhotoDlg").dialog("close").find("form").trigger("reset")});
a(document).off("click",".gallery-upload-form .files a:not([target^=_blank])").on("click",".gallery-upload-form .files a:not([target^=_blank])",function(l){l.preventDefault();a('<iframe style="display:none;"></iframe>').prop("src",this.href).appendTo("body")})})})(jQuery);var ias=null;
initIAS=function(){var a=!1,h=$("#profilePicImgCrop"),m=$(".js-edit-profile"),p=m.data("avatarmaxwidth"),u=m.data("avatarmaxheight");h.off("load").on("load",function(){if(!a){h[0].style.setProperty("max-width","none","important");h[0].style.setProperty("max-height","none","important");var q=h.width(),w=h.height();h[0].style.setProperty("max-width","");h[0].style.setProperty("max-height","");q>p||w>u?(a=!0,q=h.width(),w=h.height(),q=Math.min(p,u,q,w),ias=h.imgAreaSelect({aspectRatio:"1:1",handles:!0,
zIndex:1012,enable:!0,show:!0,x1:0,y1:0,x2:q,y2:q,onSelectChange:setDimensions,resizeMargin:"ontouchstart"in document?30:15,instance:!0,keys:!0,persistent:!0}),modifyIasForTouch("enable"),resizeAvatarEditDialog()):$("#btnProfilePhotoSave").trigger("click")}})};
function resizeAvatarEditDialog(){var a=$("#editProfilePhotoDlg");a.dialog("option","position",{my:"center",at:"center",of:window,collision:"flipfit"});var h=$(".profile-photo-wrapper",a);h.height("auto");var m=$(window).height(),p=a.closest(".edit-profile-photo-dialog-container").height(),u=h.height();a=$("#profilePicImgCrop");var q=a.imgAreaSelect({instance:!0});p>m&&(h.height(u-(p-m)),m=$(".js-edit-profile"),h=m.data("avatarmaxwidth"),m=m.data("avatarmaxheight"),p=a.width(),u=a.height(),h=Math.min(h,
m,p,u),a.imgAreaSelect({x1:0,y1:0,x2:h,y2:h}));q.update()}
function modifyIasForTouch(a){function h(m){var p=m.originalEvent.touches;if(!(1<p.length)){var u={touchstart:"mousedown",touchmove:"mousemove",touchend:"mouseup",touchcancel:"mouseout"};if("undefined"!=typeof u[m.type]){var q=p[0];p={bubbles:!0,cancelable:!1,view:window,detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:!1,altKey:!1,shiftKey:!1,metaKey:!1,button:0,buttons:0,relatedTarget:null};try{p.screenX=q.screenX,p.screenY=q.screenY,p.clientX=q.clientX,p.clientY=q.clientY}catch(w){}"touchstart"==
m.type&&(p.buttons=0,q=new MouseEvent("mousemove",p),m.target.dispatchEvent(q));p.buttons=1;u=new MouseEvent(u[m.type],p);m.target.dispatchEvent(u);if(m.target.className.match(/imgareaselect-/))return m.preventDefault(),!1}}}"ontouchstart"in document&&("enable"==a?($(document).off(".iastouch").on("touchstart.iastouch touchmove.iastouch touchend.iastouch touchcancel.iastouch",h),$("#editProfilePhotoDlg").css("-webkit-touch-callout","none"),$("body, html").addClass("h-prevent-scroll-v")):($(document).off(".iastouch"),
$("#editProfilePhotoDlg").css("-webkit-touch-callout","default"),$("body, html").removeClass("h-prevent-scroll-v")))}setDimensions=function(a,h){$("#x1").val(h.x1);$("#y1").val(h.y1);$("#x2").val(h.x2);$("#y2").val(h.y2);$("#width").val(h.width);$("#height").val(h.height)};closeUploader=function(){modifyIasForTouch("disable");$("#profilePicImgCrop").imgAreaSelect({remove:!0});null!=ias&&(ias=null);$("#profilePhotoFile").removeData(["fileupload","blueimp.fileupload.form"])};
