/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache("close email_addresses_must_match error invalid_email_address moderateuser paid_subscription_required paid_subscriptions please_enter_a_username please_enter_your_email_address please_enter_your_parent_or_guardians_email_address please_select_a_day please_select_a_month please_select_a_year register_not_agreed registeremail registration_complete registration_coppa_fail registration_gregister registration_start_failed site_terms_and_rules_title terms_of_service_page_text".split(" "),
["checkcoppa","regrequirepaidsub","reqbirthday","usecoppa","webmasteremail"]);
(function(a){if(!vBulletin.pageHasSelectors([".registration-widget"]))return!1;a(function(){function z(b,h,d,g,e){e=e||!1;0!=b&&0!=h&&0!=d&&(g&&a(".birth-date-wrapper").addClass("h-hide"),vBulletin.AJAX({call:"/registration/iscoppa",data:{month:b,day:h,year:d},success:function(c){if(c&&"undefined"!=typeof c.needcoppa){v=0!=c.needcoppa;var f=a(".birth-date-wrapper"),l=a(".signup-content");if(2==c.needcoppa){g||(vBulletin.error("error","registration_coppa_fail"),f.addClass("h-hide"));l.addClass("h-hide");
a(".coppafail_notice").removeClass("h-hide");return}var m=a(".js-registration__paidsubscription"),k=1==c.needcoppa||!e;c=1==c.needcoppa;e&&g&&!k&&(a("#regMonth").val(0),a("#regDay").val(0),a("#regYear").val(0));f.toggleClass("h-hide",k);l.removeClass("h-hide");m.toggleClass("h-hide-imp",c);m.find("select,input").prop("disabled",c);k?(a("#regContent").removeClass("h-hide"),a("#frmRegister .js-button-group").removeClass("h-hide")):a(".registration-widget select").selectBox()}a(".coppa")[v?"removeClass":
"addClass"]("h-hide-imp")},error_phrase:"registration_start_failed"}))}function q(b,h){return b?(vBulletin.warning("error",b,function(){h.trigger("focus")}),!1):!0}function D(){if(w){var b={"#regMonth":"please_select_a_month","#regDay":"please_select_a_day","#regYear":"please_select_a_year"};for(var h in b)if(0==a(h).val())return q(b[h],a(h).next(".selectBox"))}h=function(e,c,f,l,m,k){var p=a(e);if(p.length){e=p.val();if(""==a.trim(e))return q(c,p);if(f&&!f(e))return q(l,p);if(m&&(c=a(m),c.length&&
e!=c.val()))return q(k,c)}return!0};b=[["#regDataUsername","please_enter_a_username"],["#regDataEmail","please_enter_your_email_address",isValidEmailAddress,"invalid_email_address","#regDataEmailConfirm","email_addresses_must_match"]];v&&b.push(["#parentGuardianEmail","please_enter_your_parent_or_guardians_email_address",isValidEmailAddress,"invalid_email_address"]);for(var d=0;d<b.length;d++)if(!h.apply(window,b[d]))return!1;if(!vBulletin.checkPassword(a("#regDataPassword"),a("#regDataConfirmpassword")))return!1;
b="";if(!a("#cbApproveTerms").is(":checked")){b="register_not_agreed";var g=a("#cbApproveTerms")}A&&!n&&(b="paid_subscription_required",g=a(".cost"));n&&!t&&(b="please_select_a_payment_method",g=a("input.paymentapi").first());return q(b,g)}function E(){var b=this;console.log("Paid Subscriptions Data: subscriptionid: "+n+"; subscriptionsubid: "+x+"; paymentapiclass: "+t+"; currency: "+u);if(!D())return!1;a(".js-button-group .js-button",b).prop("disabled",!0);var h=a(b).serializeArray();vBulletin.AJAX({call:"/registration/registration",
data:h,success:function(d){if(d.usecoppa)location.replace(d.urlPath);else{d.newtoken&&"guest"!=d.newtoken&&vBulletin.doReplaceSecurityToken(d.newtoken);var g=function(){vBulletin.alert("registration_gregister",d.msg,null,function(){d.urlPath?location.replace(d.urlPath):(a(".signup-success").removeClass("h-hide"),a(".signup-content").addClass("h-hide"))})};vBulletin.ensureObj("paypal2");vBulletin.paypal2.regfinal=g;if(n){var e=openConfirmDialog({title:vBulletin.phrase.get("paid_subscriptions"),message:vBulletin.phrase.get("loading")+
"...",width:500,dialogClass:"paidsubscription-dialog loading",buttonLabel:{yesLabel:vBulletin.phrase.get("order"),noLabel:vBulletin.phrase.get("cancel")},onClickYesWithAjax:!0,onClickYes:function(){a(this).closest(".paidsubscription-dialog").find("form").submit()},onClickNo:function(){A?vBulletin.warning("error","paid_subscription_required",function(){e.dialog("open")}):g()}});vBulletin.AJAX({call:"/ajax/api/paidsubscription/placeorder",data:{subscriptionid:n,subscriptionsubid:x,paymentapiclass:t,
currency:u,context:"registration"},complete:function(){a("body").css("cursor","auto")},success:function(c){let f=a(".dialog-content .message",e);a(".paidsubscription-dialog").removeClass("loading");f.html(c);f.trigger("vb-instrument");a('.dialog-content .message input[type="submit"], .dialog-content .message .js-subscription__cancel',e).hide();e.dialog("option","position",{of:window})},error_message:"error_payment_form"})}else g()}},api_error:vBulletin.hv.resetOnError,error_phrase:"registration_start_failed",
complete:function(){a(".js-button-group .js-button",b).prop("disabled",!1)}})}var w=parseInt(window.vBulletin.options.get("usecoppa")),v=!1,y=!1,F=parseInt(window.vBulletin.options.get("reqbirthday")),A=parseInt(window.vBulletin.options.get("regrequirepaidsub")),n,x,t,u;(function(){a("#frmRegister").trigger("reset");setTimeout(vBulletin.hv.reset,0);if(w||F){var b=vBulletin.storagetools.getCookie("coppaage"),h=!1;if(w&&b&&parseInt(vBulletin.options.get("checkcoppa"))){if(b=b.split("-",3),3==b.length){var d=
parseInt(b[0]);var g=parseInt(b[1]);var e=parseInt(b[2]);0!=d&&0!=g&&0!=e&&(h=!0,a("#regMonth").val(d),a("#regDay").val(g),a("#regYear").val(e));z(d,g,e,h,!0)}}else a(".signup-content").removeClass("h-hide");a("#regMonth, #regDay, #regYear").off("change").on("change",function(){d=a("#regMonth").val();g=a("#regDay").val();e=a("#regYear").val();z(d,g,e,h)})}else a(".signup-content").removeClass("h-hide");a(".registration-widget select").selectBox();a("#regDataUsername").off("keydown blur").on("keydown",
function(f){13==f.keyCode&&a(this).triggerHandler("blur");return!0}).on("blur",function(){if(""==a.trim(this.value))return!0;y=!0;var f=this;vBulletin.AJAX({call:"/registration/checkusername",data:{username:a.trim(f.value)},success:function(l){},complete:function(){y=!1},after_error:function(){f.value="";f.select();f.focus()}})});var c=a(".paidsubscription_row");0<c.length&&a("select.cost",c).change(function(){var f=a(this).closest(".newsubscription_row"),l=a(this).find("option:selected").first(),
m=a(this).closest(".subscriptions_list"),k=a(".order_confirm",c);a(".payment-form",c);var p=f.data("allowedapis"),G=l.data("recurring"),B=0,C;n=f.data("id");x=l.data("subid");u=l.data("currency");a('<tr class="confirm_data"><td>'+l.data("subtitle")+"</td><td>"+l.data("duration")+"</td><td>"+l.data("value")+"</td></tr>").appendTo(a(".order_confirm_table",k));m.addClass("h-hide");k.off("click",".remove_subscription").on("click",".remove_subscription",function(){a(".confirm_data",k).remove();a("input.paymentapi",
k).closest("label").removeClass("h-hide");a(".subscriptions-order",k).prop("disabled",!1);a("select.cost",m).selectBox("value","");k.addClass("h-hide");m.removeClass("h-hide");n=0;return!1});k.off("click","input.paymentapi").on("click","input.paymentapi",function(){t=a("input.paymentapi:checked",k).val()});a("input.paymentapi",k).each(function(){var r=a(this),H=r.data("currency").split(","),I=r.data("recurring");-1==a.inArray(u,H)||-1==a.inArray(r.val(),p)||G&&!I?r.closest("label").addClass("h-hide"):
(B++,C=r)});1==B&&C.click();k.removeClass("h-hide")})})();a("#frmRegister").off("submit.usersignup").on("submit.usersignup",function(){var b=this;setTimeout(function(){y||E.apply(b)},10);return!1});a("#regBtnReset").off("click").on("click",function(b){vBulletin.hv.reset();setTimeout(function(){a(".registration-widget select").selectBox("refresh");a("#regMonth").next(".selectBox").trigger("focus")},50)})})})(jQuery);
