/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache("add_tags edit_tags error error_adding_search_tips_code_x error_adding_tags_code_x error_fetching_popular_tags invalid_server_response_please_try_again invalid_x_tag_length loading none popular_tags_cloud tag_cloud unable_to_load_tag_editor unable_to_save_tags you_may_add_one_more_tag you_may_add_x_more_tags you_may_not_add_any_more_tags".split(" "),["tagforcelower","tagmaxlen","tagminlen"]);
(function(c){function O(f,g){var q=g.split(",");g=[];c.each(q,function(k,m){""!=m&&g.push(m)});vBulletin.AJAX({call:"/ajax/api/tags/updateUserTags",data:{nodeid:f,taglist:g},success:function(k){if(k){var m=c("#content-tags-"+f);m.find(".js-content-tag, .js-content-tag-none").remove();k.tags&&0<k.tags.length?c.each(k.tags,function(v,r){var w=c("<span />").addClass("js-content-tag");c("<a />").attr("href",r.searchurl).html(r.tagtext).appendTo(w);v<k.tags.length-1&&w.append(document.createTextNode(", "));
w.appendTo(m)}):c("<span />").addClass("js-content-tag-none").html(vBulletin.phrase.get("none")).appendTo(m)}},error_phrase:"unable_to_save_tags",title_phrase:"edit_tags"})}function P(f){var g=c(this).data("node-id");vBulletin.AJAX({call:"/ajax/render/tag_editor",data:{nodeid:g,dialogOnly:!0,editPost:!0,editorClass:"js-topic-tag-editor",isAjaxTemplateRenderWithData:!0},success:function(q){c("body").append(q.template);c(document).on("vb-tag-editor-init",function(k,m){function v(){r.dialog("destroy").closest(".tag-editor-wrapper").remove()}
var r=m.$dialog;r.on("vb-tag-dialog-cancel",v);r.on("vb-tag-dialog-save",function(w,F){O(g,F.tagList);v()})});new vBulletin.tagEditor.instance(".js-topic-tag-editor",!1,!1,f)},error_phrase:"unable_to_load_tag_editor",title_phrase:"edit_tags"})}var M=vBulletin.ensureObj("jsexec.tag_editor",{exec:0});M.exec++;if(!(1<M)){var x={};vBulletin.tagEditor=vBulletin.tagEditor||{};vBulletin.tagEditor.instance=function(f,g,q,k){function m(){var a=n.find(".you-may-add-text");if(t||p){var b=t&&!p?t:!t&&p?p:Math.min(t,
p);a.find("span").text(b)}else a.addClass("h-hide");D()?d.is(":visible")&&d[0].focus():d.hide()}function v(a){a=c(this);var b=a.parent();!b.hasClass("added")&&C(a.text())&&(b.addClass("added"),d.is(":visible")&&d[0].focus());return!1}function r(a,b){0<a.length&&(b=(b.find(".tag-input").val()||"").split(","),c.each(b,function(e,h){var y=c.trim(h);a.each(function(){c(this).data("tag")==y&&c(this).addClass("added")})}))}function w(a){a.stopPropagation();var b=c(this),e=u.find(".tag-editor-container");
1==e.length?(e.dialog({title:vBulletin.phrase.get("add_tags"),autoOpen:!1,modal:!0,resizable:!1,closeOnEscape:!1,showCloseButton:!1,width:500,dialogClass:"dialog-container tag-editor-dialog-container dialog-box",open:function(){l.clearElements();var h=u.find(".tag-input").val();if(h){h=h.split(",");for(var y in h)C(c.trim(h[y]))}else z&&!d.attr("placeholder")&&d.attr("placeholder",z);0<E()&&d.show();Q(b.data("node-id"));var G=c(".tag-cloud",e);vBulletin.tagEditor.fetchPopularTags({type:u.data("type")||
"nodes",noformat:1,success:function(H){G.html(H);r(G.find(".tagcloudlink"),u)},error:function(H){G.html('<span class="error">{0}</span>'.format(H))}})},close:function(){u.data("autocomplete-instance").close()}}).dialog("open"),b.data("tag-dialog",e),e.data("parent",b.closest("form, .search-controls-tags, .form_row"))):(e=b.data("tag-dialog")||c(),e.dialog("open"));return!1}var F=this,A=!1,B=!1,I=vBulletin.options.get("tagmaxlen")||25,R=vBulletin.options.get("tagminlen")||3,t=0,p=0,J=!1,d=c(f),n=d.closest(".tag-editor-container"),
u=d.closest(".tag-editor-wrapper");n.data("node-id");var l=!1,z=d.attr("placeholder")?d.attr("placeholder"):"",K=z?z.length:10,C=function(a,b){if(!l)return!1;if("undefined"==typeof b||1>b)b=pageData.userid;var e=l.getMinLength();if(a.length<e)return vBulletin.warning("error",["invalid_x_tag_length",e]),!1;1==vBulletin.options.get("tagforcelower")&&(a=a.toLowerCase());a.length>I&&(a=a.substr(0,I));b=l.addElement(a,b);d.val("");E();return b},N=function(a){var b=a.length,e;for(e=0;e<b;++e)C(a[e])},L=
function(){d.attr("size",K);var a=JShtmlEncode(c.trim(d.val()));if(""==a)return!1;var b="Adding tag: "+a;0<D()&&(setTimeout(function(){C(a)},10),b+=" (Tag added)");console.log(b)},D=function(){if(g||0==t&&0==p)return!0;var a=l.countElements(),b=c(l.getElements()).filter(function(e,h){return 0==pageData.userid||h.value==pageData.userid}).length;a=0<t?t-a:p-a;return Math.min(0==p?a:p-b,a)},E=function(){var a=n.find(".you-may-add-x-tags"),b=D();if(!0===b)return!0;if(1<b)var e=["you_may_add_x_more_tags",
b];else 1==b?e="you_may_add_one_more_tag":(e="you_may_not_add_any_more_tags",b=0);a.toggleClass("warning",0==b).html(vBulletin.phrase.get(e));return b},Q=function(a){g?d[0].focus():x[a]?(t=x[a].maxTags,p=x[a].maxUserTags,J=x[a].canManageTags,m()):(x[a]={},vBulletin.AJAX({call:"/ajax/api/tags/getNodeTags",data:{nodeid:a},success:function(b){c.isArray(b.tags)&&(t=parseInt(b.maxtags,10),p=parseInt(b.maxusertags,10),J=b.canmanagetags,x[a]={maxTags:t,maxUserTags:p,canManageTags:J},m())},api_error:c.noop,
error:c.noop}))};this.addTag=function(a,b){C(a,b)};this.addTags=function(a){N(a)};this.setTags=function(a){l&&(l.clearElements(),N(a))};this.removeAllTags=function(){l.clearElements()};this.getTags=function(){return l?l.getLabels():!1};this.getTagEditor=function(){return d};u.data("initialized")?console.log("Tag Editor is already initialized."):(u.attr("data-initialized",!0),function(){if(0==d.length)return!1;d.attr("maxlength",I);l=new vBulletin_Autocomplete(d,{apiClass:"Tags",containerClass:(q||
"")+" entry-field h-clearfix",placeholderText:z,editorContext:{type:"tags",context:F},minLength:R,beforeAdd:function(a,b){A=B?!0:!1;return 0==D()?!1:!0},afterAdd:function(a,b){0==E()&&d.hide();d.attr("placeholder","");r(n.find(".tagcloudlink"),n)},afterDelete:function(a,b){A=B?!0:!1;b=E();if(g||0<b)d.show(),setTimeout(function(){d[0].focus()},10);d.attr("placeholder",function(){var h=l?l.getLabels():!1;return h&&0!=h.length?"":z});b=n.find(".tag-cloud .tagcloudlink");if(0==b.length){var e=n.find(".popular-tags-link");
e.length&&e.qtip&&(b=e.qtip("api").elements.tooltip.find(".tagcloudlink"))}b.each(function(){c(this).data("tag")==a&&c(this).removeClass("added")})}});d=l.getInputField();u.data("autocomplete-instance",l)}(),d.off("keydown").on("keydown",function(a){var b=c(a.target).val().length;c(a.target).attr("size",b>K?b:K);if(13==a.which)return A=B?!0:!1,L(),a.preventDefault(),!1}),d.off("blur").on("blur",function(a){B=setTimeout(function(){A||L();B=A=!1},0)}),d.off("click").on("click",function(a){c(a.target).hasClass("tag-input")||
(c(".tag-input",c(this)).trigger("focus"),A=B?!0:!1);return!1}),d.each(function(){c(this).closest("form").on("submit",L)}),c(".tag-cloud-text.inline-tag-cloud .popular-tags-link",n).off("click").on("click",function(){var a=n.find(".tag-cloud");vBulletin.tagEditor.fetchPopularTags({type:"nodes",noformat:1,success:function(b){a.html(b);r(a.find(".tagcloudlink"),n)},error:function(b){a.html('<span class="error">{0}</span>'.format(b))}})}),vBulletin.qtip.apply(c(".tag-cloud-text:not(.inline-tag-cloud) .popular-tags-link",
n),"qtip-populartags",{content:{title:{text:vBulletin.phrase.get("tag_cloud"),button:!1},text:function(a,b){function e(h){var y=vBulletin.phrase.get("error_fetching_popular_tags");h&&(y+=" "+vBulletin.phrase.get(h));b.set("content.text",'<span class="error">{0}</span>'.format(y))}vBulletin.AJAX({call:"/search/fetchTagCloud",data:{type:"nodes",noformat:1},success:function(h){b.set("content.text",'<div class="tag-cloud">{0}</div>'.format(h));h=b.elements.tooltip;h.on("click",".tag-cloud .tagcloudlink label",
v);r(h.find(".tagcloudlink"),u)},api_error:function(h){e(h[0])},error:function(){e()}});return vBulletin.phrase.get("working_ellipsis")}},position:{at:"bottom center",my:"top center",viewport:c(window),effect:!1},show:{event:"click",solo:!0},hide:"unfocus"}),n.on("click",".tag-cloud .tagcloudlink label",v),u.on("click",".add-tag-link",w),"undefined"!==typeof k&&w.call(k.target,k),c(document).trigger("vb-tag-editor-init",{$dialog:n}))};vBulletin.tagEditor.fetchPopularTags=function(f){f=f||{};f.type=
"search"!=f.type?"nodes":f.type;var g="function"==typeof f.error?f.error:c.noop;vBulletin.AJAX({call:"/search/fetchTagCloud",data:{type:f.type,noformat:f.noformat},success:function(q,k,m){"function"==typeof f.success&&f.success(q,k,m)},api_error:function(q){g("{0} {1}".format(vBulletin.phrase.get("error_fetching_popular_tags"),vBulletin.phrase.get(q[0])))},error:function(){g(vBulletin.phrase.get("error_fetching_popular_tags"))}})};c(function(){c(document).offon("click.tage",".tag-editor-container .cancel-tag-btn",
function(){c(".tag-editor-container").dialog("close").trigger("vb-tag-dialog-cancel")});c(document).offon("click.tage",".tag-editor-container .save-tag-btn",function(){var f=c(this).closest(".tag-editor-container"),g=f.find(".tag-input").val(),q=g.replace(/,/g,", "),k=f.data("parent");k.find(".tag-list span").text(q);k.find(".tag-input").val(g);k.find(".tag-list").toggleClass("h-hide",!g);f.dialog("close").trigger("vb-tag-dialog-save",{tagList:g})});c(document).offon("mousedown.tage",".tag-editor-container .autocomplete-container",
function(){var f=this;setTimeout(function(){var g=c(".autocompleteHelper:visible",f);0<g.length&&g[0].focus()},10);return!1});0<c(".js-content-entry-tag-editor").length&&vBulletin.tagEditor&&new vBulletin.tagEditor.instance(".js-content-entry-tag-editor");c(document).offon("click.tage",".js-edit-tags",P)})}})(jQuery);
