/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache(["gallery_slideshow","no_photos_found_or_post_deleted"],[]);
(function(f){function A(a,b,e,c){var d=a.find(".caption");d.html("").hide();b.links&&d.append(f("<div />").addClass("links ellipsis").html(b.links));b.title&&d.append(f("<div />").addClass("title ellipsis").html(b.title));b.caption&&d.append(f("<div />").addClass("title ellipsis").html(b.caption));b=b.links&&b.title?15:b.links||b.title?35:50;e=a.find(".slideshow-wrapper .jcarousel-item-"+e+" img");e.outerWidth();d.css({marginBottom:b+"px",width:"100%",textAlign:"center",marginLeft:"auto",marginRight:"auto"});
e.one("load",function(){var h=f(this).outerWidth();d.css("width",h+"px")});c?d.fadeIn("fast",function(){a.trigger("click")}):d.show()}function B(a){var b=vBulletin.isRtl();37==a.which?vBulletin.gallery.slideshow.jcarousel(b?"next":"prev"):39==a.which&&vBulletin.gallery.slideshow.jcarousel(b?"prev":"next");if(33<=a.which&&40>=a.which)return!1;27==a.which&&k.dialog("instance")&&k.dialog("close")}function C(a){0<(a.originalEvent.wheelDelta||-a.originalEvent.detail)?vBulletin.gallery.slideshow.jcarousel("prev"):
vBulletin.gallery.slideshow.jcarousel("next");return!1}function D(a){if(a){var b=vBulletin.isRtl(),e=0,c=!1,d=!1;function h(g,l){if(vBulletin.gallery.slideshow.jcarousel("canmove")){var n=f(".slideshow-wrapper .jcarousel-list"),q=b?"right":"left",m=parseInt(n.css(q),10);if("restore"===g)g=m+-1*e,l?(l={},l[q]=g,n.animate(l,"fast","swing")):n.css(q,g),e=0,c=!1;else if("prev"===g||"next"===g){parseInt(n.css("width"),10);m=n.find(".jcarousel-item");l=m.length;m=m.first();m=parseInt(m.css("width"),10);
var r=Math.abs(c);g="prev"===g?r-m:r+m;var t=(g?g/m:0)+1;if(0<=g&&g<=(l-1)*m&&(l={},l[q]=-1*g,n.animate(l,"fast","swing",function(){e=0;!1!==c&&(n.css("visibility","hidden"),n.css(q,c),c=!1,vBulletin.gallery.slideshow.jcarousel("scroll",t,!1),n.css("visibility","visible"))}),!1!==c))return!0}else b&&(g*=-1),n.css(q,m+g),e+=g,!1===c&&(c=m)}}function p(g){d=!0;h(g,!0)||h("restore",!0)}f(document).swipeable({swipeleft:function(g,l){p(b?"prev":"next")},swiperight:function(g,l){p(b?"next":"prev")},swiping:function(g,
l){h(l.moved.x)},swipeend:function(g,l){e&&!d&&h("restore",!0);d&&(d=!1)}})}else f(document).swipeable("disable")}function F(){var a=f("body"),b=a.css("overflow")||"auto";a.css("overflow","hidden");var e=f(window).innerWidth(),c=f(window).innerHeight();e=parseInt(e-0,10);c=parseInt(c-0,10);k.css({borderRadius:0,borderWidth:0});a.css("overflow",b);k.dialog("instance")&&(k.dialog("option","width",e),k.dialog("option","height",c))}function G(a){var b=a.closest(".js-slideshow__gallery-node"),e=0,c="",
d=null,h=null;0<b.length&&(e=parseInt(b.attr("data-node-id")||b.attr("data-nodeid"),10),c=b.data("sort")||"",b=b.closest(".ui-widget-content"),b=b.find(".toolbar-filter-overlay .filter-options"),b.length&&(d=f("input[name=filter_time]:checked",b).val(),h=f("input[name=filter_show]:checked",b).val()));0==e&&(b=a.closest(".js-post-sm"),0<b.length&&(e=parseInt(b.attr("data-nodeid"),10)));0==e&&(a=a.closest(".js-post"),0<a.length&&(e=parseInt(a.attr("data-node-id"),10)));return{nodeid:e,sort:c,filter_time:d,
filter_show:h}}function H(a){var b=a.closest(".js-post__content-text"),e={photos:[]},c=0;(b.length&&b.find(".js-lightbox, .js-lightbox-participant")||a).each(function(){var d=f(this),h=d.data("fullsize-url")||d.parent().attr("href")||d.attr("src")||"";let p=d.data("thumb-url")||h,g=d.data("title")||"";d=d.data("caption")||"";h&&(h={url:h,thumb:p,links:g,title:d},e.photos.push(h),this===a[0]&&(u=c),c++)});return e}async function I(a){if(a.hasClass("js-lightbox"))return H(a);var b=a.closest(".b-content-entry-panel__content--gallery").find(".js-photo-postdata input");
if(0<b.length){let r={photos:[]};b.filter('[name="filedataid[]"]').each(function(){var t=this.value;t={title:JShtmlEncode(b.filter('[name="title_'+t+'"]').val()),url:pageData.baseurl+"/filedata/fetch?filedataid="+t,thumb:pageData.baseurl+"/filedata/fetch?thumb=1&filedataid="+t};r.photos.push(t)});return new Promise((t,N)=>{setTimeout(()=>{t(r)},10)})}var e=a.attr("data-channelid"),c=a.attr("src")||a.attr("href"),d=G(a);a=d.nodeid;var h=d.sort,p=d.filter_time;d=d.filter_show;var g={nodeid:a},l=parseInt(f(".albumSlideShowPageNo").val(),
10),n=parseInt(f(".albumSlideShowPerPage").val(),10),q=f(".media-tab .media-filter-overlay .filter-options input:checked").val();vBulletin.media&&vBulletin.media.MEDIA_USERID&&(g.userid=vBulletin.media.MEDIA_USERID);e&&(g.channelid=e);isNaN(l)||(g.pageno=l);isNaN(n)||(g.perpage=n);q&&(g.dateFilter=q);isNaN(u)||(g.startIndex=u);h&&(g.sort=h);p&&(g.dateFilter=p);d&&(g.showFilter=d);0<a&&(g.startIndex="");var m=JSON.stringify(g);0<a&&(v[a]=v[a]||[],v[a].push(m));w[m]||await vBulletin.AJAX({call:"/filedata/gallery",
data:g}).always(r=>{!r&&c&&(r={photos:[{title:"",url:c,thumb:""}]});w[m]=r});return w[m]}function y(a,b,e){let c=a.jcarousel("size")||1,d=a.data("curIndex")||1,h;if(b!=d)return b==c?(2<c&&(h=a.jcarousel("scroll",b-1,!1)),a.jcarousel("next")):d==c&&b==c-1?a.jcarousel("prev"):h=a.jcarousel("scroll",b,e),h}function z(a){var b=f(this);x=this;if(1==b.closest("#preview-overlay").length)return!1;a&&a.preventDefault&&a.preventDefault();!1===u&&(u=b.index());f(document).offon("click",".thumbnails .image-wrapper",
function(e,c){"undefined"==typeof c&&(c=!0);f(".thumbnails .image-wrapper",k).addClass("dimmed");f(this).removeClass("dimmed");e=Number(f(this).parent().attr("jcarouselindex"));k.data("thumbclick",!0);y(vBulletin.gallery.slideshow,e,c);k.removeData("thumbclick")});a=k.find(".slideshow-wrapper");0==a.find(".slideshow-list").length&&a.append(f("<ul />").addClass("slideshow-list"));k.dialog("open");window.vBulletin.loadingIndicator.show();vBulletin.gallery.slideshow=a.jcarousel({wrap:null,animation:"fast",
easing:"swing",scroll:1,rtl:vBulletin.isRtl(),initCallback:function(e,c){"init"==c&&(window.vBulletin.loadingIndicator.show(),I(b).then(d=>{window.vBulletin.loadingIndicator.hide();J(d,e)}))},itemLoadCallback:{onBeforeAnimation:function(e,c,d){d=e.first;e.inTail&&(d=e.last);if("init"==c)return!1;if(c=k.data("image-data")){vBulletin.gallery.slideshow.data("curIndex",d);var h=c.photos.length;if(0<d)for(;d>h;)d-=h;else for(;0>=d;)d+=h;A(k,c.photos[d-1],d,!0);vBulletin.gallery.thumbnails&&(e=E(e),y(vBulletin.gallery.thumbnails,
Math.max(d-Math.floor(e.visibleCount/2),1),!0),k.data("thumbclick")||(f("#slideshow-dialog .thumbnails .image-wrapper").addClass("dimmed"),vBulletin.gallery.thumbnails.jcarousel("get",d).find(".image-wrapper").removeClass("dimmed")))}}}});"undefined"==typeof vBulletin.gallery.slideshow.data("curIndex")&&vBulletin.gallery.slideshow.data("curIndex",1);return!1}function J(a,b){if(a&&a.photos){k.data("image-data",a);K(b,a,k);k.find(".slideshow-wrapper").find(".jcarousel-prev-horizontal").addClass("b-icon b-icon__arrow-block-left").end().find(".jcarousel-next-horizontal").addClass("b-icon b-icon__arrow-block-right");
var e=k.find(".thumbnails");b=e.find(".jcarousel-prev-horizontal");e=e.find(".jcarousel-next-horizontal");b.addClass("b-icon b-icon__arrow-bar-left").toggleClass("b-icon--disabled",b.is(".jcarousel-prev-disabled"));e.addClass("b-icon b-icon__arrow-bar-right").toggleClass("b-icon--disabled",e.is(".jcarousel-next-disabled"));A(k,a.photos[0],1);1<a.photos.length&&vBulletin.gallery.thumbnails.jcarousel("get",1).find(".image-wrapper").removeClass("dimmed");var c=u;a=parseInt(f(".albumSlideShowPerPage").val(),
10);isNaN(a)||(c=u%a);0<c&&"undefined"!=typeof y(vBulletin.gallery.slideshow,c+1,!1)&&(k.find(".slideshow-wrapper").css("visibility","hidden"),window.setTimeout(function(){f(".thumbnails .image-wrapper",k).eq(c).trigger("click",[!1]);k.find(".slideshow-wrapper").css("visibility","")},0));window.vBulletin.loadingIndicator.hide()}else openAlertDialog({title:vBulletin.phrase.get("gallery_slideshow"),message:vBulletin.phrase.get("no_photos_found_or_post_deleted"),iconType:"warning"})}function K(a,b,e){let c=
b.photos.length;a.size(c);1<c?(f("#slideshow-dialog .thumbnails").show(),L(b)):f("#slideshow-dialog .thumbnails").hide();e.toggleClass("no-thumbnails",1>=c);var d=a.first||1;f.each(b.photos,function(p,g){let l=f("<a></a>").attr("href",g.url);g=f('<img alt="{0}" class="image" />'.format(g.htmltitle||"")).attr("src",g.url);let n=f('<div class="image-wrapper"></div>');l.append(g);n.append(l);a.add(d+p,n)});b=e.find(".slideshow-wrapper .slideshow-list");e=parseFloat(b.css("width"));var h=a.get(1);h=parseFloat(h.css("width"));
0<h&&e/h<c&&b.css("width",c*h+"px");a.reload()}function E(a){var b=f("#slideshow-dialog .thumbnails .jcarousel-clip"),e=b.find(".jcarousel-item").outerWidth(!0);a=a.size();b=parseInt(b.css("max-width"),10);b=Math.min(a,Math.max(1,Math.floor(b/e)));return{visibleCount:b,recommendedContainerWidth:b*e}}function L(a){function b(c){var d=f(c.buttonPrev[0]);c=f(c.buttonNext[0]);d.toggleClass("b-icon--disabled",d.is(".jcarousel-prev-disabled"));c.toggleClass("b-icon--disabled",c.is(".jcarousel-next-disabled"))}
var e=f("#slideshow-dialog .thumbnails .thumbnail-list");0==e.length&&(e=f("#slideshow-dialog .thumbnails").append(f("<ul />").addClass("thumbnail-list")));vBulletin.gallery.thumbnails=e.jcarousel({wrap:null,animation:"fast",easing:"swing",rtl:vBulletin.isRtl(),size:a.photos.length,initCallback:function(c,d){"init"==d&&(c.size(a.photos.length),f.each(a.photos,function(h,p){h=(c.first||1)+h;if(c.has(h))return!0;if(h>a.photos.length)return!1;p=f("<img />").addClass("thumbnail").on("load",function(){}).attr({src:p.thumb,
alt:""}).appendTo(f("<div />").addClass("image-wrapper dimmed"));c.add(h,p.parent().get(0))}),d=E(c),f("#slideshow-dialog .thumbnails .jcarousel-clip").css("width",d.recommendedContainerWidth+"px"),c.size()<=d.visibleCount&&(c.buttonNext.hide(),c.buttonPrev.hide()))},itemVisibleInCallback:{onBeforeAnimation:function(c,d,h,p){f("#slideshow-dialog .thumbnails").data("visible-range",{first:c.first,last:c.last})}},buttonNextCallback:b,buttonPrevCallback:b}).disableSelection()}function M(){if(x){var a=
x;var b=(vBulletin.gallery.slideshow&&vBulletin.gallery.slideshow.data("curIndex")||1)-1;k.dialog("close");u=b;z.call(a)}}vBulletin.ensureObj("gallery");var k=f("#slideshow-dialog"),u=!1,x=!1,w={},v={};vBulletin.gallery.clearCacheForNodeid=function(a){v.hasOwnProperty(a)&&v[a].forEach(b=>delete w[b]);v[a]=[]};f(function(){k.data("vb-lightbox-initialized")||(k.data("vb-lightbox-initialized",!0),f(document).offon("click","#slideshow-dialog .close-btn",function(){k.dialog("instance")&&k.dialog("close")}),
k.dialog({autoOpen:!1,resizable:!1,closeOnEscape:!0,showTitleBar:!1,modal:!0,dialogClass:"slideshow-dialog",open:function(){F();f("body").css("overflow","hidden");f(".ui-widget-overlay").on("click",function(){k.dialog("close")});f(document).offon("keydown",B);f(document).offon("mousewheel DOMMouseScroll",C);D(!0)},close:function(a,b){vBulletin.gallery.thumbnails&&vBulletin.gallery.thumbnails.jcarousel("destroy");vBulletin.gallery.slideshow&&(vBulletin.gallery.slideshow.removeData("curIndex"),vBulletin.gallery.slideshow.jcarousel("destroy"));
f("body").css("overflow","auto");f(document).off("keydown",B);f(document).off("mousewheel DOMMouseScroll",C);D(!1);u=x=!1}}))});f(function(){f(document).offon("click",".js-slideshow--item",z);f(document).offon("click",".js-lightbox",z);k.addClass("js-no-responsive-resize");f(window).on("resize",f.debounce(300,M))})})(jQuery);
