/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
var BBURL="undefined"==typeof BBURL?"":BBURL,SESSIONURL="undefined"==typeof SESSIONURL?"":SESSIONURL,SECURITYTOKEN="undefined"==typeof SECURITYTOKEN?"":SECURITYTOKEN,vbphrase="undefined"==typeof vbphrase?[]:vbphrase,vB_Editor=[],ignorequotechars=!1,pagenavcounter=0,vB_Default_Timeout=15E3,userAgent=navigator.userAgent.toLowerCase(),is_opera=0<YAHOO.env.ua.opera,is_saf=0<YAHOO.env.ua.webkit,is_ie=0<YAHOO.env.ua.ie&&!is_opera&&!is_saf,is_moz=0<YAHOO.env.ua.gecko,is_mac=-1!=userAgent.indexOf("mac");
function fetch_object(a){return document.getElementById?document.getElementById(a):document.all?document.all[a]:document.layers?document.layers[a]:null}function fetch_tags(a,b){return null==a?[]:"undefined"!=typeof a.getElementsByTagName?a.getElementsByTagName(b):a.all&&a.all.tags?a.all.tags(b):[]}function fetch_tag_count(a,b){return fetch_tags(a,b).length}function vB_PHP_Emulator(){}
vB_PHP_Emulator.prototype.stripos=function(a,b,c){"undefined"==typeof c&&(c=0);index=a.toLowerCase().indexOf(b.toLowerCase(),c);return-1==index?!1:index};vB_PHP_Emulator.prototype.ltrim=function(a){return a.replace(/^\s+/g,"")};vB_PHP_Emulator.prototype.rtrim=function(a){return a.replace(/(\s+)$/g,"")};vB_PHP_Emulator.prototype.trim=function(a){return this.ltrim(this.rtrim(a))};
vB_PHP_Emulator.prototype.preg_quote=function(a){return a.replace(/(\+|\{|\}|\(|\)|\[|\]|\||\/|\?|\^|\$|\\|\.|=|!|<|>|:|\*)/g,"\\$1")};vB_PHP_Emulator.prototype.match_all=function(a,b){if(a=a.match(RegExp(b,"gim"))){var c=[];b=new RegExp(b,"im");for(var d=0;d<a.length;d++)c[c.length]=a[d].match(b);return c}return!1};
vB_PHP_Emulator.prototype.unhtmlspecialchars=function(a,b){var c=[/&lt;/g,/&gt;/g,/&quot;/g,/&amp;/g],d=["<",">",'"',"&"],e;for(e in c)YAHOO.lang.hasOwnProperty(c,e)&&(a=a.replace(c[e],d[e]));b&&(is_ie&&(a=a.replace(/\n/g,"<#br#>")),b=document.createElement("textarea"),b.innerHTML=a,a=b.value,null!=b.parentNode&&b.parentNode.removeChild(b),is_ie&&(a=a.replace(/<#br#>/g,"\n")));return a};
vB_PHP_Emulator.prototype.unescape_cdata=function(a){return a.replace(/<=!=\[=C=D=A=T=A=\[/g,"<![CDATA[").replace(/\]=\]=>/g,"]]\x3e")};vB_PHP_Emulator.prototype.htmlspecialchars=function(a){for(var b=[is_mac&&is_ie?RegExp("&","g"):RegExp("&(?!#[0-9]+;)","g"),RegExp("<","g"),RegExp(">","g"),RegExp('"',"g")],c=["&amp;","&lt;","&gt;","&quot;"],d=0;d<b.length;d++)a=a.replace(b[d],c[d]);return a};
vB_PHP_Emulator.prototype.in_array=function(a,b,c){a=new String(a);var d;if(c)for(d in a=a.toLowerCase(),b){if(YAHOO.lang.hasOwnProperty(b,d)&&b[d].toLowerCase()==a)return d}else for(d in b)if(YAHOO.lang.hasOwnProperty(b,d)&&b[d]==a)return d;return-1};vB_PHP_Emulator.prototype.str_pad=function(a,b,c){a=new String(a);c=new String(c);if(a.length<b){for(padtext=new String(c);padtext.length<b-a.length;)padtext+=c;a=padtext.substr(0,b-a.length)+a}return a};
vB_PHP_Emulator.prototype.urlencode=function(a){a=escape(a.toString()).replace(/\+/g,"%2B");var b=a.match(/(%([0-9A-F]{2}))/gi);if(b)for(var c=0;c<b.length;c++){var d=b[c].substring(1,3);128<=parseInt(d,16)&&(a=a.replace(b[c],"%u00"+d))}return a=a.replace("%25","%u0025")};vB_PHP_Emulator.prototype.ucfirst=function(a,b){"undefined"!=typeof b&&(b=a.indexOf(b),0<b&&(a=a.substr(0,b)));a=a.split(" ");for(b=0;b<a.length;b++)a[b]=a[b].substr(0,1).toUpperCase()+a[b].substr(1);return a.join(" ")};
function vBulletin_AJAX_Error_Handler(a){console.warn("AJAX Error: Status = %s: %s",a.status,a.statusText)}function getBaseUrl(){try{var a=document.getElementsByTagName("base");return 0==a.length?"":(a=a[a.length-1].href)?a.match(/.*[\/\\]/):""}catch(b){return""}}
function detect_caps_lock(a){a=a?a:window.event;var b=a.which?a.which:a.keyCode?a.keyCode:a.charCode?a.charCode:0,c=a.shiftKey||a.modifiers&&a.modifiers&4;a=a.ctrlKey||a.modifiers&&a.modifiers&2;return 65<=b&&90>=b&&!c&&!a||97<=b&&122>=b&&c}function js_toggle_all(a,b,c,d,e){for(var g=0;g<a.elements.length;g++){var f=a.elements[g];if(f.type==b&&-1==PHP.in_array(f.name,d,!1))switch(b){case "radio":f.value==c&&(f.checked=e);break;case "select-one":f.selectedIndex=e;break;default:f.checked=e}}}
function js_select_all(a){exclude=["selectall"];js_toggle_all(a,"select-one","",exclude,a.selectall.selectedIndex)}function js_check_all(a){exclude=["keepattachments","allbox","removeall"];js_toggle_all(a,"checkbox","",exclude,a.allbox.checked)}function js_check_all_option(a,b){exclude=["inherit"];js_toggle_all(a,"radio",b,exclude,!0)}
function region_intersects(a,b){a="undefined"==typeof a.left?YAHOO.util.Dom.getRegion(a):a;b="undefined"==typeof b.left?YAHOO.util.Dom.getRegion(b):b;return a.left>b.right||a.right<b.left||a.top>b.bottom||a.bottom<b.top?!1:!0}
function do_securitytoken_replacement(a){if(""!=a){for(var b=0;b<document.forms.length;b++)document.forms[b].elements.securitytoken&&document.forms[b].elements.securitytoken.value==SECURITYTOKEN&&(document.forms[b].elements.securitytoken.value=a);SECURITYTOKEN=a;console.log("Securitytoken updated")}}
function handle_securitytoken_response(a){console.log("Processing securitytoken update");var b=JSON.parse(a.responseText);b&&b.newtoken.length?(do_securitytoken_replacement(b.newtoken),securitytoken_errors=0):handle_securitytoken_error(a)}function handle_securitytoken_error(a){console.log("Securitytoken Error");3==++securitytoken_errors&&do_securitytoken_replacement("guest")}var timeout=36E5,securitytoken_timeout=window.setTimeout("replace_securitytoken()",timeout),securitytoken_errors=0;
function replace_securitytoken(){window.clearTimeout(securitytoken_timeout);""!=SECURITYTOKEN&&"guest"!=SECURITYTOKEN&&(securitytoken_timeout=window.setTimeout("replace_securitytoken()",timeout),YAHOO.util.Connect.asyncRequest("POST","ajax/replacesecuritytoken",{success:handle_securitytoken_response,failure:handle_securitytoken_error,timeout:vB_Default_Timeout},SESSIONURL+"securitytoken="+SECURITYTOKEN+"&do=securitytoken"))}
function vBulletin_Framework(){this.elements=[];this.ajaxurls=[];this.events=[];this.time=new Date;this.add_event("systemInit")}vBulletin_Framework.prototype.init=function(){console.info("Firing System Init");this.events.systemInit.fire()};vBulletin_Framework.prototype.extend=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.baseConstructor=b;a.superClass=b.prototype};
vBulletin_Framework.prototype.register_control=function(a,b){for(var c=[],d=1;d<arguments.length;d++)c.push(arguments[d]);this.elements[a]||(console.info('Creating array vBulletin.elements["%s"]',a),this.elements[a]=[]);d=this.elements[a].push(c);console.log('vBulletin.elements["%s"][%d] = %s',a,d-1,c.join(", "))};
vBulletin_Framework.prototype.register_ajax_urls=function(a,b,c){a=a.split("?");a[1]=SESSIONURL+"securitytoken="+SECURITYTOKEN+"&ajax=1&"+a[1].replace(/\{(\d+)(:\w+)?\}/gi,"%$1$s");b=b.split("?");b[1]=SESSIONURL+"securitytoken="+SECURITYTOKEN+"&ajax=1&"+b[1].replace(/\{(\d+)(:\w+)?\}/gi,"%$1$s");console.log("Register AJAX URLs for %s",c);for(var d=0;d<c.length;d++)this.ajaxurls[c[d]]=[a,b]};vBulletin_Framework.prototype.add_event=function(a){this.events[a]=new YAHOO.util.CustomEvent(a)};
vBulletin_Framework.prototype.console=function(){if(window.console||console.firebug){for(var a=[],b=0;b<arguments.length;b++)a[a.length]=arguments[b];try{eval("console.log('"+a.join("','")+"');")}catch(c){}}};var PHP=new vB_PHP_Emulator,vBulletin=new vBulletin_Framework;YAHOO.namespace("vBulletin");
