/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 6.0.6
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2024 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
var activeElementId=0,colorPickerType=0,pickerReady=!1,colors="00 33 66 99 CC FF".split(" "),specialColors="#000000 #333333 #666666 #999999 #CCCCCC #FFFFFF #FF0000 #00FF00 #0000FF #FFFF00 #00FFFF #FF00FF".split(" ");
function init_color_preview(){if("undefined"!=typeof numColors){for(var a=0;a<numColors;a++)preview_color(a);0!=colorPickerType&&init_color_picker(colorPickerType);pickerReady=!0}else if(fetch_object("color_0")){for(a=0;fetch_object("color_"+a);)preview_color(a),a++;0!=colorPickerType&&init_color_picker(colorPickerType);pickerReady=!0}}
function preview_color(a){var b=fetch_object("color_"+a),c=fetch_object("preview_"+a),d=new RegExp(/url\(('|"|)((http:\/\/|\/)?)(.*)\1\)/i);b.onchange||(b.onchange=function(f){preview_color(a)});if(is_transparent(b.value))c.style.background="none",c.style.borderStyle="dashed",c.title="";else{var e=b.value;if(d=b.value.match(d))if("undefined"==typeof d[3]||""==d[3])e=b.value.replace(d[4],bburl+d[4]);try{color=get_color_value(e),c.style.background=color,c.style.borderStyle="inset",c.title=""}catch(f){c.style.background=
"url('../cpstyles/"+cpstylefolder+"/cp_help.gif') no-repeat center",c.style.borderStyle="dashed",c.title=vBAdmin.renderPhrase("css_value_invalid",e)}}}function set_swatch_color(a,b,c){fetch_object("sw"+a+"-"+b).style.backgroundColor=c}
function init_color_picker(a){colorPickerType=a;fetch_object("colorPickerType").value=a;var b,c;if(2>a)for(b=0;12>b;b++)set_swatch_color(0,b,"#000000"),set_swatch_color(1,b,specialColors[b]),set_swatch_color(2,b,"#000000");switch(a){case 0:green=[5,4,3,2,1,0,0,1,2,3,4,5];blue=[0,0,0,5,4,3,2,1,0,0,1,2,3,4,5,5,4,3,2,1,0];for(b=0;12>b;b++)for(c=3;21>c;c++){var d=2*Math.floor((20-c)/6)+Math.floor(b/6);var e=green[b];var f=blue[c];set_swatch_color(c,b,"#"+colors[d]+colors[e]+colors[f])}break;case 1:green=
[0,0,0,0,1,2,3,4,5,0,1,2,3,4,5,0,1,2,3,4,5];blue=[0,1,2,3,4,5,0,1,2,3,4,5];for(b=0;12>b;b++)for(c=3;21>c;c++)d=Math.floor((c-3)/6)+3*Math.floor(b/6),e=green[c],f=blue[b],set_swatch_color(c,b,"#"+colors[d]+colors[e]+colors[f]);break;case 2:var g=255;for(b=0;12>b;b++)for(c=0;21>c;c++)set_swatch_color(c,b,"rgb("+g+","+g+","+g+")"),g--,4==g&&(g=0);break;case 3:case 4:case 5:case 6:case 7:case 8:var h=g=255;for(b=0;12>b;b++)for(c=0;21>c;c++){acolor=Math.round(h);bcolor=Math.round(g);0>acolor&&(acolor=
0);switch(a){case 3:d=acolor;f=e=bcolor;break;case 4:d=bcolor;e=acolor;f=bcolor;break;case 5:e=d=bcolor;f=acolor;break;case 6:e=d=acolor;f=bcolor;break;case 7:d=acolor;e=bcolor;f=acolor;break;case 8:d=bcolor,f=e=acolor}set_swatch_color(c,b,"rgb("+d+","+e+","+f+")");1<g?g-=2.03174:(g=0,1.03<h&&(h-=2.03174))}break;default:return!1}return pickerReady=!0}
function switch_color_picker(a){0<a?8>colorPickerType?colorPickerType++:colorPickerType=0:0<colorPickerType?colorPickerType--:colorPickerType=8;init_color_picker(colorPickerType)}
function open_color_picker(a,b){pickerReady?(pickerElement=fetch_object("colorPicker"),activeElementId==a&&"none"!=pickerElement.style.display?pickerElement.style.display="none":(activeElementId=a,colorElement=fetch_object("color_"+a),previewElement=fetch_object("preview_"+a),a=previewElement.style.backgroundColor,fetch_object("oldColor").style.background=a,fetch_object("newColor").style.background=a,fetch_object("txtColor").value=colorElement.value,b||(b=window.event),"number"==typeof b.pageX?(xpos=
b.pageX,ypos=b.pageY):"number"==typeof b.clientX&&(xpos=b.clientX+document.documentElement.scrollLeft,ypos=b.clientY+document.documentElement.scrollTop),xpos+=10,ypos+=5,xpos+colorPickerWidth>=document.body.clientWidth&&(xpos=document.body.clientWidth-colorPickerWidth-5),pickerElement.style.left=xpos+"px",pickerElement.style.top=ypos+"px",pickerElement.style.display="")):alert(vBAdmin.renderPhrase("color_picker_not_ready"))}
function close_color_picker(){activeElementId=0;fetch_object("colorPicker").style.display="none"}function swatch_over(a){col_over(this)}function swatch_click(a){col_click(this)}function col_over(a){color=fetch_hex_color(a.style.backgroundColor);fetch_object("newColor").style.background=color;fetch_object("txtColor").value=color}
function col_click(a){color="transparent"==a?a:get_color_value(a.style.backgroundColor);fetch_object("color_"+activeElementId).value=color;preview_color(activeElementId);close_color_picker()}function get_color_value(a){if(a.match(/rgb\(\s*(\d+),\s*(\d+)\s*,\s*(\d+)\s*\)/i))return fetch_hex_color(a);(m=a.match(/^\s*#?(?:[a-fA-F0-9]{3}|[a-fA-F0-9]{6})\s*$/i))&&"#"!=a.substr(0,1)&&(a="#"+a);return a}
function get_rgb_value(a){return(match=a.match(/rgb\(\s*(\d+),\s*(\d+)\s*,\s*(\d+)\s*\)/i))?(console.log(match),match[0]):a.match(/^\s*#?(?:[a-fA-F0-9]{3}|[a-fA-F0-9]{6})\s*$/i)?fetch_rgb_color(a):a}
function fetch_hex_color(a){if("r"==a.substr(0,1)){colorMatch=a.match(/rgb\(\s*(\d+),\s*(\d+)\s*,\s*(\d+)\s*\)/i);for(a=1;4>a;a++)colorMatch[a]=parseInt(colorMatch[a]).toString(16),2>colorMatch[a].length&&(colorMatch[a]="0"+colorMatch[a]);a="#"+(colorMatch[1]+colorMatch[2]+colorMatch[3]).toUpperCase()}return a.toUpperCase()}
function fetch_rgb_color(a){"#"==a.substr(0,1)&&(a=a.substring(1));if(3==a.length){var b=a.substr(0,1);b+=b;var c=a.substr(1,1);c+=c;a=a.substr(2,1);a+=a}else if(6==a.length)b=a.substr(0,2),c=a.substr(2,2),a=a.substr(4,2);else return"";return"rgb("+parseInt(b,16)+", "+parseInt(c,16)+", "+parseInt(a,16)+")"}function is_transparent(a){return""==a||"none"==a||"transparent"==a?!0:!1};
